package com.bytedance.android.live.settings.initializer;

import X.AnonymousClass073;
import X.C56;
import X.C57;
import X.C58;
import X.C59;
import X.C5A;
import X.C5B;
import X.C5C;
import X.C5D;
import X.C5E;
import X.C5F;
import X.C5G;
import X.C5H;
import X.C5I;
import X.C5V;
import X.C5W;
import X.C5X;
import X.C5Y;
import X.C5Z;
import X.InterfaceC30752C5c;
import com.bytedance.android.live.annotation.ScopeValue;
import com.bytedance.android.live.broadcast.setting.MobileGameBroadcastFeedbackConfig;
import com.bytedance.android.live.broadcast.setting.MobileHighPingAdjustBitrateConfig;
import com.bytedance.android.live.broadcast.setting.MobileHighPingOptimizeConfig;
import com.bytedance.android.live_settings.Group;
import com.bytedance.android.live_settings.LiveSettingModel;
import com.bytedance.android.livesdk.livesetting.broadcast.LiveRecyclerViewOptData;
import com.bytedance.android.livesdk.livesetting.model.DrawerLoadOpt;
import com.bytedance.android.livesdk.livesetting.model.LiveTooltipDebugConfig;
import com.bytedance.android.livesdk.livesetting.performance.LivePanelCostTimeModel;
import com.bytedance.android.livesdk.livesetting.performance.LiveRecyclerviewPerformanceOptData;
import com.bytedance.android.livesdk.livesetting.roomfunction.LiveTooltip;
import com.bytedance.android.livesdk.model.MonitorSampleData;
import com.google.gson.p;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/* loaded from: classes6.dex */
public final class SettingsInitializer implements InterfaceC30752C5c {
    public static final SettingsInitializer INSTANCE = new SettingsInitializer();

    @Override // X.InterfaceC30752C5c
    public HashMap<String, LiveSettingModel> getModelMap() {
        HashMap<String, LiveSettingModel> hashMap = new HashMap<>(1883);
        HashMap<String, LiveSettingModel> hashMap2 = C5Y.LIZ;
        if (hashMap2.size() <= 0) {
            ArrayList arrayList = new ArrayList();
            Boolean bool = Boolean.FALSE;
            arrayList.add(new Group(new p(bool), "default group", true));
            Boolean bool2 = Boolean.TRUE;
            arrayList.add(new Group(new p(bool2), "experiment_group", false));
            ScopeValue scopeValue = ScopeValue.BROADCAST;
            LiveSettingModel liveSettingModel = new LiveSettingModel("com.bytedance.android.livesdk.livesetting.broadcast.GameLiveLandscapeEnterOp", scopeValue, "boolean", "landscape_audience_enter_room_optimze", new p(bool), "kangzhibo.1", arrayList);
            Class<?> cls = Boolean.TYPE;
            ArrayList LIZJ = AnonymousClass073.LIZJ(liveSettingModel, cls, hashMap2, "com.bytedance.android.livesdk.livesetting.broadcast.GameLiveLandscapeEnterOp", liveSettingModel);
            LIZJ.add(new Group(new p((Number) 1), "default group", true));
            LiveSettingModel liveSettingModel2 = new LiveSettingModel("com.bytedance.android.livesdk.livesetting.broadcast.LiveBGMSetting", scopeValue, "int", "live_upgrade_bgm", new p((Number) 1), "zhutianye", LIZJ);
            Class cls2 = Integer.TYPE;
            ArrayList LIZJ2 = AnonymousClass073.LIZJ(liveSettingModel2, cls2, hashMap2, "com.bytedance.android.livesdk.livesetting.broadcast.LiveBGMSetting", liveSettingModel2);
            LIZJ2.add(new Group(new p((Number) 0), "default group", true));
            LiveSettingModel liveSettingModel3 = new LiveSettingModel("com.bytedance.android.livesdk.livesetting.broadcast.LiveKaraokeSetting", scopeValue, "int", "live_host_karaok_enable", new p((Number) 0), "lishuo.oo", LIZJ2);
            ArrayList LIZJ3 = AnonymousClass073.LIZJ(liveSettingModel3, cls2, hashMap2, "com.bytedance.android.livesdk.livesetting.broadcast.LiveKaraokeSetting", liveSettingModel3);
            LIZJ3.add(new Group(new p(""), "default group", true));
            LiveSettingModel liveSettingModel4 = new LiveSettingModel("com.bytedance.android.livesdk.livesetting.broadcast.LiveRecyclerViewImageOptSetting", scopeValue, "LiveRecyclerViewOptData", "live_load_image_when_scroll_rv", new p(""), "wangsiyue.kw", LIZJ3);
            ArrayList LIZJ4 = AnonymousClass073.LIZJ(liveSettingModel4, LiveRecyclerViewOptData.class, hashMap2, "com.bytedance.android.livesdk.livesetting.broadcast.LiveRecyclerViewImageOptSetting", liveSettingModel4);
            LIZJ4.add(new Group(new p((Number) 0), "default group", true));
            LIZJ4.add(new Group(new p((Number) 1), "experiment_group", false));
            ScopeValue scopeValue2 = ScopeValue.WATCHLIVE;
            LiveSettingModel liveSettingModel5 = new LiveSettingModel("com.bytedance.android.livesdk.livesetting.broadcast.LiveWatchDialogOrientationSetting", scopeValue2, "int", "ttlive_game_dialog_orientation", new p((Number) 0), "dingyitong.03", LIZJ4);
            ArrayList LIZJ5 = AnonymousClass073.LIZJ(liveSettingModel5, cls2, hashMap2, "com.bytedance.android.livesdk.livesetting.broadcast.LiveWatchDialogOrientationSetting", liveSettingModel5);
            LIZJ5.add(new Group(new p(bool), "default group", true));
            LiveSettingModel liveSettingModel6 = new LiveSettingModel("com.bytedance.android.livesdk.livesetting.broadcast.TtLiveBackgroundSetting", scopeValue, "boolean", "tt_live_background", new p(bool), "liujinyang.jeanee", LIZJ5);
            ArrayList LIZJ6 = AnonymousClass073.LIZJ(liveSettingModel6, cls, hashMap2, "com.bytedance.android.livesdk.livesetting.broadcast.TtLiveBackgroundSetting", liveSettingModel6);
            LIZJ6.add(new Group(new p(bool), "Default", true));
            LiveSettingModel liveSettingModel7 = new LiveSettingModel("com.bytedance.android.livesdk.livesetting.broadcast.preview.LivePreviewMoreSetting", scopeValue, "boolean", "live_preview_broadcast_more", new p(bool), "liumiao.chris", LIZJ6);
            ArrayList LIZJ7 = AnonymousClass073.LIZJ(liveSettingModel7, cls, hashMap2, "com.bytedance.android.livesdk.livesetting.broadcast.preview.LivePreviewMoreSetting", liveSettingModel7);
            Float valueOf = Float.valueOf(1.0f);
            LIZJ7.add(new Group(new p((Number) valueOf), "default group", true));
            ScopeValue scopeValue3 = ScopeValue.OTHER;
            LiveSettingModel liveSettingModel8 = new LiveSettingModel("com.bytedance.android.livesdk.livesetting.drawer.DrawerMaxSlideControlSetting", scopeValue3, "float", "live_drawer_max_slide_control_opt", new p((Number) valueOf), "shizhongyu.001", LIZJ7);
            Class cls3 = Float.TYPE;
            ArrayList LIZJ8 = AnonymousClass073.LIZJ(liveSettingModel8, cls3, hashMap2, "com.bytedance.android.livesdk.livesetting.drawer.DrawerMaxSlideControlSetting", liveSettingModel8);
            LIZJ8.add(new Group(new p(bool), "default group", true));
            LIZJ8.add(new Group(new p(bool2), "experiment_group", false));
            LiveSettingModel liveSettingModel9 = new LiveSettingModel("com.bytedance.android.livesdk.livesetting.feed.LiveLandscapeInnerFeedSetting", scopeValue, "boolean", "ttlive_landscape_inner_feed_setting", new p(bool), "kangzhibo.1", LIZJ8);
            ArrayList LIZJ9 = AnonymousClass073.LIZJ(liveSettingModel9, cls, hashMap2, "com.bytedance.android.livesdk.livesetting.feed.LiveLandscapeInnerFeedSetting", liveSettingModel9);
            Float valueOf2 = Float.valueOf(-1.0f);
            LIZJ9.add(new Group(new p((Number) valueOf2), "default group", true));
            ScopeValue scopeValue4 = ScopeValue.LINKMIC;
            LiveSettingModel liveSettingModel10 = new LiveSettingModel("com.bytedance.android.livesdk.livesetting.linkmic.TTliveAnchorDeviceScoreSetting", scopeValue4, "float", "ttlive_anchor_device_score", new p((Number) valueOf2), "huangjian.jann", LIZJ9);
            ArrayList LIZJ10 = AnonymousClass073.LIZJ(liveSettingModel10, cls3, hashMap2, "com.bytedance.android.livesdk.livesetting.linkmic.TTliveAnchorDeviceScoreSetting", liveSettingModel10);
            LIZJ10.add(new Group(new p((Number) 0), "default group", true));
            LiveSettingModel liveSettingModel11 = new LiveSettingModel("com.bytedance.android.livesdk.livesetting.linkmic.multilive.MultiGuestV3AudioBeOccupiedGuestABSetting", scopeValue4, "int", "multi_guest_audio_be_occupied_guest_ab", new p((Number) 0), "wusihao.666", LIZJ10);
            ArrayList LIZJ11 = AnonymousClass073.LIZJ(liveSettingModel11, cls2, hashMap2, "com.bytedance.android.livesdk.livesetting.linkmic.multilive.MultiGuestV3AudioBeOccupiedGuestABSetting", liveSettingModel11);
            LIZJ11.add(new Group(new p(bool), "default group", true));
            LiveSettingModel liveSettingModel12 = new LiveSettingModel("com.bytedance.android.livesdk.livesetting.other.EnableParsePushSlimroomSetting", scopeValue3, "boolean", "enable_parse_push_slimroom", new p(bool), "wangyan.shang", LIZJ11);
            ArrayList LIZJ12 = AnonymousClass073.LIZJ(liveSettingModel12, cls, hashMap2, "com.bytedance.android.livesdk.livesetting.other.EnableParsePushSlimroomSetting", liveSettingModel12);
            LIZJ12.add(new Group(new p(bool), "default group", true));
            LiveSettingModel liveSettingModel13 = new LiveSettingModel("com.bytedance.android.livesdk.livesetting.other.LiveDialogFragmentOptSetting", scopeValue3, "boolean", "live_dialog_fragment_opt", new p(bool), "lishuo.oo", LIZJ12);
            ArrayList LIZJ13 = AnonymousClass073.LIZJ(liveSettingModel13, cls, hashMap2, "com.bytedance.android.livesdk.livesetting.other.LiveDialogFragmentOptSetting", liveSettingModel13);
            LIZJ13.add(new Group(new p(bool), "default group", true));
            ScopeValue scopeValue5 = ScopeValue.PERFORMANCE;
            LiveSettingModel liveSettingModel14 = new LiveSettingModel("com.bytedance.android.livesdk.livesetting.other.LiveDispatchApplyInsetsOptSettings", scopeValue5, "boolean", "live_dispatch_apply_insets_opt", new p(bool), "liuxiangdong.richard", LIZJ13);
            ArrayList LIZJ14 = AnonymousClass073.LIZJ(liveSettingModel14, cls, hashMap2, "com.bytedance.android.livesdk.livesetting.other.LiveDispatchApplyInsetsOptSettings", liveSettingModel14);
            LIZJ14.add(new Group(new p(bool2), "default group", true));
            LiveSettingModel liveSettingModel15 = new LiveSettingModel("com.bytedance.android.livesdk.livesetting.other.LiveMessagePlatformCommonControlBubble", scopeValue3, "boolean", "live_message_platform_common_control_bubble", new p(bool2), "liushe", LIZJ14);
            ArrayList LIZJ15 = AnonymousClass073.LIZJ(liveSettingModel15, cls, hashMap2, "com.bytedance.android.livesdk.livesetting.other.LiveMessagePlatformCommonControlBubble", liveSettingModel15);
            LIZJ15.add(new Group(new p(""), "default group", true));
            LiveSettingModel liveSettingModel16 = new LiveSettingModel("com.bytedance.android.livesdk.livesetting.other.LiveMessagePlatformCommonPreferenceBubbleSetting", scopeValue3, "java.lang.String", "live_message_platform_common_preference_bubble", new p(""), "liushe", LIZJ15);
            ArrayList LIZJ16 = AnonymousClass073.LIZJ(liveSettingModel16, String.class, hashMap2, "com.bytedance.android.livesdk.livesetting.other.LiveMessagePlatformCommonPreferenceBubbleSetting", liveSettingModel16);
            LIZJ16.add(new Group(new p(""), "default group", true));
            LiveSettingModel liveSettingModel17 = new LiveSettingModel("com.bytedance.android.livesdk.livesetting.other.LiveBubbleBlockListSetting", scopeValue3, "List<String>", "live_message_platform_bubble_block_list", new p(""), "wuzhongle", LIZJ16);
            ArrayList LIZJ17 = AnonymousClass073.LIZJ(liveSettingModel17, List.class, hashMap2, "com.bytedance.android.livesdk.livesetting.other.LiveBubbleBlockListSetting", liveSettingModel17);
            LIZJ17.add(new Group(new p(""), "default group", true));
            LiveSettingModel liveSettingModel18 = new LiveSettingModel("com.bytedance.android.livesdk.livesetting.other.LiveMessagePlatformCommonPreferenceRedDotSetting", scopeValue3, "java.lang.String", "live_message_platform_common_preference_red_dot", new p(""), "liushe", LIZJ17);
            ArrayList LIZJ18 = AnonymousClass073.LIZJ(liveSettingModel18, String.class, hashMap2, "com.bytedance.android.livesdk.livesetting.other.LiveMessagePlatformCommonPreferenceRedDotSetting", liveSettingModel18);
            LIZJ18.add(new Group(new p(""), "default group", true));
            LiveSettingModel liveSettingModel19 = new LiveSettingModel("com.bytedance.android.livesdk.livesetting.other.LiveRedDotBlockListSetting", scopeValue3, "List<String>", "live_message_platform_red_dot_block_list", new p(""), "wuzhongle", LIZJ18);
            ArrayList LIZJ19 = AnonymousClass073.LIZJ(liveSettingModel19, List.class, hashMap2, "com.bytedance.android.livesdk.livesetting.other.LiveRedDotBlockListSetting", liveSettingModel19);
            LIZJ19.add(new Group(new p(""), "default group", true));
            LiveSettingModel liveSettingModel20 = new LiveSettingModel("com.bytedance.android.livesdk.livesetting.other.LiveTooltipDebugSetting", scopeValue3, "LiveTooltipDebugConfig", "live_tooltip_debug", new p(""), "liushe", LIZJ19);
            ArrayList LIZJ20 = AnonymousClass073.LIZJ(liveSettingModel20, LiveTooltipDebugConfig.class, hashMap2, "com.bytedance.android.livesdk.livesetting.other.LiveTooltipDebugSetting", liveSettingModel20);
            LIZJ20.add(new Group(new p(bool), "control_group", true));
            LIZJ20.add(new Group(new p(bool2), "experimental_group", false));
            LiveSettingModel liveSettingModel21 = new LiveSettingModel("com.bytedance.android.livesdk.livesetting.roomfunction.ToolBarButtonWithTextExperiment", scopeValue2, "boolean", "live_toolbar_with_title", new p(bool), "wangyan.shang", LIZJ20);
            ArrayList LIZJ21 = AnonymousClass073.LIZJ(liveSettingModel21, cls, hashMap2, "com.bytedance.android.livesdk.livesetting.roomfunction.ToolBarButtonWithTextExperiment", liveSettingModel21);
            LIZJ21.add(new Group(new p((Number) 0), "default group", true));
            LiveSettingModel liveSettingModel22 = new LiveSettingModel("com.bytedance.android.livesdk.livesetting.other.UserLevelBadgePositionSetting", scopeValue3, "int", "live_top_badge_position", new p((Number) 0), "liuwentao.android", LIZJ21);
            ArrayList LIZJ22 = AnonymousClass073.LIZJ(liveSettingModel22, cls2, hashMap2, "com.bytedance.android.livesdk.livesetting.other.UserLevelBadgePositionSetting", liveSettingModel22);
            LIZJ22.add(new Group(new p((Number) 0), "default group", true));
            LiveSettingModel liveSettingModel23 = new LiveSettingModel("com.bytedance.android.livesdk.livesetting.performance.DataChannelGlobalOptSetting", scopeValue5, "int", "enable_data_channel_global_opt", new p((Number) 0), "qiuyihao", LIZJ22);
            liveSettingModel23.setPreciseExperiment(true);
            ArrayList LIZJ23 = AnonymousClass073.LIZJ(liveSettingModel23, cls2, hashMap2, "com.bytedance.android.livesdk.livesetting.performance.DataChannelGlobalOptSetting", liveSettingModel23);
            LIZJ23.add(new Group(new p((Number) 0), "default group", true));
            LiveSettingModel liveSettingModel24 = new LiveSettingModel("com.bytedance.android.livesdk.livesetting.performance.LiveBroadcastLiveLogOpt", scopeValue5, "int", "live_broadcast_livelog_opt", new p((Number) 0), "zhutianye", LIZJ23);
            ArrayList LIZJ24 = AnonymousClass073.LIZJ(liveSettingModel24, cls2, hashMap2, "com.bytedance.android.livesdk.livesetting.performance.LiveBroadcastLiveLogOpt", liveSettingModel24);
            LIZJ24.add(new Group(new p(bool), "default group", true));
            LiveSettingModel liveSettingModel25 = new LiveSettingModel("com.bytedance.android.livesdk.livesetting.performance.LiveClearScreenDrawOptSetting", scopeValue5, "boolean", "live_clear_screen_draw_opt", new p(bool), "liuxiangdong.richard", LIZJ24);
            ArrayList LIZJ25 = AnonymousClass073.LIZJ(liveSettingModel25, cls, hashMap2, "com.bytedance.android.livesdk.livesetting.performance.LiveClearScreenDrawOptSetting", liveSettingModel25);
            LIZJ25.add(new Group(new p(bool), "default group", true));
            LiveSettingModel liveSettingModel26 = new LiveSettingModel("com.bytedance.android.livesdk.livesetting.performance.LiveDrawOptSetting", scopeValue5, "boolean", "live_draw_opt", new p(bool), "liuxiangdong.richard", LIZJ25);
            ArrayList LIZJ26 = AnonymousClass073.LIZJ(liveSettingModel26, cls, hashMap2, "com.bytedance.android.livesdk.livesetting.performance.LiveDrawOptSetting", liveSettingModel26);
            LIZJ26.add(new Group(new p(""), "default group", true));
            LiveSettingModel liveSettingModel27 = new LiveSettingModel("com.bytedance.android.livesdk.livesetting.performance.LiveRecyclerviewPerformanceOptSwitchSetting", scopeValue5, "LiveRecyclerviewPerformanceOptData", "live_recyclerview_preformance_opt_switch", new p(""), "liukan.kk", LIZJ26);
            ArrayList LIZJ27 = AnonymousClass073.LIZJ(liveSettingModel27, LiveRecyclerviewPerformanceOptData.class, hashMap2, "com.bytedance.android.livesdk.livesetting.performance.LiveRecyclerviewPerformanceOptSwitchSetting", liveSettingModel27);
            LIZJ27.add(new Group(new p(bool), "default group", true));
            LiveSettingModel liveSettingModel28 = new LiveSettingModel("com.bytedance.android.livesdk.livesetting.performance.LiveRvPoolFluencySupportSampleSetting", scopeValue5, "boolean", "live_rv_pool_fluency_support_sample", new p(bool), "liujinyang.jeanee", LIZJ27);
            ArrayList LIZJ28 = AnonymousClass073.LIZJ(liveSettingModel28, cls, hashMap2, "com.bytedance.android.livesdk.livesetting.performance.LiveRvPoolFluencySupportSampleSetting", liveSettingModel28);
            LIZJ28.add(new Group(new p(bool), "default group", true));
            LiveSettingModel liveSettingModel29 = new LiveSettingModel("com.bytedance.android.livesdk.livesetting.performance.LiveUltimateInflateSwitchSetting", scopeValue5, "boolean", "live_ultimateinflate_switch", new p(bool), "liukan.kk", LIZJ28);
            ArrayList LIZJ29 = AnonymousClass073.LIZJ(liveSettingModel29, cls, hashMap2, "com.bytedance.android.livesdk.livesetting.performance.LiveUltimateInflateSwitchSetting", liveSettingModel29);
            LIZJ29.add(new Group(new p(""), "default group", true));
            LiveSettingModel liveSettingModel30 = new LiveSettingModel("com.bytedance.android.livesdk.livesetting.performance.PanelOpenCostTimesSetting", scopeValue5, "LivePanelCostTimeModel", "live_sdk_panel_open_cost_times", new p(""), "liukan.kk", LIZJ29);
            ArrayList LIZJ30 = AnonymousClass073.LIZJ(liveSettingModel30, LivePanelCostTimeModel.class, hashMap2, "com.bytedance.android.livesdk.livesetting.performance.PanelOpenCostTimesSetting", liveSettingModel30);
            LIZJ30.add(new Group(new p(bool), "default group", true));
            LiveSettingModel liveSettingModel31 = new LiveSettingModel("com.bytedance.android.livesdk.livesetting.performance.RankOptimizeSetting", ScopeValue.RANK, "boolean", "live_rank_optimize_setting", new p(bool), "mengqingyu.21", LIZJ30);
            ArrayList LIZJ31 = AnonymousClass073.LIZJ(liveSettingModel31, cls, hashMap2, "com.bytedance.android.livesdk.livesetting.performance.RankOptimizeSetting", liveSettingModel31);
            LIZJ31.add(new Group(new p(""), "default group", true));
            LiveSettingModel liveSettingModel32 = new LiveSettingModel("com.bytedance.android.livesdk.livesetting.roomfunction.LiveTooltipAlogSetting", scopeValue3, "LiveTooltip", "live_tooltip_alog_setting", new p(""), "xiaotao.123", LIZJ31);
            ArrayList LIZJ32 = AnonymousClass073.LIZJ(liveSettingModel32, LiveTooltip.class, hashMap2, "com.bytedance.android.livesdk.livesetting.roomfunction.LiveTooltipAlogSetting", liveSettingModel32);
            LIZJ32.add(new Group(new p(bool), "default group", true));
            LiveSettingModel liveSettingModel33 = new LiveSettingModel("com.bytedance.android.livesdk.livesetting.roomfunction.TextPieceHelperBugfixSetting", ScopeValue.ROOMFUNCTION, "boolean", "text_piece_helper_bugfix_setting", new p(bool), "sunshuo.man", LIZJ32);
            ArrayList LIZJ33 = AnonymousClass073.LIZJ(liveSettingModel33, cls, hashMap2, "com.bytedance.android.livesdk.livesetting.roomfunction.TextPieceHelperBugfixSetting", liveSettingModel33);
            LIZJ33.add(new Group(new p(bool), "default group", true));
            LIZJ33.add(new Group(new p(bool2), "v2", false));
            LiveSettingModel liveSettingModel34 = new LiveSettingModel("com.bytedance.android.livesdk.livesetting.watchlive.EnableSurfaceViewOptimizeSetting", scopeValue2, "boolean", "enable_surface_view_optimize", new p(bool), "zhangzhenlei", LIZJ33);
            ArrayList LIZJ34 = AnonymousClass073.LIZJ(liveSettingModel34, cls, hashMap2, "com.bytedance.android.livesdk.livesetting.watchlive.EnableSurfaceViewOptimizeSetting", liveSettingModel34);
            LIZJ34.add(new Group(new p(bool), "default group", true));
            LiveSettingModel liveSettingModel35 = new LiveSettingModel("com.bytedance.android.livesdk.livesetting.watchlive.FirstScreenDebounceClickEnabledSetting", scopeValue2, "boolean", "first_screen_debounce_click_enabled", new p(bool), "liuxiangdong.richard", LIZJ34);
            ArrayList LIZJ35 = AnonymousClass073.LIZJ(liveSettingModel35, cls, hashMap2, "com.bytedance.android.livesdk.livesetting.watchlive.FirstScreenDebounceClickEnabledSetting", liveSettingModel35);
            LIZJ35.add(new Group(new p((Number) 300), "default group", true));
            LiveSettingModel liveSettingModel36 = new LiveSettingModel("com.bytedance.android.livesdk.livesetting.watchlive.FirstScreenDebounceClickIntervalSetting", scopeValue2, "int", "first_screen_debounce_click_interval", new p((Number) 300), "liuxiangdong.richard", LIZJ35);
            ArrayList LIZJ36 = AnonymousClass073.LIZJ(liveSettingModel36, cls2, hashMap2, "com.bytedance.android.livesdk.livesetting.watchlive.FirstScreenDebounceClickIntervalSetting", liveSettingModel36);
            LIZJ36.add(new Group(new p(""), "default group", true));
            LiveSettingModel liveSettingModel37 = new LiveSettingModel("com.bytedance.android.livesdk.livesetting.watchlive.LiveDrawerLoadOptSetting", scopeValue3, "DrawerLoadOpt", "tt_live_drawer_load_opt", new p(""), "shizhongyu.001", LIZJ36);
            ArrayList LIZJ37 = AnonymousClass073.LIZJ(liveSettingModel37, DrawerLoadOpt.class, hashMap2, "com.bytedance.android.livesdk.livesetting.watchlive.LiveDrawerLoadOptSetting", liveSettingModel37);
            LIZJ37.add(new Group(new p(bool), "default group", true));
            LIZJ37.add(new Group(new p(bool2), "v1", false));
            LiveSettingModel liveSettingModel38 = new LiveSettingModel("com.bytedance.android.livesdk.stream.performance.abs.AudienceBlockHeartBeatMonitorEnableSetting", scopeValue2, "boolean", "live_stream_performance_auheartbeatmonitor_enable", new p(bool), "wanghui.wh", LIZJ37);
            liveSettingModel38.setDefaultCustomClass(cls);
            hashMap2.put("com.bytedance.android.livesdk.stream.performance.abs.AudienceBlockHeartBeatMonitorEnableSetting", liveSettingModel38);
        }
        hashMap.putAll(hashMap2);
        HashMap<String, LiveSettingModel> hashMap3 = C5V.LIZ;
        if (hashMap3.size() <= 0) {
            ArrayList arrayList2 = new ArrayList();
            arrayList2.add(new Group(new p((Number) 180), "default group", true));
            ScopeValue scopeValue6 = ScopeValue.BROADCAST;
            LiveSettingModel liveSettingModel39 = new LiveSettingModel("com.bytedance.android.common.setting.ShowLowPerformanceTipsDuration", scopeValue6, "int", "show_low_performance_tips_inapp_duartion_time", new p((Number) 180), "lijianchang", arrayList2);
            Class cls4 = Integer.TYPE;
            ArrayList LIZJ38 = AnonymousClass073.LIZJ(liveSettingModel39, cls4, hashMap3, "com.bytedance.android.common.setting.ShowLowPerformanceTipsDuration", liveSettingModel39);
            LIZJ38.add(new Group(new p((Number) 0), "default group", true));
            LiveSettingModel liveSettingModel40 = new LiveSettingModel("com.bytedance.android.common.setting.ShowLowPerformanceTipsSwitcher", scopeValue6, "int", "show_low_performance_tips", new p((Number) 0), "lijianchang", LIZJ38);
            ArrayList LIZJ39 = AnonymousClass073.LIZJ(liveSettingModel40, cls4, hashMap3, "com.bytedance.android.common.setting.ShowLowPerformanceTipsSwitcher", liveSettingModel40);
            LIZJ39.add(new Group(new p((Number) 6), "default group", true));
            LiveSettingModel liveSettingModel41 = new LiveSettingModel("com.bytedance.android.common.setting.ShowTipLowEndDeviceMax", scopeValue6, "int", "show_tip_low_end_device_max", new p((Number) 6), "lijianchang", LIZJ39);
            ArrayList LIZJ40 = AnonymousClass073.LIZJ(liveSettingModel41, cls4, hashMap3, "com.bytedance.android.common.setting.ShowTipLowEndDeviceMax", liveSettingModel41);
            LIZJ40.add(new Group(new p(""), "default group", true));
            LiveSettingModel liveSettingModel42 = new LiveSettingModel("com.bytedance.android.live.broadcast.setting.MobileGameFeedbackAnalyseInfo", scopeValue6, "MobileGameBroadcastFeedbackConfig", "mobile_game_feedback_analyse_info", new p(""), "lijianchang", LIZJ40);
            ArrayList LIZJ41 = AnonymousClass073.LIZJ(liveSettingModel42, MobileGameBroadcastFeedbackConfig.class, hashMap3, "com.bytedance.android.live.broadcast.setting.MobileGameFeedbackAnalyseInfo", liveSettingModel42);
            LIZJ41.add(new Group(new p(""), "default group", true));
            LiveSettingModel liveSettingModel43 = new LiveSettingModel("com.bytedance.android.live.broadcast.setting.MobileHighPingAdjustBitrateInfo", scopeValue6, "MobileHighPingAdjustBitrateConfig", "high_ping_adjust_bitrate", new p(""), "lijianchang", LIZJ41);
            ArrayList LIZJ42 = AnonymousClass073.LIZJ(liveSettingModel43, MobileHighPingAdjustBitrateConfig.class, hashMap3, "com.bytedance.android.live.broadcast.setting.MobileHighPingAdjustBitrateInfo", liveSettingModel43);
            LIZJ42.add(new Group(new p(""), "default group", true));
            LiveSettingModel liveSettingModel44 = new LiveSettingModel("com.bytedance.android.live.broadcast.setting.MobileHighPingOptimizeInfo", scopeValue6, "MobileHighPingOptimizeConfig", "mobile_high_ping_optimize_config", new p(""), "lijianchang", LIZJ42);
            liveSettingModel44.setDefaultCustomClass(MobileHighPingOptimizeConfig.class);
            hashMap3.put("com.bytedance.android.live.broadcast.setting.MobileHighPingOptimizeInfo", liveSettingModel44);
        }
        hashMap.putAll(hashMap3);
        HashMap<String, LiveSettingModel> hashMap4 = C5X.LIZ;
        if (hashMap4.size() <= 0) {
            ArrayList arrayList3 = new ArrayList();
            arrayList3.add(new Group(new p(""), "default group", true));
            LiveSettingModel liveSettingModel45 = new LiveSettingModel("com.bytedance.android.livesdk.comp.api.subscription.base.flashcomponent.setting.FlashComponentSetting", ScopeValue.SUBSCRIPTION, "java.lang.String", "flash_component_setting", new p(""), "qiuyihao", arrayList3);
            liveSettingModel45.setDefaultCustomClass(String.class);
            hashMap4.put("com.bytedance.android.livesdk.comp.api.subscription.base.flashcomponent.setting.FlashComponentSetting", liveSettingModel45);
        }
        hashMap.putAll(hashMap4);
        HashMap<String, LiveSettingModel> hashMap5 = C5Z.LIZ;
        if (hashMap5.size() <= 0) {
            ArrayList arrayList4 = new ArrayList();
            Boolean bool3 = Boolean.FALSE;
            arrayList4.add(new Group(new p(bool3), "default group", true));
            LiveSettingModel liveSettingModel46 = new LiveSettingModel("com.bytedance.android.livesdk.livesetting.linkmic.LivesdkLinkmicMultiGuestLayoutViewOptimizeSetting", ScopeValue.LINKMIC, "boolean", "livesdk_linkmic_multi_guest_layout_view_optimize", new p(bool3), "zhouliang", arrayList4);
            Class cls5 = Boolean.TYPE;
            ArrayList LIZJ43 = AnonymousClass073.LIZJ(liveSettingModel46, cls5, hashMap5, "com.bytedance.android.livesdk.livesetting.linkmic.LivesdkLinkmicMultiGuestLayoutViewOptimizeSetting", liveSettingModel46);
            LIZJ43.add(new Group(new p(bool3), "default group", true));
            LiveSettingModel liveSettingModel47 = new LiveSettingModel("com.bytedance.android.livesdk.livesetting.other.LiveEcommerceInnerSetting", ScopeValue.OTHER, "boolean", "ec_inner_opt_mode", new p(bool3), "wanglikun.eric", LIZJ43);
            ArrayList LIZJ44 = AnonymousClass073.LIZJ(liveSettingModel47, cls5, hashMap5, "com.bytedance.android.livesdk.livesetting.other.LiveEcommerceInnerSetting", liveSettingModel47);
            LIZJ44.add(new Group(new p(""), "default group", true));
            ScopeValue scopeValue7 = ScopeValue.PERFORMANCE;
            LiveSettingModel liveSettingModel48 = new LiveSettingModel("com.bytedance.android.livesdk.livesetting.other.LiveMonitorSampleSetting", scopeValue7, "MonitorSampleData", "live_slardar_monitor_sample_opt", new p(""), "shizhongyu.001", LIZJ44);
            ArrayList LIZJ45 = AnonymousClass073.LIZJ(liveSettingModel48, MonitorSampleData.class, hashMap5, "com.bytedance.android.livesdk.livesetting.other.LiveMonitorSampleSetting", liveSettingModel48);
            LIZJ45.add(new Group(new p(""), "default group", true));
            LiveSettingModel liveSettingModel49 = new LiveSettingModel("com.bytedance.android.livesdk.livesetting.performance.CpuTemperaturePathListSetting", scopeValue7, "java.lang.String[]", "cpu_temperature_list_path", new p(""), "wangyan.shang", LIZJ45);
            ArrayList LIZJ46 = AnonymousClass073.LIZJ(liveSettingModel49, String[].class, hashMap5, "com.bytedance.android.livesdk.livesetting.performance.CpuTemperaturePathListSetting", liveSettingModel49);
            LIZJ46.add(new Group(new p(""), "default group", true));
            LiveSettingModel liveSettingModel50 = new LiveSettingModel("com.bytedance.android.livesdk.livesetting.performance.LiveDowngradeThreadMapSetting", scopeValue7, "Map<String, Double>", "live_downgrade_thread_map", new p(""), "sunqiang.2759", LIZJ46);
            ArrayList LIZJ47 = AnonymousClass073.LIZJ(liveSettingModel50, Map.class, hashMap5, "com.bytedance.android.livesdk.livesetting.performance.LiveDowngradeThreadMapSetting", liveSettingModel50);
            Boolean bool4 = Boolean.TRUE;
            LIZJ47.add(new Group(new p(bool4), "default group", true));
            LiveSettingModel liveSettingModel51 = new LiveSettingModel("com.bytedance.android.livesdk.livesetting.performance.LiveMtEnableCpuRateSetting", scopeValue7, "boolean", "live_mt_enable_cpu_rate", new p(bool4), "lishuo.oo", LIZJ47);
            ArrayList LIZJ48 = AnonymousClass073.LIZJ(liveSettingModel51, cls5, hashMap5, "com.bytedance.android.livesdk.livesetting.performance.LiveMtEnableCpuRateSetting", liveSettingModel51);
            LIZJ48.add(new Group(new p(bool3), "default group", true));
            LiveSettingModel liveSettingModel52 = new LiveSettingModel("com.bytedance.android.livesdk.livesetting.performance.LiveMtEnableCpuSpeedRateSetting", scopeValue7, "boolean", "live_mt_enable_cpu_speed_rate", new p(bool3), "lishuo.oo", LIZJ48);
            ArrayList LIZJ49 = AnonymousClass073.LIZJ(liveSettingModel52, cls5, hashMap5, "com.bytedance.android.livesdk.livesetting.performance.LiveMtEnableCpuSpeedRateSetting", liveSettingModel52);
            LIZJ49.add(new Group(new p((Number) 1), "default group", true));
            LiveSettingModel liveSettingModel53 = new LiveSettingModel("com.bytedance.android.livesdk.livesetting.performance.LiveMtEnableInstantCpuRateSetting", scopeValue7, "int", "live_mt_enable_instant_cpu_rate", new p((Number) 1), "lishuo.oo", LIZJ49);
            Class<?> cls6 = Integer.TYPE;
            ArrayList LIZJ50 = AnonymousClass073.LIZJ(liveSettingModel53, cls6, hashMap5, "com.bytedance.android.livesdk.livesetting.performance.LiveMtEnableInstantCpuRateSetting", liveSettingModel53);
            LIZJ50.add(new Group(new p(bool3), "default group", true));
            LiveSettingModel liveSettingModel54 = new LiveSettingModel("com.bytedance.android.livesdk.livesetting.performance.LiveMtEnableUseProcFileCpuRateSetting", scopeValue7, "boolean", "live_mt_enable_use_proc_file_cpu_rate", new p(bool3), "lishuo.oo", LIZJ50);
            ArrayList LIZJ51 = AnonymousClass073.LIZJ(liveSettingModel54, cls5, hashMap5, "com.bytedance.android.livesdk.livesetting.performance.LiveMtEnableUseProcFileCpuRateSetting", liveSettingModel54);
            LIZJ51.add(new Group(new p(""), "default group", true));
            LiveSettingModel liveSettingModel55 = new LiveSettingModel("com.bytedance.android.livesdk.livesetting.performance.LiveUpgradeApiMapSetting", scopeValue7, "Map<String, Double>", "live_upgrade_api_map", new p(""), "sunqiang.2759", LIZJ51);
            ArrayList LIZJ52 = AnonymousClass073.LIZJ(liveSettingModel55, Map.class, hashMap5, "com.bytedance.android.livesdk.livesetting.performance.LiveUpgradeApiMapSetting", liveSettingModel55);
            LIZJ52.add(new Group(new p((Number) 10000L), "default group", true));
            LiveSettingModel liveSettingModel56 = new LiveSettingModel("com.bytedance.android.livesdk.livesetting.performance.LiveWatchDogStopDelayDurationSetting", scopeValue7, "long", "live_watchdog_stop_delay_duration", new p((Number) 10000L), "lishuo.oo", LIZJ52);
            ArrayList LIZJ53 = AnonymousClass073.LIZJ(liveSettingModel56, Long.TYPE, hashMap5, "com.bytedance.android.livesdk.livesetting.performance.LiveWatchDogStopDelayDurationSetting", liveSettingModel56);
            LIZJ53.add(new Group(new p((Number) 0), "v0-online", true));
            LIZJ53.add(new Group(new p((Number) 1), "v1-downgrade-thread", false));
            LIZJ53.add(new Group(new p((Number) 2), "v2-upgrade-api", false));
            LIZJ53.add(new Group(new p((Number) 3), "v3-slide-boost", false));
            LIZJ53.add(new Group(new p((Number) 4), "v4-byte-gpu-quit", false));
            LIZJ53.add(new Group(new p((Number) 5), "v5-enable-all", false));
            LiveSettingModel liveSettingModel57 = new LiveSettingModel("com.bytedance.android.livesdk.livesetting.performance.LiveWatchThreadPriorityOptSetting", scopeValue7, "int", "live_watch_thread_priority_opt", new p((Number) 0), "sunqiang.2759", LIZJ53);
            ArrayList LIZJ54 = AnonymousClass073.LIZJ(liveSettingModel57, cls6, hashMap5, "com.bytedance.android.livesdk.livesetting.performance.LiveWatchThreadPriorityOptSetting", liveSettingModel57);
            LIZJ54.add(new Group(new p(bool3), "control_group", true));
            LIZJ54.add(new Group(new p(bool4), "experimental_group", false));
            LiveSettingModel liveSettingModel58 = new LiveSettingModel("com.bytedance.android.livesdk.livesetting.performance.degrade.DisableEnterRoomLinkOptSetting", scopeValue7, "boolean", "disable_enter_room_link_opt", new p(bool3), "wangyan.shang", LIZJ54);
            ArrayList LIZJ55 = AnonymousClass073.LIZJ(liveSettingModel58, cls5, hashMap5, "com.bytedance.android.livesdk.livesetting.performance.degrade.DisableEnterRoomLinkOptSetting", liveSettingModel58);
            LIZJ55.add(new Group(new p((Number) 0), "default group", true));
            LIZJ55.add(new Group(new p((Number) 1), "experiment_group", false));
            ScopeValue scopeValue8 = ScopeValue.WATCHLIVE;
            LiveSettingModel liveSettingModel59 = new LiveSettingModel("com.bytedance.android.livesdk.livesetting.watchlive.LiveGameMultiStreamWatch", scopeValue8, "int", "ttlive_game_multi_stream_watch_live", new p((Number) 0), "dingyitong.03", LIZJ55);
            ArrayList LIZJ56 = AnonymousClass073.LIZJ(liveSettingModel59, cls6, hashMap5, "com.bytedance.android.livesdk.livesetting.watchlive.LiveGameMultiStreamWatch", liveSettingModel59);
            LIZJ56.add(new Group(new p((Number) 0), "default group", true));
            LIZJ56.add(new Group(new p((Number) 1), "v1 , enable preload for ec", false));
            LIZJ56.add(new Group(new p((Number) 2), "v2 , enable preload all room", false));
            LiveSettingModel liveSettingModel60 = new LiveSettingModel("com.bytedance.android.livesdk.livesetting.watchlive.LivePreloadInteractionLayerSetting", scopeValue8, "int", "live_preload_interaction_layer", new p((Number) 0), "wangyan.shang", LIZJ56);
            liveSettingModel60.setDefaultCustomClass(cls6);
            hashMap5.put("com.bytedance.android.livesdk.livesetting.watchlive.LivePreloadInteractionLayerSetting", liveSettingModel60);
        }
        hashMap.putAll(hashMap5);
        hashMap.putAll(C59.LIZ());
        HashMap<String, LiveSettingModel> hashMap6 = C5W.LIZ;
        if (hashMap6.size() <= 0) {
            ArrayList arrayList5 = new ArrayList();
            Boolean bool5 = Boolean.FALSE;
            arrayList5.add(new Group(new p(bool5), "default", true));
            LiveSettingModel liveSettingModel61 = new LiveSettingModel("com.bytedance.android.livesdk.livesetting.watchlive.LiveNetworkSyncAllowList", ScopeValue.WATCHLIVE, "boolean", "live_network_sync_allow", new p(bool5), "zengwei.godv", arrayList5);
            liveSettingModel61.setDefaultCustomClass(Boolean.TYPE);
            hashMap6.put("com.bytedance.android.livesdk.livesetting.watchlive.LiveNetworkSyncAllowList", liveSettingModel61);
        }
        hashMap.putAll(hashMap6);
        HashMap<String, LiveSettingModel> hashMap7 = C56.LIZ;
        if (hashMap7.size() <= 0) {
            C56.LIZ();
            C56.LIZIZ();
            C56.LJI();
            C56.LJII();
            C56.LJIIIIZZ();
            C56.LJIIIZ();
            C56.LJIIJ();
            C56.LJIIJJI();
            C56.LJIIL();
            C56.LJIILIIL();
            C56.LIZJ();
            C56.LIZLLL();
            C56.LJ();
            C56.LJFF();
        }
        hashMap.putAll(hashMap7);
        hashMap.putAll(C58.LIZ());
        hashMap.putAll(C5E.LIZ());
        hashMap.putAll(C5D.LIZ());
        hashMap.putAll(C5I.LIZ());
        hashMap.putAll(C5H.LIZ());
        hashMap.putAll(C5F.LIZ());
        hashMap.putAll(C57.LJ());
        hashMap.putAll(C5C.LIZ());
        hashMap.putAll(C5A.LIZ());
        hashMap.putAll(C5G.LIZ());
        hashMap.putAll(C5B.LIZ());
        return hashMap;
    }
}
