package X;

import android.app.Activity;
import android.content.Context;
import com.bytedance.mt.protector.impl.UriProtector;
import com.ss.android.ugc.aweme.feed.model.CardStruct;
import com.ss.android.ugc.aweme.im.sdk.common.controller.providedservices.IMService;
import com.ss.android.ugc.aweme.im.service.IIMService;
import com.ss.android.ugc.aweme.profile.model.User;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.TimeUnit;
import kotlin.jvm.internal.AqS170S0100000_4;
import kotlin.jvm.internal.o;

/* loaded from: classes5.dex */
public final class A7W implements InterfaceC55760LuW {
    public final InterfaceC70422pa LIZ = C48841JEv.LIZ(T2R.LJIIJJI().plus(C78613UtF.LIZJ));
    public final ConcurrentHashMap<C238479Xn, AbstractC72932td<User>> LIZIZ = new ConcurrentHashMap<>();
    public final XLM LIZJ;
    public final XJO LIZLLL;
    public XKQ LJ;
    public C73411SrX LJFF;
    public final C79863Bm LJI;

    @Override // X.InterfaceC55760LuW
    public final void LIZ() {
        this.LIZIZ.clear();
        C48841JEv.LIZJ(this.LIZ, null);
    }

    @Override // X.InterfaceC55760LuW
    public final C79863Bm LIZIZ() {
        return this.LJI;
    }

    public A7W(int i) {
        XLM LIZ = V8H.LIZ(new C33Y(0));
        this.LIZJ = LIZ;
        this.LIZLLL = XJR.LIZ();
        this.LJI = V1M.LIZLLL(LIZ);
    }

    public static void LJI(ActivityC45651qj activityC45651qj) {
        ActivityC45651qj LJJIFFI = C45804HyK.LJJIFFI(activityC45651qj);
        if (!C25706A7a.LIZ() || LJJIFFI == null) {
            C221018lt.LJFF("@LinkRelation", "not enable showPrivacyNotice!, skip!");
        } else {
            C221018lt.LJFF("@LinkRelation", "try showPrivacyNotice!");
            new C25710A7e(LJJIFFI, false).LIZ();
        }
    }

    @Override // X.InterfaceC55760LuW
    public final void LIZJ(User sharerUser) {
        o.LJIIIZ(sharerUser, "sharerUser");
        if (!A7Z.LIZ()) {
            return;
        }
        StringBuilder LIZ = X1D.LIZ();
        LIZ.append("recordRelation for login user: ");
        LIZ.append(sharerUser.getUid());
        C221018lt.LJFF("@LinkRelation", X1D.LIZIZ(LIZ));
        C238479Xn LJ = C55786Luw.LJ(sharerUser);
        if (LJ == null) {
            return;
        }
        XKX.LIZLLL(this.LIZ, null, null, new C238419Xh(this, LJ, null), 3);
    }

    public final void LJ(android.net.Uri uri) {
        XKX.LIZLLL(this.LIZ, null, null, new C9XZ(uri, null), 3);
        if (A7Z.LIZ()) {
            if (o.LJ(UriProtector.getQueryParameter(uri, "utm_campaign"), "client_share")) {
                String queryParameter = UriProtector.getQueryParameter(uri, "user_id");
                if (queryParameter == null) {
                    queryParameter = "";
                }
                if (!o.LJ(queryParameter, ((RBX) HG3.LJIILL()).getCurUserId())) {
                    return;
                } else {
                    throw new IllegalArgumentException("the share link generated by myself, ignore it!");
                }
            }
            throw new IllegalArgumentException("the link is not generated by the client!");
        }
        throw new IllegalStateException("LinkRelationUnifyExp is not enabled, ignore it!");
    }

    public final void LJFF(Activity activity) {
        ActivityC45651qj LJJIFFI = C45804HyK.LJJIFFI(activity);
        if (LJJIFFI != null) {
            LJI(LJJIFFI);
        }
        C73411SrX c73411SrX = this.LJFF;
        if (c73411SrX != null) {
            c73411SrX.dispose();
        }
    }

    /* JADX WARN: Multi-variable type inference failed */
    @Override // X.InterfaceC55760LuW
    public final void LIZLLL(Context context, android.net.Uri shareUri) {
        EnumC57171McB enumC57171McB;
        ActivityC45651qj activityC45651qj;
        C73411SrX LJIIIIZZ;
        Integer LJJIL;
        o.LJIIIZ(context, "context");
        o.LJIIIZ(shareUri, "shareUri");
        String LJ = V18.LJ(shareUri, "share_link_id");
        String LJ2 = V18.LJ(shareUri, "user_id");
        String LJ3 = V18.LJ(shareUri, "checksum");
        String LJ4 = V18.LJ(shareUri, "social_share_type");
        if (LJ4 != null && (LJJIL = C38350F3i.LJJIL(LJ4)) != null) {
            enumC57171McB = C55786Luw.LJFF(LJJIL.intValue());
        } else {
            enumC57171McB = null;
        }
        if (LJ == null) {
            LJ = "";
        }
        if (LJ2 == null) {
            LJ2 = "";
        }
        String LJ5 = V18.LJ(shareUri, "sec_user_id");
        if (LJ3 == null) {
            LJ3 = "";
        }
        if (enumC57171McB == null) {
            enumC57171McB = EnumC57171McB.DEFAULT;
        }
        String LJ6 = V18.LJ(shareUri, "utm_source");
        String LJ7 = V18.LJ(shareUri, "timestamp");
        String LJ8 = V18.LJ(shareUri, "gids");
        if (LJ8 == null && (LJ8 = V18.LJ(shareUri, "aweme_id")) == null && (LJ8 = V18.LJ(shareUri, "share_item_id")) == null) {
            LJ8 = CardStruct.IStatusCode.DEFAULT;
        }
        C238479Xn c238479Xn = new C238479Xn(LJ, LJ2, LJ5, LJ3, enumC57171McB, LJ6, LJ7, LJ8, V18.LJ(shareUri, "invitation_scene"));
        String lastPathSegment = shareUri.getLastPathSegment();
        if (lastPathSegment == null) {
            lastPathSegment = V18.LJ(shareUri, "id");
        }
        boolean LIZ = C70412pZ.LIZ();
        boolean z = false;
        A7W a7w = LIZ;
        if (LIZ != 0) {
            IIMService createIIMServicebyMonsterPlugin = IMService.createIIMServicebyMonsterPlugin(false);
            createIIMServicebyMonsterPlugin.getLandAutoMsgToChatHelper().LIZJ(c238479Xn.LIZ, lastPathSegment, c238479Xn.LJII, c238479Xn.LIZIZ, c238479Xn.LIZLLL, c238479Xn.LJI);
            a7w = createIIMServicebyMonsterPlugin;
        }
        try {
            a7w = this;
            a7w.LJ(shareUri);
            IMService.createIIMServicebyMonsterPlugin(false).getAutoMessageTooltipHelper().LIZJ(c238479Xn.LIZIZ);
            ActivityC45651qj LJJIFFI = C45804HyK.LJJIFFI(context);
            Activity LJIIIIZZ2 = C84763XOl.LJIIIIZZ();
            if (LJIIIIZZ2 != null) {
                activityC45651qj = C45804HyK.LJJIFFI(LJIIIIZZ2);
            } else {
                activityC45651qj = null;
            }
            StringBuilder LIZ2 = X1D.LIZ();
            LIZ2.append("current activity is null: ");
            if (activityC45651qj == null) {
                z = true;
            }
            LIZ2.append(z);
            C221018lt.LJFF("@LinkRelation", X1D.LIZIZ(LIZ2));
            if (!(!A7Y.LIZ()) || activityC45651qj != null) {
                if (o.LJ(LJJIFFI, activityC45651qj) || activityC45651qj == null) {
                    C73411SrX c73411SrX = a7w.LJFF;
                    if (c73411SrX != null) {
                        c73411SrX.dispose();
                    }
                    if (A7Y.LIZ()) {
                        LJIIIIZZ = C73542Ste.LJIIIIZZ(C84763XOl.LIZLLL().LJJLIIIJJI(3L, TimeUnit.SECONDS), new AqS170S0100000_4(a7w, 43), null, new AqS170S0100000_4(a7w, 44), 2);
                    } else {
                        LJIIIIZZ = C73542Ste.LJIIIIZZ(C84763XOl.LIZLLL(), null, null, new AqS170S0100000_4(a7w, 45), 3);
                    }
                    a7w.LJFF = LJIIIIZZ;
                } else {
                    LJI(activityC45651qj);
                }
            }
            AbstractC72932td<User> abstractC72932td = a7w.LIZIZ.get(c238479Xn);
            if (abstractC72932td instanceof C72912tb) {
                User user = (User) ((C72912tb) abstractC72932td).LIZ;
                a7w.LIZJ.setValue(new C33Y(c238479Xn, abstractC72932td));
                StringBuilder LIZ3 = X1D.LIZ();
                LIZ3.append("post sharer(");
                LIZ3.append(V18.LJII(user));
                LIZ3.append(" from cache!");
                C221018lt.LJFF("@LinkRelation", X1D.LIZIZ(LIZ3));
                return;
            }
            if (abstractC72932td instanceof C72922tc) {
                C221018lt.LJFF("@LinkRelation", "sharer is loading, ignore this request!");
            } else {
                a7w.LIZJ.setValue(new C33Y(c238479Xn, new C72922tc()));
                XKX.LIZLLL(a7w.LIZ, null, null, new C238429Xi(a7w, c238479Xn, null), 3);
            }
        } catch (Exception e) {
            String message = e.getMessage();
            if (message == null) {
                message = "";
            }
            C221018lt.LIZIZ("@LinkRelation", message);
            a7w.LIZJ.setValue(new C33Y(c238479Xn, new C3C1(e)));
        }
    }
}
