package X;

import com.bytedance.android.livesdk.livesetting.performance.LiveLayoutPreloadThreadPriority;
import com.bytedance.android.livesdk.model.AdLiveEnterRoomConfig;
import com.ss.android.ugc.effectmanager.common.utils.FileUtils;

/* loaded from: classes6.dex */
public final class BJL {
    public String LIZ;
    public String LIZIZ;
    public final Long LIZJ;
    public String LIZLLL;
    public String LJ;
    public String LJFF;
    public Boolean LJI;
    public final String LJII;
    public final String LJIIIIZZ;
    public final Long LJIIIZ;
    public final String LJIIJ;
    public final String LJIIJJI;
    public final String LJIIL;
    public final String LJIILIIL;
    public final Long LJIILJJIL;
    public final Long LJIILL;
    public final Long LJIILLIIL;
    public final Long LJIIZILJ;
    public String LJIJ;
    public String LJIJI;
    public final long LJIJJ;
    public final String LJIJJLI;
    public String LJIL;
    public Integer LJJ;
    public String LJJI;
    public String LJJIFFI;
    public String LJJII;
    public String LJJIII;
    public String LJJIIJ;
    public int LJJIIJZLJL;
    public long LJJIIZ;
    public AdLiveEnterRoomConfig LJJIIZI;
    public int LJJIJ;
    public int LJJIJIIJI;
    public final Integer LJJIJIIJIL;
    public final String LJJIJIL;
    public final long LJJIJL;
    public final String LJJIJLIJ;
    public java.util.Map<String, String> LJJIL;
    public final String LJJIZ;
    public final Integer LJJJ;
    public final Integer LJJJI;
    public final Integer LJJJIL;

    public BJL() {
        this(null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0L, null, null, null, null, null, null, null, null, 0, null, 0, 0, null, null, 0L, null, null, null, null, null, null, -1, 65535);
    }

    public BJL(String str, String str2, Long l, String str3, String str4, String str5, Boolean bool, String str6, Long l2, String str7, String str8, String str9, String str10, Long l3, Long l4, Long l5, Long l6, String str11, long j, String str12, String str13, Integer num, String str14, String str15, String str16, String str17, String str18, int i, AdLiveEnterRoomConfig adLiveEnterRoomConfig, int i2, int i3, Integer num2, String str19, long j2, String str20, java.util.Map map, String str21, Integer num3, Integer num4, Integer num5, int i4, int i5) {
        String str22 = str7;
        Long l7 = l2;
        String str23 = str6;
        Boolean bool2 = bool;
        String str24 = str2;
        Long l8 = l;
        String str25 = str3;
        String str26 = str4;
        String str27 = str5;
        Integer num6 = num5;
        Integer num7 = num3;
        String str28 = str21;
        java.util.Map map2 = map;
        long j3 = j2;
        int i6 = i3;
        AdLiveEnterRoomConfig adLiveEnterRoomConfig2 = adLiveEnterRoomConfig;
        int i7 = i;
        String str29 = str18;
        Integer num8 = num4;
        Long l9 = l4;
        String str30 = str19;
        String str31 = str17;
        Long l10 = l3;
        Long l11 = l5;
        long j4 = j;
        String str32 = str8;
        int i8 = i2;
        String str33 = str9;
        Long l12 = l6;
        String str34 = str11;
        String str35 = str13;
        String str36 = str20;
        String str37 = str10;
        Integer num9 = num;
        String str38 = str12;
        Integer num10 = num2;
        String str39 = str14;
        String str40 = str15;
        String str41 = str16;
        String str42 = (i4 & 1) != 0 ? null : str;
        str24 = (i4 & 2) != 0 ? null : str24;
        l8 = (i4 & 4) != 0 ? null : l8;
        str25 = (i4 & 8) != 0 ? null : str25;
        str26 = (i4 & 16) != 0 ? null : str26;
        str27 = (i4 & 32) != 0 ? null : str27;
        bool2 = (i4 & 64) != 0 ? null : bool2;
        str23 = (i4 & 128) != 0 ? null : str23;
        l7 = (i4 & 512) != 0 ? null : l7;
        str22 = (i4 & 1024) != 0 ? null : str22;
        str32 = (i4 & 2048) != 0 ? null : str32;
        str33 = (i4 & 4096) != 0 ? null : str33;
        str37 = (i4 & FileUtils.BUFFER_SIZE) != 0 ? null : str37;
        l10 = (i4 & 16384) != 0 ? -1L : l10;
        l9 = (i4 & 32768) != 0 ? -1L : l9;
        l11 = (65536 & i4) != 0 ? -1L : l11;
        l12 = (131072 & i4) != 0 ? -1L : l12;
        str34 = (524288 & i4) != 0 ? "" : str34;
        j4 = (2097152 & i4) != 0 ? 0L : j4;
        str38 = (4194304 & i4) != 0 ? null : str38;
        str35 = (8388608 & i4) != 0 ? null : str35;
        num9 = (i4 & 33554432) != 0 ? 0 : num9;
        str39 = (67108864 & i4) != 0 ? null : str39;
        str40 = (134217728 & i4) != 0 ? null : str40;
        str41 = (268435456 & i4) != 0 ? null : str41;
        str31 = (536870912 & i4) != 0 ? null : str31;
        str29 = (1073741824 & i4) != 0 ? null : str29;
        i7 = (i4 & LiveLayoutPreloadThreadPriority.DEFAULT) != 0 ? -1 : i7;
        adLiveEnterRoomConfig2 = (i5 & 8) != 0 ? null : adLiveEnterRoomConfig2;
        i8 = (i5 & 16) != 0 ? 0 : i8;
        i6 = (i5 & 32) != 0 ? 0 : i6;
        num10 = (i5 & 128) != 0 ? null : num10;
        str30 = (i5 & 256) != 0 ? null : str30;
        j3 = (i5 & 512) != 0 ? -1L : j3;
        str36 = (i5 & 1024) != 0 ? null : str36;
        map2 = (i5 & 2048) != 0 ? null : map2;
        str28 = (i5 & 4096) != 0 ? null : str28;
        num7 = (i5 & FileUtils.BUFFER_SIZE) != 0 ? null : num7;
        num8 = (i5 & 16384) != 0 ? null : num8;
        num6 = (i5 & 32768) != 0 ? null : num6;
        this.LIZ = str42;
        this.LIZIZ = str24;
        this.LIZJ = l8;
        this.LIZLLL = str25;
        this.LJ = str26;
        this.LJFF = str27;
        this.LJI = bool2;
        this.LJII = str23;
        this.LJIIIIZZ = null;
        this.LJIIIZ = l7;
        this.LJIIJ = str22;
        this.LJIIJJI = str32;
        this.LJIIL = str33;
        this.LJIILIIL = str37;
        this.LJIILJJIL = l10;
        this.LJIILL = l9;
        this.LJIILLIIL = l11;
        this.LJIIZILJ = l12;
        this.LJIJ = null;
        this.LJIJI = str34;
        this.LJIJJ = j4;
        this.LJIJJLI = str38;
        this.LJIL = str35;
        this.LJJ = num9;
        this.LJJI = str39;
        this.LJJIFFI = str40;
        this.LJJII = str41;
        this.LJJIII = str31;
        this.LJJIIJ = str29;
        this.LJJIIJZLJL = i7;
        this.LJJIIZ = 0L;
        this.LJJIIZI = adLiveEnterRoomConfig2;
        this.LJJIJ = i8;
        this.LJJIJIIJI = i6;
        this.LJJIJIIJIL = num10;
        this.LJJIJIL = str30;
        this.LJJIJL = j3;
        this.LJJIJLIJ = str36;
        this.LJJIL = map2;
        this.LJJIZ = str28;
        this.LJJJ = num7;
        this.LJJJI = num8;
        this.LJJJIL = num6;
    }
}
