package X;

/* renamed from: X.0HD, reason: invalid class name */
/* loaded from: classes.dex */
public final class C0HD {
    public static final C0HE LIZ;
    public static final C0HE LIZIZ;
    public static final C0HE LIZJ;
    public static final C0HE LIZLLL;
    public static final C0HE LJ;
    public static final C0HE LJFF;
    public static final C0HE LJI;
    public static final C0HE LJII;
    public static final C0HE LJIIIIZZ;
    public static final C0HE LJIIIZ;
    public static final C0HE LJIIJ;
    public static final C0HE LJIIJJI;
    public static final C0HE LJIIL;
    public static final C0HE LJIILIIL;
    public static final C0HE LJIILJJIL;
    public static final C0HE LJIILL;
    public static final C0HE LJIILLIIL;
    public static final C0HE LJIIZILJ;
    public static final C0HE LJIJ;
    public static final C0HE LJIJI;
    public static final C0HE LJIJJ;
    public static final C0HE LJIJJLI;
    public static final C0HE LJIL;

    static {
        C0HC LIZ2 = C0HE.LIZ();
        LIZ2.LIZ = 3;
        LIZ2.LIZIZ = "Google Play In-app Billing API version is less than 3";
        LIZ = LIZ2.LIZ();
        C0HC LIZ3 = C0HE.LIZ();
        LIZ3.LIZ = 3;
        LIZ3.LIZIZ = "Google Play In-app Billing API version is less than 9";
        LIZIZ = LIZ3.LIZ();
        C0HC LIZ4 = C0HE.LIZ();
        LIZ4.LIZ = 3;
        LIZ4.LIZIZ = "Billing service unavailable on device.";
        LIZJ = LIZ4.LIZ();
        C0HC LIZ5 = C0HE.LIZ();
        LIZ5.LIZ = 5;
        LIZ5.LIZIZ = "Client is already in the process of connecting to billing service.";
        LIZLLL = LIZ5.LIZ();
        C0HC LIZ6 = C0HE.LIZ();
        LIZ6.LIZ = 5;
        LIZ6.LIZIZ = "The list of SKUs can't be empty.";
        LJ = LIZ6.LIZ();
        C0HC LIZ7 = C0HE.LIZ();
        LIZ7.LIZ = 5;
        LIZ7.LIZIZ = "SKU type can't be empty.";
        LJFF = LIZ7.LIZ();
        C0HC LIZ8 = C0HE.LIZ();
        LIZ8.LIZ = 5;
        LIZ8.LIZIZ = "Product type can't be empty.";
        LJI = LIZ8.LIZ();
        C0HC LIZ9 = C0HE.LIZ();
        LIZ9.LIZ = -2;
        LIZ9.LIZIZ = "Client does not support extra params.";
        LJII = LIZ9.LIZ();
        C0HC LIZ10 = C0HE.LIZ();
        LIZ10.LIZ = 5;
        LIZ10.LIZIZ = "Invalid purchase token.";
        LJIIIIZZ = LIZ10.LIZ();
        C0HC LIZ11 = C0HE.LIZ();
        LIZ11.LIZ = 6;
        LIZ11.LIZIZ = "An internal error occurred.";
        LJIIIZ = LIZ11.LIZ();
        C0HC LIZ12 = C0HE.LIZ();
        LIZ12.LIZ = 5;
        LIZ12.LIZIZ = "SKU can't be null.";
        LIZ12.LIZ();
        C0HC LIZ13 = C0HE.LIZ();
        LIZ13.LIZ = 0;
        LJIIJ = LIZ13.LIZ();
        C0HC LIZ14 = C0HE.LIZ();
        LIZ14.LIZ = -1;
        LIZ14.LIZIZ = "Service connection is disconnected.";
        LJIIJJI = LIZ14.LIZ();
        C0HC LIZ15 = C0HE.LIZ();
        LIZ15.LIZ = -3;
        LIZ15.LIZIZ = "Timeout communicating with service.";
        LJIIL = LIZ15.LIZ();
        C0HC LIZ16 = C0HE.LIZ();
        LIZ16.LIZ = -2;
        LIZ16.LIZIZ = "Client does not support subscriptions.";
        LJIILIIL = LIZ16.LIZ();
        C0HC LIZ17 = C0HE.LIZ();
        LIZ17.LIZ = -2;
        LIZ17.LIZIZ = "Client does not support subscriptions update.";
        LJIILJJIL = LIZ17.LIZ();
        C0HC LIZ18 = C0HE.LIZ();
        LIZ18.LIZ = -2;
        LIZ18.LIZIZ = "Client does not support get purchase history.";
        LIZ18.LIZ();
        C0HC LIZ19 = C0HE.LIZ();
        LIZ19.LIZ = -2;
        LIZ19.LIZIZ = "Client does not support price change confirmation.";
        LJIILL = LIZ19.LIZ();
        C0HC LIZ20 = C0HE.LIZ();
        LIZ20.LIZ = -2;
        LIZ20.LIZIZ = "Play Store version installed does not support cross selling products.";
        LJIILLIIL = LIZ20.LIZ();
        C0HC LIZ21 = C0HE.LIZ();
        LIZ21.LIZ = -2;
        LIZ21.LIZIZ = "Client does not support multi-item purchases.";
        LJIIZILJ = LIZ21.LIZ();
        C0HC LIZ22 = C0HE.LIZ();
        LIZ22.LIZ = -2;
        LIZ22.LIZIZ = "Client does not support offer_id_token.";
        LJIJ = LIZ22.LIZ();
        C0HC LIZ23 = C0HE.LIZ();
        LIZ23.LIZ = -2;
        LIZ23.LIZIZ = "Client does not support ProductDetails.";
        LJIJI = LIZ23.LIZ();
        C0HC LIZ24 = C0HE.LIZ();
        LIZ24.LIZ = -2;
        LIZ24.LIZIZ = "Client does not support in-app messages.";
        LJIJJ = LIZ24.LIZ();
        C0HC LIZ25 = C0HE.LIZ();
        LIZ25.LIZ = -2;
        LIZ25.LIZIZ = "Client does not support alternative billing.";
        LIZ25.LIZ();
        C0HC LIZ26 = C0HE.LIZ();
        LIZ26.LIZ = 5;
        LIZ26.LIZIZ = "Unknown feature";
        LJIJJLI = LIZ26.LIZ();
        C0HC LIZ27 = C0HE.LIZ();
        LIZ27.LIZ = -2;
        LIZ27.LIZIZ = "Play Store version installed does not support get billing config.";
        LJIL = LIZ27.LIZ();
    }
}
