package X;

import com.bytedance.android.livesdk.livesetting.broadcast.LiveTryModeCountDownThresholdSetting;
import com.bytedance.android.livesdk.livesetting.pullstream.LiveNetAdaptiveHurryTimeSetting;
import com.bytedance.im.core.client.IMSdkTraceConfig;
import com.bytedance.im.core.client.OptimizeConvListPullConfig;
import com.bytedance.im.core.client.RecentLinkConfig;
import com.bytedance.im.core.client.ReportDBInfoConfig;
import com.bytedance.im.core.client.ReportTaskInfoConfig;
import com.bytedance.im.core.repair.completeness.IMCompletenessConfiguration;
import java.util.ArrayList;
import java.util.List;

/* renamed from: X.4eO, reason: invalid class name and case insensitive filesystem */
/* loaded from: classes2.dex */
public final class C114444eO {
    public boolean LIZ;
    public boolean LIZJ;
    public boolean LIZLLL;
    public boolean LJ;
    public int LJFF;
    public String LJI;
    public String LJIIIIZZ;
    public int LJIIJJI;
    public int LJIILJJIL;
    public int LJIILLIIL;
    public int[] LJIJ;
    public int LJIJJ;
    public boolean LJIL;
    public boolean LJJ;
    public boolean LJJIIZ;
    public ReportTaskInfoConfig LJJJI;
    public boolean LJJJIL;
    public final int LJJJJ;
    public int LJJJJI;
    public final int LJJJJIZL;
    public final int LJJJJJ;
    public boolean LJJJJJL;
    public final long LJJJJL;
    public final IMSdkTraceConfig LJJJJLI;
    public final C2P0 LJJJJLL;
    public boolean LJJJJZ;
    public final boolean LJJJJZI;
    public final boolean LJJJLIIL;
    public final double LJJJLL;
    public final boolean LJJJLZIJ;
    public boolean LJJJZ;
    public boolean LJJL;
    public boolean LJJLI;
    public boolean LJJLIIIIJ;
    public C4N5 LJJLIIIJ;
    public final boolean LJJLIIIJILLIZJL;
    public boolean LJJLIIIJJI;
    public boolean LJJLIIIJJIZ;
    public boolean LJJLIIIJL;
    public final long LJJLIIIJLJLI;
    public boolean LJJLIIIJLLLLLLLZ;
    public boolean LJJLIIJ;
    public int LJJLIL;
    public int LJJLJ;
    public boolean LJJLJLI;
    public boolean LJJLL;
    public boolean LJJZ;
    public boolean LJJZZI;
    public boolean LJJZZIII;
    public boolean LJL;
    public boolean LJLI;
    public long LJLIIIL;
    public boolean LJLIIL;
    public boolean LJLIL;
    public boolean LJLILLLLZI;
    public int LJLJI;
    public boolean LJLJJI;
    public boolean LJLJJL;
    public boolean LJLJJLL;
    public int LJLJL;
    public List<Integer> LJLJLJ;
    public List<Integer> LJLJLLL;
    public List<Integer> LJLL;
    public boolean LJLLI;
    public boolean LJLLILLLL;
    public boolean LJLLJ;
    public boolean LJLLL;
    public boolean LJLLLL;
    public boolean LJLLLLLL;
    public IMCompletenessConfiguration LJLZ;
    public boolean LJZ;
    public boolean LJZI;
    public int LIZIZ = 2;
    public final boolean LJII = true;
    public final int LJIIIZ = 6144;
    public final int LJIIJ = 1024;
    public int LJIIL = 3;
    public int LJIILIIL = 1000;
    public int LJIILL = LiveNetAdaptiveHurryTimeSetting.DEFAULT;
    public int[] LJIIZILJ = {0};
    public boolean LJIJI = true;
    public final int LJIJJLI = 1;
    public int LJJI = 20;
    public String LJJIFFI = "";
    public boolean LJJII = true;
    public final int LJJIII = LiveNetAdaptiveHurryTimeSetting.DEFAULT;
    public final int LJJIIJ = -1;
    public int LJJIIJZLJL = -1;
    public final boolean LJJIIZI = true;
    public C63615Oxv LJJIJ = new C63615Oxv(LiveTryModeCountDownThresholdSetting.DEFAULT, 3, 300);
    public long LJJIJIIJI = 1000;
    public OptimizeConvListPullConfig LJJIJIIJIL = new OptimizeConvListPullConfig();
    public final int LJJIJIL = 30;
    public boolean LJJIJL = false;
    public boolean LJJIJLIJ = false;
    public final RecentLinkConfig LJJIL = new RecentLinkConfig();
    public final boolean LJJIZ = true;
    public int LJJJ = 0;

    public C114444eO() {
        new ReportDBInfoConfig();
        this.LJJJI = new ReportTaskInfoConfig();
        this.LJJJIL = false;
        this.LJJJJ = 10;
        this.LJJJJI = 1;
        this.LJJJJIZL = 50;
        this.LJJJJJ = 1;
        this.LJJJJJL = false;
        this.LJJJJL = 2000L;
        this.LJJJJLI = IMSdkTraceConfig.DEFAULT;
        this.LJJJJLL = C2P0.LIZIZ;
        this.LJJJJZ = false;
        this.LJJJJZI = true;
        this.LJJJLIIL = true;
        this.LJJJLL = 1.0d;
        this.LJJJLZIJ = true;
        this.LJJJZ = false;
        this.LJJL = false;
        this.LJJLI = false;
        this.LJJLIIIIJ = false;
        this.LJJLIIIJ = null;
        this.LJJLIIIJILLIZJL = true;
        this.LJJLIIIJJI = false;
        this.LJJLIIIJJIZ = false;
        this.LJJLIIIJL = false;
        this.LJJLIIIJLJLI = 20L;
        this.LJJLIIIJLLLLLLLZ = false;
        this.LJJLIIJ = false;
        this.LJJLIL = 0;
        this.LJJLJ = 100;
        this.LJJLJLI = false;
        this.LJJLL = true;
        this.LJJZ = false;
        this.LJJZZI = true;
        this.LJJZZIII = false;
        this.LJL = false;
        this.LJLI = false;
        this.LJLIIIL = 5000L;
        this.LJLIIL = true;
        this.LJLIL = false;
        this.LJLILLLLZI = false;
        this.LJLJI = 1;
        this.LJLJJI = true;
        this.LJLJJL = false;
        this.LJLJJLL = false;
        this.LJLJL = 10;
        this.LJLJLJ = new ArrayList();
        this.LJLJLLL = new ArrayList();
        this.LJLL = new ArrayList();
        this.LJLLI = false;
        this.LJLLILLLL = false;
        this.LJLLJ = false;
        this.LJLLL = false;
        this.LJLLLL = false;
        this.LJLLLLLL = false;
        this.LJLZ = new IMCompletenessConfiguration();
        this.LJZ = false;
        this.LJZI = false;
    }
}
