package X;

import android.content.Context;
import android.content.Intent;
import android.content.res.AssetManager;
import com.bytedance.android.livesdk.model.ByteAudioConfig;

/* renamed from: X.0gv, reason: invalid class name and case insensitive filesystem */
/* loaded from: classes.dex */
public final class C14090gv {
    public final Context LIZ;
    public final String LIZIZ;
    public final int LIZJ;
    public final int LIZLLL;
    public final int LJ;
    public final int LJFF;
    public final int LJI;
    public final int LJII;
    public final int LJIIIIZZ;
    public final int LJIIIZ;
    public final int LJIIJ;
    public final int LJIIJJI;
    public final int LJIIL;
    public final boolean LJIILIIL;
    public final int LJIILJJIL;
    public final int LJIILL;
    public final long LJIILLIIL;
    public final int LJIIZILJ;
    public final int LJIJ;
    public final InterfaceC15330iv LJIJI;
    public final InterfaceC15340iw LJIJJ;
    public final Intent LJIJJLI;
    public final int LJIL;
    public final int LJJ;
    public final ByteAudioConfig LJJI;
    public final int LJJIFFI;
    public final float LJJII;
    public final boolean LJJIII;
    public final int LJJIIJ;
    public final boolean LJJIIJZLJL;
    public final boolean LJJIIZ;
    public final String LJJIIZI;
    public final boolean LJJIJ;
    public final String LJJIJIIJI;
    public String LJJIJIIJIL;
    public final AssetManager LJJIJIL;
    public final Object LJJIJL;
    public final String LJJIJLIJ;
    public final boolean LJJIL;
    public final int LJJIZ;
    public final String LJJJ;
    public final boolean LJJJI;
    public final boolean LJJJIL;
    public final boolean LJJJJ;
    public final boolean LJJJJI;
    public final boolean LJJJJIZL;
    public final boolean LJJJJJ;
    public final int LJJJJJL;
    public final boolean LJJJJL;

    public C14090gv(C14080gu c14080gu) {
        this.LJJIII = true;
        this.LJJJJI = true;
        this.LJJJJJL = -1;
        this.LIZ = c14080gu.LIZ;
        this.LIZIZ = c14080gu.LIZIZ;
        this.LIZJ = c14080gu.LIZJ;
        this.LIZLLL = c14080gu.LIZLLL;
        this.LJ = c14080gu.LJ;
        this.LJFF = c14080gu.LJFF;
        this.LJI = c14080gu.LJI;
        this.LJII = c14080gu.LJII;
        this.LJIIIIZZ = c14080gu.LJIIIIZZ;
        this.LJIIJJI = c14080gu.LJIIIZ;
        this.LJIIL = c14080gu.LJIIJ;
        this.LJIILIIL = c14080gu.LJIIJJI;
        this.LJIILJJIL = c14080gu.LJIIL;
        this.LJIILL = c14080gu.LJIILIIL;
        this.LJIILLIIL = c14080gu.LJIILJJIL;
        this.LJIIZILJ = c14080gu.LJIILL;
        this.LJIJ = c14080gu.LJIILLIIL;
        this.LJIJI = c14080gu.LJJIJ;
        this.LJIJJ = c14080gu.LJIJJLI;
        this.LJIJJLI = c14080gu.LJIIZILJ;
        this.LJIL = c14080gu.LJIJ;
        this.LJJ = c14080gu.LJIJI;
        this.LJJI = c14080gu.LJIJJ;
        this.LJJIFFI = c14080gu.LJIL;
        this.LJJIJIIJI = c14080gu.LJJ;
        this.LJJII = c14080gu.LJJI;
        this.LJJIII = c14080gu.LJJIFFI;
        this.LJJIIJ = c14080gu.LJJII;
        this.LJJIIJZLJL = c14080gu.LJJIII;
        this.LJJIIZ = c14080gu.LJJIIJ;
        this.LJJIIZI = c14080gu.LJJIIJZLJL;
        this.LJJIJ = c14080gu.LJJIIZ;
        this.LJJIJIIJIL = c14080gu.LJJIIZI;
        this.LJJIJIL = c14080gu.LJJIJIIJIL;
        this.LJJIJLIJ = c14080gu.LJJIJIL;
        this.LJJIJL = c14080gu.LJJIJL;
        this.LJJIL = c14080gu.LJJIJLIJ;
        this.LJIIJ = c14080gu.LJJIZ;
        this.LJIIIZ = c14080gu.LJJIL;
        this.LJJIZ = c14080gu.LJJJ;
        this.LJJJ = c14080gu.LJJJI;
        this.LJJJI = c14080gu.LJJJIL;
        this.LJJJIL = c14080gu.LJJJJ;
        this.LJJJJ = c14080gu.LJJJJI;
        this.LJJJJI = c14080gu.LJJJJIZL;
        this.LJJJJIZL = c14080gu.LJJJJL;
        this.LJJJJJ = c14080gu.LJJJJLI;
        this.LJJJJJL = c14080gu.LJJJJJ;
        this.LJJJJL = c14080gu.LJJJJJL;
    }
}
