package X;

import android.content.Context;
import kotlin.jvm.internal.o;

/* renamed from: X.6n3, reason: invalid class name and case insensitive filesystem */
/* loaded from: classes3.dex */
public final class C170776n3 {
    public static final Object LIZ;
    public static final String LIZIZ;

    static {
        Context context = C1280550v.LIZ().LIZ().LIZIZ;
        o.LJI(context);
        String absolutePath = C16880lQ.LLIIJLIL(context).getAbsolutePath();
        Object obj = "";
        if (absolutePath == null) {
            absolutePath = "";
        }
        Context context2 = C1280550v.LIZ().LIZ().LIZIZ;
        o.LJI(context2);
        Object LLIIJI = C16880lQ.LLIIJI(context2, null);
        if (LLIIJI != null) {
            obj = LLIIJI;
        }
        LIZ = obj;
        StringBuilder LIZ2 = X1D.LIZ();
        LIZ2.append(absolutePath);
        LIZ2.append("/newdrafts");
        X1D.LIZIZ(LIZ2);
        StringBuilder LIZ3 = X1D.LIZ();
        LIZ3.append(absolutePath);
        LIZ3.append("/downloadAudio/");
        X1D.LIZIZ(LIZ3);
        StringBuilder LIZ4 = X1D.LIZ();
        LIZ4.append(absolutePath);
        LIZ4.append("/downloadSound/");
        X1D.LIZIZ(LIZ4);
        StringBuilder LIZ5 = X1D.LIZ();
        LIZ5.append(absolutePath);
        LIZ5.append("/downloadMusic/");
        X1D.LIZIZ(LIZ5);
        StringBuilder LIZ6 = X1D.LIZ();
        LIZ6.append(absolutePath);
        LIZ6.append("/downloadMaterial/");
        X1D.LIZIZ(LIZ6);
        StringBuilder LIZ7 = X1D.LIZ();
        LIZ7.append(absolutePath);
        LIZ7.append("/downloadTemplateVideo/");
        X1D.LIZIZ(LIZ7);
        StringBuilder LIZ8 = X1D.LIZ();
        LIZ8.append(absolutePath);
        LIZ8.append("/downloadGuideVideo/");
        X1D.LIZIZ(LIZ8);
        StringBuilder LIZ9 = X1D.LIZ();
        LIZ9.append(absolutePath);
        LIZ9.append("/downloadGuide/");
        X1D.LIZIZ(LIZ9);
        StringBuilder LIZ10 = X1D.LIZ();
        LIZ10.append(absolutePath);
        LIZ10.append("/templatetmp/");
        X1D.LIZIZ(LIZ10);
        StringBuilder LIZ11 = X1D.LIZ();
        LIZ11.append(absolutePath);
        LIZ11.append("/uploadtmp/");
        X1D.LIZIZ(LIZ11);
        StringBuilder LIZ12 = X1D.LIZ();
        LIZ12.append(absolutePath);
        LIZ12.append("/text/");
        X1D.LIZIZ(LIZ12);
        StringBuilder LIZ13 = X1D.LIZ();
        LIZ13.append(absolutePath);
        LIZ13.append("/effect/");
        X1D.LIZIZ(LIZ13);
        StringBuilder LIZ14 = X1D.LIZ();
        LIZ14.append(absolutePath);
        LIZ14.append("/canvas/");
        X1D.LIZIZ(LIZ14);
        StringBuilder LIZ15 = X1D.LIZ();
        LIZ15.append(absolutePath);
        LIZ15.append("/local_canvas/");
        X1D.LIZIZ(LIZ15);
        StringBuilder LIZ16 = X1D.LIZ();
        LIZ16.append(absolutePath);
        LIZ16.append("/cache/");
        X1D.LIZIZ(LIZ16);
        StringBuilder LIZ17 = X1D.LIZ();
        LIZ17.append(absolutePath);
        LIZ17.append("/audio/");
        X1D.LIZIZ(LIZ17);
        StringBuilder LIZ18 = X1D.LIZ();
        LIZ18.append(absolutePath);
        LIZ18.append("/enhance/");
        X1D.LIZIZ(LIZ18);
        StringBuilder LIZ19 = X1D.LIZ();
        LIZ19.append(absolutePath);
        LIZ19.append("/reverse/");
        X1D.LIZIZ(LIZ19);
        StringBuilder LIZ20 = X1D.LIZ();
        LIZ20.append(absolutePath);
        LIZ20.append("/cartoon/");
        X1D.LIZIZ(LIZ20);
        StringBuilder LIZ21 = X1D.LIZ();
        LIZ21.append(obj);
        LIZ21.append("/disk_cache/");
        LIZIZ = X1D.LIZIZ(LIZ21);
        StringBuilder LIZ22 = X1D.LIZ();
        LIZ22.append(obj);
        LIZ22.append("/export");
        X1D.LIZIZ(LIZ22);
        StringBuilder LIZ23 = X1D.LIZ();
        LIZ23.append(absolutePath);
        LIZ23.append("/epilogue/");
        String LIZIZ2 = X1D.LIZIZ(LIZ23);
        StringBuilder LIZ24 = X1D.LIZ();
        LIZ24.append(absolutePath);
        LIZ24.append("/cut_same_workspace");
        X1D.LIZIZ(LIZ24);
        StringBuilder LIZ25 = X1D.LIZ();
        LIZ25.append(absolutePath);
        LIZ25.append("/replicate_tmp/");
        X1D.LIZIZ(LIZ25);
        StringBuilder LIZ26 = X1D.LIZ();
        LIZ26.append(absolutePath);
        LIZ26.append("/clouddraft/");
        X1D.LIZIZ(LIZ26);
        StringBuilder LIZ27 = X1D.LIZ();
        LIZ27.append(LIZIZ2);
        LIZ27.append("epilogue2.mp4");
        X1D.LIZIZ(LIZ27);
        StringBuilder LIZ28 = X1D.LIZ();
        LIZ28.append(LIZIZ2);
        LIZ28.append("epilogue_anim");
        X1D.LIZIZ(LIZ28);
        StringBuilder LIZ29 = X1D.LIZ();
        LIZ29.append(LIZIZ2);
        LIZ29.append("anim_in");
        X1D.LIZIZ(LIZ29);
        StringBuilder LIZ30 = X1D.LIZ();
        LIZ30.append(LIZIZ2);
        LIZ30.append("epilogue_anim.zip");
        X1D.LIZIZ(LIZ30);
        StringBuilder LIZ31 = X1D.LIZ();
        LIZ31.append(LIZIZ2);
        LIZ31.append("anim_in.zip");
        X1D.LIZIZ(LIZ31);
        StringBuilder LIZ32 = X1D.LIZ();
        LIZ32.append(absolutePath);
        LIZ32.append("/frame/");
        X1D.LIZIZ(LIZ32);
        StringBuilder LIZ33 = X1D.LIZ();
        LIZ33.append(absolutePath);
        LIZ33.append("/media_tag_cache/");
        X1D.LIZIZ(LIZ33);
    }
}
