package X;

import Y.ARunnableS1S0010000_6;
import android.support.v4.media.session.PlaybackStateCompat;
import com.bytedance.android.livesdk.livesetting.broadcast.LiveMaxRetainAlogMessageSizeSetting;
import com.bytedance.android.livesdk.livesetting.performance.LivePlayEnforceIntervalSetting;
import com.bytedance.ies.abmock.ClientExpManager;
import com.bytedance.ies.abmock.SettingsManager;
import com.bytedance.ies.ugc.aweme.commercialize.splash.core.SplashAdServiceImpl;
import com.bytedance.ies.ugc.aweme.commercialize.splash.service.ISplashAdService;
import com.bytedance.ies.ugc.statisticlogger.config.AppLogSendCallbackConfig;
import com.bytedance.keva.Keva;
import com.ss.android.ugc.aweme.ab.WebSocketInitExperiment;
import com.ss.android.ugc.aweme.account.experiment.AccountFeatureFlagService;
import com.ss.android.ugc.aweme.app.host.AwemeHostApplication;
import com.ss.android.ugc.aweme.dmt_integration.AVInitializerImpl;
import com.ss.android.ugc.aweme.ecommerce.mall.ECommerceMallService;
import com.ss.android.ugc.aweme.experiment.FollowFeedViewStubExperiment;
import com.ss.android.ugc.aweme.experiment.ReDexExperimentOpt;
import com.ss.android.ugc.aweme.experiment.ViewStubOptExperiment;
import com.ss.android.ugc.aweme.experiment.ViewStubOptExperimentV2;
import com.ss.android.ugc.aweme.friendstab.experiment.FriendsTabTopExperiment;
import com.ss.android.ugc.aweme.legoImp.ClientSLIDataUploader;
import com.ss.android.ugc.aweme.relation.recuser.IRecUserService;
import com.ss.android.ugc.aweme.relation.recuser.RecUserServiceImpl;
import com.ss.android.ugc.aweme.settings.SparkEcomOptimizeExperiment;
import com.ss.android.ugc.aweme.settings.SparkWebViewOptimizeExperiment;
import com.ss.android.ugc.feed.platform.componentmanager.data.FeedComponentsData;
import com.ss.android.ugc.feed.platform.componentmanager.data.FeedMultiSceneComponentsData;
import defpackage.e1;

/* renamed from: X.Dnc, reason: case insensitive filesystem */
/* loaded from: classes7.dex */
public final class C34948Dnc {
    public static void LIZ() {
        if (System.currentTimeMillis() - C35007DoZ.LIZ.LIZ().getLong("clear_timestamp", 0L) < 21600000) {
            return;
        }
        C35007DoZ.LIZIZ.LIZ().edit().putBoolean("trigger_launch_protect_drill_crash", e1.LIZ(31744, "trigger_launch_protect_drill_crash", true, false)).apply();
    }

    public static void LIZIZ() {
        Keva repo = Keva.getRepo("ab_repo_cold_boot_muti");
        FFL.LJIIIZ().getClass();
        boolean z = true;
        repo.storeInt("zl_gunda_opt", FFL.LJIIJ(31744, 846, "zl_gunda_opt", true));
        FFL.LJIIIZ().getClass();
        int LJIIJ = FFL.LJIIJ(31744, 1, "zl_fill_stack1", true);
        repo.storeInt("zl_fill_stack1", LJIIJ);
        FFL.LJIIIZ().getClass();
        C279117r.LIZLLL(31744, 1, "zl_opt_anonymous1", true, repo, "zl_opt_anonymous1");
        C279117r.LIZLLL(31744, 1, "zl_crash_hold", true, repo, "zl_crash_hold");
        C279117r.LIZLLL(31744, 20000, "zl_jit_block_launch_time2", true, repo, "zl_jit_block_launch_time2");
        C279117r.LIZLLL(31744, -1, "zl_jit_block_interval_time2", true, repo, "zl_jit_block_interval_time2");
        C279117r.LIZLLL(31744, -1, "zl_jit_block_priority2", true, repo, "zl_jit_block_priority2");
        repo.storeInt("zl_string_builder", FFL.LJIIJ(31744, 1, "zl_string_builder", true));
        if ((LJIIJ & 2) == 0) {
            z = false;
        }
        C37179EiV.LJFF.post(new ARunnableS1S0010000_6(z, 2));
    }

    public static void LIZJ() {
        boolean LIZ = C34639Did.LIZ();
        long LIZIZ = DNV.LIZIZ();
        if (LIZ) {
            try {
                Thread.sleep(LIZIZ);
            } catch (Exception unused) {
            }
        }
        Keva fin = ((Number) C34585Dhl.LIZ.getValue()).intValue() == 1 ? new FIN(Keva.getRepo(FollowFeedViewStubExperiment.REPO_NAME)) : Keva.getRepo(FollowFeedViewStubExperiment.REPO_NAME);
        FFL.LJIIIZ().getClass();
        fin.storeInt("optimize_user_service", FFL.LJIIJ(31744, 2, "optimize_user_service_option", true));
        FFL.LJIIIZ().getClass();
        C279117r.LIZLLL(31744, 0, "key_preload_player_1", true, fin, "key_preload_player_1");
        C279017q.LIZJ(31744, "key_get_player_config", true, false, fin, "key_get_player_config");
        C279117r.LIZLLL(31744, 0, "key_opt_precreate_lock", true, fin, "key_opt_precreate_lock");
        fin.storeBoolean("key_new_fps", FFL.LJIIJ(31744, 1, "new_fps", true) == 1);
        FFL.LJIIIZ().getClass();
        C279017q.LIZJ(31744, "async_audio_request_focus_ab", true, false, fin, "async_audio_opt_ab_enabled");
        C279017q.LIZJ(31744, "disable_audio_manager_helper", true, false, fin, "audio_focus_opt_ab");
        C279017q.LIZJ(31744, "sp_queued_work_anr_ab_v2", true, false, fin, "sp_queued_work_ab");
        C279017q.LIZJ(31744, "sp_async_queued_work", true, true, fin, "sp_queued_work_async_opt");
        fin.storeInt("zl_async_inflate", FFL.LJIIJ(31744, 1074, "zl_async_inflate", true));
        C35820E4a.LIZLLL(FKM.LIZ()).edit().putBoolean("isInTikTokRegionForAbTestInit", C85990Xow.LJIIIZ()).apply();
        fin.storeBoolean("isInTikTokRegionForAbTestInit", C85990Xow.LJIIIZ());
        FFL.LJIIIZ().getClass();
        C279117r.LIZLLL(31744, 2, "is_opt_lego_schedule", true, fin, "is_opt_lego_schedule");
        C279117r.LIZLLL(31744, 1, "is_opt_lego_add_v2", true, fin, "is_opt_lego_add_v2");
        C279117r.LIZLLL(31744, 5825, "cold_boot_opt_v3", true, fin, "cold_boot_opt_v3");
        C279117r.LIZLLL(31744, 0, "first_feed_ok", true, fin, "first_feed_ok");
        C279117r.LIZLLL(31744, 0, "jump_cookie", true, fin, "jump_cookie");
        C279117r.LIZLLL(31744, 5, "npth_refactor", true, fin, "npth_refactor");
        C279117r.LIZLLL(31744, 0, "sky_eye_gson_flip", true, fin, "sky_eye_gson_flip");
        C279117r.LIZLLL(31744, 2, "cold_boot_degradation", true, fin, "cold_boot_degradation");
        C279117r.LIZLLL(31744, 0, "optimize_user_store_option", true, fin, "key_optimize_user_store");
        C279117r.LIZLLL(31744, 59, "push_start_opt_v1", true, fin, "push_start_opt_v1");
        fin.storeInt("init_module_opt", FFL.LJIIJ(31744, 2, "init_module_opt", true));
        fin.storeBoolean("open_new_anr_monitor_v2", C30591Hz.LJIIZILJ());
        fin.storeBoolean("cursor_window_shrink", C78977Uz7.LJJJJZ());
        fin.storeInt("feed_preload_request", FFL.LJIIIZ().LJIIJJI(ClientExpManager.new_user_nonuj_feed_preload_opt(), "new_user_nonuj_feed_preload_opt"));
        FFL.LJIIIZ().getClass();
        fin.storeInt("feed_preload_opt", FFL.LJIIJ(31744, 0, "feed_preload_opt", true));
        FKN.LIZJ();
        fin.storeBoolean("optimize_preinituser", true);
        fin.storeBoolean("optimize_splashad_early", C34498DgM.LIZ);
        fin.storeInt("apm_thread_opt_type", C35044DpA.LIZJ());
        fin.storeBoolean("apm_net_monitor_opt", C35035Dp1.LIZ());
        fin.storeBoolean("hybrid_monitor_regex_opt", C35012Doe.LIZ());
        fin.storeBoolean("apm_sdk_monitor_opt", C35015Doh.LIZ());
        fin.storeInt("apm_event_cache_opt", C34162Daw.LIZ());
        fin.storeBoolean("apm_terminal_monitor_opt", C35032Doy.LIZIZ());
        fin.storeBoolean("optimize_av_early", C34495DgJ.LIZ);
        fin.storeBoolean("optimize_appfly_early", C34496DgK.LIZ);
        fin.storeBoolean("optimize_async_splitcompatinstall", C34802DlG.LIZ);
        fin.storeBoolean("optimize_newuserjourney", C34813DlR.LIZ);
        fin.storeBoolean("optimize_newuserjourneyelaborate", C34812DlQ.LIZ);
        fin.storeBoolean("optimize_personalize", C34816DlU.LIZ);
        fin.storeBoolean("optimize_storykeva", C34803DlH.LIZ);
        FFL.LJIIIZ().getClass();
        fin.storeBoolean("thread_stack_opt", FFL.LJ(31744, "thread_stack_opt", true, true));
        fin.storeBoolean("optimize_x2cpreloadtabs", C34976Do4.LIZ);
        IRecUserService LJIILLIIL = RecUserServiceImpl.LJIILLIIL();
        if (LJIILLIIL != null && LJIILLIIL.LIZIZ() != null) {
            LJIILLIIL.LIZIZ().LIZIZ();
        }
        C77266UUc.LIZIZ.LJIILIIL();
        FFL.LJIIIZ().getClass();
        fin.storeInt("cold_boot_mainfragment_opt", FFL.LJIIJ(31744, 2, "cold_boot_mainfragment_opt", true));
        FFL.LJIIIZ().getClass();
        C279117r.LIZLLL(31744, 0, "xjl_feed_refresh_populate_opt", true, fin, "xjl_feed_refresh_populate_opt");
        fin.storeBoolean("no_network_opt", FFL.LJ(31744, "no_network_opt", true, false));
        SettingsManager.LIZLLL().getClass();
        fin.storeBoolean("optimize_dead_system", SettingsManager.LIZ("dead_system_solution", true));
        SettingsManager.LIZLLL().getClass();
        fin.storeBoolean("optimize_webview", SettingsManager.LIZ("preload_webview", false));
        FFL.LJIIIZ().getClass();
        C279017q.LIZJ(31744, "v1_uninstall_enable", true, true, fin, "v1_uninstall_enable");
        C279117r.LIZLLL(31744, 0, "cold_boot_optim_v1", true, fin, "cold_boot_optim_v1");
        C279117r.LIZLLL(31744, 0, "cold_boot_optim_v2", true, fin, "cold_boot_optim_v2");
        C279117r.LIZLLL(31744, 0, "enable_request_tag", true, fin, "enable_request_tag");
        C279117r.LIZLLL(31744, 0, "is_small_task_opt", true, fin, "is_small_task_opt");
        fin.storeInt("cold_boot_mainfragment_opt", FFL.LJIIJ(31744, 2, "cold_boot_mainfragment_opt", true));
        C55723Ltv.LIZIZ.LIZJ();
        FFL.LJIIIZ().getClass();
        fin.storeInt("cold_boot_cpu_monitor", FFL.LJIIJ(31744, 0, "cold_boot_cpu_monitor", true));
        FFL.LJIIIZ().getClass();
        C279117r.LIZLLL(31744, 18, "splash_opt", true, fin, "splash_opt");
        fin.storeInt("splash_new_factory_opt", FFL.LJIIJ(31744, 1, "splash_new_factory_opt", true));
        ISplashAdService LJJI = SplashAdServiceImpl.LJJI();
        if (LJJI != null) {
            LJJI.LJFF();
        }
        boolean LIZ2 = C34639Did.LIZ();
        long LIZIZ2 = DNV.LIZIZ();
        if (LIZ2) {
            try {
                Thread.sleep(LIZIZ2);
            } catch (Exception unused2) {
            }
        }
        FFL.LJIIIZ().getClass();
        fin.storeBoolean("passive_gecko_clean_enbled_v7", FFL.LJ(31744, "passive_gecko_clean_enbled_v7", true, false));
        FFL.LJIIIZ().getClass();
        C279117r.LIZLLL(31744, 1, "preload_feed_count", true, fin, "preload_feed_count");
        C279117r.LIZLLL(31744, 2, "zl_queuedwork_opt", true, fin, "zl_queuedwork_opt");
        fin.storeInt("zl_queuedwork_sleep", FFL.LJIIJ(31744, 100, "zl_queuedwork_sleep", true));
        fin.storeInt("feed_adapter_get_view_delay", ((Number) C35010Doc.LIZ.getValue()).intValue());
        fin.storeInt("viewpager_load_delay_phase", DXC.LIZ());
        fin.storeBoolean("first_feed_msg_focus_send_opt", C34990DoI.LIZ);
        fin.storeBoolean("first_feed_msg_asynchronous_opt", C34988DoG.LIZ);
        fin.storeBoolean("first_feed_msg_post_animation_opt", C34956Dnk.LIZ);
        fin.storeBoolean("first_feed_preloadcachevideocover_v2", C34959Dnn.LIZ);
        fin.storeBoolean("first_feed_preloadnetvideocover_v2", C34961Dnp.LIZ);
        fin.storeBoolean("first_feed_usecachedcoverbitmap_v2", C34963Dnr.LIZ);
        fin.storeBoolean("first_feed_dont_move_doframe_opt", C34986DoE.LIZ);
        FFL.LJIIIZ().getClass();
        C279117r.LIZLLL(31744, 1024, "is_downgrade_splite_opt", true, fin, "is_downgrade_splite_opt");
        C279117r.LIZLLL(31744, 7, "appflyer_opt", true, fin, "appflyer_opt");
        fin.storeInt("cold_boot_preload_class", FFL.LJIIJ(31744, 2, "cold_boot_preload_class", true));
        fin.storeInt("second_page_compile_opt", C34286Dcw.LIZ());
        fin.storeBoolean("optimize_preloadtuxview", C34978Do6.LIZ);
        fin.storeBoolean("optimize_preloadviewelaborate", C34980Do8.LIZ);
        fin.storeBoolean("optimize_asyncpreloadlayout", C34989DoH.LIZ);
        fin.storeBoolean("optimize_andinflatethread", C34970Dny.LIZ);
        fin.storeBoolean("optimize_videoseekbar", C34969Dnx.LIZ);
        fin.storeInt("optimize_preloadfeedtype", C34971Dnz.LIZ);
        fin.storeBoolean("optimize_asyncinflatefragmentmainpage_v2", C34983DoB.LIZ);
        fin.storeBoolean("optimize_asyncinflatefragmentmain", C34981Do9.LIZ);
        fin.storeBoolean("optimize_asyncinflatefragmentfeed", C34977Do5.LIZ);
        fin.storeBoolean("optimize_asyncinflatefragmentfeedfollow", C34979Do7.LIZ);
        fin.storeBoolean("optimize_asyncinflatecoldbootfinish", C34975Do3.LIZ);
        fin.storeLong("optimize_asyncinflateprofiledelaytime", C34994DoM.LIZ);
        fin.storeLong("degradation_pendinginterval", C34993DoL.LIZ);
        fin.storeBoolean("optimize_publishtabelaborate", C34982DoA.LIZ);
        fin.storeBoolean("optimize_maintabstrip", C34973Do1.LIZ);
        fin.storeBoolean("optimize_precreaterecommendfragment", C34965Dnt.LIZ);
        fin.storeBoolean("optimize_precreatefollowfragment", C34964Dns.LIZ);
        fin.storeBoolean("optimize_liveiconelaborate", C34958Dnm.LIZ);
        fin.storeBoolean("optimize_bottomareaassem", C34962Dnq.LIZ);
        fin.storeBoolean("optimize_lazyareaassem", C34955Dnj.LIZ);
        fin.storeBoolean("optimize_rightareaassem", C34984DoC.LIZ);
        fin.storeBoolean("optimize_videodiggassem", C34968Dnw.LIZ);
        fin.storeBoolean("optimize_followbubble", C34967Dnv.LIZ);
        fin.storeBoolean("optimize_asynccheckfission", C34974Do2.LIZ);
        fin.storeBoolean("optimize_feedloading", C34960Dno.LIZ);
        fin.storeBoolean("optimize_feedbackground", C34954Dni.LIZ);
        fin.storeBoolean("optimize_feeddmtview", C34957Dnl.LIZ);
        fin.storeBoolean("optimize_reuseunconsumefeed", C34814DlS.LIZ);
        fin.storeBoolean("optimize_preloadonlywifi", C34809DlN.LIZ);
        fin.storeBoolean("optimize_preloawarmdvideocover", C34497DgL.LIZ);
        fin.storeBoolean("optimize_preloadallvideo", C34811DlP.LIZ);
        fin.storeInt("optimize_cachevideocount", DV9.LIZ);
        fin.storeBoolean("optimize_prerendervideo", C34795Dl9.LIZ);
        fin.storeInt("optimize_preloadwarmfeedcount", DV7.LIZ);
        fin.storeBoolean("optimize_preloadwarmfragmentviews", C34794Dl8.LIZ);
        fin.storeBoolean("optimize_feedtryplay", C34793Dl7.LIZ);
        fin.storeBoolean("optimize_preloadtabs", C34785Dkz.LIZ);
        fin.storeInt("decorview_async_optim", C34949Dnd.LIZ());
        FFL.LJIIIZ().getClass();
        fin.storeInt("splash_downgrade", FFL.LJIIJ(31744, 0, "splash_downgrade", true));
        C54968Lhk.LIZ.LIZ();
        fin.storeBoolean("optimize_deletefilesless128m", C34779Dkt.LIZ);
        fin.storeBoolean("optimize_deletefilesless64m", C34780Dku.LIZ);
        FFL.LJIIIZ().getClass();
        C279017q.LIZJ(31744, "key_string_builder_optimize", true, false, fin, "key_string_builder_optimize");
        C279117r.LIZLLL(31744, 0, "widget_downgrade", true, fin, "widget_downgrade");
        fin.storeInt("ab_earse_opt", FFL.LJIIJ(31744, 1, "ab_earse_opt", true));
        fin.storeBoolean("codecoverage_enable", C34796DlA.LIZ());
        fin.storeBoolean("codecoverage_memory_opt", C34798DlC.LIZ());
        FFL.LJIIIZ().getClass();
        C279017q.LIZJ(31744, "key_jit_debug_info_optimize", true, true, fin, "key_jit_debug_info_optimize");
        C279117r.LIZLLL(31744, 0, "prefetcher_cold_start", true, fin, "prefetcher_cold_start");
        fin.storeLong("prefetcher_step_size", FFL.LJIILIIL(31744, PlaybackStateCompat.ACTION_SET_SHUFFLE_MODE_ENABLED, "prefetcher_step_size"));
        FFL.LJIIIZ().getClass();
        fin.storeLong("prefetcher_step_sleep_duration", FFL.LJIILIIL(31744, LivePlayEnforceIntervalSetting.DEFAULT, "prefetcher_step_sleep_duration"));
        FFL.LJIIIZ().getClass();
        C279117r.LIZLLL(31744, 0, "applog_cold_boot_downgrade", true, fin, "applog_cold_boot_downgrade");
        C279117r.LIZLLL(31744, LiveMaxRetainAlogMessageSizeSetting.DEFAULT, "NpthANRCollectOpt", true, fin, "key_anr_collect_interval_ab");
        fin.storeInt("high_frequency_function_opt", FFL.LJIIJ(31744, 0, "high_frequency_function_opt", true));
        fin.storeBoolean("optimize_preloadplayerso", C34950Dne.LIZ);
        fin.storeInt("optimize_preloadplayerso_type_2570", C34950Dne.LIZIZ);
        C34296Dd6.LIZ.getClass();
        fin.storeInt("live_preParse_dns_exp", C34296Dd6.LIZ());
        FFL.LJIIIZ().getClass();
        C279117r.LIZLLL(31744, 0, "network_speed_mode_precise", true, fin, "network_speed_mode_precise");
        fin.storeBoolean("suspend_preconnect_power_opt", FFL.LJ(31744, "suspend_preconnect_power_opt", true, true));
        fin.storeBoolean("optimize_preloadinstance", C34810DlO.LIZ);
        fin.storeBoolean("optimize_preexecutehookwebview", C34820DlY.LIZ);
        FFL.LJIIIZ().getClass();
        C279117r.LIZLLL(31744, 1, "zl_feed_player_time", true, fin, "zl_feed_player_time");
        C279117r.LIZLLL(31744, 1, "zl_viewstub_test", true, fin, "zl_viewstub_test");
        C279117r.LIZLLL(31744, 1, "zl_feed_opt_doframe1", true, fin, "zl_feed_opt_doframe1");
        fin.storeInt("zl_opt_doframe_global1", FFL.LJIIJ(31744, 1, "zl_opt_doframe_global", true));
        FFL.LJIIIZ().getClass();
        fin.storeFloat("zl_feed_opt_doframe_level1", FFL.LJIIIIZZ(31744, "zl_feed_opt_doframe_level1", 0.5f));
        FFL.LJIIIZ().getClass();
        C279117r.LIZLLL(31744, 1, "zl_opt_assem_delay", true, fin, "zl_opt_assem_delay");
        C279117r.LIZLLL(31744, 1, "zl_opt_assem_delay_time", true, fin, "zl_opt_assem_delay_time");
        fin.storeInt("zl_feed_opt_print", FFL.LJIIJ(31744, 1, "zl_feed_opt_print", true));
        fin.storeBoolean("optimize_hookmainassetv2", C34772Dkm.LIZ);
        fin.storeBoolean("optimize_launchactivity", C34783Dkx.LIZ);
        boolean LIZ3 = C34639Did.LIZ();
        long LIZIZ3 = DNV.LIZIZ();
        if (LIZ3) {
            try {
                Thread.sleep(LIZIZ3);
            } catch (Exception unused3) {
            }
        }
        fin.storeBoolean("optimize_mainlooperenhance", C34771Dkl.LIZ);
        fin.storeBoolean("optimize_mainlooperprinter", C34773Dkn.LIZ);
        fin.storeBoolean("optimize_unusedpreload", C34806DlK.LIZ);
        fin.storeBoolean("optimize_userservice", C34807DlL.LIZ);
        fin.storeBoolean("optimize_disablefirstfission", C34817DlV.LIZ);
        fin.storeBoolean("optimize_disablefirstdraw", C34815DlT.LIZ);
        fin.storeBoolean("optimize_disablefirstdrawv2", C34781Dkv.LIZ);
        fin.storeBoolean("optimize_combinefeeddraw", C34804DlI.LIZ);
        fin.storeBoolean("optimize_combinefeeddrawv2", C78685UuP.LJJJJLL());
        fin.storeBoolean("optimize_combinev2focus", C78915Uy7.LJIJI());
        fin.storeBoolean("optimize_combinev2doframe", C78857UxB.LJJIJIL());
        fin.storeBoolean("enable_preload_codec_list", C34808DlM.LIZ);
        fin.storeBoolean("optimize_preexecuteavenv", C34818DlW.LIZ);
        fin.storeBoolean("optimize_preloadsplash", C34777Dkr.LIZ);
        fin.storeBoolean("optimize_deadsystemensure", C34770Dkk.LIZ);
        fin.storeBoolean("optimize_applicationresource", C34775Dkp.LIZ);
        fin.storeBoolean("optimize_activityresource", C34768Dki.LIZ);
        fin.storeBoolean("optimize_enablelogtask_v3", C34782Dkw.LIZ);
        fin.storeBoolean("optimize_abreport", C47261Igj.LJJIII());
        fin.storeLong("optimize_logbootfinishtaskinterval", C34991DoJ.LIZ);
        fin.storeBoolean("optimize_preexecutex2c", C34805DlJ.LIZ);
        fin.storeBoolean("optimize_asyncjatotask", C34985DoD.LIZ);
        fin.storeBoolean("optimize_videodecopt", C34769Dkj.LIZ);
        fin.storeLong("optimize_delayliverequest", C34992DoK.LIZ);
        fin.storeBoolean("optimize_disablesharerequest", C34819DlX.LIZ);
        fin.storeBoolean("optimize_asyncpreload", C34987DoF.LIZ);
        fin.storeBoolean("optimize_mainlooperservice", C34774Dko.LIZ);
        fin.storeBoolean("optimize_anonymoushandler", C34696DjY.LIZ);
        fin.storeBoolean("optimize_loadedapkdispatcher", C34765Dkf.LIZ);
        fin.storeBoolean("optimize_corehandler", C34766Dkg.LIZ);
        fin.storeBoolean("optimize_assemhandler", C78596Usy.LJJIJ());
        fin.storeBoolean("optimize_dispatchedcontinuation", C78897Uxp.LJJIFFI());
        fin.storeBoolean("optimize_looperidle", C34767Dkh.LIZ);
        fin.storeBoolean("optimize_controlloadedapk", C34709Djl.LIZ);
        fin.storeBoolean("optimize_loadvcn", C34764Dke.LIZ);
        fin.storeBoolean("optimize_boostdoframe", C34701Djd.LIZ);
        fin.storeBoolean("optimize_degradepredrawable", C34778Dks.LIZ);
        fin.storeBoolean("optimize_degradepreact_v2", C34776Dkq.LIZ);
        fin.storeInt("optimize_holdupapplog", C78857UxB.LJJIJIIJIL());
        fin.storeInt("optimize_disabledrawcount", C79234V7u.LJIJJLI());
        fin.storeInt("optimize_endlesslooper", C87277YNd.LJIJJ());
        fin.storeBoolean("optimize_createbeforecreatetask_v2", C34699Djb.LIZ);
        fin.storeBoolean("optimize_preloadhometabvm", C34972Do0.LIZ);
        fin.storeBoolean("optimize_logictab", C34966Dnu.LIZ);
        fin.storeBoolean("optimize_fixav", C34703Djf.LIZ);
        FFL.LJIIIZ().getClass();
        C279117r.LIZLLL(31744, 0, "widget_lazy", true, fin, "widget_lazy");
        C279117r.LIZLLL(31744, 0, "coldboot_mainact_task_exp", true, fin, "coldboot_mainact_task_exp");
        C279117r.LIZLLL(31744, 0, "app_widget_optimize_experiment_2370", true, fin, "app_widget_optimize_experiment_2370");
        C279117r.LIZLLL(31744, 0, "player_resume_experiment", true, fin, "player_resume_experiment");
        fin.storeInt("main_looper_private_repo_opt_enable", FFL.LJIIJ(31744, 0, "main_looper_private_opt_switch", true));
        C1XY.LJJIJ();
        ClientSLIDataUploader.LIZ();
        C78685UuP.LJJLIIJ(EF7.LIZIZ());
        C78688UuS.LJJLIIIJ(EF7.LIZIZ());
        fin.storeBoolean("tryplay_preexecute", ((Boolean) C34851Dm3.LIZ.getValue()).booleanValue());
        FFL.LJIIIZ().getClass();
        C279117r.LIZLLL(31744, 0, "settings_manager_notify_settings_experiment_2370", true, fin, "settings_manager_notify_settings_experiment_2370");
        C279117r.LIZLLL(31744, -1, "memory_downgrade_opt", true, fin, "memory_downgrade_opt");
        C279117r.LIZLLL(31744, 0, "use_BDXBridgeSDK", true, fin, "use_BDXBridgeSDK");
        C279117r.LIZLLL(31744, 0, "use_BDXBridgeSDK_lynx", true, fin, "use_BDXBridgeSDK_lynx");
        C279117r.LIZLLL(31744, 1, "invoke_bridge_unregister", true, fin, "invoke_bridge_unregister");
        C279117r.LIZLLL(31744, 0, "echo_preload", true, fin, "echo_preload");
        C279017q.LIZJ(31744, "search_json_lazy_parse", true, true, fin, "search_json_lazy_parse");
        C279017q.LIZJ(31744, "enable_safe_air_cushion", true, false, fin, "enable_safe_air_cushion");
        C279017q.LIZJ(31744, "enable_feed_video_meta_json_opt", true, false, fin, "enable_feed_video_meta_json_opt");
        C279017q.LIZJ(31744, "enable_topview_json_opt", true, false, fin, "enable_topview_json_opt");
        C279117r.LIZLLL(31744, 0, "topview_task_new_thread", true, fin, "topview_task_new_thread");
        fin.storeBoolean("disable_throwable_print_stack_trace", FFL.LJ(31744, "disable_throwable_print_stack_trace", true, false));
        fin.storeBoolean("resources_preload_io_thread", C34800DlE.LIZ());
        FFL.LJIIIZ().getClass();
        C279117r.LIZLLL(31744, 0, "json_memory_opt", true, fin, "json_memory_opt");
        C279117r.LIZLLL(31744, 0, "key_binder_cache_1", true, fin, "key_binder_cache_1");
        C279117r.LIZLLL(31744, 0, "key_jato_hwui_opt", true, fin, "key_jato_hwui_opt");
        C279117r.LIZLLL(31744, 0, "feed_cache_video_opt", true, fin, "feed_cache_video_opt");
        C279117r.LIZLLL(31744, 0, "feed_cache_get_order", true, fin, "feed_cache_get_order");
        C279117r.LIZLLL(31744, 0, "init_webview_opt", true, fin, "init_webview_opt");
        C279117r.LIZLLL(31744, 0, "feed_cache_preload_opt", true, fin, "feed_cache_preload_opt");
        C279117r.LIZLLL(31744, 0, "xjl_feed_enter_homepage_binder_call_opt_v2", true, fin, "xjl_feed_enter_homepage_binder_call_opt_v2");
        C279117r.LIZLLL(31744, 0, "xjl_feed_enter_homepage_binder_call_opt_v3", true, fin, "xjl_feed_enter_homepage_binder_call_opt_v3");
        C279117r.LIZLLL(31744, 1, "zl_scalpel_opt_first", true, fin, "zl_scalpel_opt_first");
        fin.storeInt("zl_scalpel", FFL.LJIIJ(31744, 1, "zl_scalpel", true));
        C38855FMt.LIZ();
        C38855FMt c38855FMt = C92J.LIZ;
        if (c38855FMt.LIZJ == 1) {
            FFL.LJIIIZ().getClass();
            fin.storeInt("zl_perflock_qcom", FFL.LJIIJ(31744, 1, "zl_perflock_qcom", true));
            FFL.LJIIIZ().getClass();
            C279117r.LIZLLL(31744, 0, "zl_perflock_interval", true, fin, "zl_perflock_interval");
            fin.storeString("zl_perflock_param", FFL.LJIILJJIL(31744, "zl_perflock_param", "", true));
        } else {
            C38855FMt.LIZ();
            if (c38855FMt.LIZJ == 2) {
                FFL.LJIIIZ().getClass();
                fin.storeInt("zl_perflock_mtk", FFL.LJIIJ(31744, 1, "zl_perflock_mtk", true));
                FFL.LJIIIZ().getClass();
                C279117r.LIZLLL(31744, 0, "zl_perflock_mtk_interval", true, fin, "zl_perflock_mtk_interval");
                fin.storeString("zl_mtk_param", FFL.LJIILJJIL(31744, "zl_mtk_param", "", true));
            } else {
                C38855FMt.LIZ();
                if (c38855FMt.LIZJ == 3) {
                    FFL.LJIIIZ().getClass();
                    fin.storeInt("zl_perflock_kirin", FFL.LJIIJ(31744, 1, "zl_perflock_kirin", true));
                }
            }
        }
        if (C38523F9z.LIZJ) {
            FFL.LJIIIZ().getClass();
            fin.storeInt("zl_network_ipc_fix", FFL.LJIIJ(31744, 1, "zl_network_ipc_fix", true));
        }
        FFL.LJIIIZ().getClass();
        fin.storeFloat("zl_scalpelconfig", FFL.LJIIIIZZ(31744, "zl_scalpelconfig", 6.0f));
        FFL.LJIIIZ().getClass();
        fin.storeInt("thread_convergence_init_async", FFL.LJIIJ(31744, 0, "thread_convergence_init_async", true));
        AwemeHostApplication LIZ4 = FKM.LIZ();
        FFL.LJIIIZ().getClass();
        C35820E4a.LJ(LIZ4, FFL.LJIIJ(31744, 0, "thread_convergence_init_async", true));
        FFL.LJIIIZ().getClass();
        fin.storeInt("feed_cache_filter_opt", FFL.LJIIJ(31744, 0, "feed_cache_filter_opt", true));
        FFL.LJIIIZ().getClass();
        C279117r.LIZLLL(31744, 6, "is_downgrade_splite_opt_v2", true, fin, "is_downgrade_splite_opt_v2");
        C279117r.LIZLLL(31744, 0, "base_activity_get_resources_optimize_experiment", true, fin, "base_activity_get_resources_optimize_experiment");
        C279117r.LIZLLL(31744, 0, "fluency_downgrade_opt_v2", true, fin, "fluency_downgrade_opt_v2");
        C279117r.LIZLLL(31744, 1, "thread_pool_block_opt", true, fin, "thread_pool_block_opt");
        C279117r.LIZLLL(31744, 0, "cold_boot_mainAct_degradation", true, fin, "cold_boot_mainAct_degradation");
        C279117r.LIZLLL(31744, -100, "set_main_thread_priority", true, fin, "set_main_thread_priority");
        C279117r.LIZLLL(31744, 0, "io_thread_cpu_boost_v2620", true, fin, "io_thread_cpu_boost_v2620");
        C279017q.LIZJ(31744, "experiment_manager_bug_fix_experiment", true, true, fin, "experiment_manager_bug_fix_experiment");
        C279017q.LIZJ(31744, "second_feed_item_view_preload", true, false, fin, "second_feed_item_view_preload");
        C279117r.LIZLLL(31744, 0, "memory_downgrade_v2_opt", true, fin, "memory_downgrade_v2_opt");
        fin.storeInt("swipe_video_downgrade_experiment", FFL.LJIIJ(31744, 0, "swipe_video_downgrade_experiment", true));
        boolean LIZ5 = C34639Did.LIZ();
        long LIZIZ4 = DNV.LIZIZ();
        if (LIZ5) {
            try {
                Thread.sleep(LIZIZ4);
            } catch (Exception unused4) {
            }
        }
        C34580Dhg.LIZJ();
        FFL.LJIIIZ().getClass();
        fin.storeBoolean("feed_single_video_opt", FFL.LJ(31744, "feed_single_video_opt", true, false));
        FFL.LJIIIZ().getClass();
        C279017q.LIZJ(31744, "feed_single_video_opt_2", true, true, fin, "feed_single_video_opt_2");
        fin.storeBoolean("root_node_async", FFL.LJ(31744, "root_node_async", true, false));
        AVInitializerImpl.LIZ().updateAB();
        boolean LIZ6 = C34639Did.LIZ();
        long LIZIZ5 = DNV.LIZIZ();
        if (LIZ6) {
            try {
                Thread.sleep(LIZIZ5);
            } catch (Exception unused5) {
            }
        }
        FFL.LJIIIZ().getClass();
        fin.storeInt("feed_digg_count_view_hw_layer_experiment", FFL.LJIIJ(31744, 0, "feed_digg_count_view_hw_layer_experiment", true));
        FFL.LJIIIZ().getClass();
        C279117r.LIZLLL(31744, 0, "feed_comment_count_view_hw_layer_experiment", true, fin, "feed_comment_count_view_hw_layer_experiment");
        C279117r.LIZLLL(31744, 0, "feed_comment_icon_hw_layer_experiment", true, fin, "feed_comment_icon_hw_layer_experiment");
        C279117r.LIZLLL(31744, 0, "feed_share_count_view_hw_layer_experiment", true, fin, "feed_share_count_view_hw_layer_experiment");
        C279117r.LIZLLL(31744, 0, "feed_author_title_view_hw_layer_experiment", true, fin, "feed_author_title_view_hw_layer_experiment");
        C279117r.LIZLLL(31744, 0, "feed_video_desc_view_hw_layer_experiment", true, fin, "feed_video_desc_view_hw_layer_experiment");
        C279117r.LIZLLL(31744, 0, "feed_music_icon_hw_layer_experiment", true, fin, "feed_music_icon_hw_layer_experiment");
        C279117r.LIZLLL(31744, 0, "tool_bar_left_icon_hw_layer_experiment", true, fin, "tool_bar_left_icon_hw_layer_experiment");
        C279117r.LIZLLL(31744, 0, "tool_bar_right_icon_hw_layer_experiment", true, fin, "tool_bar_right_icon_hw_layer_experiment");
        C279117r.LIZLLL(31744, 0, "feed_line_progress_bar_hw_layer_experiment", true, fin, "feed_line_progress_bar_hw_layer_experiment");
        C279117r.LIZLLL(31744, 0, "feed_report_warn_ll_hw_layer_experiment", true, fin, "feed_report_warn_ll_hw_layer_experiment");
        C279117r.LIZLLL(31744, 0, "video_music_cover_hw_layer_experiment", true, fin, "video_music_cover_hw_layer_experiment");
        C279117r.LIZLLL(31744, 0, "feed_avatar_hw_layer_experiment", true, fin, "feed_avatar_hw_layer_experiment");
        C279117r.LIZLLL(31744, 0, "fps_reporter_upload_experiment", true, fin, "fps_reporter_upload_experiment");
        C279017q.LIZJ(31744, "deterioration_fix_exp", true, false, fin, "deterioration_fix_exp");
        C279117r.LIZLLL(31744, 0, "thread_convergence_optimize_experiment", true, fin, "thread_convergence_optimize_experiment");
        C279117r.LIZLLL(31744, 0, "player_config_simplify_opt", true, fin, "player_config_simplify_opt");
        C279017q.LIZJ(31744, "performance_opt_great_reversal_2440", true, false, fin, "performance_opt_great_reversal_2440");
        C279017q.LIZJ(31744, "performance_player_opt_great_reversal", true, false, fin, "performance_player_opt_great_reversal");
        C279117r.LIZLLL(31744, 0, "ab_dynamic_feature_opt", true, fin, "ab_dynamic_feature_opt");
        fin.storeInt("settings_manager_notify_callback_experiment", FFL.LJIIJ(31744, 0, "settings_manager_notify_callback_experiment", true));
        C35053DpJ.LIZ();
        FFL.LJIIIZ().getClass();
        fin.storeBoolean(ViewStubOptExperiment.KEY, FFL.LJ(31744, ViewStubOptExperiment.KEY, true, false));
        fin.storeBoolean("topview_splash_x2c_1_enable", C35029Dov.LIZ());
        fin.storeBoolean("coldboot_commerce_logic_opt_enable", C34305DdF.LIZ());
        FFL.LJIIIZ().getClass();
        C279017q.LIZJ(31744, "request_combine_lazy_startup_experiment", true, false, fin, "request_combine_lazy_startup_experiment");
        C279017q.LIZJ(31744, "settings_v3_migrate_experiment", true, false, fin, "settings_v3_migrate_experiment");
        C279017q.LIZJ(31744, "ab_common_request_retry_experiment", true, false, fin, "ab_common_request_retry_experiment");
        C279117r.LIZLLL(31744, 0, "paging_transition_experiment", true, fin, "paging_transition_experiment");
        C279117r.LIZLLL(31744, 0, "slide_transition_experiment", true, fin, "slide_transition_experiment");
        C279117r.LIZLLL(31744, 0, "fresco_executor_supplier_fix_experiment", true, fin, "fresco_executor_supplier_fix_experiment");
        fin.storeBoolean("can_switch_paging_duration", FFL.LJ(31744, "can_switch_paging_duration", true, false));
        fin.storeBoolean("tt_mall_top_tab_experiment", ECommerceMallService.v3().G2());
        SettingsManager.LIZLLL().getClass();
        fin.storeString("sliver_tracker_str", SettingsManager.LJI("sliver_tracker_str", ""));
        FFL.LJIIIZ().getClass();
        fin.storeBoolean(ViewStubOptExperimentV2.KEY, FFL.LJ(31744, ViewStubOptExperimentV2.KEY, true, false));
        FFL.LJIIIZ().getClass();
        fin.storeFloat("xjl_feed_apm_sampling_opt", FFL.LJIIIIZZ(31744, "xjl_feed_apm_sampling_opt", -1.0f));
        FFL.LJIIIZ().getClass();
        fin.storeFloat("xjl_feed_apm_sampling_opt_report_v1", FFL.LJIIIIZZ(31744, "xjl_feed_apm_sampling_opt_report_v1", 1.0f));
        FFL.LJIIIZ().getClass();
        C279117r.LIZLLL(31744, 0, "new_fps_monitor_exp", true, fin, "new_fps_monitor_exp");
        fin.storeInt("xjl_feed_apm_looper_println_opt", FFL.LJIIJ(31744, 0, "xjl_feed_apm_looper_println_opt", true));
        SettingsManager.LIZLLL().getClass();
        fin.storeBoolean("network_set_rxjava_error_handler", SettingsManager.LIZ("network_set_rxjava_error_handler", true));
        FFL.LJIIIZ().getClass();
        C279117r.LIZLLL(31744, 0, "double_color_ball_invalidate_delay_experiment", true, fin, "double_color_ball_invalidate_delay_experiment");
        C279117r.LIZLLL(31744, 0, "fresco_fade_duration_disable_experiment", true, fin, "fresco_fade_duration_disable_experiment");
        C279117r.LIZLLL(31744, 0, "fyp_animation_delay_experiment", true, fin, "fyp_animation_delay_experiment");
        fin.storeBoolean("out_of_memory_error_clear_bitmap_cache", FFL.LJ(31744, "out_of_memory_error_clear_bitmap_cache", true, false));
        FHD LIZLLL = FHD.LIZLLL();
        AppLogSendCallbackConfig.Model model = AppLogSendCallbackConfig.LIZJ;
        LIZLLL.getClass();
        fin.storeString("AppLog_send_callback_config", C75792yF.LIZJ(FHD.LJIIJJI(AppLogSendCallbackConfig.Model.class, model, "AppLog_send_callback_config", false)));
        SettingsManager.LIZLLL().getClass();
        fin.storeBoolean("old_offline_clean_settings", SettingsManager.LIZ("old_offline_clean_settings", false));
        SettingsManager.LIZLLL().getClass();
        fin.storeString("lancet_hook_method_collector", SettingsManager.LJI("lancet_hook_method_collector", ""));
        FFL.LJIIIZ().getClass();
        C279117r.LIZLLL(31744, 0, "feed_jato_queue_buffer_opt_on_startup", true, fin, "feed_jato_queue_buffer_opt_on_startup");
        C279117r.LIZLLL(31744, -1, "olduser_loadmore_cache_opt", true, fin, "olduser_loadmore_cache_opt");
        fin.storeInt("old_user_login_experience_v2_opt_switch", FFL.LJIIJ(31744, 0, "old_user_login_experience_v2_opt_switch", true));
        SettingsManager.LIZLLL().getClass();
        fin.storeBoolean("power_permssion_enable_bpea", SettingsManager.LIZ("power_permssion_enable_bpea", true));
        C34591Dhr.LIZ();
        C34593Dht.LIZ();
        ReDexExperimentOpt.update();
        LIZIZ();
        LIZ();
        FHD.LIZLLL().getClass();
        fin.storeString("feed_components", C75792yF.LIZJ(FHD.LJIIJJI(FeedComponentsData.class, null, "feed_components", true)));
        FHD.LIZLLL().getClass();
        fin.storeString("multi_scene_feed_components", C75792yF.LIZJ(FHD.LJIIJJI(FeedMultiSceneComponentsData.class, null, "multi_scene_feed_components", true)));
        FFL.LJIIIZ().getClass();
        fin.storeInt("video_consistency_experiment", FFL.LJIIJ(31744, 0, "video_consistency_experiment", true));
        C35610DyI.LIZ(EF7.LIZIZ());
        FFL.LJIIIZ().getClass();
        fin.storeLong("player_jato_boot_config", FFL.LJIILIIL(31744, 0L, "player_jato_boot_config"));
        FFL.LJIIIZ().getClass();
        fin.storeLong("player_jato_start_activity_config", FFL.LJIILIIL(31744, 0L, "player_jato_start_activity_config"));
        FFL.LJIIIZ().getClass();
        fin.storeLong("player_jato_start_service_config", FFL.LJIILIIL(31744, 0L, "player_jato_start_service_config"));
        FFL.LJIIIZ().getClass();
        fin.storeLong("player_jato_receiver_config", FFL.LJIILIIL(31744, 0L, "player_jato_receiver_config"));
        FFL.LJIIIZ().getClass();
        fin.storeLong("player_jato_pager_scroll_config", FFL.LJIILIIL(31744, 0L, "player_jato_pager_scroll_config"));
        FFL.LJIIIZ().getClass();
        fin.storeLong("player_jato_pager_adapter_config", FFL.LJIILIIL(31744, 0L, "player_jato_pager_adapter_config"));
        FFL.LJIIIZ().getClass();
        fin.storeLong("player_jato_view_scroll_config", FFL.LJIILIIL(31744, 0L, "player_jato_view_scroll_config"));
        FFL.LJIIIZ().getClass();
        fin.storeLong("player_jato_view_adapter_config", FFL.LJIILIIL(31744, 0L, "player_jato_view_adapter_config"));
        FFL.LJIIIZ().getClass();
        fin.storeLong("player_jato_boost_min_interval", FFL.LJIILIIL(31744, 500L, "player_jato_boost_min_interval"));
        FFL.LJIIIZ().getClass();
        C279017q.LIZJ(31744, "zero_video_view_monitor_olduser_exp", true, false, fin, "zero_video_view_monitor_olduser_exp");
        C279117r.LIZLLL(31744, 0, "task_after_boot_finish_priority_degrade_experiment", true, fin, "task_after_boot_finish_priority_degrade_experiment");
        C279117r.LIZLLL(31744, 0, "v_provider_cache_experiment", true, fin, "v_provider_cache_experiment");
        C279117r.LIZLLL(31744, 0, "get_fragment_optimize_experiment", true, fin, "get_fragment_optimize_experiment");
        C279117r.LIZLLL(31744, 0, "find_target_scope_fail_fast_experiment", true, fin, "find_target_scope_fail_fast_experiment");
        C279117r.LIZLLL(31744, 0, "slow_method_drop_count_index_experiment", true, fin, "slow_method_drop_count_index_experiment");
        C279117r.LIZLLL(31744, 0, "app_launcher_cpu_stage", true, fin, "app_launcher_cpu_stage");
        fin.storeInt("xjl_alog_report_by_thread_pool_exp", FFL.LJIIJ(31744, 0, "xjl_alog_report_by_thread_pool_exp", true));
        FFL LJIIIZ = FFL.LJIIIZ();
        WebSocketInitExperiment.MetaData metaData = WebSocketInitExperiment.LIZ;
        LJIIIZ.getClass();
        WebSocketInitExperiment.MetaData metaData2 = (WebSocketInitExperiment.MetaData) FFL.LJIJ(true, "web_socket_init_timing", 31744, WebSocketInitExperiment.MetaData.class, metaData);
        if (metaData2 != null) {
            fin.storeInt("web_socket_init_timing_group", metaData2.initTimingGroup);
            fin.storeInt("web_socket_init_timing_work_type", metaData2.initTaskWorkType);
        }
        FFL.LJIIIZ().getClass();
        fin.storeInt("ws_modularization", FFL.LJIIJ(31744, 0, "ws_modularization", true));
        C34683DjL.LIZ();
        FFL.LJIIIZ().getClass();
        C279117r.LIZLLL(31744, 0, "xjl_bd_location_net_manager_opt", true, fin, "xjl_bd_location_net_manager_opt");
        C279117r.LIZLLL(31744, 0, "xjl_image_option_to_string_exp", true, fin, "xjl_image_option_to_string_exp");
        C279117r.LIZLLL(31744, 0, "xjl_tux_auto_size_cache_exp", true, fin, "xjl_tux_auto_size_cache_exp");
        C279117r.LIZLLL(31744, 0, "feed_binder_sim_country_info_exp", true, fin, "feed_binder_sim_country_info_exp");
        C279117r.LIZLLL(31744, 0, "feed_small_screen_for_size_experiment", true, fin, "feed_small_screen_for_size_experiment");
        C279117r.LIZLLL(31744, 0, "feed_small_screen_for_size_no_bottom_experiment", true, fin, "feed_small_screen_for_size_no_bottom_experiment");
        C279117r.LIZLLL(31744, 0, "xjl_feed_alog_sampling_exp", true, fin, "xjl_feed_alog_sampling_exp");
        C279117r.LIZLLL(31744, 0, "xjl_feed_scrap_view_clear_ext", true, fin, "xjl_feed_scrap_view_clear_ext");
        C279117r.LIZLLL(31744, 0, "xjl_feed_sync_frame_state_opt_exp", true, fin, "xjl_feed_sync_frame_state_opt_exp");
        fin.storeInt("xjl_feed_sync_frame_opt_type_exp", FFL.LJIIJ(31744, 0, "xjl_feed_sync_frame_opt_type_exp", true));
        Z9N.LIZIZ.LJLJL();
        C97L.LIZ();
        C61491OBj.LJLIIIL();
        C35019Dol.LIZJ();
        FFL.LJIIIZ().getClass();
        fin.storeBoolean("aot_disable_opt", FFL.LJ(31744, "aot_disable_opt", true, false));
        FFL.LJIIIZ().getClass();
        C279117r.LIZLLL(31744, 0, "retrofit_reflection_rx_java_optimization_experiment", true, fin, "retrofit_reflection_rx_java_optimization_experiment");
        C279117r.LIZLLL(31744, 0, "big_screen_bottom_height", true, fin, "big_screen_bottom_height");
        C279117r.LIZLLL(31744, 0, "system_launch_ab_preload_experiment", true, fin, "system_launch_ab_preload_experiment");
        fin.storeLong("aot_threshold_opt", FFL.LJIILIIL(31744, -1L, "aot_threshold_opt"));
        FFL.LJIIIZ().getClass();
        fin.storeLong("aot_foreground_check_opt", FFL.LJIILIIL(31744, -1L, "aot_foreground_check_opt"));
        FFL.LJIIIZ().getClass();
        fin.storeInt("assem_ext_provider_sink_scope_define", FFL.LJIIJ(31744, 1, "assem_ext_provider_sink_scope_define", true));
        SettingsManager.LIZLLL().getClass();
        fin.storeBoolean("vprovider_logger_setting_v2", SettingsManager.LIZ("vprovider_logger_setting_v2", false));
        SettingsManager.LIZLLL().getClass();
        fin.storeBoolean("enable_assem_log_settings", SettingsManager.LIZ("enable_assem_log_settings", false));
        SettingsManager.LIZLLL().getClass();
        fin.storeBoolean("enable_assem_vm_lock_3060", SettingsManager.LIZ("enable_assem_vm_lock_3060", true));
        SettingsManager.LIZLLL().getClass();
        fin.storeBoolean("vprovider_check_circular_attach_setting", SettingsManager.LIZ("vprovider_check_circular_attach_setting", true));
        SettingsManager.LIZLLL().getClass();
        fin.storeBoolean("enable_fix_assem_memory_leak", SettingsManager.LIZ("enable_fix_assem_memory_leak", true));
        SettingsManager.LIZLLL().getClass();
        fin.storeBoolean("enable_fix_assem_slot_async_lifecycle", SettingsManager.LIZ("enable_fix_assem_slot_async_lifecycle", true));
        SettingsManager.LIZLLL().getClass();
        fin.storeBoolean("enable_fix_fragment_assemble_memory_leak", SettingsManager.LIZ("enable_fix_fragment_assemble_memory_leak", true));
        SettingsManager.LIZLLL().getClass();
        fin.storeBoolean("enable_optimise_shared_vm_lifecycle", SettingsManager.LIZ("enable_optimise_shared_vm_lifecycle", true));
        FFL.LJIIIZ().getClass();
        C279117r.LIZLLL(31744, 0, "follow_preload_opt", true, fin, "follow_preload_opt");
        fin.storeBoolean(FollowFeedViewStubExperiment.KEY, FFL.LJ(31744, FollowFeedViewStubExperiment.KEY, true, false));
        SettingsManager.LIZLLL().getClass();
        fin.storeInt("tab_preload_for_fcp", SettingsManager.LJ("tab_preload_for_fcp", 0));
        FFL.LJIIIZ().getClass();
        C279117r.LIZLLL(31744, 0, "feed_tab_platform_enable", true, fin, "feed_tab_platform_enable");
        fin.storeInt("ultimate_inflater_layout_preload_for_fyp_at_lest_2880", FFL.LJIIJ(31744, 0, "ultimate_inflater_layout_preload_for_fyp_at_lest_2880", true));
        C35499DwV.LIZ.getClass();
        C35499DwV.LIZJ.getValue();
        FFL.LJIIIZ().getClass();
        fin.storeInt("tt_friends_experiment", FFL.LJIIJ(31744, -1, "tt_friends_experiment", true));
        fin.storeInt("tt_friends_top_tab_experiment_index", FriendsTabTopExperiment.LIZ().indexOnTop);
        FFL.LJIIIZ().getClass();
        C279117r.LIZLLL(31744, 0, "tt_now_enabled", true, fin, "tt_now_enable_group");
        fin.storeInt("scalpel_background_runnable_experiment", FFL.LJIIJ(31744, 0, "scalpel_background_runnable_experiment", true));
        AccountFeatureFlagService.LJI().LIZLLL();
        FFL.LJIIIZ().getClass();
        C279017q.LIZJ(31744, "vk_init_provider_startup_experiment", true, false, fin, "vk_init_provider_startup_experiment");
        fin.storeInt("ttk_contact_bytesync_enabled_experiment", FFL.LJIIJ(31744, 0, "ttk_contact_bytesync_enabled", true));
        fin.storeInt("splash_realtime", C2305693c.LIZIZ());
        fin.storeLong("splash_realtime_timeout", C35026Dos.LIZ());
        fin.storeBoolean("splash_realtime_np", C35041Dp7.LIZ());
        fin.storeLong("splash_realtime_np_delay_time", C35023Dop.LIZ());
        FFL.LJIIIZ().getClass();
        fin.storeInt("traffic_monitor_experiment", FFL.LJIIJ(31744, 0, "traffic_monitor_experiment", true));
        FFL.LJIIIZ().getClass();
        fin.storeFloat("traffic_monitor_sampling_experiment", FFL.LJIIIIZZ(31744, "traffic_monitor_sampling_experiment", 1.0f));
        FFL.LJIIIZ().getClass();
        C279117r.LIZLLL(31744, 0, "tt_fix_collect_callback_anr", true, fin, "tt_fix_collect_callback_anr");
        C279117r.LIZLLL(31744, 0, "tt_memory_protect_opt", true, fin, "tt_memory_protect_opt");
        C279117r.LIZLLL(31744, 180, "tt_app_memory_loop_time", true, fin, "tt_app_memory_loop_time");
        C279117r.LIZLLL(31744, 0, "tt_app_memory_trim_ratio", true, fin, "tt_app_memory_trim_ratio");
        C279117r.LIZLLL(31744, 0, "tt_check_app_compat_theme_opt", true, fin, "tt_check_app_compat_theme_opt");
        C279117r.LIZLLL(31744, 0, "tt_theme_enforcement_opt", true, fin, "tt_theme_enforcement_opt");
        C279117r.LIZLLL(31744, 0, "tt_resources_compat_opt", true, fin, "tt_resources_compat_opt");
        C279117r.LIZLLL(31744, 0, "tt_disable_event_tracker_opt", true, fin, "tt_disable_event_tracker_opt");
        C279117r.LIZLLL(31744, 0, "tt_tracing_return_false_opt", true, fin, "tt_tracing_return_false_opt");
        C279117r.LIZLLL(31744, 0, "tt_logger_and_tostring_opt", true, fin, "tt_logger_and_tostring_opt");
        C279117r.LIZLLL(31744, 0, "tt_set_max_spins", true, fin, "tt_set_max_spins");
        C279117r.LIZLLL(31744, 0, "top_thread_runnable_experiment", true, fin, "top_thread_runnable_experiment");
        C279117r.LIZLLL(31744, 0, "content_capture_opt", true, fin, "content_capture_opt");
        C279117r.LIZLLL(31744, 0, "key_gson_get_adapter_1", true, fin, "key_gson_get_adapter_1");
        C279017q.LIZJ(31744, "open_bdtracker_event_priority", true, false, fin, "open_bdtracker_event_priority");
        C279117r.LIZLLL(31744, 0, "bdtracker_report_req_num", true, fin, "bdtracker_report_req_num");
        C279117r.LIZLLL(31744, 0, "gecko_clean_phase_three_experiment", true, fin, "gecko_clean_phase_three_experiment");
        C279117r.LIZLLL(31744, 7, "gecko_clean_phase_three_expire_day_experiment", true, fin, "gecko_clean_phase_three_expire_day_experiment");
        C279017q.LIZJ(31744, "open_onEvent_optimization", true, false, fin, "open_onEvent_optimization");
        C279017q.LIZJ(31744, "ttk_a11y_system_setting_track_enabled", true, false, fin, "ttk_a11y_system_setting_track_enabled");
        C279117r.LIZLLL(31744, 0, "aweme_oncreate_before_super_tasks_anr_opt", true, fin, "aweme_oncreate_before_super_tasks_anr_opt");
        C279117r.LIZLLL(31744, 0, "apm_init_push_process_opt", true, fin, "apm_init_push_process_opt");
        fin.storeBoolean("strict_mode_thread_policy_violation_check", FFL.LJ(31744, "strict_mode_thread_policy_violation_check", true, false));
        C35274Dss.LIZIZ();
        FFL.LJIIIZ().getClass();
        fin.storeInt("paging_transition_more_fast_scroll_experiment", FFL.LJIIJ(31744, 0, "paging_transition_more_fast_scroll_experiment", true));
        FFL LJIIIZ2 = FFL.LJIIIZ();
        SparkWebViewOptimizeExperiment.WebViewOptimizeModel webViewOptimizeModel = SparkWebViewOptimizeExperiment.LIZ;
        LJIIIZ2.getClass();
        fin.storeString("spark_webview_optimize_experiment", C75792yF.LIZJ(FFL.LJIJ(true, "spark_webview_optimize_experiment", 31744, SparkWebViewOptimizeExperiment.WebViewOptimizeModel.class, webViewOptimizeModel)));
        FFL LJIIIZ3 = FFL.LJIIIZ();
        SparkEcomOptimizeExperiment.EcomOptimizeModel ecomOptimizeModel = SparkEcomOptimizeExperiment.LIZ;
        LJIIIZ3.getClass();
        fin.storeString("spark_ecom_optimize_experiment", C75792yF.LIZJ(FFL.LJIJ(true, "spark_ecom_optimize_experiment", 31744, SparkEcomOptimizeExperiment.EcomOptimizeModel.class, ecomOptimizeModel)));
        SettingsManager.LIZLLL().getClass();
        fin.storeString("ms_settings_android", SettingsManager.LJI("ms_settings_android", "5d3a57922d5da57e49f3625d79d0d4669632612f6582c496d8487843468bbb85fcbe5f71fde92348b08d9efdd9971c3040dcbab55c2b2843"));
    }
}
