package X;

import android.os.SystemClock;
import fjb.a;
import org.json.JSONObject;

@InterfaceC65848Psq(c = "com.ss.android.ugc.aweme.im.sdk.common.controller.analytics.IMAutoGeneratedMessageAnalytics$onMessageSent$1", f = "IMAutoGeneratedMessageAnalytics.kt", l = {75}, m = "invokeSuspend")
/* renamed from: X.3V6, reason: invalid class name */
/* loaded from: classes2.dex */
public final class C3V6 extends AbstractC65782Prm implements InterfaceC88471Ynr<InterfaceC70422pa, InterfaceC67352kd<? super C76800UCe>, Object> {
    public int LJLIL;
    public final /* synthetic */ C109544Rq LJLILLLLZI;
    public final /* synthetic */ C63540Owi LJLJI;
    public final /* synthetic */ C3V8 LJLJJI;

    /* JADX WARN: 'super' call moved to the top of the method (can break code semantics) */
    public C3V6(C109544Rq c109544Rq, C63540Owi c63540Owi, C3V8 c3v8, InterfaceC67352kd<? super C3V6> interfaceC67352kd) {
        super(2, interfaceC67352kd);
        this.LJLILLLLZI = c109544Rq;
        this.LJLJI = c63540Owi;
        this.LJLJJI = c3v8;
    }

    @Override // fjb.a
    public final InterfaceC67352kd<C76800UCe> create(Object obj, InterfaceC67352kd<?> interfaceC67352kd) {
        return new C3V6(this.LJLILLLLZI, this.LJLJI, this.LJLJJI, interfaceC67352kd);
    }

    @Override // fjb.a
    public final Object invokeSuspend(Object obj) {
        EnumC58928NAu enumC58928NAu = EnumC58928NAu.COROUTINE_SUSPENDED;
        int i = this.LJLIL;
        if (i != 0) {
            if (i == 1) {
                C141335gf.LIZJ(obj);
            } else {
                throw new IllegalStateException("call to 'resume' before 'invoke' with coroutine");
            }
        } else {
            C141335gf.LIZJ(obj);
            C106714Gt c106714Gt = C106714Gt.LIZ;
            C109544Rq c109544Rq = this.LJLILLLLZI;
            long uptimeMillis = SystemClock.uptimeMillis();
            C63540Owi c63540Owi = this.LJLJI;
            this.LJLIL = 1;
            obj = c106714Gt.LIZIZ(c109544Rq, uptimeMillis, c63540Owi, this);
            if (obj == enumC58928NAu) {
                return enumC58928NAu;
            }
        }
        JSONObject jSONObject = (JSONObject) obj;
        jSONObject.put("message_type", C3V2.LIZ(this.LJLILLLLZI));
        this.LJLJJI.LIZ("dm_system_messages_response", jSONObject);
        C106714Gt.LIZJ(jSONObject, this.LJLJI);
        return C76800UCe.LIZ;
    }

    @Override // X.InterfaceC88471Ynr
    public final Object invoke(InterfaceC70422pa interfaceC70422pa, InterfaceC67352kd<? super C76800UCe> interfaceC67352kd) {
        return ((a) create(interfaceC70422pa, interfaceC67352kd)).invokeSuspend(C76800UCe.LIZ);
    }
}
