package X;

import Y.ACListenerS42S0200000_7;
import Y.ARunnableS43S0100000_7;
import android.os.Handler;
import androidx.fragment.app.FragmentManager;
import androidx.lifecycle.MutableLiveData;
import com.bytedance.keva.Keva;
import com.bytedance.tux.sheet.sheet.TuxSheet;
import com.ss.android.ugc.aweme.creative.model.music.MusicObject;
import com.ss.android.ugc.aweme.internal.CrossLanguageUserExperiment;
import com.ss.android.ugc.aweme.shortvideo.edit.VideoPublishEditModel;
import com.ss.android.ugc.aweme.shortvideo.experiment.AutogeneratedCaptionLanguageSelection;
import com.ss.android.ugc.aweme.shortvideo.model.CommonSettingItemStatus;
import java.util.ArrayList;
import kotlin.jvm.internal.AqS157S0100000_7;
import kotlin.jvm.internal.AqS7S0111000_7;
import ujb.o;

/* renamed from: X.G6y, reason: case insensitive filesystem */
/* loaded from: classes8.dex */
public final class C40992G6y {
    public final C29S LIZ;
    public final CommonSettingItemStatus LIZIZ;
    public final VideoPublishEditModel LIZJ;
    public final G6O LIZLLL;
    public final InterfaceC65784Pro<C76800UCe> LJ;
    public final C62822Ol8 LJFF;

    public static boolean LIZIZ() {
        if (o.LJJJJIZL("us", C44296Ha0.LIZ(), true) || o.LJJJJIZL("au", C44296Ha0.LIZ(), true)) {
            return true;
        }
        return false;
    }

    public final boolean LIZ() {
        boolean z;
        MusicObject musicObject;
        if ((C44384HbQ.LJLJJI(this.LIZJ) && this.LIZJ.voiceVolume != 0.0f) || this.LIZJ.hasRecord()) {
            z = true;
        } else {
            z = false;
        }
        if (C40975G6h.LIZ()) {
            if (!z && ((musicObject = this.LIZJ.creativeModel.musicBuzModel.music) == null || musicObject.isPgc)) {
                return false;
            }
            return true;
        }
        return z;
    }

    public final void LIZLLL() {
        int i = 0;
        if (C52250Kf0.LIZIZ()) {
            VideoPublishEditModel videoPublishEditModel = this.LIZJ;
            if (videoPublishEditModel.captionStruct == null && videoPublishEditModel.isPrivate == 0 && LIZ() && !LIZIZ() && !Keva.getRepo("TOOLS_PUBLISH_REPO_NAME").getBoolean("autogenerated_caption_popup_shown_again", false) && !GAE.LIZ()) {
                this.LIZLLL.LIZ.LJI(Boolean.FALSE);
                C29S c29s = this.LIZ;
                String LJJIIJZLJL = C78685UuP.LJJIIJZLJL();
                AutogeneratedCaptionLanguageSelection[] LIZ = DU6.LIZ();
                ArrayList arrayList = new ArrayList(LIZ.length);
                int length = LIZ.length;
                while (true) {
                    if (i >= length) {
                        break;
                    }
                    AutogeneratedCaptionLanguageSelection autogeneratedCaptionLanguageSelection = LIZ[i];
                    if (kotlin.jvm.internal.o.LJ(autogeneratedCaptionLanguageSelection.getCode(), LJJIIJZLJL)) {
                        LJJIIJZLJL = autogeneratedCaptionLanguageSelection.getLocalName();
                        break;
                    } else {
                        arrayList.add(C76800UCe.LIZ);
                        i++;
                    }
                }
                C41539GRz c41539GRz = new C41539GRz(c29s, LJJIIJZLJL);
                TuxSheet tuxSheet = new ASL().LIZ;
                tuxSheet.LJLLI = c41539GRz;
                C16880lQ.LJJIZ(c41539GRz.getBtnDismiss(), new ACListenerS42S0200000_7(tuxSheet, this, 28));
                C16880lQ.LJIILLIIL(c41539GRz.getIvClose(), new ACListenerS42S0200000_7(tuxSheet, this, 29));
                FragmentManager supportFragmentManager = this.LIZ.getSupportFragmentManager();
                kotlin.jvm.internal.o.LJIIIIZZ(supportFragmentManager, "activity.supportFragmentManager");
                tuxSheet.show(supportFragmentManager, "ManageAutoGeneratedCaptionsIntroView");
                Keva.getRepo("TOOLS_PUBLISH_REPO_NAME").storeBoolean("autogenerated_caption_popup_shown_again", true);
                VideoPublishEditModel videoPublishEditModel2 = this.LIZJ;
                String str = videoPublishEditModel2.mShootWay;
                String creationId = videoPublishEditModel2.getCreationId();
                kotlin.jvm.internal.o.LJIIIIZZ(creationId, "model.creationId");
                C145995oB c145995oB = new C145995oB();
                c145995oB.LJI("enter_from", "video_post_page");
                c145995oB.LJI("creation_id", creationId);
                if (str == null) {
                    str = "";
                }
                c145995oB.LJI("shoot_way", str);
                c145995oB.LJI("author_id", C44172HVg.LJIJ.getCurrentUserID());
                FMX.LJIIL("asr_authorization_intro_show", c145995oB.LIZ);
            }
        }
    }

    public final boolean LIZJ(int i) {
        if (!LIZ() || (!GAE.LIZ() && i != 0)) {
            return true;
        }
        return false;
    }

    public final void LJ(int i, boolean z, boolean z2) {
        int i2;
        if (CrossLanguageUserExperiment.LIZJ().LIZIZ() && !this.LIZJ.hasSubtitle()) {
            MutableLiveData<Integer> mutableLiveData = this.LIZIZ._visibility;
            if (GAE.LIZ()) {
                i2 = 8;
            } else {
                i2 = 0;
            }
            mutableLiveData.setValue(i2);
            boolean LIZJ = LIZJ(i);
            if (this.LIZJ.captionStruct != null) {
                this.LIZIZ._visibility.setValue(8);
                this.LIZIZ._checked.setValue(Boolean.FALSE);
            } else if (C52250Kf0.LIZIZ() && LIZIZ()) {
                this.LIZIZ._visibility.setValue(8);
                this.LIZIZ._checked.setValue(Boolean.TRUE);
                if (z2) {
                    LIZLLL();
                }
            } else if (LIZJ) {
                this.LIZIZ._alpha.setValue(Float.valueOf(0.4f));
                this.LIZIZ._checked.setValue(Boolean.FALSE);
            } else {
                this.LIZIZ._alpha.setValue(Float.valueOf(1.0f));
                this.LIZIZ._checked.setValue(Boolean.valueOf(z));
                if (C52250Kf0.LIZIZ()) {
                    if (z2) {
                        LIZLLL();
                    }
                } else {
                    Boolean value = this.LIZIZ._checked.getValue();
                    Boolean bool = Boolean.FALSE;
                    if (kotlin.jvm.internal.o.LJ(value, bool) && C00F.LIZ(31744, 0, "show_sheet_on_auto_generated_captions", true) > 0 && (!C40987G6t.LIZ.getBoolean("auto_pop_once_auto_caption_sheet", false))) {
                        this.LIZLLL.LIZ.LJI(bool);
                        new Handler(C16880lQ.LLJJJJ()).post(new ARunnableS43S0100000_7(this, 125));
                    }
                }
            }
            this.LIZIZ.setOnClickListener(new AqS7S0111000_7(LIZJ, this, i, 1));
            return;
        }
        this.LIZIZ._visibility.setValue(8);
    }

    public C40992G6y(C29S activity, CommonSettingItemStatus itemStatus, VideoPublishEditModel model, G6O bubbleViewManager, G6M moreOptionsHighlight) {
        kotlin.jvm.internal.o.LJIIIZ(activity, "activity");
        kotlin.jvm.internal.o.LJIIIZ(itemStatus, "itemStatus");
        kotlin.jvm.internal.o.LJIIIZ(model, "model");
        kotlin.jvm.internal.o.LJIIIZ(bubbleViewManager, "bubbleViewManager");
        kotlin.jvm.internal.o.LJIIIZ(moreOptionsHighlight, "moreOptionsHighlight");
        this.LIZ = activity;
        this.LIZIZ = itemStatus;
        this.LIZJ = model;
        this.LIZLLL = bubbleViewManager;
        this.LJ = moreOptionsHighlight;
        this.LJFF = C221108m2.LIZIZ(new AqS157S0100000_7(this, 528));
    }
}
