package X;

import com.ss.android.ugc.aweme.effectplatform.EffectPlatform;
import com.ss.android.ugc.aweme.out.AVExternalServiceImpl;
import java.util.HashSet;

/* renamed from: X.GvO, reason: case insensitive filesystem */
/* loaded from: classes8.dex */
public final class C43074GvO {
    static {
        HashSet hashSet = new HashSet();
        HashSet hashSet2 = new HashSet();
        hashSet2.add(C43075GvP.LIZIZ);
        hashSet2.add(C43075GvP.LIZJ);
        hashSet2.add(C43075GvP.LIZLLL);
        hashSet2.add(C43075GvP.LJI);
        hashSet2.add(C43075GvP.LJII);
        hashSet2.add(C43075GvP.LJIIIIZZ);
        hashSet2.add(C43075GvP.LJIIIZ);
        hashSet2.add(C43075GvP.LJIIJ);
        hashSet2.add(C43075GvP.LJIIJJI);
        hashSet2.add(EffectPlatform.LJLJJI.getPath());
        hashSet2.add(C43075GvP.LJIIL);
        hashSet2.add(C43075GvP.LJIILIIL);
        hashSet2.add(C43075GvP.LJIILJJIL);
        hashSet2.add(C43075GvP.LJIILLIIL);
        hashSet2.add(C43075GvP.LJ);
        hashSet2.add(C43075GvP.LJFF);
        hashSet2.add(C44529Hdl.LJIIZILJ);
        StringBuilder LIZ = X1D.LIZ();
        String str = C43075GvP.LIZ;
        LIZ.append(str);
        LIZ.append("ve_frame_cache2");
        hashSet2.add(X1D.LIZIZ(LIZ));
        StringBuilder LIZ2 = X1D.LIZ();
        LIZ2.append(str);
        LIZ2.append("mvtheme");
        hashSet2.add(X1D.LIZIZ(LIZ2));
        StringBuilder LIZ3 = X1D.LIZ();
        LIZ3.append(str);
        LIZ3.append("filter");
        hashSet2.add(X1D.LIZIZ(LIZ3));
        hashSet2.add(C135045Rs.LIZ());
        StringBuilder LIZ4 = X1D.LIZ();
        LIZ4.append(str);
        LIZ4.append("extract_split_video");
        hashSet2.add(X1D.LIZIZ(LIZ4));
        StringBuilder LIZ5 = X1D.LIZ();
        LIZ5.append(str);
        LIZ5.append("shortvideo/shoot/");
        hashSet2.add(X1D.LIZIZ(LIZ5));
        StringBuilder LIZ6 = X1D.LIZ();
        LIZ6.append(str);
        LIZ6.append("shortvideo/videoedit/");
        hashSet2.add(X1D.LIZIZ(LIZ6));
        StringBuilder LIZ7 = X1D.LIZ();
        LIZ7.append(str);
        LIZ7.append("shortvideo/publish");
        hashSet2.add(X1D.LIZIZ(LIZ7));
        StringBuilder LIZ8 = X1D.LIZ();
        LIZ8.append(str);
        LIZ8.append("shortvideo/cache/");
        hashSet2.add(X1D.LIZIZ(LIZ8));
        StringBuilder LIZ9 = X1D.LIZ();
        LIZ9.append(str);
        LIZ9.append("shortvideo/resources/");
        hashSet2.add(X1D.LIZIZ(LIZ9));
        StringBuilder LIZ10 = X1D.LIZ();
        LIZ10.append(str);
        LIZ10.append("shortvideo/draft/");
        hashSet2.add(X1D.LIZIZ(LIZ10));
        StringBuilder LIZ11 = X1D.LIZ();
        LIZ11.append(str);
        LIZ11.append("shortvideo/story");
        hashSet2.add(X1D.LIZIZ(LIZ11));
        StringBuilder LIZ12 = X1D.LIZ();
        LIZ12.append(str);
        LIZ12.append("multi_edit/");
        hashSet2.add(X1D.LIZIZ(LIZ12));
        StringBuilder LIZ13 = X1D.LIZ();
        LIZ13.append(str);
        LIZ13.append("filter/");
        hashSet2.add(X1D.LIZIZ(LIZ13));
        StringBuilder LIZ14 = X1D.LIZ();
        LIZ14.append(str);
        LIZ14.append("font/");
        hashSet2.add(X1D.LIZIZ(LIZ14));
        StringBuilder LIZ15 = X1D.LIZ();
        LIZ15.append(str);
        LIZ15.append("effect/");
        hashSet2.add(X1D.LIZIZ(LIZ15));
        StringBuilder LIZ16 = X1D.LIZ();
        LIZ16.append(str);
        LIZ16.append("music/");
        hashSet2.add(X1D.LIZIZ(LIZ16));
        StringBuilder LIZ17 = X1D.LIZ();
        LIZ17.append(str);
        LIZ17.append("effectmodel/");
        hashSet2.add(X1D.LIZIZ(LIZ17));
        StringBuilder LIZ18 = X1D.LIZ();
        LIZ18.append(str);
        LIZ18.append("audio-effect/");
        hashSet2.add(X1D.LIZIZ(LIZ18));
        StringBuilder LIZ19 = X1D.LIZ();
        LIZ19.append(str);
        LIZ19.append("mvtheme/");
        hashSet2.add(X1D.LIZIZ(LIZ19));
        StringBuilder LIZ20 = X1D.LIZ();
        LIZ20.append(str);
        LIZ20.append("pin/");
        hashSet2.add(X1D.LIZIZ(LIZ20));
        StringBuilder LIZ21 = X1D.LIZ();
        LIZ21.append(str);
        LIZ21.append("extract_shot/");
        hashSet2.add(X1D.LIZIZ(LIZ21));
        StringBuilder LIZ22 = X1D.LIZ();
        LIZ22.append(str);
        LIZ22.append("videoimage_mixed_resize/");
        hashSet2.add(X1D.LIZIZ(LIZ22));
        String shareDir = AVExternalServiceImpl.LIZ().configService().cacheConfig().shareDir();
        StringBuilder LIZ23 = X1D.LIZ();
        LIZ23.append(shareDir);
        LIZ23.append("openPlatform/");
        hashSet2.add(X1D.LIZIZ(LIZ23));
        hashSet2.add(C60903NvH.LJIIJJI().LJJIJL().getPathService().getRoot());
        hashSet2.add(C60903NvH.LJIIJJI().LJJIJL().getPathService().getCacheRoot());
        hashSet.addAll(hashSet2);
    }

    public static final String LIZ() {
        StringBuilder LIZ = X1D.LIZ();
        LIZ.append(C16880lQ.LLLLLLLLLL().toString());
        LIZ.append("/DCIM/Camera/");
        return X1D.LIZIZ(LIZ);
    }
}
