package X;

import android.view.Surface;
import com.ss.android.ugc.aweme.player.sdk.api.OnPlayerPreparedListener;
import com.ss.android.ugc.aweme.player.sdk.api.OnPreRenderListener;
import com.ss.android.ugc.playerkit.simapicommon.model.SimVideo;
import com.ss.android.ugc.playerkit.simapicommon.model.SimVideoUrlModel;
import java.util.HashMap;
import java.util.List;
import org.json.JSONObject;

/* renamed from: X.IWf, reason: case insensitive filesystem */
/* loaded from: classes9.dex */
public final class C46745IWf {
    public static final /* synthetic */ int LJJLIL = 0;
    public OnPreRenderListener LIZ;
    public OnPlayerPreparedListener LIZIZ;
    public SimVideo LIZJ;
    public List<C47123IeV> LIZLLL;
    public EnumC47177IfN LJFF;
    public SimVideoUrlModel LJI;
    public boolean LJII;
    public boolean LJIIIIZZ;
    public int LJIIJ;
    public int LJIIJJI;
    public int LJIIL;
    public Surface LJIILIIL;
    public boolean LJIJJLI;
    public boolean LJIL;
    public boolean LJJ;
    public boolean LJJI;
    public boolean LJJII;
    public boolean LJJIII;
    public long LJJIIJ;
    public InterfaceC47143Iep LJJIIJZLJL;
    public InterfaceC47128Iea LJJIIZ;
    public List<? extends Surface> LJJIJ;
    public boolean LJJIJIIJI;
    public boolean LJJIJIIJIL;
    public boolean LJJIJIL;
    public boolean LJJIJL;
    public boolean LJJIJLIJ;
    public boolean LJJIL;
    public boolean LJJIZ;
    public boolean LJJJ;
    public int LJJJI;
    public String LJJJIL;
    public JSONObject LJJJJ;
    public boolean LJJJJL;
    public HashMap<String, Object> LJJJJLI;
    public boolean LJJJJLL;
    public boolean LJJJJZI;
    public boolean LJJJLIIL;
    public boolean LJJJLL;
    public boolean LJJJLZIJ;
    public String LJJJZ;
    public long LJJLIIIJ;
    public boolean LJJLIIIJILLIZJL;
    public String LJJLIIIJJI;
    public IZG LJJLIIIJJIZ;
    public boolean LJJLIIIJLJLI;
    public String LJJLIIJ;
    public int LJ = -1;
    public boolean LJIIIZ = true;
    public boolean LJIILJJIL = IZ8.LJJIJLIJ();
    public boolean LJIILL = true;
    public String LJIILLIIL = "";
    public String LJIIZILJ = "";
    public boolean LJIJ = true;
    public boolean LJIJI = true;
    public IWI LJIJJ = IWI.Normal;
    public float LJJIFFI = 1.0f;
    public InterfaceC47125IeX<Long, Long> LJJIIZI = new C47241IgP(1);
    public boolean LJJJJI = true;
    public boolean LJJJJIZL = true;
    public int LJJJJJ = -1;
    public int LJJJJJL = -1;
    public boolean LJJJJZ = true;
    public float LJJL = Float.MIN_VALUE;
    public int LJJLI = -1;
    public String LJJLIIIIJ = "";
    public int LJJLIIIJL = 1;
    public final int LJJLIIIJLLLLLLLZ = -1;
}
