package X;

import com.aweme.storage.StorageCleanServiceImpl;
import com.aweme.ttkvstorage.UpdateRegisterKeyImpl;
import com.bytedance.awemelobby.LobbyNonceGenerator;
import com.bytedance.ies.im.core.service.IMCoreProxyService;
import com.bytedance.ies.ugc.aweme.commercialize.compliance.service.ComplianceServiceImpl;
import com.bytedance.ies.ugc.aweme.commercialize.compliance.service.ConsistentContentAndAdChoiceServiceImpl;
import com.bytedance.ies.ugc.aweme.commercialize.intelligence.IntelligenceModuleImpl;
import com.bytedance.ies.ugc.aweme.commercialize.intelligence.feed.AdReRankServiceManager;
import com.bytedance.ies.ugc.aweme.commercialize.scene.impl.AdSceneServiceImpl;
import com.bytedance.ies.ugc.aweme.commercialize.search.arch.v2.module.GlobalSearchAdModuleImpl;
import com.bytedance.ies.ugc.aweme.commercialize.splash.core.SplashAdServiceImpl;
import com.bytedance.ies.ugc.aweme.commercialize.splash.core.SplashSettingServiceImpl;
import com.bytedance.ies.ugc.aweme.commercialize.splash.realtimesplash.RealTimeSplashManagerImpl;
import com.bytedance.ies.ugc.aweme.commercialize.splash.realtimesplashnp.RealTimeSplashNPManagerImpl;
import com.bytedance.ies.ugc.aweme.network.RetrofitFactory;
import com.bytedance.ies.ugc.statisticlogger.btm.BTMTrackerServiceImpl;
import com.bytedance.ies.ugc.ttkvstorageimpl.UserAccountImpl;
import com.bytedance.ies.ugc.ttkvstorageimpl.settings.TTKVStorageSettings;
import com.bytedance.lighten.loader.ImagePipelineConfigFactory;
import com.bytedance.pumbaa.PumbaaServiceImpl;
import com.bytedance.pumbaa.bpea.adapter.BPEAServiceImp;
import com.bytedance.pumbaa.hybrid.impl.HybridServiceImpl;
import com.bytedance.pumbaa.hybrid.monitor.HybridMonitorServiceImpl;
import com.bytedance.pumbaa.hybrid.rasp.RaspServiceImpl;
import com.bytedance.pumbaa.monitor.adapter.MonitorServiceImpl;
import com.bytedance.pumbaa.network.adapter.NetworkServiceImpl;
import com.bytedance.pumbaa.pdp.PolicyDecisionImp;
import com.bytedance.pumbaa.ruler.adapter.RuleEngineServiceImpl;
import com.bytedance.tiktok.homepage.services.MainPageFragmentImpl;
import com.lingo.caption.LingoCaptionImpl;
import com.lingo.caption.LingoCaptionInnerImpl;
import com.ss.android.elearning.lingo.log.ElLogDefault;
import com.ss.android.elearning.lingo.lynx.LingoLynxImpl;
import com.ss.android.elearning.lingo.roma.RomaServiceImpl;
import com.ss.android.elearning.lingo.tracker.impl.ElTrackerServiceImpl;
import com.ss.android.experiment.ImageHeaderConfigImpl;
import com.ss.android.experiment.LauncherExperimentsImpl;
import com.ss.android.legoimpl.ABLegoTaskImpl;
import com.ss.android.newmedia.ad.WebAdUserAgentServiceImpl;
import com.ss.android.ugc.AwemeAppBuildConfig;
import com.ss.android.ugc.aweme.AccountService;
import com.ss.android.ugc.aweme.ActivityRouterServiceImpl;
import com.ss.android.ugc.aweme.AnoleServiceImpl;
import com.ss.android.ugc.aweme.AutobackupService;
import com.ss.android.ugc.aweme.BuildConfigAllServiceImpl;
import com.ss.android.ugc.aweme.CQrcodeService;
import com.ss.android.ugc.aweme.CrossPlatformLegacyServiceImpl;
import com.ss.android.ugc.aweme.DetailFeedServiceImpl;
import com.ss.android.ugc.aweme.DubbingServiceImpl;
import com.ss.android.ugc.aweme.InboxRepostFeedServiceImpl;
import com.ss.android.ugc.aweme.NewUserJourneyService;
import com.ss.android.ugc.aweme.NujPerformanceService;
import com.ss.android.ugc.aweme.PerfMonitorServiceImpl;
import com.ss.android.ugc.aweme.PreloadApiServiceImpl;
import com.ss.android.ugc.aweme.PrivacyDisclaimerUtilService;
import com.ss.android.ugc.aweme.ProfileNaviServiceImpl;
import com.ss.android.ugc.aweme.SettingsMainApiImpl;
import com.ss.android.ugc.aweme.UgAllServiceImpl;
import com.ss.android.ugc.aweme.account.AccountInitServiceImpl;
import com.ss.android.ugc.aweme.account.PreLoginHandleService;
import com.ss.android.ugc.aweme.account.agegate.RegistrationAgeGateServiceImpl;
import com.ss.android.ugc.aweme.account.experiment.AccountBindingsService;
import com.ss.android.ugc.aweme.account.experiment.AccountFeatureFlagService;
import com.ss.android.ugc.aweme.account.experiment.MultiAccountService;
import com.ss.android.ugc.aweme.account.guestmode.GuestModeServiceImpl;
import com.ss.android.ugc.aweme.account.login.GoogleOneTapLogger;
import com.ss.android.ugc.aweme.account.login.googleonetap.GoogleOneTapService;
import com.ss.android.ugc.aweme.account.login.passkey.PasskeyService;
import com.ss.android.ugc.aweme.account.login.prevlogin.PrevLoginPlatformService;
import com.ss.android.ugc.aweme.account.login.twostep.nonce.AccountNonceUtilImpl;
import com.ss.android.ugc.aweme.account.login.v2.ui.PrivateAccountTipsViewDelegate;
import com.ss.android.ugc.aweme.account.main.AccountMainServiceImpl;
import com.ss.android.ugc.aweme.account.passwordcheck.service.KnownWeakPasswordService;
import com.ss.android.ugc.aweme.account.popup.popuphelper.PasskeyPopUpHelper;
import com.ss.android.ugc.aweme.account.popup.popuphelper.SyncNicknameAndUsernamePopUpHelper;
import com.ss.android.ugc.aweme.account.profilebadge.ProfileBadgeServiceImpl;
import com.ss.android.ugc.aweme.account.prompt.AccountShowConfirmPromptServiceImpl;
import com.ss.android.ugc.aweme.accountxbridge.AccountBDXBridgeService;
import com.ss.android.ugc.aweme.ad.FeedAdServiceImpl;
import com.ss.android.ugc.aweme.ad.comment.AdCommentService;
import com.ss.android.ugc.aweme.ad.feed.CommercializeFeedServiceImpl;
import com.ss.android.ugc.aweme.ad.feed.adexperience.CommerceAdExperienceServiceImpl;
import com.ss.android.ugc.aweme.ad.feed.feinteraction.AdFeInteractionImpl;
import com.ss.android.ugc.aweme.ad.feed.ibe.CommerceIBEService;
import com.ss.android.ugc.aweme.ad.feed.photomode.AdPhotoModeServiceImpl;
import com.ss.android.ugc.aweme.ad.feed.photomode.IAdSlidePreloadImpl;
import com.ss.android.ugc.aweme.ad.feed.shakeEgg.ShakeEggService;
import com.ss.android.ugc.aweme.ad.feed.utils.FeedBackDialogManagerService;
import com.ss.android.ugc.aweme.ad.preload.AdLandPagePreloadServiceImpl;
import com.ss.android.ugc.aweme.ad.preload.gecko.GeckoPreloadServiceImpl;
import com.ss.android.ugc.aweme.ad.prerender.PreRenderWebViewManager;
import com.ss.android.ugc.aweme.ad.subpage.CommerceLandPageModuleImpl;
import com.ss.android.ugc.aweme.adaptation.saa.SAAService;
import com.ss.android.ugc.aweme.aigc.AIGCAvatarServiceImpl;
import com.ss.android.ugc.aweme.album.ToolsAlbumServiceImpl;
import com.ss.android.ugc.aweme.anchor.service.AnchorListServiceImpl;
import com.ss.android.ugc.aweme.anchor.service.AnchorOperationServiceImpl;
import com.ss.android.ugc.aweme.anchor.service.AnchorStateServiceImpl;
import com.ss.android.ugc.aweme.anchor.service.CustomAnchorViewServicImpl;
import com.ss.android.ugc.aweme.anchor.service.EcommerceAnchorService;
import com.ss.android.ugc.aweme.api.AnchorBusinessApiImpl;
import com.ss.android.ugc.aweme.api.FeedServiceImpl;
import com.ss.android.ugc.aweme.api.LegoBusinessServiceImpl;
import com.ss.android.ugc.aweme.api.component.AdComponentServiceImpl;
import com.ss.android.ugc.aweme.app.AwemeApplicationServiceImpl;
import com.ss.android.ugc.aweme.app.InitAllServiceImpl;
import com.ss.android.ugc.aweme.app.accountsdk.AccountInitializer;
import com.ss.android.ugc.aweme.app.launch.SystemServiceApiImpl;
import com.ss.android.ugc.aweme.app.launch.TaskServiceImpl;
import com.ss.android.ugc.aweme.app.services.DownloadService;
import com.ss.android.ugc.aweme.app.services.HybridABInfoService;
import com.ss.android.ugc.aweme.app.services.LauncherService;
import com.ss.android.ugc.aweme.app.services.NewUserMainModuleService;
import com.ss.android.ugc.aweme.app.services.RegionService;
import com.ss.android.ugc.aweme.app.services.WebviewService;
import com.ss.android.ugc.aweme.appsflyer.AppsflyerImpl;
import com.ss.android.ugc.aweme.audiomode.fullepisodev2.service.FullEpisodeRouterServiceImpl;
import com.ss.android.ugc.aweme.audiomode.legoimpl.AudioSDKABLegoLauncherTaskImpl;
import com.ss.android.ugc.aweme.audiomode.vopclone.service.VopBDXBridgeServiceImpl;
import com.ss.android.ugc.aweme.audiomode.vopclone.service.VopCloneServiceImpl;
import com.ss.android.ugc.aweme.autofill.AdAutofillService;
import com.ss.android.ugc.aweme.avatar.AvatarImageServiceImpl;
import com.ss.android.ugc.aweme.avatar.AvatarInternalServiceImpl;
import com.ss.android.ugc.aweme.awemeservice.AwemeService;
import com.ss.android.ugc.aweme.awemeservice.RequestIdService;
import com.ss.android.ugc.aweme.base.service.FeedSkylightServiceImpl;
import com.ss.android.ugc.aweme.base.service.FeedSkylightServiceProviderImpl;
import com.ss.android.ugc.aweme.benchmark.BTCHConfigurationImpl;
import com.ss.android.ugc.aweme.benchmark.BenchmarkCollectionInitService;
import com.ss.android.ugc.aweme.benchmark.BenchmarkInitService;
import com.ss.android.ugc.aweme.benchmark.BenchmarkServiceImpl;
import com.ss.android.ugc.aweme.brdatagift.BemobiGiftServiceImpl;
import com.ss.android.ugc.aweme.bullet.BulletHostProxy;
import com.ss.android.ugc.aweme.bullet.impl.BulletService;
import com.ss.android.ugc.aweme.casting.CastingServiceImpl;
import com.ss.android.ugc.aweme.cct.OpenCCTUtils;
import com.ss.android.ugc.aweme.challenge.ChallengeDetailLegacyServiceImpl;
import com.ss.android.ugc.aweme.challenge.ChallengeDetailServiceImpl;
import com.ss.android.ugc.aweme.challenge.service.ChallengeDetailProvider;
import com.ss.android.ugc.aweme.challenge.service.ChallengeServiceImpl;
import com.ss.android.ugc.aweme.childhook.services.ChildHookServiceImpl;
import com.ss.android.ugc.aweme.comment.record.CommentStickerRecordServiceImpl;
import com.ss.android.ugc.aweme.comment.service.CommentServiceImpl;
import com.ss.android.ugc.aweme.comment.service.KeyboardServiceImpl;
import com.ss.android.ugc.aweme.comment.service.NoticeCommentHelperServiceImpl;
import com.ss.android.ugc.aweme.commerce.sdk.service.CommerceService;
import com.ss.android.ugc.aweme.commerce.tools.challenge.CommerceToolsChallengeService;
import com.ss.android.ugc.aweme.commerce.tools.common.CommerceToolsService;
import com.ss.android.ugc.aweme.commerce.tools.common.EventCenter;
import com.ss.android.ugc.aweme.commerce.tools.common.publish.CommerceToolsPublishService;
import com.ss.android.ugc.aweme.commerce.tools.mission.service.CommerceToolsMissionService;
import com.ss.android.ugc.aweme.commerce.tools.music.CommerceToolsMusicService;
import com.ss.android.ugc.aweme.commerce.tools.music.promote.PromoteRepalceMusicServiceImpl;
import com.ss.android.ugc.aweme.commerce.tools.sticker.service.CommerceToolsStickerServiceImpl;
import com.ss.android.ugc.aweme.commerce.tools.tcm.service.CommerceToolsTcmServiceImpl;
import com.ss.android.ugc.aweme.commercialize.AwemeContextServiceImpl;
import com.ss.android.ugc.aweme.commercialize.LegacyCommercializeServiceImpl;
import com.ss.android.ugc.aweme.commercialize.anchor.service.GetLeadsAnchorService;
import com.ss.android.ugc.aweme.commercialize.assem.AdAssemUtils;
import com.ss.android.ugc.aweme.commercialize.ba.impl.automessage.ui.helper.BaAutoMessageServiceImpl;
import com.ss.android.ugc.aweme.commercialize.ba.impl.service.BAAnchorServiceImpl;
import com.ss.android.ugc.aweme.commercialize.ba.impl.service.BABusinessSuitePageServiceImp;
import com.ss.android.ugc.aweme.commercialize.ba.impl.service.BAProfilePageServiceImpl;
import com.ss.android.ugc.aweme.commercialize.ba.impl.service.BASwitchToPAorBAServiceImpl;
import com.ss.android.ugc.aweme.commercialize.challenge.service.CommerceChallengeServiceImpl;
import com.ss.android.ugc.aweme.commercialize.depend.AdCommentDependImpl;
import com.ss.android.ugc.aweme.commercialize.depend.AdRouterHandlerDependImpl;
import com.ss.android.ugc.aweme.commercialize.depend.AdTaskDependImpl;
import com.ss.android.ugc.aweme.commercialize.depend.AdTrackDependImpl;
import com.ss.android.ugc.aweme.commercialize.ecommerce.service.ShoppingAdsServiceImpl;
import com.ss.android.ugc.aweme.commercialize.engagement.trace.EngagementTraceImpl;
import com.ss.android.ugc.aweme.commercialize.feed.AdAssemServiceImpl;
import com.ss.android.ugc.aweme.commercialize.feed.AdAssemblerServiceImpl;
import com.ss.android.ugc.aweme.commercialize.feed.AdTagServiceImpl;
import com.ss.android.ugc.aweme.commercialize.feed.candidate.CandidateRequestImpl;
import com.ss.android.ugc.aweme.commercialize.feed.slide.guide.MainPageSlideImpl;
import com.ss.android.ugc.aweme.commercialize.hybrid.impl.AdHybridContainerManager;
import com.ss.android.ugc.aweme.commercialize.hybrid.impl.web.service.impl.AdWebJumpInterceptor;
import com.ss.android.ugc.aweme.commercialize.impl.CommerceServiceImpl;
import com.ss.android.ugc.aweme.commercialize.live.promote.service.PromoteUtilImpl;
import com.ss.android.ugc.aweme.commercialize.live.service.CommercializeLiveServiceImpl;
import com.ss.android.ugc.aweme.commercialize.log.AdLogServiceImpl;
import com.ss.android.ugc.aweme.commercialize.log.FeedRawAdLogUtilsImpl;
import com.ss.android.ugc.aweme.commercialize.log.LogHelperImpl;
import com.ss.android.ugc.aweme.commercialize.measurement.MeasurementServiceImpl;
import com.ss.android.ugc.aweme.commercialize.measurement.mrc.MRCManager;
import com.ss.android.ugc.aweme.commercialize.media.impl.service.CommerceMediaServiceImpl;
import com.ss.android.ugc.aweme.commercialize.mission.CommerceMissionServiceImpl;
import com.ss.android.ugc.aweme.commercialize.playfun.AdPlayFunAsseUtils;
import com.ss.android.ugc.aweme.commercialize.prefetch.AdWebViewPrefetchManager;
import com.ss.android.ugc.aweme.commercialize.preview.service.AdsPreviewServiceImpl;
import com.ss.android.ugc.aweme.commercialize.profile.impl.ad.CommerceProfileService;
import com.ss.android.ugc.aweme.commercialize.profile.talent.TalentAdRevenueShareServiceImpl;
import com.ss.android.ugc.aweme.commercialize.service.CommerceCommonServiceImpl;
import com.ss.android.ugc.aweme.commercialize.sticker.service.CommerceLockStickerServiceImpl;
import com.ss.android.ugc.aweme.commercialize.utils.AdOpenHelperImpl;
import com.ss.android.ugc.aweme.commercialize.utils.NoticeChallengePropertyUtilImpl;
import com.ss.android.ugc.aweme.commercialize.views.AdLightWebPageOpenUtils;
import com.ss.android.ugc.aweme.commercialize_x.service.CommercializeAdServiceImpl;
import com.ss.android.ugc.aweme.compliance.ComplianceDependServiceImpl;
import com.ss.android.ugc.aweme.compliance.business.agecontrol.PNSAgeControlService;
import com.ss.android.ugc.aweme.compliance.business.policy.CompliancePolicyServiceImpl;
import com.ss.android.ugc.aweme.compliance.business.serviceimpl.AgeAppealServiceImpl;
import com.ss.android.ugc.aweme.compliance.business.serviceimpl.AgeGateServiceImpl;
import com.ss.android.ugc.aweme.compliance.business.serviceimpl.BanAppealServiceImpl;
import com.ss.android.ugc.aweme.compliance.business.serviceimpl.ChildModeServiceImpl;
import com.ss.android.ugc.aweme.compliance.business.serviceimpl.ComplianceBusinessServiceImpl;
import com.ss.android.ugc.aweme.compliance.business.serviceimpl.ComplianceSettingsServiceImpl;
import com.ss.android.ugc.aweme.compliance.business.serviceimpl.PnSSearchHistoryServiceImpl;
import com.ss.android.ugc.aweme.compliance.business.serviceimpl.PolicyNoticeServiceImpl;
import com.ss.android.ugc.aweme.compliance.business.serviceimpl.PrivateAccountServiceImpl;
import com.ss.android.ugc.aweme.compliance.business.serviceimpl.ReportServiceImpl;
import com.ss.android.ugc.aweme.compliance.business.serviceimpl.TermsConsentServiceImpl;
import com.ss.android.ugc.aweme.compliance.business.serviceimpl.TpcConsentServiceImpl;
import com.ss.android.ugc.aweme.compliance.business.share.ShareWarningInfoServiceImpl;
import com.ss.android.ugc.aweme.compliance.business.statemachine.PNSUserStateManager;
import com.ss.android.ugc.aweme.compliance.common.serviceimpl.ComplianceMonitorServiceImpl;
import com.ss.android.ugc.aweme.compliance.common.serviceimpl.HydrogenServiceImpl;
import com.ss.android.ugc.aweme.compliance.consent.consentmanagementframework.PNSConsentServiceImpl;
import com.ss.android.ugc.aweme.compliance.consent.serviceimpl.ConsentServiceImpl;
import com.ss.android.ugc.aweme.compliance.consent.serviceimpl.PNSDeviceConsentServiceImpl;
import com.ss.android.ugc.aweme.compliance.protection.serviceimpl.AlgoRefreshServiceImpl;
import com.ss.android.ugc.aweme.compliance.protection.serviceimpl.AntiAddictionServiceImpl;
import com.ss.android.ugc.aweme.compliance.protection.serviceimpl.FamilyPairingServiceImpl;
import com.ss.android.ugc.aweme.compliance.protection.serviceimpl.ProtectionServiceImpl;
import com.ss.android.ugc.aweme.compliance.sandbox.serviceimpl.SandboxServiceImpl;
import com.ss.android.ugc.aweme.compliance.sandbox.webview.WebViewTTNetHandlerImp;
import com.ss.android.ugc.aweme.configcenter.AwemeConfigCenter;
import com.ss.android.ugc.aweme.contact.service.IMContactServiceImpl;
import com.ss.android.ugc.aweme.contentlanguage.ContentLanguageServiceImpl;
import com.ss.android.ugc.aweme.contentlanguage.api.ContentLanguageGuideServiceImpl;
import com.ss.android.ugc.aweme.creatorcenter.CreatorCenterPreloadServiceImpl;
import com.ss.android.ugc.aweme.creatortools.creatorplus.service.CreatorToolServiceImpl;
import com.ss.android.ugc.aweme.crossplatform.business.MixActivityContainerProvider;
import com.ss.android.ugc.aweme.deeplink.DeepLinkServiceImpl;
import com.ss.android.ugc.aweme.detail.api.DetailApiProxyImpl;
import com.ss.android.ugc.aweme.detail.panel.DuetModeCameraServiceImpl;
import com.ss.android.ugc.aweme.di.ImEntranceService;
import com.ss.android.ugc.aweme.discover.impl.DiscoveryAsyncInflateImpl;
import com.ss.android.ugc.aweme.dmt_integration.AVInitializerImpl;
import com.ss.android.ugc.aweme.donation.DonationServiceImpl;
import com.ss.android.ugc.aweme.download.DownloadAwemeVideoServiceImpl;
import com.ss.android.ugc.aweme.download.impl.component_impl.DownloadServiceImpl;
import com.ss.android.ugc.aweme.duet.impl.DuetDetailServiceImpl;
import com.ss.android.ugc.aweme.duetmode.impl.DuetDiscoverServiceImpl;
import com.ss.android.ugc.aweme.ecommerce.ECommerceHybridServiceImpl;
import com.ss.android.ugc.aweme.ecommerce.ECommerceThirdPartyHybridServiceImpl;
import com.ss.android.ugc.aweme.ecommerce.ECommerceXBridgeService;
import com.ss.android.ugc.aweme.ecommerce.ab.ECommerceArchServiceImpl;
import com.ss.android.ugc.aweme.ecommerce.base.common.EcomImageMonitorImpl;
import com.ss.android.ugc.aweme.ecommerce.base.common.EcommerceLiveDegradeExp;
import com.ss.android.ugc.aweme.ecommerce.base.common.EcommerceMonitorService;
import com.ss.android.ugc.aweme.ecommerce.base.common.view.CommerceHybridBottomSheetDialogFragmentBehaviorImpl;
import com.ss.android.ugc.aweme.ecommerce.base.pdp.jsb.service.PdpCardBridgeServiceImpl;
import com.ss.android.ugc.aweme.ecommerce.base.pdp.repository.PdpPreviewServiceImpl;
import com.ss.android.ugc.aweme.ecommerce.core.preloader.LowResolutionImageCache;
import com.ss.android.ugc.aweme.ecommerce.core.router.EcomSparkSubInterceptorProvider;
import com.ss.android.ugc.aweme.ecommerce.core.router.StrategyService;
import com.ss.android.ugc.aweme.ecommerce.core.services.ECImageService;
import com.ss.android.ugc.aweme.ecommerce.core.services.ECommerceService;
import com.ss.android.ugc.aweme.ecommerce.fashionmall.FashionMallService;
import com.ss.android.ugc.aweme.ecommerce.fashionmall.FashionMallTabIconService;
import com.ss.android.ugc.aweme.ecommerce.mall.ECommerceMallService;
import com.ss.android.ugc.aweme.ecommerce.mall.MallServiceManager;
import com.ss.android.ugc.aweme.ecommerce.mall.vm.ShopIconServiceImpl;
import com.ss.android.ugc.aweme.ecommerce.schema.EcSchemaService;
import com.ss.android.ugc.aweme.ecommerce.showcase.ECommerceShowcaseService;
import com.ss.android.ugc.aweme.ecommerce.showcase.EcommerceStoreBizLogServiceImpl;
import com.ss.android.ugc.aweme.ecommerce.showcase.EcommerceStoreTechLogServiceImpl;
import com.ss.android.ugc.aweme.ecommerce.showcase.settings.RomaSchemaGroupShoppingStoreSettings;
import com.ss.android.ugc.aweme.ecommerce.smartcheck.integrate.SmartCheckIntegrateImpl;
import com.ss.android.ugc.aweme.ecommerce.ug.common.service.EcUgCommonService;
import com.ss.android.ugc.aweme.ecommerce.ug.deeplink.service.EcUgDeeplinkService;
import com.ss.android.ugc.aweme.ecommerce.ug.feedeccard.service.EcUgFeedEcCardService;
import com.ss.android.ugc.aweme.ecommerce.ug.newinstall.service.EcUgNewInstallService;
import com.ss.android.ugc.aweme.ecommerce.ug.popup.service.EcUgPopupService;
import com.ss.android.ugc.aweme.ecommerce.ug.vsa.service.EcUgVSAService;
import com.ss.android.ugc.aweme.ecommercebase.monitor.PageNodeMonitorService;
import com.ss.android.ugc.aweme.ecommercelive.framework.serviceimpl.ECommerceLiveServiceImpl;
import com.ss.android.ugc.aweme.effectplatform.EffectStorageCleanServiceImpl;
import com.ss.android.ugc.aweme.effectplatforn.EffectPlatformFactory;
import com.ss.android.ugc.aweme.experiment.DoubleColorBallAnimationViewExperimentServiceImpl;
import com.ss.android.ugc.aweme.experiment.LogInterceptImpl;
import com.ss.android.ugc.aweme.experiment.PagingScrollSettingApiImpl;
import com.ss.android.ugc.aweme.experiment.ViewPagerSlideTransitionServiceImpl;
import com.ss.android.ugc.aweme.explore.service.ExploreFeedServiceImpl;
import com.ss.android.ugc.aweme.favorites.business.aweme.AwemeCollectionAgent;
import com.ss.android.ugc.aweme.favorites.business.aweme.AwemeCollectionCountAgent;
import com.ss.android.ugc.aweme.favorites.business.playlist.PlaylistCollectionStateAgent;
import com.ss.android.ugc.aweme.feed.api.FeedFragmentClassService;
import com.ss.android.ugc.aweme.feed.api.FeedModuleServiceImpl;
import com.ss.android.ugc.aweme.feed.assem.music.mute.OpenOnMuteImpl;
import com.ss.android.ugc.aweme.feed.consumption.impl.ConsumeLoginLoginServiceImpl;
import com.ss.android.ugc.aweme.feed.consumption.impl.RecommendConsumeServiceImpl;
import com.ss.android.ugc.aweme.feed.count.impl.FeedPlayNumServiceImpl;
import com.ss.android.ugc.aweme.feed.helper.FeedSharePlayInfoHelperProvider;
import com.ss.android.ugc.aweme.feed.landscape.EducatePhotoModeServiceImpl;
import com.ss.android.ugc.aweme.feed.landscape.LandscapeEducatorImpl;
import com.ss.android.ugc.aweme.feed.landscape.service.LandscapeFeedServiceImpl;
import com.ss.android.ugc.aweme.feed.motivatelogin.MotivateLoginPopupManager;
import com.ss.android.ugc.aweme.feed.service.FeedComponentServiceImpl;
import com.ss.android.ugc.aweme.feed.spi.CommonFeedServiceImpl;
import com.ss.android.ugc.aweme.feed.survey.spi.SurveyConfigServiceImpl;
import com.ss.android.ugc.aweme.feed.ui.FeedRecommendFragmentProvider;
import com.ss.android.ugc.aweme.feed.ui.font.FeedUniformFontServiceImpl;
import com.ss.android.ugc.aweme.feed.ui.progressguidance.NewUserProgressBarManager;
import com.ss.android.ugc.aweme.feed.utils.MallLogUtilsImpl;
import com.ss.android.ugc.aweme.feedback.runtime.behavior.RuntimeBehaviorServiceImpl;
import com.ss.android.ugc.aweme.feedback.screenshot.ScreenShotFeedbackService;
import com.ss.android.ugc.aweme.follow.service.FollowFeedServiceImpl;
import com.ss.android.ugc.aweme.follow.widget.FollowWidgetServiceImpl;
import com.ss.android.ugc.aweme.forward.statistics.ForwardStatisticsServiceImpl;
import com.ss.android.ugc.aweme.framework.services.DowngradeImplManager;
import com.ss.android.ugc.aweme.framework.services.ServiceManager;
import com.ss.android.ugc.aweme.framework.services.ServiceProvider;
import com.ss.android.ugc.aweme.friends.service.FriendsServiceImpl;
import com.ss.android.ugc.aweme.friends.service.SocialFriendsService;
import com.ss.android.ugc.aweme.friends.services.FollowService;
import com.ss.android.ugc.aweme.friendstab.service.FriendsFeedServiceImpl;
import com.ss.android.ugc.aweme.googlemap.AdGoogleMapService;
import com.ss.android.ugc.aweme.homepage.msadapt.MSAdaptionService;
import com.ss.android.ugc.aweme.homepage.spi.HomePageCommonServiceImpl;
import com.ss.android.ugc.aweme.homepage.ui.experiment.EasyNavigationExperimentServiceImpl;
import com.ss.android.ugc.aweme.hybridkit.HybridKitTaskImpl;
import com.ss.android.ugc.aweme.hybridkit.task.PiaConfigTask;
import com.ss.android.ugc.aweme.hybridkit.web.WebViewInjectServiceImpl;
import com.ss.android.ugc.aweme.im.sdk.common.controller.providedservices.IMService;
import com.ss.android.ugc.aweme.im.sdk.common.data.service.StoryIMService;
import com.ss.android.ugc.aweme.im.sdk.iescore.IMCoreDependProxyService;
import com.ss.android.ugc.aweme.im.sdk.notification.NotificationManagerServiceImpl;
import com.ss.android.ugc.aweme.im.sdk.u16.controller.IMUnder16ProxyImpl;
import com.ss.android.ugc.aweme.image.DraweeConfigOutService;
import com.ss.android.ugc.aweme.image.LightenConfigOutService;
import com.ss.android.ugc.aweme.impl.LauncherTaskApiImpl;
import com.ss.android.ugc.aweme.impl.OptimizerHelperServiceImpl;
import com.ss.android.ugc.aweme.impl.StrategyImpl;
import com.ss.android.ugc.aweme.inbox.InboxEasyNavigationPageNameServiceImpl;
import com.ss.android.ugc.aweme.inbox.service.InboxMobEventServiceImpl;
import com.ss.android.ugc.aweme.inbox.service.InboxServiceImpl;
import com.ss.android.ugc.aweme.inbox.skylight.plat.InboxSkylightService;
import com.ss.android.ugc.aweme.influencer.ECommerceLiveBridgeMethodServiceImpl;
import com.ss.android.ugc.aweme.influencer.ecommercelive.framework.serviceimpl.EcommerceInfluencerServiceImpl;
import com.ss.android.ugc.aweme.initializer.AVServiceProxyImpl;
import com.ss.android.ugc.aweme.innerpush.InnerPushServiceImpl;
import com.ss.android.ugc.aweme.internal.AVCommerceServiceImpl;
import com.ss.android.ugc.aweme.internal.AVTagServiceImpl;
import com.ss.android.ugc.aweme.internal.CrossLanguageUserExperiment;
import com.ss.android.ugc.aweme.internal.PrivacyServiceImpl;
import com.ss.android.ugc.aweme.internal.ShareServiceImpl;
import com.ss.android.ugc.aweme.internal.ShoutOutServiceImpl;
import com.ss.android.ugc.aweme.journey.feed.notinterested.NotInterestedTutorialService;
import com.ss.android.ugc.aweme.kids.commonfeed.report.ReportAwemeManager;
import com.ss.android.ugc.aweme.kids.component.music.KidsMusicEntrance;
import com.ss.android.ugc.aweme.kids.discovery.DiscoveryServiceImpl;
import com.ss.android.ugc.aweme.kids.homepage.compliance.KidsSettingsServiceImpl;
import com.ss.android.ugc.aweme.kids.intergration.account.KidsAccountServiceImpl;
import com.ss.android.ugc.aweme.kids.intergration.common.KidsCommonServiceImpl;
import com.ss.android.ugc.aweme.kids.intergration.common.KidsPolicyNoticeServiceImp;
import com.ss.android.ugc.aweme.kids.liked.FavoriteServiceImpl;
import com.ss.android.ugc.aweme.kids.profile.ProfileServiceImpl;
import com.ss.android.ugc.aweme.kids.recommendfeed.RecommendFeedServiceImpl;
import com.ss.android.ugc.aweme.kvstorage.SharedPreferencesProvider;
import com.ss.android.ugc.aweme.lancet.AppLogReaperServiceImpl;
import com.ss.android.ugc.aweme.landpage.AdLandPageServiceImpl;
import com.ss.android.ugc.aweme.landpage.survey.AdLandPageSurveyServiceImpl;
import com.ss.android.ugc.aweme.launcher.LauncherServiceImpl;
import com.ss.android.ugc.aweme.launcher.serviceimpl.account.AccountImpl;
import com.ss.android.ugc.aweme.launcher.serviceimpl.crashsdk.CrashSdkImpl;
import com.ss.android.ugc.aweme.launcher.serviceimpl.godzilla.GodzillaImpl;
import com.ss.android.ugc.aweme.legacy.AbTestManagerImpl;
import com.ss.android.ugc.aweme.legacy.ColdLaunchRequestCombinerImpl;
import com.ss.android.ugc.aweme.legacy.FollowTabBubbleGuideHelperImpl;
import com.ss.android.ugc.aweme.legacy.SearchResultStatisticsImpl;
import com.ss.android.ugc.aweme.legacy.select.SocialCardServiceImp;
import com.ss.android.ugc.aweme.legoImp.CrashSdkTaskImpl;
import com.ss.android.ugc.aweme.legoImp.LoginProxyImpl;
import com.ss.android.ugc.aweme.legoImp.NetWorkInjectImpl;
import com.ss.android.ugc.aweme.legoImp.NetworkConfigProvider;
import com.ss.android.ugc.aweme.legoImp.ProviderConfigOutImpl;
import com.ss.android.ugc.aweme.legoImp.SysOptTaskImpl;
import com.ss.android.ugc.aweme.legoImp.TaskManagerConfigImpl;
import com.ss.android.ugc.aweme.legoImp.WatcherImpl;
import com.ss.android.ugc.aweme.legoImp.task.PowerPermissionsTask;
import com.ss.android.ugc.aweme.legoImp.task.pumbaa.TTPSystemAPIInit;
import com.ss.android.ugc.aweme.legoImpl.AccountInitializerTaskImpl;
import com.ss.android.ugc.aweme.legoImpl.FrescoLegoTaskImpl;
import com.ss.android.ugc.aweme.legoImpl.task.ExitBackgroundImpl;
import com.ss.android.ugc.aweme.library.impl.LibraryReuseServiceImpl;
import com.ss.android.ugc.aweme.lingo.GeckoService;
import com.ss.android.ugc.aweme.live.LiveHostOuterService;
import com.ss.android.ugc.aweme.live.LiveOuterService;
import com.ss.android.ugc.aweme.live.LiveVersionCodeProvider;
import com.ss.android.ugc.aweme.live.SearchCardLiveService;
import com.ss.android.ugc.aweme.locale.LocalServiceImpl;
import com.ss.android.ugc.aweme.log.AdWebLogService;
import com.ss.android.ugc.aweme.login.LoginUtilsServiceImpl;
import com.ss.android.ugc.aweme.main.ActivityResourceOptApiImpl;
import com.ss.android.ugc.aweme.main.InterceptHomeBackPressServiceImpl;
import com.ss.android.ugc.aweme.main.MainPageExperimentServiceImpl;
import com.ss.android.ugc.aweme.main.MainPageServiceImpl;
import com.ss.android.ugc.aweme.main.dialogmanager.CleanDialogServiceImpl;
import com.ss.android.ugc.aweme.main.replace.ReplaceMusicDownloadService;
import com.ss.android.ugc.aweme.main.spi.HomePageServiceImpl;
import com.ss.android.ugc.aweme.main.uiApiImpl.HomePageUIFrameServiceImpl;
import com.ss.android.ugc.aweme.mention.service.CommentMentionServiceImpl;
import com.ss.android.ugc.aweme.mention.service.MentionDataServiceImpl;
import com.ss.android.ugc.aweme.mention.service.MentionViewServiceImpl;
import com.ss.android.ugc.aweme.miniapp.impl.MiniAppDependServiceImpl;
import com.ss.android.ugc.aweme.mix.services.MixFeedService;
import com.ss.android.ugc.aweme.ml.common.ClientAiInitServiceImpl;
import com.ss.android.ugc.aweme.ml.common.MLCommonServiceImpl;
import com.ss.android.ugc.aweme.ml.feature.MLDataCenterServiceImpl;
import com.ss.android.ugc.aweme.ml.feature.SmartDataTrackerServiceImpl;
import com.ss.android.ugc.aweme.ml.feature.pitaya.PitayaFeatureCenterServiceImpl;
import com.ss.android.ugc.aweme.ml.har.SmartHARServiceImpl;
import com.ss.android.ugc.aweme.ml.impl.SmartCDNRankServiceImpl;
import com.ss.android.ugc.aweme.ml.impl.SmartFeedAdUIServiceImpl;
import com.ss.android.ugc.aweme.ml.impl.SmartFeedLoadMoreServiceImpl;
import com.ss.android.ugc.aweme.ml.impl.SmartFeedPreloadServiceImpl;
import com.ss.android.ugc.aweme.ml.impl.SmartPreloadCommentV2ServiceImpl;
import com.ss.android.ugc.aweme.ml.impl.SmartPreloadProfileV2ServiceImpl;
import com.ss.android.ugc.aweme.ml.infra.SmartClassifyServiceImpl;
import com.ss.android.ugc.aweme.ml.infra.SmartCommonPreloadServiceImpl;
import com.ss.android.ugc.aweme.ml.infra.SmartDataCenterApiServiceImpl;
import com.ss.android.ugc.aweme.ml.infra.SmartMLSceneServiceImpl;
import com.ss.android.ugc.aweme.ml.infra.SmartPlaytimePredictServiceImpl;
import com.ss.android.ugc.aweme.ml.infra.SmartRegressCalculateServiceImpl;
import com.ss.android.ugc.aweme.ml.ohr.SmartOHRServiceImpl;
import com.ss.android.ugc.aweme.music.service.MusicDetailService;
import com.ss.android.ugc.aweme.music.service.ProfileMusicTabService;
import com.ss.android.ugc.aweme.mvtemplate.impl.MovieReuseServiceImpl;
import com.ss.android.ugc.aweme.net.NetworkApiImpl;
import com.ss.android.ugc.aweme.net.mutli.network.SpeedModeServiceImpl;
import com.ss.android.ugc.aweme.net.preload.PowerPreloadServiceImpl;
import com.ss.android.ugc.aweme.newfollow.statistics.FollowStatisticsServiceImpl;
import com.ss.android.ugc.aweme.newuser.NewUserImpl;
import com.ss.android.ugc.aweme.notice.DmNoticeProxyImpl;
import com.ss.android.ugc.aweme.notification.creator.service.NotificationFragmentServiceImpl;
import com.ss.android.ugc.aweme.notification.service.ActivityAdapterServiceImp;
import com.ss.android.ugc.aweme.notification.service.NoticeCountServiceImpl;
import com.ss.android.ugc.aweme.notification.service.NoticeCountTabBadgePresentServiceImpl;
import com.ss.android.ugc.aweme.notification.service.NoticeServiceImpl;
import com.ss.android.ugc.aweme.notification.service.OldNoticeCountServiceImpl;
import com.ss.android.ugc.aweme.notification.service.RedPointServiceImpl;
import com.ss.android.ugc.aweme.nows.external.CreativeNowServiceImpl;
import com.ss.android.ugc.aweme.nows.feed.caption.NowCaptionService;
import com.ss.android.ugc.aweme.nows.service.NowCommonFeedServiceImpl;
import com.ss.android.ugc.aweme.nows.service.NowDailyPushService;
import com.ss.android.ugc.aweme.nows.service.NowDistributionService;
import com.ss.android.ugc.aweme.nows.service.NowFeedPreLoadServiceImpl;
import com.ss.android.ugc.aweme.nows.service.NowLimitService;
import com.ss.android.ugc.aweme.nows.service.NowUserPublishService;
import com.ss.android.ugc.aweme.nows.service.NowWidgetService;
import com.ss.android.ugc.aweme.nows.service.NowsTabServiceImpl;
import com.ss.android.ugc.aweme.nows.service.ProfileNowsServiceImpl;
import com.ss.android.ugc.aweme.offlinemode.service.OfflineModeServiceImpl;
import com.ss.android.ugc.aweme.opt.BackendApiCallerOptService;
import com.ss.android.ugc.aweme.out.AVExternalServiceImpl;
import com.ss.android.ugc.aweme.out.AVServiceImpl;
import com.ss.android.ugc.aweme.paid.content.PaidContentAnchorAttachServiceImpl;
import com.ss.android.ugc.aweme.paidcontent.manageseries.notification.SeriesNotificationServiceImpl;
import com.ss.android.ugc.aweme.paidcontent.manageseries.notification.SeriesVideoUploadServiceImpl;
import com.ss.android.ugc.aweme.paidseries.broadcaster.before.service.PaidSeriesLiveApiService;
import com.ss.android.ugc.aweme.pipfeed.PipServiceImpl;
import com.ss.android.ugc.aweme.pipo.PipoService;
import com.ss.android.ugc.aweme.plugin.PluginService;
import com.ss.android.ugc.aweme.plugin.aab.AabPluginServiceImpl;
import com.ss.android.ugc.aweme.pns.agegate.PNSAgeGateServiceImpl;
import com.ss.android.ugc.aweme.pns.gatekeeper.GatekeeperManager;
import com.ss.android.ugc.aweme.pns.universalpopup.core.UniversalPopupManager;
import com.ss.android.ugc.aweme.pns.universalpopup.core.UniversalPopupManager2;
import com.ss.android.ugc.aweme.poi.map.service.GoogleMapServiceImpl;
import com.ss.android.ugc.aweme.poi.service.PoiServiceImpl;
import com.ss.android.ugc.aweme.portrait.impl.PortraitCenterInitServiceImpl;
import com.ss.android.ugc.aweme.portrait.impl.imclient.IMClientPortraitProducerService;
import com.ss.android.ugc.aweme.power.powersave.PowerModeHandlerProxy;
import com.ss.android.ugc.aweme.profile.mutual.ProfileShowMutualTabServiceImpl;
import com.ss.android.ugc.aweme.profile.popup.AvatarAndNicknamePopupController;
import com.ss.android.ugc.aweme.profile.ui.v2.UserProfilePreloadHelper;
import com.ss.android.ugc.aweme.profile.widgets.navbar.entrances.MafRedPointDismissHelper;
import com.ss.android.ugc.aweme.prop.impl.EffectHintSelectDialogServiceImpl;
import com.ss.android.ugc.aweme.prop.impl.PropReuseServiceImpl;
import com.ss.android.ugc.aweme.property.EditorProIconServiceImpl;
import com.ss.android.ugc.aweme.publish.service.PublishConfigExternalService;
import com.ss.android.ugc.aweme.qainvitation.service.QAInvitationService;
import com.ss.android.ugc.aweme.qrcode.QRCodeServiceImpl;
import com.ss.android.ugc.aweme.qrcode.view.BridgeScanHandlerImpl;
import com.ss.android.ugc.aweme.qrcode.view.QRCodePermissionActivityStarter;
import com.ss.android.ugc.aweme.question.impl.QuestionDetailServiceImpl;
import com.ss.android.ugc.aweme.recommend.users.RecommendUserServiceImpl;
import com.ss.android.ugc.aweme.record.ExteriorRecordPageFactoryImpl;
import com.ss.android.ugc.aweme.relation.auth.spi.AuthServiceImpl;
import com.ss.android.ugc.aweme.relation.avatar.FollowAvatarServiceImpl;
import com.ss.android.ugc.aweme.relation.label.AvatarUnionServiceImpl;
import com.ss.android.ugc.aweme.relation.label.RelationLabelTextViewServiceImpl;
import com.ss.android.ugc.aweme.relation.mutual.MutualRelationServiceImpl;
import com.ss.android.ugc.aweme.relation.recuser.RecUserServiceImpl;
import com.ss.android.ugc.aweme.relation.service.InviteFriendsService;
import com.ss.android.ugc.aweme.relation.storage.RelationStorageServiceImpl;
import com.ss.android.ugc.aweme.relation.usercard.spi.RelationUserCardInternalService;
import com.ss.android.ugc.aweme.request_combine.common.ServerPortraitCollections;
import com.ss.android.ugc.aweme.request_combine.request.SettingRequestExtraInfoImpl;
import com.ss.android.ugc.aweme.screenshot.ScreenShotService;
import com.ss.android.ugc.aweme.search.arch.v2.protocol.card.parser.SearchSingleCardTemplateServiceImpl;
import com.ss.android.ugc.aweme.search.arch.v2.services.SearchComponentServiceImpl;
import com.ss.android.ugc.aweme.search.common.communicate.SearchUserService;
import com.ss.android.ugc.aweme.search.ecommerce.ECommerceGeneralSearchWidgetServiceImpl;
import com.ss.android.ugc.aweme.search.ecommerce.EcomSearchServiceImpl;
import com.ss.android.ugc.aweme.search.ecommerce.SearchMiddleForEcService;
import com.ss.android.ugc.aweme.search.lynx.core.communicate.jsbridge.SearchBDXBridgeServiceImpl;
import com.ss.android.ugc.aweme.search.widget.core.communicate.SearchWidgetServiceImpl;
import com.ss.android.ugc.aweme.sec.SecApiImpl;
import com.ss.android.ugc.aweme.service.AttributionService;
import com.ss.android.ugc.aweme.service.ByteLingoServiceImpl;
import com.ss.android.ugc.aweme.service.CaptionKevaServiceImpl;
import com.ss.android.ugc.aweme.service.CaptionServiceImpl;
import com.ss.android.ugc.aweme.service.CaptionSheetServiceImpl;
import com.ss.android.ugc.aweme.service.CommonFeedApiService;
import com.ss.android.ugc.aweme.service.DanmakuServiceImpl;
import com.ss.android.ugc.aweme.service.EncourageLoginPopupManager;
import com.ss.android.ugc.aweme.service.FriendsTabDbService;
import com.ss.android.ugc.aweme.service.LingoCaptionServiceImpl;
import com.ss.android.ugc.aweme.service.MentionVideoService;
import com.ss.android.ugc.aweme.service.NearbyFeedServiceImpl;
import com.ss.android.ugc.aweme.service.PaidContentBannerServiceImpl;
import com.ss.android.ugc.aweme.service.PaidContentCollectionPlayProgressServiceImpl;
import com.ss.android.ugc.aweme.service.PaidContentPaymentServiceImpl;
import com.ss.android.ugc.aweme.service.PaidContentPreviewTagServiceImpl;
import com.ss.android.ugc.aweme.service.PaidContentSdpTrailerService;
import com.ss.android.ugc.aweme.service.PaidContentServiceImpl;
import com.ss.android.ugc.aweme.service.PhotoDownloadServiceImpl;
import com.ss.android.ugc.aweme.service.PhotoViewModelImpl;
import com.ss.android.ugc.aweme.service.PostModeServiceImpl;
import com.ss.android.ugc.aweme.service.SeriesPricingServiceImpl;
import com.ss.android.ugc.aweme.service.SocInteractionAvatarServiceImpl;
import com.ss.android.ugc.aweme.service.SocPubDistributeServiceImpl;
import com.ss.android.ugc.aweme.service.SocPubStatusRepoServiceImpl;
import com.ss.android.ugc.aweme.service.Social2TabRouteService;
import com.ss.android.ugc.aweme.service.Social2TabServiceImpl;
import com.ss.android.ugc.aweme.service.TextModeServiceImpl;
import com.ss.android.ugc.aweme.service.earlyfeedback.EarlyFeedbackService;
import com.ss.android.ugc.aweme.service.increaseloginnotify.IncreaseLoginNotifyService;
import com.ss.android.ugc.aweme.service.newusermode.NewUserModeService;
import com.ss.android.ugc.aweme.service.nickname.NicknameSignupExperiment;
import com.ss.android.ugc.aweme.service.perfetservice.ICLAPerfETServiceImpl;
import com.ss.android.ugc.aweme.service.proactive.ProactiveTriggersService;
import com.ss.android.ugc.aweme.service.protection.TooltipApplicabilityService;
import com.ss.android.ugc.aweme.service.unlogindigg.UnLoginDiggService;
import com.ss.android.ugc.aweme.services.AccountHelperService;
import com.ss.android.ugc.aweme.services.ApiNetworkServiceForAccount;
import com.ss.android.ugc.aweme.services.ArticleModeServiceImpl;
import com.ss.android.ugc.aweme.services.BaseUserService;
import com.ss.android.ugc.aweme.services.BindService;
import com.ss.android.ugc.aweme.services.BusinessComponentServiceImpl;
import com.ss.android.ugc.aweme.services.BusinessGoodsServiceImpl;
import com.ss.android.ugc.aweme.services.BusinessMainServiceImpl;
import com.ss.android.ugc.aweme.services.BusinessModuleServiceImpl;
import com.ss.android.ugc.aweme.services.ClearCacheService;
import com.ss.android.ugc.aweme.services.CloudTokenLoginService;
import com.ss.android.ugc.aweme.services.CommerceXBridgetServiceImpl;
import com.ss.android.ugc.aweme.services.ExitBackgroundActivityImpl;
import com.ss.android.ugc.aweme.services.IAVMixFeedServiceImpl;
import com.ss.android.ugc.aweme.services.IAVSettingServiceImpl;
import com.ss.android.ugc.aweme.services.MainServiceForJsb;
import com.ss.android.ugc.aweme.services.MainServiceHelperImpl;
import com.ss.android.ugc.aweme.services.MainXBridgeServiceImpl;
import com.ss.android.ugc.aweme.services.MandatoryLoginService;
import com.ss.android.ugc.aweme.services.MusicService;
import com.ss.android.ugc.aweme.services.NetworkContextService;
import com.ss.android.ugc.aweme.services.NetworkLevelService;
import com.ss.android.ugc.aweme.services.NetworkQualityServiceImpl;
import com.ss.android.ugc.aweme.services.NetworkStandardApiImpl;
import com.ss.android.ugc.aweme.services.NetworkStandardUIServiceImpl;
import com.ss.android.ugc.aweme.services.NetworkStateServiceImpl;
import com.ss.android.ugc.aweme.services.PerformanceMainServiceImpl;
import com.ss.android.ugc.aweme.services.PowerContextImpl;
import com.ss.android.ugc.aweme.services.RetrofitService;
import com.ss.android.ugc.aweme.services.SaveInfoDialogService;
import com.ss.android.ugc.aweme.services.SmartLockService;
import com.ss.android.ugc.aweme.services.ToolsBusinessServiceImpl;
import com.ss.android.ugc.aweme.services.ToolsCPUDataServiceImpl;
import com.ss.android.ugc.aweme.services.TrafficStatisticsServiceImpl;
import com.ss.android.ugc.aweme.services.UserInfoUpdateAdapterService;
import com.ss.android.ugc.aweme.services.WebViewTweakerService;
import com.ss.android.ugc.aweme.services.editeffect.EffectAnchorServiceImpl;
import com.ss.android.ugc.aweme.services.function.FunctionSupportServiceImpl;
import com.ss.android.ugc.aweme.services.video.OneMinuteH5PreloadServiceImpl;
import com.ss.android.ugc.aweme.servicimpl.AutoCutServiceImpl;
import com.ss.android.ugc.aweme.servicimpl.CreativePageService;
import com.ss.android.ugc.aweme.servicimpl.EditRootSceneFactoryDelegate;
import com.ss.android.ugc.aweme.servicimpl.EmojiServiceImplDiff;
import com.ss.android.ugc.aweme.servicimpl.PageFactoryDelegate;
import com.ss.android.ugc.aweme.servicimpl.SplitVideoServiceImpl;
import com.ss.android.ugc.aweme.servicimpl.TTEPPageFactoryDelegate;
import com.ss.android.ugc.aweme.setting.GetPushSettingCallback;
import com.ss.android.ugc.aweme.setting.PromoteEntryCheckServiceImpl;
import com.ss.android.ugc.aweme.setting.UpdateSettingServiceImpl;
import com.ss.android.ugc.aweme.setting.page.datasave.SpeedModeSettingImpl;
import com.ss.android.ugc.aweme.setting.serverpush.service.PushSettingServiceImpl;
import com.ss.android.ugc.aweme.setting.services.AppUpdateService;
import com.ss.android.ugc.aweme.setting.services.I18nService;
import com.ss.android.ugc.aweme.setting.services.SettingDependServiceImpl;
import com.ss.android.ugc.aweme.setting.services.SettingServiceImpl;
import com.ss.android.ugc.aweme.setting.services.StorageServiceImpl;
import com.ss.android.ugc.aweme.setting.services.VideoGiftService;
import com.ss.android.ugc.aweme.settingsrequest.AbTestManagerApiImpl;
import com.ss.android.ugc.aweme.settingsrequest.ConfigCenterCenterBridgeImpl;
import com.ss.android.ugc.aweme.settingsrequest.SettingManagerServiceImpl;
import com.ss.android.ugc.aweme.settingsrequest.SettingsLegacyImpl;
import com.ss.android.ugc.aweme.settingsrequest.SettingsRequestApiImpl;
import com.ss.android.ugc.aweme.settingsrequest.SettingsRequestServiceImpl;
import com.ss.android.ugc.aweme.share.ShareDependServiceImpl;
import com.ss.android.ugc.aweme.share.ShareExtServiceImpl;
import com.ss.android.ugc.aweme.share.ShareFlavorServiceImpl;
import com.ss.android.ugc.aweme.share.ShareH5ServiceImpl;
import com.ss.android.ugc.aweme.share.ShareRespSendServiceImpl;
import com.ss.android.ugc.aweme.share.gif.GifShareService;
import com.ss.android.ugc.aweme.share.viewmodel.FeedStateVMServiceImpl;
import com.ss.android.ugc.aweme.shortcut.TiktokShortcutManager;
import com.ss.android.ugc.aweme.shortvideo.AllowVideoThresholdUtils;
import com.ss.android.ugc.aweme.shortvideo.BusinessPublishImpl;
import com.ss.android.ugc.aweme.shortvideo.DuetDownloadService;
import com.ss.android.ugc.aweme.shortvideo.MediaChosenResultProcessFactory;
import com.ss.android.ugc.aweme.shortvideo.PublishServiceFactoryImpl;
import com.ss.android.ugc.aweme.shortvideo.edit.videolength.VideoLengthChecker;
import com.ss.android.ugc.aweme.shortvideo.experiment.PublishPageImpl;
import com.ss.android.ugc.aweme.shortvideo.jsb.CreativeToolXBridgeService;
import com.ss.android.ugc.aweme.shortvideo.library.service.LibraryCameraServiceImpl;
import com.ss.android.ugc.aweme.shortvideo.mvtemplate.choosemedia.AlbumServiceImpl;
import com.ss.android.ugc.aweme.shortvideo.sticker.comment.CommentFavoriteServiceImpl;
import com.ss.android.ugc.aweme.shortvideo.sticker.question.QuestionFavoriteServiceImpl;
import com.ss.android.ugc.aweme.shortvideo.util.StitchDownloadServiceImpl;
import com.ss.android.ugc.aweme.spark.AdSparkUtils;
import com.ss.android.ugc.aweme.specact.SpecActServiceImpl;
import com.ss.android.ugc.aweme.stemfeed.service.StemFeedServiceImpl;
import com.ss.android.ugc.aweme.sticker.AddYoursModelCheckService;
import com.ss.android.ugc.aweme.sticker.AddYoursStickerFactoryService;
import com.ss.android.ugc.aweme.sticker.AddYoursStickerRecordServiceImpl;
import com.ss.android.ugc.aweme.sticker.StickerContainerService;
import com.ss.android.ugc.aweme.sticker.StickerServiceImpl;
import com.ss.android.ugc.aweme.storage.MusicStorageCleanServiceImpl;
import com.ss.android.ugc.aweme.story.publish.SocialPublishBridgeServiceImpl;
import com.ss.android.ugc.aweme.story.service.StoryDistributionService;
import com.ss.android.ugc.aweme.story.service.StoryServiceImpl;
import com.ss.android.ugc.aweme.sync.ByteSyncApiImpl;
import com.ss.android.ugc.aweme.sync.ByteSyncInitProviderImpl;
import com.ss.android.ugc.aweme.tablet.TabletServiceProxy;
import com.ss.android.ugc.aweme.tag.service.TagServiceImpl;
import com.ss.android.ugc.aweme.tools.live.sticker.StickerViewServiceImpl;
import com.ss.android.ugc.aweme.topic.TopicAnchorFactory;
import com.ss.android.ugc.aweme.topic.TopicCommonService;
import com.ss.android.ugc.aweme.topic.book.BookTokServiceImpl;
import com.ss.android.ugc.aweme.topic.movie.MovieTokServiceImpl;
import com.ss.android.ugc.aweme.topic.trendingtopic.VideoTrendingTopicServiceImpl;
import com.ss.android.ugc.aweme.topicfeed.service.TopicFeedServiceImpl;
import com.ss.android.ugc.aweme.trace.AwemeTraceLogAdapter;
import com.ss.android.ugc.aweme.trace.PageTraceApiImpl;
import com.ss.android.ugc.aweme.trace.TraceConfigApiImpl;
import com.ss.android.ugc.aweme.trace.TraceLogWrapApiImpl;
import com.ss.android.ugc.aweme.trace.UnsampledTraceLoggerImpl;
import com.ss.android.ugc.aweme.traffic.TrafficMonitorService;
import com.ss.android.ugc.aweme.translation.service.TranslationKevaServiceImpl;
import com.ss.android.ugc.aweme.translation.service.TranslationLangKevaServiceImpl;
import com.ss.android.ugc.aweme.translation.service.TranslationServiceImpl;
import com.ss.android.ugc.aweme.trending.service.TrendingDetailServiceImpl;
import com.ss.android.ugc.aweme.ug.UgCommonServiceImpl;
import com.ss.android.ugc.aweme.ug.brand.BrandServiceImpl;
import com.ss.android.ugc.aweme.upvote.service.UpvoteServiceImpl;
import com.ss.android.ugc.aweme.userservice.UserService;
import com.ss.android.ugc.aweme.utils.AppWidgetServiceImpl;
import com.ss.android.ugc.aweme.utils.EnterProfileServiceImpl;
import com.ss.android.ugc.aweme.utils.GsonHolder;
import com.ss.android.ugc.aweme.utils.InterceptorHolder;
import com.ss.android.ugc.aweme.utils.LanguageService;
import com.ss.android.ugc.aweme.utils.NotificationClickHelperImpl;
import com.ss.android.ugc.aweme.utils.SchemaPageHelperImpl;
import com.ss.android.ugc.aweme.utils.WSHelperImpl;
import com.ss.android.ugc.aweme.utils.gecko.GeckoLocalServiceImpl;
import com.ss.android.ugc.aweme.watch.history.di.WatchHistoryValueService;
import com.ss.android.ugc.aweme.watermark.WaterMarkServiceImpl;
import com.ss.android.ugc.aweme.wavepublish.dm.service.DMPublishServiceImpl;
import com.ss.android.ugc.aweme.web.CrossPlatformJsbProxy;
import com.ss.android.ugc.aweme.web.GeckoXClientManager;
import com.ss.android.ugc.aweme.web.business.preload.AdWebViewInterceptorService;
import com.ss.android.ugc.aweme.web.business.special.AdWebSpecialService;
import com.ss.android.ugc.aweme.web.creation.WebCreationPromoteServiceImpl;
import com.ss.android.ugc.aweme.web.intercept.forest.AdWebViewForestServiceImpl;
import com.ss.android.ugc.aweme.web.permission.AdWebPermissionService;
import com.ss.android.ugc.aweme.web.realtimeres.AdLandPageRealtimeResourceModule;
import com.ss.android.ugc.aweme.web.utils.AdWebUtils;
import com.ss.android.ugc.aweme.websocket.bridge.WsManager;
import com.ss.android.ugc.aweme.websocket.bridge.WsMonitor;
import com.ss.android.ugc.aweme.zerorating.ZeroRatingMainServiceImpl;
import com.ss.android.ugc.awemepushlib.manager.PushPermissionPopupManager;
import com.ss.android.ugc.bytebench.EditorStickerDowngradeServiceImpl;
import com.ss.android.ugc.feed.platform.panel.autoscroll.FypAutoScrollServiceImpl;
import com.ss.android.ugc.feed.platform.panel.earphone.EarphonePlayerControl;
import com.ss.android.ugc.feed.platform.service.FindTargetScopeFailFasterServiceImpl;
import com.ss.android.ugc.gamora.editor.EditVideoInfoServiceImpl;
import com.ss.android.ugc.gamora.editor.audio.copyrightdetect.AutoSoundCheckService;
import com.ss.android.ugc.gamora.editor.audioservice.service.audioglitch.AudioGlitchService;
import com.ss.android.ugc.gamora.editor.audioservice.service.voicedetection.VoiceDetectorService;
import com.ss.android.ugc.gamora.editor.audioservice.service.watermark.AudioWatermarkServiceImpl;
import com.ss.android.ugc.gamora.editor.lightening.canvas.forward.DefaultStoryForwardServiceImpl;
import com.ss.android.ugc.gamora.editor.music.stream.MusicStreamServiceImpl;
import com.ss.android.ugc.gamora.editor.sticker.donation.DonationUtils;
import com.ss.android.ugc.gamora.editor.sticker.nature.NatureGuideFragmentServiceImpl;
import com.ss.android.ugc.gamora.editor.toolbar.ReplaceMusicServiceImpl;
import com.ss.android.ugc.gamora.editorpro.crop.VideoCropService;
import com.ss.android.ugc.gamora.recorder.vopclone.VopCameraClientService;
import com.ss.android.ugc.gamora.recorder.vopclone.VopPermissionService;
import com.ss.android.ugc.localnotify.CommonLocalNotifyService;
import com.ss.android.ugc.localnotify.NonLoginNotifyService;
import com.ss.android.ugc.musicprovider.MusicProviderConfigProxy;
import com.ss.android.ugc.now.interaction.service.InteractionService;
import com.ss.android.ugc.sdk.ShareSdkServiceImpl;
import com.ss.android.ugc.tiktok.addyours.service.AddYoursServiceImpl;
import com.ss.android.ugc.tiktok.addyours.service.InviteFriendsServiceImpl;
import com.ss.android.ugc.tiktok.addyours.service.PerformanceServiceImpl;
import com.ss.android.ugc.tiktok.deeplink.impl.DeeplinkPrefetchImpl;
import com.ss.android.ugc.tiktok.location.serviceimpl.LocationServiceImpl;
import com.ss.android.ugc.tiktok.location_api.service.LocationPluginServiceImpl;
import com.ss.android.ugc.tiktok.seclink.impl.SecLinkServiceImpl;
import com.ss.android.ugc.tiktok.security.ClientSecurityServiceImpl;
import com.ss.android.ugc.trill.openauthorize.AuthorizeCommonService;
import com.ss.android.ugc.trill.setting.ICLALanguageServiceImpl;
import dmt.av.services.VEEncodingImpl;
import java.util.concurrent.ConcurrentHashMap;

/* renamed from: X.Mr6, reason: case insensitive filesystem */
/* loaded from: classes11.dex */
public final class C58096Mr6 {
    public static volatile DownloadServiceImpl A;
    public static volatile FeedModuleServiceImpl A0;
    public static volatile AVTagServiceImpl A1;
    public static volatile ActivityResourceOptApiImpl A2;
    public static volatile NowDistributionService A3;
    public static volatile ServerPortraitCollections A4;
    public static volatile BaseUserService A5;
    public static volatile SettingServiceImpl A6;
    public static volatile MovieTokServiceImpl A7;
    public static volatile MusicStreamServiceImpl A8;
    public static volatile DuetDetailServiceImpl B;
    public static volatile OpenOnMuteImpl B0;
    public static volatile CrossLanguageUserExperiment B1;
    public static volatile InterceptHomeBackPressServiceImpl B2;
    public static volatile NowFeedPreLoadServiceImpl B3;
    public static volatile SettingRequestExtraInfoImpl B4;
    public static volatile BindService B5;
    public static volatile StorageServiceImpl B6;
    public static volatile VideoTrendingTopicServiceImpl B7;
    public static volatile DonationUtils B8;
    public static volatile DuetDiscoverServiceImpl C;
    public static volatile ConsumeLoginLoginServiceImpl C0;
    public static volatile PrivacyServiceImpl C1;
    public static volatile MainPageExperimentServiceImpl C2;
    public static volatile NowLimitService C3;
    public static volatile ScreenShotService C4;
    public static volatile BusinessComponentServiceImpl C5;
    public static volatile VideoGiftService C6;
    public static volatile TopicFeedServiceImpl C7;
    public static volatile NatureGuideFragmentServiceImpl C8;
    public static volatile ECommerceHybridServiceImpl D;
    public static volatile RecommendConsumeServiceImpl D0;
    public static volatile ShareServiceImpl D1;
    public static volatile MainPageServiceImpl D2;
    public static volatile NowUserPublishService D3;
    public static volatile SearchSingleCardTemplateServiceImpl D4;
    public static volatile BusinessGoodsServiceImpl D5;
    public static volatile AbTestManagerApiImpl D6;
    public static volatile AwemeTraceLogAdapter D7;
    public static volatile ReplaceMusicServiceImpl D8;
    public static volatile ECommerceThirdPartyHybridServiceImpl E;
    public static volatile FeedPlayNumServiceImpl E0;
    public static volatile ShoutOutServiceImpl E1;
    public static volatile CleanDialogServiceImpl E2;
    public static volatile NowWidgetService E3;
    public static volatile SearchComponentServiceImpl E4;
    public static volatile BusinessMainServiceImpl E5;
    public static volatile ConfigCenterCenterBridgeImpl E6;
    public static volatile PageTraceApiImpl E7;
    public static volatile VideoCropService E8;
    public static volatile ECommerceXBridgeService F;
    public static volatile FeedSharePlayInfoHelperProvider F0;
    public static volatile NotInterestedTutorialService F1;
    public static volatile ReplaceMusicDownloadService F2;
    public static volatile NowsTabServiceImpl F3;
    public static volatile SearchUserService F4;
    public static volatile BusinessModuleServiceImpl F5;
    public static volatile SettingManagerServiceImpl F6;
    public static volatile TraceConfigApiImpl F7;
    public static volatile VopCameraClientService F8;
    public static volatile ECommerceArchServiceImpl G;
    public static volatile EducatePhotoModeServiceImpl G0;
    public static volatile ReportAwemeManager G1;
    public static volatile HomePageServiceImpl G2;
    public static volatile ProfileNowsServiceImpl G3;
    public static volatile Object G4;
    public static volatile ClearCacheService G5;
    public static volatile SettingsLegacyImpl G6;
    public static volatile TraceLogWrapApiImpl G7;
    public static volatile VopPermissionService G8;
    public static volatile EcomImageMonitorImpl H;
    public static volatile LandscapeEducatorImpl H0;
    public static volatile KidsMusicEntrance H1;
    public static volatile HomePageUIFrameServiceImpl H2;
    public static volatile OfflineModeServiceImpl H3;
    public static volatile ECommerceGeneralSearchWidgetServiceImpl H4;
    public static volatile CloudTokenLoginService H5;
    public static volatile SettingsRequestApiImpl H6;
    public static volatile UnsampledTraceLoggerImpl H7;
    public static volatile CommonLocalNotifyService H8;
    public static volatile EcommerceLiveDegradeExp I;
    public static volatile LandscapeFeedServiceImpl I0;
    public static volatile DiscoveryServiceImpl I1;
    public static volatile CommentMentionServiceImpl I2;
    public static volatile BackendApiCallerOptService I3;
    public static volatile EcomSearchServiceImpl I4;
    public static volatile CommerceXBridgetServiceImpl I5;
    public static volatile SettingsRequestServiceImpl I6;
    public static volatile TrafficMonitorService I7;
    public static volatile NonLoginNotifyService I8;

    /* renamed from: J, reason: collision with root package name */
    public static volatile EcommerceMonitorService f81J;
    public static volatile MotivateLoginPopupManager J0;
    public static volatile KidsSettingsServiceImpl J1;
    public static volatile MentionDataServiceImpl J2;
    public static volatile AVExternalServiceImpl J3;
    public static volatile SearchMiddleForEcService J4;
    public static volatile ExitBackgroundActivityImpl J5;
    public static volatile ShareDependServiceImpl J6;
    public static volatile TranslationKevaServiceImpl J7;
    public static volatile MusicProviderConfigProxy J8;
    public static volatile CommerceHybridBottomSheetDialogFragmentBehaviorImpl K;
    public static volatile FeedComponentServiceImpl K0;
    public static volatile KidsAccountServiceImpl K1;
    public static volatile MentionViewServiceImpl K2;
    public static volatile AVServiceImpl K3;
    public static volatile SearchBDXBridgeServiceImpl K4;
    public static volatile IAVMixFeedServiceImpl K5;
    public static volatile ShareExtServiceImpl K6;
    public static volatile TranslationLangKevaServiceImpl K7;
    public static volatile InteractionService K8;
    public static volatile PdpCardBridgeServiceImpl L;
    public static volatile CommonFeedServiceImpl L0;
    public static volatile KidsCommonServiceImpl L1;
    public static volatile MiniAppDependServiceImpl L2;
    public static volatile PaidContentAnchorAttachServiceImpl L3;
    public static volatile SearchWidgetServiceImpl L4;
    public static volatile IAVSettingServiceImpl L5;
    public static volatile ShareFlavorServiceImpl L6;
    public static volatile TranslationServiceImpl L7;
    public static volatile ShareSdkServiceImpl L8;
    public static volatile StorageCleanServiceImpl LIZ;
    public static volatile UpdateRegisterKeyImpl LIZIZ;
    public static volatile LobbyNonceGenerator LIZJ;
    public static volatile Object LIZLLL;
    public static volatile Object LJ;
    public static volatile Object LJFF;
    public static volatile Object LJI;
    public static volatile Object LJII;
    public static volatile Object LJIIIIZZ;
    public static volatile Object LJIIIZ;
    public static volatile Object LJIIJ;
    public static volatile Object LJIIJJI;
    public static volatile Object LJIIL;
    public static volatile Object LJIILIIL;
    public static volatile Object LJIILJJIL;
    public static volatile IMCoreProxyService LJIILL;
    public static volatile ComplianceServiceImpl LJIILLIIL;
    public static volatile ConsistentContentAndAdChoiceServiceImpl LJIIZILJ;
    public static volatile IntelligenceModuleImpl LJIJ;
    public static volatile AdReRankServiceManager LJIJI;
    public static volatile AdSceneServiceImpl LJIJJ;
    public static volatile GlobalSearchAdModuleImpl LJIJJLI;
    public static volatile SplashAdServiceImpl LJIL;
    public static volatile SplashSettingServiceImpl LJJ;
    public static volatile RealTimeSplashManagerImpl LJJI;
    public static volatile RealTimeSplashNPManagerImpl LJJIFFI;
    public static volatile RetrofitFactory LJJII;
    public static volatile BTMTrackerServiceImpl LJJIII;
    public static volatile UserAccountImpl LJJIIJ;
    public static volatile TTKVStorageSettings LJJIIJZLJL;
    public static volatile ImagePipelineConfigFactory LJJIIZ;
    public static volatile PumbaaServiceImpl LJJIIZI;
    public static volatile BPEAServiceImp LJJIJ;
    public static volatile HybridServiceImpl LJJIJIIJI;
    public static volatile HybridMonitorServiceImpl LJJIJIIJIL;
    public static volatile RaspServiceImpl LJJIJIL;
    public static volatile MonitorServiceImpl LJJIJL;
    public static volatile NetworkServiceImpl LJJIJLIJ;
    public static volatile PolicyDecisionImp LJJIL;
    public static volatile RuleEngineServiceImpl LJJIZ;
    public static volatile MainPageFragmentImpl LJJJ;
    public static volatile LingoCaptionImpl LJJJI;
    public static volatile LingoCaptionInnerImpl LJJJIL;
    public static volatile ElLogDefault LJJJJ;
    public static volatile LingoLynxImpl LJJJJI;
    public static volatile RomaServiceImpl LJJJJIZL;
    public static volatile ElTrackerServiceImpl LJJJJJ;
    public static volatile ImageHeaderConfigImpl LJJJJJL;
    public static volatile LauncherExperimentsImpl LJJJJL;
    public static volatile ABLegoTaskImpl LJJJJLI;
    public static volatile WebAdUserAgentServiceImpl LJJJJLL;
    public static volatile AwemeAppBuildConfig LJJJJZ;
    public static volatile AccountService LJJJJZI;
    public static volatile ActivityRouterServiceImpl LJJJLIIL;
    public static volatile AnoleServiceImpl LJJJLL;
    public static volatile AutobackupService LJJJLZIJ;
    public static volatile BuildConfigAllServiceImpl LJJJZ;
    public static volatile CQrcodeService LJJL;
    public static volatile CrossPlatformLegacyServiceImpl LJJLI;
    public static volatile DetailFeedServiceImpl LJJLIIIIJ;
    public static volatile DubbingServiceImpl LJJLIIIJ;
    public static volatile InboxRepostFeedServiceImpl LJJLIIIJILLIZJL;
    public static volatile NewUserJourneyService LJJLIIIJJI;
    public static volatile NujPerformanceService LJJLIIIJJIZ;
    public static volatile PerfMonitorServiceImpl LJJLIIIJL;
    public static volatile PreloadApiServiceImpl LJJLIIIJLJLI;
    public static volatile PrivacyDisclaimerUtilService LJJLIIIJLLLLLLLZ;
    public static volatile ProfileNaviServiceImpl LJJLIIJ;
    public static volatile SettingsMainApiImpl LJJLIL;
    public static volatile UgAllServiceImpl LJJLJ;
    public static volatile AccountInitServiceImpl LJJLJLI;
    public static volatile PreLoginHandleService LJJLL;
    public static volatile RegistrationAgeGateServiceImpl LJJZ;
    public static volatile AccountBindingsService LJJZZI;
    public static volatile AccountFeatureFlagService LJJZZIII;
    public static volatile MultiAccountService LJL;
    public static volatile GuestModeServiceImpl LJLI;
    public static volatile GoogleOneTapLogger LJLIIIL;
    public static volatile GoogleOneTapService LJLIIL;
    public static volatile PasskeyService LJLIL;
    public static volatile PrevLoginPlatformService LJLILLLLZI;
    public static volatile AccountNonceUtilImpl LJLJI;
    public static volatile PrivateAccountTipsViewDelegate LJLJJI;
    public static volatile AccountMainServiceImpl LJLJJL;
    public static volatile KnownWeakPasswordService LJLJJLL;
    public static volatile PasskeyPopUpHelper LJLJL;
    public static volatile SyncNicknameAndUsernamePopUpHelper LJLJLJ;
    public static volatile ProfileBadgeServiceImpl LJLJLLL;
    public static volatile AccountShowConfirmPromptServiceImpl LJLL;
    public static volatile AccountBDXBridgeService LJLLI;
    public static volatile FeedAdServiceImpl LJLLILLLL;
    public static volatile AdCommentService LJLLJ;
    public static volatile CommercializeFeedServiceImpl LJLLL;
    public static volatile CommerceAdExperienceServiceImpl LJLLLL;
    public static volatile AdFeInteractionImpl LJLLLLLL;
    public static volatile CommerceIBEService LJLZ;
    public static volatile AdPhotoModeServiceImpl LJZ;
    public static volatile IAdSlidePreloadImpl LJZI;
    public static volatile ShakeEggService LJZL;
    public static volatile FeedBackDialogManagerService LL;
    public static volatile AdLandPagePreloadServiceImpl LLD;
    public static volatile GeckoPreloadServiceImpl LLF;
    public static volatile PreRenderWebViewManager LLFF;
    public static volatile CommerceLandPageModuleImpl LLFFF;
    public static volatile SAAService LLFII;
    public static volatile AIGCAvatarServiceImpl LLFZ;
    public static volatile ToolsAlbumServiceImpl LLI;
    public static volatile AnchorListServiceImpl LLIFFJFJJ;
    public static volatile AnchorOperationServiceImpl LLII;
    public static volatile AnchorStateServiceImpl LLIIII;
    public static volatile CustomAnchorViewServicImpl LLIIIILZ;
    public static volatile EcommerceAnchorService LLIIIJ;
    public static volatile AnchorBusinessApiImpl LLIIIL;
    public static volatile FeedServiceImpl LLIIIZ;
    public static volatile LegoBusinessServiceImpl LLIIJI;
    public static volatile AdComponentServiceImpl LLIIJLIL;
    public static volatile AwemeApplicationServiceImpl LLIIL;
    public static volatile InitAllServiceImpl LLIILII;
    public static volatile AccountInitializer LLIILZL;
    public static volatile SystemServiceApiImpl LLIIZ;
    public static volatile TaskServiceImpl LLIL;
    public static volatile DownloadService LLILII;
    public static volatile HybridABInfoService LLILIL;
    public static volatile LauncherService LLILL;
    public static volatile NewUserMainModuleService LLILLIZIL;
    public static volatile RegionService LLILLJJLI;
    public static volatile WebviewService LLILLL;
    public static volatile AppsflyerImpl LLILZ;
    public static volatile FullEpisodeRouterServiceImpl LLILZIL;
    public static volatile AudioSDKABLegoLauncherTaskImpl LLILZLL;
    public static volatile VopBDXBridgeServiceImpl LLIZ;
    public static volatile VopCloneServiceImpl LLIZLLLIL;
    public static volatile AdAutofillService LLJ;
    public static volatile AvatarImageServiceImpl LLJI;
    public static volatile AvatarInternalServiceImpl LLJIJIL;
    public static volatile AwemeService LLJILJIL;
    public static volatile RequestIdService LLJILJILJ;
    public static volatile FeedSkylightServiceImpl LLJILLL;
    public static volatile FeedSkylightServiceProviderImpl LLJJ;
    public static volatile BTCHConfigurationImpl LLJJI;
    public static volatile BenchmarkCollectionInitService LLJJIII;
    public static volatile BenchmarkInitService LLJJIJI;
    public static volatile BenchmarkServiceImpl LLJJIJIIJIL;
    public static volatile Object LLJJIJIL;
    public static volatile Object LLJJJ;
    public static volatile BemobiGiftServiceImpl LLJJJIL;
    public static volatile BulletHostProxy LLJJJJ;
    public static volatile BulletService LLJJJJJIL;
    public static volatile CastingServiceImpl LLJJJJLIIL;
    public static volatile OpenCCTUtils LLJJL;
    public static volatile ChallengeDetailLegacyServiceImpl LLJJLIIIJLLLLLLLZ;
    public static volatile ChallengeDetailServiceImpl LLJL;
    public static volatile ChallengeDetailProvider LLJLIL;
    public static volatile ChallengeServiceImpl LLJLILLLLZIIL;
    public static volatile ChildHookServiceImpl LLJLL;
    public static volatile CommentStickerRecordServiceImpl LLJLLIL;
    public static volatile CommentServiceImpl LLJLLL;
    public static volatile KeyboardServiceImpl LLJZ;
    public static volatile NoticeCommentHelperServiceImpl LLJZIJLIL;
    public static volatile CommerceService LLL;
    public static volatile CommerceToolsChallengeService LLLF;
    public static volatile CommerceToolsService LLLFF;
    public static volatile EventCenter LLLFFI;
    public static volatile CommerceToolsPublishService LLLFZ;
    public static volatile CommerceToolsMissionService LLLI;
    public static volatile CommerceToolsMusicService LLLII;
    public static volatile PromoteRepalceMusicServiceImpl LLLIIII;
    public static volatile CommerceToolsStickerServiceImpl LLLIIIIL;
    public static volatile CommerceToolsTcmServiceImpl LLLIIIL;
    public static volatile AwemeContextServiceImpl LLLIIL;
    public static volatile LegacyCommercializeServiceImpl LLLIILIL;
    public static volatile GetLeadsAnchorService LLLIL;
    public static volatile AdAssemUtils LLLILZ;
    public static volatile BaAutoMessageServiceImpl LLLILZJ;
    public static volatile BAAnchorServiceImpl LLLILZLLLI;
    public static volatile BABusinessSuitePageServiceImp LLLIZZ;
    public static volatile BAProfilePageServiceImpl LLLJ;
    public static volatile BASwitchToPAorBAServiceImpl LLLJIL;
    public static volatile CommerceChallengeServiceImpl LLLJL;
    public static volatile AdCommentDependImpl LLLL;
    public static volatile AdRouterHandlerDependImpl LLLLII;
    public static volatile AdTaskDependImpl LLLLIIIILLL;
    public static volatile AdTrackDependImpl LLLLIIL;
    public static volatile ShoppingAdsServiceImpl LLLLIILL;
    public static volatile EngagementTraceImpl LLLLIILLL;
    public static volatile AdAssemServiceImpl LLLLIL;
    public static volatile AdAssemblerServiceImpl LLLLILI;
    public static volatile AdTagServiceImpl LLLLJ;
    public static volatile CandidateRequestImpl LLLLJI;
    public static volatile MainPageSlideImpl LLLLL;
    public static volatile AdHybridContainerManager LLLLLIL;
    public static volatile AdWebJumpInterceptor LLLLLILLIL;
    public static volatile CommerceServiceImpl LLLLLJIL;
    public static volatile PromoteUtilImpl LLLLLJLJLL;
    public static volatile CommercializeLiveServiceImpl LLLLLL;
    public static volatile AdLogServiceImpl LLLLLLIL;
    public static volatile FeedRawAdLogUtilsImpl LLLLLLJ;
    public static volatile LogHelperImpl LLLLLLL;
    public static volatile MeasurementServiceImpl LLLLLLLLL;
    public static volatile MRCManager LLLLLLLLLL;
    public static volatile CommerceMediaServiceImpl LLLLLLLZIL;
    public static volatile CommerceMissionServiceImpl LLLLLLZ;
    public static volatile AdPlayFunAsseUtils LLLLLLZZ;
    public static volatile AdWebViewPrefetchManager LLLLLZ;
    public static volatile AdsPreviewServiceImpl LLLLLZIL;
    public static volatile CommerceProfileService LLLLLZL;
    public static volatile TalentAdRevenueShareServiceImpl LLLLZ;
    public static volatile CommerceCommonServiceImpl LLLLZI;
    public static volatile CommerceLockStickerServiceImpl LLLLZIL;
    public static volatile AdOpenHelperImpl LLLLZLL;
    public static volatile NoticeChallengePropertyUtilImpl LLLLZLLIL;
    public static volatile AdLightWebPageOpenUtils LLLLZLLLI;
    public static volatile CommercializeAdServiceImpl LLLZ;
    public static volatile ComplianceDependServiceImpl LLLZI;
    public static volatile PNSAgeControlService LLLZIIL;
    public static volatile CompliancePolicyServiceImpl LLLZIL;
    public static volatile AgeAppealServiceImpl LLLZL;
    public static volatile AgeGateServiceImpl LLLZLL;
    public static volatile BanAppealServiceImpl LLLZLZ;
    public static volatile ChildModeServiceImpl LLLZZ;
    public static volatile ComplianceBusinessServiceImpl LLLZZIL;
    public static volatile ComplianceSettingsServiceImpl LLZ;
    public static volatile PnSSearchHistoryServiceImpl LLZIL;
    public static volatile PolicyNoticeServiceImpl LLZILL;
    public static volatile PrivateAccountServiceImpl LLZL;
    public static volatile ReportServiceImpl LLZLI;
    public static volatile TermsConsentServiceImpl LLZLL;
    public static volatile TpcConsentServiceImpl LLZLLIL;
    public static volatile ShareWarningInfoServiceImpl LLZLLLL;
    public static volatile PNSUserStateManager LLZZ;
    public static volatile ComplianceMonitorServiceImpl LLZZJLIL;
    public static volatile HydrogenServiceImpl LLZZLLIL;
    public static volatile PNSConsentServiceImpl LLZZZIL;
    public static volatile ConsentServiceImpl LLZZZZ;
    public static volatile PdpPreviewServiceImpl M;
    public static volatile SurveyConfigServiceImpl M0;
    public static volatile KidsPolicyNoticeServiceImp M1;
    public static volatile MixFeedService M2;
    public static volatile SeriesNotificationServiceImpl M3;
    public static volatile SecApiImpl M4;
    public static volatile MainServiceForJsb M5;
    public static volatile ShareH5ServiceImpl M6;
    public static volatile TrendingDetailServiceImpl M7;
    public static volatile AddYoursServiceImpl M8;
    public static volatile LowResolutionImageCache N;
    public static volatile FeedRecommendFragmentProvider N0;
    public static volatile FavoriteServiceImpl N1;
    public static volatile ClientAiInitServiceImpl N2;
    public static volatile SeriesVideoUploadServiceImpl N3;
    public static volatile AttributionService N4;
    public static volatile MainServiceHelperImpl N5;
    public static volatile ShareRespSendServiceImpl N6;
    public static volatile UgCommonServiceImpl N7;
    public static volatile InviteFriendsServiceImpl N8;
    public static volatile EcomSparkSubInterceptorProvider O;
    public static volatile FeedUniformFontServiceImpl O0;
    public static volatile ProfileServiceImpl O1;
    public static volatile MLCommonServiceImpl O2;
    public static volatile PaidSeriesLiveApiService O3;
    public static volatile ByteLingoServiceImpl O4;
    public static volatile MainXBridgeServiceImpl O5;
    public static volatile com.ss.android.ugc.aweme.share.ShareServiceImpl O6;
    public static volatile BrandServiceImpl O7;
    public static volatile PerformanceServiceImpl O8;
    public static volatile StrategyService P;
    public static volatile NewUserProgressBarManager P0;
    public static volatile RecommendFeedServiceImpl P1;
    public static volatile MLDataCenterServiceImpl P2;
    public static volatile PipServiceImpl P3;
    public static volatile CaptionKevaServiceImpl P4;
    public static volatile MandatoryLoginService P5;
    public static volatile GifShareService P6;
    public static volatile UpvoteServiceImpl P7;
    public static volatile DeeplinkPrefetchImpl P8;
    public static volatile ECImageService Q;
    public static volatile MallLogUtilsImpl Q0;
    public static volatile com.ss.android.ugc.aweme.kids.setting.SettingServiceImpl Q1;
    public static volatile SmartDataTrackerServiceImpl Q2;
    public static volatile PipoService Q3;
    public static volatile CaptionServiceImpl Q4;
    public static volatile MusicService Q5;
    public static volatile FeedStateVMServiceImpl Q6;
    public static volatile UserService Q7;
    public static volatile LocationPluginServiceImpl Q8;
    public static volatile ECommerceService R;
    public static volatile RuntimeBehaviorServiceImpl R0;
    public static volatile SharedPreferencesProvider R1;
    public static volatile PitayaFeatureCenterServiceImpl R2;
    public static volatile PluginService R3;
    public static volatile CaptionSheetServiceImpl R4;
    public static volatile NetworkContextService R5;
    public static volatile TiktokShortcutManager R6;
    public static volatile AppWidgetServiceImpl R7;
    public static volatile LocationServiceImpl R8;
    public static volatile com.ss.android.ugc.aweme.ecommerce.eventcenter.EventCenter S;
    public static volatile ScreenShotFeedbackService S0;
    public static volatile AppLogReaperServiceImpl S1;
    public static volatile SmartHARServiceImpl S2;
    public static volatile AabPluginServiceImpl S3;
    public static volatile CommonFeedApiService S4;
    public static volatile NetworkLevelService S5;
    public static volatile AllowVideoThresholdUtils S6;
    public static volatile EnterProfileServiceImpl S7;
    public static volatile SecLinkServiceImpl S8;
    public static volatile FashionMallService T;
    public static volatile FollowFeedServiceImpl T0;
    public static volatile AdLandPageServiceImpl T1;
    public static volatile SmartCDNRankServiceImpl T2;
    public static volatile PNSAgeGateServiceImpl T3;
    public static volatile DanmakuServiceImpl T4;
    public static volatile NetworkQualityServiceImpl T5;
    public static volatile BusinessPublishImpl T6;
    public static volatile GsonHolder T7;
    public static volatile ClientSecurityServiceImpl T8;
    public static volatile FashionMallTabIconService U;
    public static volatile FollowWidgetServiceImpl U0;
    public static volatile AdLandPageSurveyServiceImpl U1;
    public static volatile SmartFeedAdUIServiceImpl U2;
    public static volatile GatekeeperManager U3;
    public static volatile EncourageLoginPopupManager U4;
    public static volatile NetworkStandardApiImpl U5;
    public static volatile DuetDownloadService U6;
    public static volatile InterceptorHolder U7;
    public static volatile com.ss.android.ugc.trill.download.DownloadServiceImpl U8;
    public static volatile ECommerceMallService V;
    public static volatile ForwardStatisticsServiceImpl V0;
    public static volatile LauncherServiceImpl V1;
    public static volatile SmartFeedLoadMoreServiceImpl V2;
    public static volatile UniversalPopupManager V3;
    public static volatile FriendsTabDbService V4;
    public static volatile NetworkStandardUIServiceImpl V5;
    public static volatile MediaChosenResultProcessFactory V6;
    public static volatile LanguageService V7;
    public static volatile AuthorizeCommonService V8;
    public static volatile MallServiceManager W;
    public static volatile FriendsServiceImpl W0;
    public static volatile AccountImpl W1;
    public static volatile SmartFeedPreloadServiceImpl W2;
    public static volatile UniversalPopupManager2 W3;
    public static volatile LingoCaptionServiceImpl W4;
    public static volatile NetworkStateServiceImpl W5;
    public static volatile PublishServiceFactoryImpl W6;
    public static volatile NotificationClickHelperImpl W7;
    public static volatile ICLALanguageServiceImpl W8;

    /* renamed from: X, reason: collision with root package name */
    public static volatile ShopIconServiceImpl f82X;
    public static volatile SocialFriendsService X0;
    public static volatile CrashSdkImpl X1;
    public static volatile SmartPreloadCommentV2ServiceImpl X2;
    public static volatile GoogleMapServiceImpl X3;
    public static volatile MentionVideoService X4;
    public static volatile PerformanceMainServiceImpl X5;
    public static volatile VideoLengthChecker X6;
    public static volatile SchemaPageHelperImpl X7;
    public static volatile VEEncodingImpl X8;

    /* renamed from: Y, reason: collision with root package name */
    public static volatile EcSchemaService f83Y;
    public static volatile FollowService Y0;
    public static volatile GodzillaImpl Y1;
    public static volatile SmartPreloadProfileV2ServiceImpl Y2;
    public static volatile PoiServiceImpl Y3;
    public static volatile NearbyFeedServiceImpl Y4;
    public static volatile PowerContextImpl Y5;
    public static volatile PublishPageImpl Y6;
    public static volatile WSHelperImpl Y7;
    public static volatile ECommerceShowcaseService Z;
    public static volatile FriendsFeedServiceImpl Z0;
    public static volatile AbTestManagerImpl Z1;
    public static volatile SmartClassifyServiceImpl Z2;
    public static volatile PortraitCenterInitServiceImpl Z3;
    public static volatile PaidContentBannerServiceImpl Z4;
    public static volatile RetrofitService Z5;
    public static volatile CreativeToolXBridgeService Z6;
    public static volatile GeckoLocalServiceImpl Z7;
    public static volatile PNSDeviceConsentServiceImpl a;
    public static volatile EcommerceStoreBizLogServiceImpl a0;
    public static volatile AdGoogleMapService a1;
    public static volatile ColdLaunchRequestCombinerImpl a2;
    public static volatile SmartCommonPreloadServiceImpl a3;
    public static volatile IMClientPortraitProducerService a4;
    public static volatile PaidContentCollectionPlayProgressServiceImpl a5;
    public static volatile SaveInfoDialogService a6;
    public static volatile LibraryCameraServiceImpl a7;
    public static volatile WatchHistoryValueService a8;
    public static volatile com.ss.android.ugc.aweme.compliance.privacy.impl.PrivacyServiceImpl b;
    public static volatile EcommerceStoreTechLogServiceImpl b0;
    public static volatile MSAdaptionService b1;
    public static volatile FollowTabBubbleGuideHelperImpl b2;
    public static volatile SmartDataCenterApiServiceImpl b3;
    public static volatile PowerModeHandlerProxy b4;
    public static volatile PaidContentPaymentServiceImpl b5;
    public static volatile SmartLockService b6;
    public static volatile AlbumServiceImpl b7;
    public static volatile WaterMarkServiceImpl b8;
    public static volatile AlgoRefreshServiceImpl c;
    public static volatile RomaSchemaGroupShoppingStoreSettings c0;
    public static volatile HomePageCommonServiceImpl c1;
    public static volatile SearchResultStatisticsImpl c2;
    public static volatile SmartMLSceneServiceImpl c3;
    public static volatile ProfileShowMutualTabServiceImpl c4;
    public static volatile PaidContentPreviewTagServiceImpl c5;
    public static volatile ToolsBusinessServiceImpl c6;
    public static volatile CommentFavoriteServiceImpl c7;
    public static volatile DMPublishServiceImpl c8;
    public static volatile AntiAddictionServiceImpl d;
    public static volatile SmartCheckIntegrateImpl d0;
    public static volatile EasyNavigationExperimentServiceImpl d1;
    public static volatile SocialCardServiceImp d2;
    public static volatile SmartPlaytimePredictServiceImpl d3;
    public static volatile AvatarAndNicknamePopupController d4;
    public static volatile PaidContentSdpTrailerService d5;
    public static volatile ToolsCPUDataServiceImpl d6;
    public static volatile QuestionFavoriteServiceImpl d7;
    public static volatile CrossPlatformJsbProxy d8;
    public static volatile FamilyPairingServiceImpl e;
    public static volatile EcUgCommonService e0;
    public static volatile HybridKitTaskImpl e1;
    public static volatile CrashSdkTaskImpl e2;
    public static volatile SmartRegressCalculateServiceImpl e3;
    public static volatile UserProfilePreloadHelper e4;
    public static volatile PaidContentServiceImpl e5;
    public static volatile TrafficStatisticsServiceImpl e6;
    public static volatile com.ss.android.ugc.aweme.shortvideo.subtitle.CaptionServiceImpl e7;
    public static volatile GeckoXClientManager e8;
    public static volatile ProtectionServiceImpl f;
    public static volatile EcUgDeeplinkService f0;
    public static volatile PiaConfigTask f1;
    public static volatile LoginProxyImpl f2;
    public static volatile SmartOHRServiceImpl f3;
    public static volatile MafRedPointDismissHelper f4;
    public static volatile PhotoDownloadServiceImpl f5;
    public static volatile UserInfoUpdateAdapterService f6;
    public static volatile StitchDownloadServiceImpl f7;
    public static volatile AdWebViewInterceptorService f8;
    public static volatile SandboxServiceImpl g;
    public static volatile EcUgFeedEcCardService g0;
    public static volatile WebViewInjectServiceImpl g1;
    public static volatile NetWorkInjectImpl g2;
    public static volatile MusicDetailService g3;
    public static volatile EffectHintSelectDialogServiceImpl g4;
    public static volatile PhotoViewModelImpl g5;
    public static volatile WebViewTweakerService g6;
    public static volatile AdSparkUtils g7;
    public static volatile AdWebSpecialService g8;
    public static volatile WebViewTTNetHandlerImp h;
    public static volatile EcUgNewInstallService h0;
    public static volatile IMService h1;
    public static volatile NetworkConfigProvider h2;
    public static volatile ProfileMusicTabService h3;
    public static volatile PropReuseServiceImpl h4;
    public static volatile PostModeServiceImpl h5;
    public static volatile EffectAnchorServiceImpl h6;
    public static volatile SpecActServiceImpl h7;
    public static volatile WebCreationPromoteServiceImpl h8;
    public static volatile com.ss.android.ugc.aweme.component.music.MusicService i;
    public static volatile EcUgPopupService i0;
    public static volatile StoryIMService i1;
    public static volatile ProviderConfigOutImpl i2;
    public static volatile MovieReuseServiceImpl i3;
    public static volatile EditorProIconServiceImpl i4;
    public static volatile SeriesPricingServiceImpl i5;
    public static volatile FunctionSupportServiceImpl i6;
    public static volatile StemFeedServiceImpl i7;
    public static volatile AdWebViewForestServiceImpl i8;
    public static volatile AwemeConfigCenter.AwemeConfigCenterImpl j;
    public static volatile EcUgVSAService j0;
    public static volatile IMCoreDependProxyService j1;
    public static volatile SysOptTaskImpl j2;
    public static volatile NetworkApiImpl j3;
    public static volatile PublishConfigExternalService j4;
    public static volatile SocInteractionAvatarServiceImpl j5;
    public static volatile OneMinuteH5PreloadServiceImpl j6;
    public static volatile AddYoursModelCheckService j7;
    public static volatile AdWebPermissionService j8;
    public static volatile IMContactServiceImpl k;
    public static volatile PageNodeMonitorService k0;
    public static volatile NotificationManagerServiceImpl k1;
    public static volatile TaskManagerConfigImpl k2;
    public static volatile SpeedModeServiceImpl k3;
    public static volatile QAInvitationService k4;
    public static volatile SocPubDistributeServiceImpl k5;
    public static volatile AutoCutServiceImpl k6;
    public static volatile AddYoursStickerFactoryService k7;
    public static volatile AdLandPageRealtimeResourceModule k8;
    public static volatile ContentLanguageServiceImpl l;
    public static volatile ECommerceLiveServiceImpl l0;
    public static volatile IMUnder16ProxyImpl l1;
    public static volatile WatcherImpl l2;
    public static volatile PowerPreloadServiceImpl l3;
    public static volatile QRCodeServiceImpl l4;
    public static volatile SocPubStatusRepoServiceImpl l5;
    public static volatile CreativePageService l6;
    public static volatile AddYoursStickerRecordServiceImpl l7;
    public static volatile AdWebUtils l8;
    public static volatile ContentLanguageGuideServiceImpl m;
    public static volatile Object m0;
    public static volatile DraweeConfigOutService m1;
    public static volatile PowerPermissionsTask m2;
    public static volatile FollowStatisticsServiceImpl m3;
    public static volatile BridgeScanHandlerImpl m4;
    public static volatile Social2TabRouteService m5;
    public static volatile EditRootSceneFactoryDelegate m6;
    public static volatile StickerContainerService m7;
    public static volatile WsManager m8;

    /* renamed from: n, reason: collision with root package name */
    public static volatile CreatorCenterPreloadServiceImpl f84n;
    public static volatile Object n0;
    public static volatile LightenConfigOutService n1;
    public static volatile TTPSystemAPIInit n2;
    public static volatile NewUserImpl n3;
    public static volatile QRCodePermissionActivityStarter n4;
    public static volatile Social2TabServiceImpl n5;
    public static volatile EmojiServiceImplDiff n6;
    public static volatile StickerServiceImpl n7;

    /* renamed from: n8, reason: collision with root package name */
    public static volatile WsMonitor f85n8;
    public static volatile CreatorToolServiceImpl o;
    public static volatile EffectStorageCleanServiceImpl o0;
    public static volatile LauncherTaskApiImpl o1;
    public static volatile AccountInitializerTaskImpl o2;

    /* renamed from: o3, reason: collision with root package name */
    public static volatile DmNoticeProxyImpl f86o3;
    public static volatile QuestionDetailServiceImpl o4;
    public static volatile TextModeServiceImpl o5;
    public static volatile PageFactoryDelegate o6;
    public static volatile MusicStorageCleanServiceImpl o7;
    public static volatile ZeroRatingMainServiceImpl o8;
    public static volatile MixActivityContainerProvider p;
    public static volatile EffectPlatformFactory p0;
    public static volatile OptimizerHelperServiceImpl p1;
    public static volatile FrescoLegoTaskImpl p2;
    public static volatile NotificationFragmentServiceImpl p3;
    public static volatile RecommendUserServiceImpl p4;
    public static volatile EarlyFeedbackService p5;
    public static volatile SplitVideoServiceImpl p6;
    public static volatile SocialPublishBridgeServiceImpl p7;

    /* renamed from: p8, reason: collision with root package name */
    public static volatile PushPermissionPopupManager f87p8;
    public static volatile DeepLinkServiceImpl q;
    public static volatile DoubleColorBallAnimationViewExperimentServiceImpl q0;
    public static volatile StrategyImpl q1;
    public static volatile ExitBackgroundImpl q2;
    public static volatile ActivityAdapterServiceImp q3;
    public static volatile ExteriorRecordPageFactoryImpl q4;
    public static volatile IncreaseLoginNotifyService q5;
    public static volatile TTEPPageFactoryDelegate q6;
    public static volatile StoryDistributionService q7;

    /* renamed from: q8, reason: collision with root package name */
    public static volatile EditorStickerDowngradeServiceImpl f88q8;
    public static volatile DetailApiProxyImpl r;
    public static volatile LogInterceptImpl r0;
    public static volatile InboxEasyNavigationPageNameServiceImpl r1;
    public static volatile LibraryReuseServiceImpl r2;
    public static volatile NoticeCountServiceImpl r3;
    public static volatile AuthServiceImpl r4;
    public static volatile NewUserModeService r5;
    public static volatile GetPushSettingCallback r6;
    public static volatile StoryServiceImpl r7;
    public static volatile FypAutoScrollServiceImpl r8;
    public static volatile DuetModeCameraServiceImpl s;
    public static volatile PagingScrollSettingApiImpl s0;
    public static volatile InboxMobEventServiceImpl s1;
    public static volatile GeckoService s2;
    public static volatile NoticeCountTabBadgePresentServiceImpl s3;
    public static volatile FollowAvatarServiceImpl s4;
    public static volatile NicknameSignupExperiment s5;
    public static volatile PromoteEntryCheckServiceImpl s6;
    public static volatile ByteSyncApiImpl s7;
    public static volatile EarphonePlayerControl s8;
    public static volatile com.ss.android.ugc.aweme.di.CommerceServiceImpl t;
    public static volatile ViewPagerSlideTransitionServiceImpl t0;
    public static volatile InboxServiceImpl t1;
    public static volatile LiveHostOuterService t2;
    public static volatile NoticeServiceImpl t3;
    public static volatile AvatarUnionServiceImpl t4;
    public static volatile ICLAPerfETServiceImpl t5;
    public static volatile UpdateSettingServiceImpl t6;
    public static volatile ByteSyncInitProviderImpl t7;
    public static volatile FindTargetScopeFailFasterServiceImpl t8;
    public static volatile ImEntranceService u;
    public static volatile ExploreFeedServiceImpl u0;
    public static volatile InboxSkylightService u1;
    public static volatile LiveOuterService u2;
    public static volatile OldNoticeCountServiceImpl u3;
    public static volatile RelationLabelTextViewServiceImpl u4;
    public static volatile ProactiveTriggersService u5;
    public static volatile SpeedModeSettingImpl u6;
    public static volatile TabletServiceProxy u7;
    public static volatile EditVideoInfoServiceImpl u8;
    public static volatile DiscoveryAsyncInflateImpl v;
    public static volatile AwemeCollectionAgent v0;
    public static volatile ECommerceLiveBridgeMethodServiceImpl v1;
    public static volatile LiveVersionCodeProvider v2;
    public static volatile RedPointServiceImpl v3;
    public static volatile MutualRelationServiceImpl v4;

    /* renamed from: v5, reason: collision with root package name */
    public static volatile TooltipApplicabilityService f89v5;
    public static volatile PushSettingServiceImpl v6;
    public static volatile TagServiceImpl v7;
    public static volatile AutoSoundCheckService v8;
    public static volatile com.ss.android.ugc.aweme.discover.impl.DiscoveryServiceImpl w;
    public static volatile AwemeCollectionCountAgent w0;
    public static volatile EcommerceInfluencerServiceImpl w1;
    public static volatile SearchCardLiveService w2;
    public static volatile CreativeNowServiceImpl w3;
    public static volatile RecUserServiceImpl w4;
    public static volatile UnLoginDiggService w5;
    public static volatile AppUpdateService w6;
    public static volatile StickerViewServiceImpl w7;
    public static volatile AudioGlitchService w8;
    public static volatile AVInitializerImpl x;
    public static volatile PlaylistCollectionStateAgent x0;
    public static volatile AVServiceProxyImpl x1;
    public static volatile LocalServiceImpl x2;
    public static volatile NowCaptionService x3;
    public static volatile InviteFriendsService x4;
    public static volatile AccountHelperService x5;
    public static volatile I18nService x6;
    public static volatile TopicAnchorFactory x7;
    public static volatile VoiceDetectorService x8;
    public static volatile DonationServiceImpl y;
    public static volatile com.ss.android.ugc.aweme.favorites.service.FavoriteServiceImpl y0;
    public static volatile InnerPushServiceImpl y1;
    public static volatile AdWebLogService y2;
    public static volatile NowCommonFeedServiceImpl y3;
    public static volatile RelationStorageServiceImpl y4;
    public static volatile ApiNetworkServiceForAccount y5;
    public static volatile com.ss.android.ugc.aweme.setting.services.LanguageService y6;
    public static volatile TopicCommonService y7;
    public static volatile AudioWatermarkServiceImpl y8;
    public static volatile DownloadAwemeVideoServiceImpl z;
    public static volatile FeedFragmentClassService z0;
    public static volatile AVCommerceServiceImpl z1;
    public static volatile LoginUtilsServiceImpl z2;
    public static volatile NowDailyPushService z3;
    public static volatile RelationUserCardInternalService z4;
    public static volatile ArticleModeServiceImpl z5;
    public static volatile SettingDependServiceImpl z6;
    public static volatile BookTokServiceImpl z7;
    public static volatile DefaultStoryForwardServiceImpl z8;

    static {
        new ConcurrentHashMap();
    }

    public static Object LIZ(Class cls, boolean z9) {
        Object downgradeImpl;
        if (DowngradeImplManager.getInstance().isServiceForceDowngrade(cls) && (downgradeImpl = DowngradeImplManager.getInstance().getDowngradeImpl(cls)) != null) {
            return downgradeImpl;
        }
        if (z9) {
            return null;
        }
        try {
            java.util.Set set = (java.util.Set) ServiceManager.get().getServiceProviderMap().get(cls);
            if (set != null && !set.isEmpty()) {
                return ((ServiceProvider) set.toArray()[0]).get();
            }
            return null;
        } catch (Exception e9) {
            C16880lQ.LLLLIIL(e9);
            return null;
        }
    }
}
