package X;

import java.util.ArrayList;

/* renamed from: X.Oew, reason: case insensitive filesystem */
/* loaded from: classes11.dex */
public final class C62438Oew {
    public static final String[] LIZ = {"top", "ad_settings", "ad_share_data_action", "ad_plan", "blacklist", "block_user", "favorite", "captions", "copy", "delete", "delete", "dislike", "save", "now_save", "duet", "create_sticker", "top", "gif", "insight", "add_calendar", "delete_live_event", "edit_live_event", "report_music", "live_photo", "message", "play_list", "save_no_watermark", "privacy", "promote", "promote_for_others", "react", "report", "unfollow", "now_extend_rule", "following_feed_0_following", "remove_follower", "report_hashtag", "report_music", "report_sticker", "report_qna", "ad_report", "shoutouts_report", "report", "report_paid_series", "restrict", "reuse_mv_template", "reuse_sticker", "status", "stitch", "campaign_detail", "qr_code", "report_live", "qa_invite", "live_dislike_action", "video_tag_edit", "video_tag_remove", "ad_personalization_new", "browser", "refresh", "bc_view_insights", "bc_remove_tag", "refresh", "save_photo", "save_image", "effect info action", "remove_original_sound", "clear_mode", "auto_scroll", "report_live_links", "playback_speed", "admin", "auto_translate", "caption_switch", "why_this_video", "key_video_fullscreen_center_crop", "live_feed_back", "image_save", "edit_post", "replace_sound", "privacy_setting", "rename_video_collection", "delete_video_collection", "podcast", "suggest_an_edit", "claim_your_store", "follow_widget", "picture_in_picture", "repost", "share_to_story", "remove_ugc_template", "danmaku", "casting", "manage_feed", "definition_selection_key", "moderator_setting_action", "promote_button", "share_setting", "live_game_drops_watch", "pip_switch", "prompt_customize_fyp"};
    public static final ArrayList<String> LIZIZ = C47261Igj.LJII("video_tag_remove", "bc_view_insights", "insight", "campaign_detail", "ad_personalization_new", "report", "dislike", "save", "prompt_customize_fyp", "casting", "why_this_video", "now_save", "save_photo", "top", "promote", "play_list", "reuse_sticker", "reuse_mv_template", "status", "green_screen", "real_time", "captions", "promote_for_others", "duet", "stitch", "create_sticker", "clear_mode", "auto_scroll", "react", "favorite", "playback_speed", "manage_captions", "video_tag_edit", "edit_post", "replace_sound", "privacy", "remove_ugc_template", "live_photo", "gif", "ad_settings", "delete", "ad_plan", "bc_remove_tag", "suggest_en_edit", "picture_in_picture", "podcast", "qr_code");
}
