package X;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import java.util.List;

/* renamed from: X.RCc, reason: case insensitive filesystem */
/* loaded from: classes13.dex */
public final class C69154RCc extends Message<C69154RCc, C69321RIn> {
    public static final ProtoAdapter<C69154RCc> ADAPTER = new C69153RCb();
    public Boolean accept_private_policy;
    public String account_region;
    public RN9 ad_cover_title;
    public List<REV> ad_cover_url;
    public String ad_order_id;
    public Integer apple_account;
    public Long authority_status;
    public REV avatar_168x168;
    public REV avatar_300x300;
    public C69378RKs avatar_decoration;
    public Long avatar_decoration_id;
    public REV avatar_larger;
    public REV avatar_medium;
    public REV avatar_pendant_larger;
    public REV avatar_pendant_medium;
    public REV avatar_pendant_thumb;
    public REV avatar_thumb;
    public Boolean avatar_update_reminder;
    public String avatar_uri;
    public Integer aweme_count;
    public C69259RGd badge_info;
    public String bind_phone;
    public String bio_email;
    public String bio_secure_url;
    public String bio_url;
    public String birthday;
    public Integer birthday_hide_level;
    public RG0 brand_info;
    public List<Integer> can_message_follow_status_list;
    public Boolean can_modify_school_info;
    public List<C69160RCi> cha_list;
    public String city;
    public Integer collect_count;
    public Integer comment_filter_status;
    public Integer comment_setting;
    public RFV commerce_info;
    public C69450RNm commerce_permissions;
    public RGS commerce_user_info;
    public Integer commerce_user_level;
    public String country;
    public List<REV> cover_url;
    public Long create_time;
    public Integer creator_level;
    public String custom_verify;
    public String cv_level;
    public Boolean display_wvalantine_activity_entry;
    public String district;
    public Long download_prompt_ts;
    public Integer download_setting;
    public Integer duet_setting;
    public Integer education;
    public C69462RNy effect_detail;
    public String email;
    public String enterprise_verify_reason;
    public Integer favoriting_count;
    public Integer fb_expire_time;
    public Integer follow_status;
    public Integer follower_count;
    public Integer follower_status;
    public List<RGP> followers_detail;
    public Integer following_count;
    public Boolean force_private_account;
    public Integer friends_status;
    public Integer gender;
    public RH4 general_permission;
    public List<String> geofencing;
    public String google_account;
    public Boolean has_email;
    public Boolean has_facebook_token;
    public Boolean has_insights;
    public Boolean has_orders;
    public Boolean has_twitter_token;
    public Boolean has_youtube_token;
    public Integer hide_following_follower_list;
    public Boolean hide_search;
    public C69447RNj honor_info;
    public String ins_id;
    public Boolean is_activity_user;
    public Boolean is_ad_fake;
    public Boolean is_block;
    public Boolean is_blocked;
    public Boolean is_discipline_member;
    public Boolean is_effect_artist;
    public Boolean is_email_verified;
    public Boolean is_flowcard_member;
    public Boolean is_in_same_note_exp_group;
    public Boolean is_life_style;
    public Boolean is_minor;
    public Boolean is_mirror;
    public Boolean is_phone_binded;
    public Boolean is_pro_account;
    public Boolean is_star;
    public Boolean is_user_data_miss;
    public String iso_country_code;
    public List<C69268RGm> item_list;
    public String language;
    public Long latest_order_time;
    public C69432RMu life_story_block;
    public Integer live_agreement;
    public Integer live_agreement_time;
    public Boolean live_commerce;
    public Integer live_verify;
    public Integer login_platform;
    public C69257RGb matched_friend;
    public Integer mplatform_followers_count;
    public Integer need_recommend;
    public String nickname;
    public Boolean nickname_update_reminder;
    public Integer notify_private_account;
    public C69261RGf original_musician;
    public List<RHH> platform_sync_info;
    public Integer pr_exempt;
    public Boolean prevent_download;
    public Integer profile_tab_type;
    public String province;
    public Integer qa_status;
    public RHW quick_shop_info;
    public RLV r_fans_group_info;
    public Integer react_setting;
    public String recommend_reason;
    public String recommend_reason_relation;
    public Double recommend_score;
    public Long reflow_page_gid;
    public Long reflow_page_uid;
    public String region;
    public Long register_time;
    public List<C69255RFz> relative_users;
    public String remark_name;
    public REV room_cover;
    public String room_data;
    public Long room_id;
    public String room_type_tag;
    public Integer school_visible;
    public String sec_uid;
    public Integer secret;
    public C69199RDv share_info;
    public String share_qrcode_uri;
    public Integer shield_comment_notice;
    public Integer shield_digg_notice;
    public Integer shield_follow_notice;
    public String shop_micro_app;
    public String short_id;
    public Boolean show_image_bubble;
    public String signature;
    public String signature_language;
    public String social_info;
    public Integer special_lock;
    public RGQ sprint_support_user_info;
    public Integer star_billboard_rank;
    public Integer status;
    public Integer stitch_setting;
    public Integer story_status;
    public Integer total_favorited;
    public Integer tw_expire_time;
    public String twitter_id;
    public String twitter_name;
    public List<Long> type_label;
    public String uid;
    public String unique_id;
    public Integer unique_id_modify_time;
    public Boolean user_canceled;
    public Integer user_mode;
    public C69459RNv user_now_pack_info;
    public Integer user_period;
    public Integer user_rate;
    public Integer verification_type;
    public String verify_info;
    public REV video_icon;
    public String video_icon_virtual_URI;
    public RMK video_unread_info;
    public Boolean watch_status;
    public Boolean with_commerce_enterprise_tab_entry;
    public Boolean with_commerce_entry;
    public Boolean with_commerce_newbie_task;
    public Boolean with_fusion_shop_entry;
    public Boolean with_item_commerce_entry;
    public Boolean with_new_goods;
    public Boolean with_shop_entry;
    public Boolean with_star_atlas_entry;
    public String youtube_channel_id;
    public String youtube_channel_title;
    public Integer youtube_expire_time;

    public C69154RCc() {
        super(ADAPTER, C64537PUn.EMPTY);
        this.followers_detail = C63685Oz3.LJIIIIZZ();
        this.platform_sync_info = C63685Oz3.LJIIIIZZ();
        this.geofencing = C63685Oz3.LJIIIIZZ();
        this.cover_url = C63685Oz3.LJIIIIZZ();
        this.item_list = C63685Oz3.LJIIIIZZ();
        this.type_label = C63685Oz3.LJIIIIZZ();
        this.ad_cover_url = C63685Oz3.LJIIIIZZ();
        this.relative_users = C63685Oz3.LJIIIIZZ();
        this.cha_list = C63685Oz3.LJIIIIZZ();
        this.can_message_follow_status_list = C63685Oz3.LJIIIIZZ();
    }

    @Override // com.squareup.wire.Message
    /* renamed from: newBuilder */
    public Message.Builder<C69154RCc, C69321RIn> newBuilder2() {
        return null;
    }

    @Override // com.squareup.wire.Message
    /* renamed from: newBuilder, reason: avoid collision after fix types in other method */
    public /* bridge */ /* synthetic */ Message.Builder<C69154RCc, C69321RIn> newBuilder2() {
        newBuilder2();
        return null;
    }
}
