package X;

import com.ss.android.vesdk.ROTATE_DEGREE;
import com.ss.android.vesdk.VEEditor;
import com.ss.android.vesdk.VEVideoEncodeSettings;
import com.ss.android.vesdk.VEWaterMarkPosition;
import com.ss.android.vesdk.settings.VEVideoEncodePreset;
import com.ss.android.vesdk.settings.VEVideoEncodeProfile;

/* renamed from: X.YNf, reason: case insensitive filesystem */
/* loaded from: classes16.dex */
public final /* synthetic */ class C87279YNf {
    public static final /* synthetic */ int[] LIZ;
    public static final /* synthetic */ int[] LIZIZ;
    public static final /* synthetic */ int[] LIZJ;
    public static final /* synthetic */ int[] LIZLLL;
    public static final /* synthetic */ int[] LJ;
    public static final /* synthetic */ int[] LJFF;
    public static final /* synthetic */ int[] LJI;
    public static final /* synthetic */ int[] LJII;
    public static final /* synthetic */ int[] LJIIIIZZ;
    public static final /* synthetic */ int[] LJIIIZ;
    public static final /* synthetic */ int[] LJIIJ;
    public static final /* synthetic */ int[] LJIIJJI;

    static {
        VEEditor.VEState.values();
        VEEditor.VEState.PREPARED.ordinal();
        VEEditor.VEState.STARTED.ordinal();
        VEEditor.VEState.PAUSED.ordinal();
        VEEditor.VEState.SEEKING.ordinal();
        VEEditor.VEState.STOPPED.ordinal();
        VEEditor.VEState.IDLE.ordinal();
        int[] iArr = new int[EnumC135185Sg.values().length];
        LIZ = iArr;
        iArr[EnumC135185Sg.PREPARED.ordinal()] = 1;
        iArr[EnumC135185Sg.STARTED.ordinal()] = 2;
        iArr[EnumC135185Sg.PAUSED.ordinal()] = 3;
        iArr[EnumC135185Sg.SEEKING.ordinal()] = 4;
        iArr[EnumC135185Sg.STOPPED.ordinal()] = 5;
        iArr[EnumC135185Sg.IDLE.ordinal()] = 6;
        EnumC133595Md.values();
        EnumC133595Md.EDITOR_SEEK_FLAG_LastSeek.ordinal();
        EnumC133595Md.EDITOR_SEEK_FLAG_OnGoing.ordinal();
        EnumC133595Md.EDITOR_SEEK_FLAG_LAST_UpdateInOut.ordinal();
        EnumC133595Md.EDITOR_SEEK_FLAG_LAST_UpdateIn.ordinal();
        EnumC133595Md.EDITOR_SEEK_FLAG_LAST_UpdateOut.ordinal();
        X6A.values();
        X6A.ENCODE_STANDARD_H264.ordinal();
        X6A.ENCODE_STANDARD_ByteVC1.ordinal();
        X6A.ENCODE_STANDARD_MPEG4.ordinal();
        int[] iArr2 = new int[VEVideoEncodeSettings.ENCODE_STANDARD.values().length];
        LIZIZ = iArr2;
        iArr2[VEVideoEncodeSettings.ENCODE_STANDARD.ENCODE_STANDARD_H264.ordinal()] = 1;
        iArr2[VEVideoEncodeSettings.ENCODE_STANDARD.ENCODE_STANDARD_ByteVC1.ordinal()] = 2;
        iArr2[VEVideoEncodeSettings.ENCODE_STANDARD.ENCODE_STANDARD_MPEG4.ordinal()] = 3;
        int[] iArr3 = new int[VEVideoEncodeProfile.values().length];
        LIZJ = iArr3;
        iArr3[VEVideoEncodeProfile.ENCODE_PROFILE_UNKNOWN.ordinal()] = 1;
        iArr3[VEVideoEncodeProfile.ENCODE_PROFILE_BASELINE.ordinal()] = 2;
        iArr3[VEVideoEncodeProfile.ENCODE_PROFILE_HIGH.ordinal()] = 3;
        iArr3[VEVideoEncodeProfile.ENCODE_PROFILE_MAIN.ordinal()] = 4;
        int[] iArr4 = new int[VEVideoEncodeSettings.ENCODE_PROFILE.values().length];
        LIZLLL = iArr4;
        iArr4[VEVideoEncodeSettings.ENCODE_PROFILE.ENCODE_PROFILE_UNKNOWN.ordinal()] = 1;
        iArr4[VEVideoEncodeSettings.ENCODE_PROFILE.ENCODE_PROFILE_BASELINE.ordinal()] = 2;
        iArr4[VEVideoEncodeSettings.ENCODE_PROFILE.ENCODE_PROFILE_HIGH.ordinal()] = 3;
        iArr4[VEVideoEncodeSettings.ENCODE_PROFILE.ENCODE_PROFILE_MAIN.ordinal()] = 4;
        EnumC87281YNh.values();
        EnumC87281YNh.ENCODE_PROFILE_UNKNOWN.ordinal();
        EnumC87281YNh.ENCODE_PROFILE_BASELINE.ordinal();
        EnumC87281YNh.ENCODE_PROFILE_HIGH.ordinal();
        EnumC87281YNh.ENCODE_PROFILE_MAIN.ordinal();
        int[] iArr5 = new int[VEVideoEncodeSettings.ENCODE_BITRATE_MODE.values().length];
        LJ = iArr5;
        iArr5[VEVideoEncodeSettings.ENCODE_BITRATE_MODE.ENCODE_BITRATE_ABR.ordinal()] = 1;
        iArr5[VEVideoEncodeSettings.ENCODE_BITRATE_MODE.ENCODE_BITRATE_CRF.ordinal()] = 2;
        iArr5[VEVideoEncodeSettings.ENCODE_BITRATE_MODE.ENCODE_BITRATE_QP.ordinal()] = 3;
        iArr5[VEVideoEncodeSettings.ENCODE_BITRATE_MODE.ENCODE_BITRATE_VBR.ordinal()] = 4;
        EnumC84292X6i.values();
        EnumC84292X6i.ENCODE_BITRATE_ABR.ordinal();
        EnumC84292X6i enumC84292X6i = EnumC84292X6i.ENCODE_BITRATE_CRF;
        enumC84292X6i.ordinal();
        EnumC84292X6i enumC84292X6i2 = EnumC84292X6i.ENCODE_BITRATE_QP;
        enumC84292X6i2.ordinal();
        EnumC84292X6i.ENCODE_BITRATE_VBR.ordinal();
        int[] iArr6 = new int[VEVideoEncodePreset.values().length];
        LJFF = iArr6;
        iArr6[VEVideoEncodePreset.ENCODE_LEVEL_FAST.ordinal()] = 1;
        iArr6[VEVideoEncodePreset.ENCODE_LEVEL_FASTER.ordinal()] = 2;
        iArr6[VEVideoEncodePreset.ENCODE_LEVEL_MEDIUM.ordinal()] = 3;
        iArr6[VEVideoEncodePreset.ENCODE_LEVEL_PLACEBO.ordinal()] = 4;
        iArr6[VEVideoEncodePreset.ENCODE_LEVEL_SLOW.ordinal()] = 5;
        iArr6[VEVideoEncodePreset.ENCODE_LEVEL_SLOWER.ordinal()] = 6;
        iArr6[VEVideoEncodePreset.ENCODE_LEVEL_SUPERFAST.ordinal()] = 7;
        iArr6[VEVideoEncodePreset.ENCODE_LEVEL_ULTRAFAST.ordinal()] = 8;
        iArr6[VEVideoEncodePreset.ENCODE_LEVEL_VERYFAST.ordinal()] = 9;
        iArr6[VEVideoEncodePreset.ENCODE_LEVEL_VERYSLOW.ordinal()] = 10;
        int[] iArr7 = new int[VEVideoEncodeSettings.ENCODE_PRESET.values().length];
        LJI = iArr7;
        iArr7[VEVideoEncodeSettings.ENCODE_PRESET.ENCODE_LEVEL_FAST.ordinal()] = 1;
        iArr7[VEVideoEncodeSettings.ENCODE_PRESET.ENCODE_LEVEL_FASTER.ordinal()] = 2;
        iArr7[VEVideoEncodeSettings.ENCODE_PRESET.ENCODE_LEVEL_MEDIUM.ordinal()] = 3;
        iArr7[VEVideoEncodeSettings.ENCODE_PRESET.ENCODE_LEVEL_PLACEBO.ordinal()] = 4;
        iArr7[VEVideoEncodeSettings.ENCODE_PRESET.ENCODE_LEVEL_SLOW.ordinal()] = 5;
        iArr7[VEVideoEncodeSettings.ENCODE_PRESET.ENCODE_LEVEL_SLOWER.ordinal()] = 6;
        iArr7[VEVideoEncodeSettings.ENCODE_PRESET.ENCODE_LEVEL_SUPERFAST.ordinal()] = 7;
        iArr7[VEVideoEncodeSettings.ENCODE_PRESET.ENCODE_LEVEL_ULTRAFAST.ordinal()] = 8;
        iArr7[VEVideoEncodeSettings.ENCODE_PRESET.ENCODE_LEVEL_VERYFAST.ordinal()] = 9;
        iArr7[VEVideoEncodeSettings.ENCODE_PRESET.ENCODE_LEVEL_VERYSLOW.ordinal()] = 10;
        EnumC87280YNg.values();
        EnumC87280YNg enumC87280YNg = EnumC87280YNg.ENCODE_LEVEL_FAST;
        enumC87280YNg.ordinal();
        EnumC87280YNg enumC87280YNg2 = EnumC87280YNg.ENCODE_LEVEL_FASTER;
        enumC87280YNg2.ordinal();
        EnumC87280YNg enumC87280YNg3 = EnumC87280YNg.ENCODE_LEVEL_MEDIUM;
        enumC87280YNg3.ordinal();
        EnumC87280YNg enumC87280YNg4 = EnumC87280YNg.ENCODE_LEVEL_PLACEBO;
        enumC87280YNg4.ordinal();
        EnumC87280YNg enumC87280YNg5 = EnumC87280YNg.ENCODE_LEVEL_SLOW;
        enumC87280YNg5.ordinal();
        EnumC87280YNg enumC87280YNg6 = EnumC87280YNg.ENCODE_LEVEL_SLOWER;
        enumC87280YNg6.ordinal();
        EnumC87280YNg enumC87280YNg7 = EnumC87280YNg.ENCODE_LEVEL_SUPERFAST;
        enumC87280YNg7.ordinal();
        EnumC87280YNg enumC87280YNg8 = EnumC87280YNg.ENCODE_LEVEL_ULTRAFAST;
        enumC87280YNg8.ordinal();
        EnumC87280YNg enumC87280YNg9 = EnumC87280YNg.ENCODE_LEVEL_VERYFAST;
        enumC87280YNg9.ordinal();
        EnumC87280YNg enumC87280YNg10 = EnumC87280YNg.ENCODE_LEVEL_VERYSLOW;
        enumC87280YNg10.ordinal();
        EnumC87280YNg.values();
        enumC87280YNg.ordinal();
        enumC87280YNg2.ordinal();
        enumC87280YNg3.ordinal();
        enumC87280YNg4.ordinal();
        enumC87280YNg5.ordinal();
        enumC87280YNg6.ordinal();
        enumC87280YNg7.ordinal();
        enumC87280YNg8.ordinal();
        enumC87280YNg9.ordinal();
        enumC87280YNg10.ordinal();
        YBS.values();
        YBS.BL.ordinal();
        YBS.BR.ordinal();
        YBS.TL.ordinal();
        YBS.TL_BR.ordinal();
        YBS.TR.ordinal();
        int[] iArr8 = new int[VEWaterMarkPosition.values().length];
        LJII = iArr8;
        iArr8[VEWaterMarkPosition.BL.ordinal()] = 1;
        iArr8[VEWaterMarkPosition.BR.ordinal()] = 2;
        iArr8[VEWaterMarkPosition.TL.ordinal()] = 3;
        iArr8[VEWaterMarkPosition.TL_BR.ordinal()] = 4;
        iArr8[VEWaterMarkPosition.TR.ordinal()] = 5;
        int[] iArr9 = new int[VEVideoEncodeSettings.COMPILE_TYPE.values().length];
        LJIIIIZZ = iArr9;
        iArr9[VEVideoEncodeSettings.COMPILE_TYPE.COMPILE_TYPE_MP4.ordinal()] = 1;
        iArr9[VEVideoEncodeSettings.COMPILE_TYPE.COMPILE_TYPE_GIF.ordinal()] = 2;
        iArr9[VEVideoEncodeSettings.COMPILE_TYPE.COMPILE_TYPE_HIGH_GIF.ordinal()] = 3;
        iArr9[VEVideoEncodeSettings.COMPILE_TYPE.COMPILE_TYPE_PNG.ordinal()] = 4;
        iArr9[VEVideoEncodeSettings.COMPILE_TYPE.COMPILE_TYPE_JPEG.ordinal()] = 5;
        iArr9[VEVideoEncodeSettings.COMPILE_TYPE.COMPILE_TYPE_WEBP.ordinal()] = 6;
        EnumC84130X0c.values();
        EnumC84130X0c.COMPILE_TYPE_MP4.ordinal();
        EnumC84130X0c.COMPILE_TYPE_GIF.ordinal();
        EnumC84130X0c.COMPILE_TYPE_HIGH_GIF.ordinal();
        EnumC84130X0c.COMPILE_TYPE_PNG.ordinal();
        EnumC84130X0c.COMPILE_TYPE_JPEG.ordinal();
        EnumC84130X0c.COMPILE_TYPE_WEBP.ordinal();
        EnumC84292X6i.values();
        enumC84292X6i2.ordinal();
        enumC84292X6i.ordinal();
        C5NA.values();
        C5NA.NLE_GET_FRAMES_MODE_NORMAL.ordinal();
        C5NA.NLE_GET_FRAMES_MODE_NOEFFECT.ordinal();
        int[] iArr10 = new int[VEEditor.GET_FRAMES_FLAGS.values().length];
        LJIIIZ = iArr10;
        iArr10[VEEditor.GET_FRAMES_FLAGS.GET_FRAMES_MODE_NORMAL.ordinal()] = 1;
        iArr10[VEEditor.GET_FRAMES_FLAGS.GET_FRAMES_MODE_NOEFFECT.ordinal()] = 2;
        int[] iArr11 = new int[ROTATE_DEGREE.values().length];
        LJIIJ = iArr11;
        iArr11[ROTATE_DEGREE.ROTATE_90.ordinal()] = 1;
        iArr11[ROTATE_DEGREE.ROTATE_180.ordinal()] = 2;
        iArr11[ROTATE_DEGREE.ROTATE_270.ordinal()] = 3;
        int[] iArr12 = new int[C5NI.values().length];
        LJIIJJI = iArr12;
        iArr12[C5NI.VIDEO_OUT_RATIO_1_1.ordinal()] = 1;
        iArr12[C5NI.VIDEO_OUT_RATIO_4_3.ordinal()] = 2;
        iArr12[C5NI.VIDEO_OUT_RATIO_3_4.ordinal()] = 3;
        iArr12[C5NI.VIDEO_OUT_RATIO_16_9.ordinal()] = 4;
        iArr12[C5NI.VIDEO_OUT_RATIO_9_16.ordinal()] = 5;
        EnumC123864ta.values();
        EnumC123864ta.VIDEO.ordinal();
        EnumC123864ta.AUDIO.ordinal();
    }
}
