package X;

import android.util.Pair;
import com.bytedance.im.core.proto.AckMessageResponseBody;
import com.bytedance.im.core.proto.BatchDeleteConversationResponseBody;
import com.bytedance.im.core.proto.BatchGetConversationParticipantsReadIndexResponseBody;
import com.bytedance.im.core.proto.BatchGetMessagesResponseBody;
import com.bytedance.im.core.proto.BatchMarkConversationReadResponseBody;
import com.bytedance.im.core.proto.BatchUnmarkMessageResponseBody;
import com.bytedance.im.core.proto.BatchUpdateConversationParticipantResponseBody;
import com.bytedance.im.core.proto.BlockMembersResponseBody;
import com.bytedance.im.core.proto.BroadcastUserCounterResponseBody;
import com.bytedance.im.core.proto.CheckMessagesPerUserResponseBody;
import com.bytedance.im.core.proto.ConversationAddParticipantsResponseBody;
import com.bytedance.im.core.proto.ConversationMessagePreViewResponseBody;
import com.bytedance.im.core.proto.ConversationParticipantsListResponseBody;
import com.bytedance.im.core.proto.ConversationRemoveParticipantsResponseBody;
import com.bytedance.im.core.proto.CreateConversationV2ResponseBody;
import com.bytedance.im.core.proto.DeleteMultiStrangerConversationResponseBody;
import com.bytedance.im.core.proto.GetCmdMessageRespBody;
import com.bytedance.im.core.proto.GetConfigsResponseBody;
import com.bytedance.im.core.proto.GetConversationInfoListByFavoriteV2ResponseBody;
import com.bytedance.im.core.proto.GetConversationInfoListByTopV2ResponseBody;
import com.bytedance.im.core.proto.GetConversationInfoListV2ResponseBody;
import com.bytedance.im.core.proto.GetConversationInfoV2ResponseBody;
import com.bytedance.im.core.proto.GetConversationParticipantsMinIndexV3ResponseBody;
import com.bytedance.im.core.proto.GetConversationParticipantsReadIndexV3ResponseBody;
import com.bytedance.im.core.proto.GetConversationsCheckInfoResponseBody;
import com.bytedance.im.core.proto.GetConversationsCheckInfoV2ResponseBody;
import com.bytedance.im.core.proto.GetMessageByIdResponseBody;
import com.bytedance.im.core.proto.GetMessageInfoByIndexV2RangeResponseBody;
import com.bytedance.im.core.proto.GetMessageInfoByIndexV2ResponseBody;
import com.bytedance.im.core.proto.GetMessagesCheckInfoInConversationResponseBody;
import com.bytedance.im.core.proto.GetMessagesCheckInfoV2ResponseBody;
import com.bytedance.im.core.proto.GetMessagesResponseBody;
import com.bytedance.im.core.proto.GetRecentMessageRespBody;
import com.bytedance.im.core.proto.GetStrangerConversationListResponseBody;
import com.bytedance.im.core.proto.GetStrangerMessagesResponseBody;
import com.bytedance.im.core.proto.GetStrangerUnreadCountResponseBody;
import com.bytedance.im.core.proto.GetTicketResponseBody;
import com.bytedance.im.core.proto.GetUserConversationListResponseBody;
import com.bytedance.im.core.proto.InputStatusNotify;
import com.bytedance.im.core.proto.MarkConversationReadNotify;
import com.bytedance.im.core.proto.MarkMessageResponseBody;
import com.bytedance.im.core.proto.MarkMsgGetUnreadCountResponseBody;
import com.bytedance.im.core.proto.MarkMsgUnreadCountReportResponseBody;
import com.bytedance.im.core.proto.MarkMultiStrangerConversationReadResponseBody;
import com.bytedance.im.core.proto.MessageByInitResponseBody;
import com.bytedance.im.core.proto.MessagesInConversationResponseBody;
import com.bytedance.im.core.proto.MessagesPerUserComboInboxTypeResponseBody;
import com.bytedance.im.core.proto.MessagesPerUserInitComboInboxTypeResponseBody;
import com.bytedance.im.core.proto.MessagesPerUserInitV2ResponseBody;
import com.bytedance.im.core.proto.MessagesPerUserResponseBody;
import com.bytedance.im.core.proto.ModifyMessagePropertyResponseBody;
import com.bytedance.im.core.proto.NewDirectPushNotify;
import com.bytedance.im.core.proto.NewMessageNotify;
import com.bytedance.im.core.proto.PreviewerGetConversationInfoListResponseBody;
import com.bytedance.im.core.proto.PreviewerMessagesInConversationResponseBody;
import com.bytedance.im.core.proto.PullMarkMessageResponseBody;
import com.bytedance.im.core.proto.ResponseBody;
import com.bytedance.im.core.proto.SendInputStatusResponseBody;
import com.bytedance.im.core.proto.SendMessageResponseBody;
import com.bytedance.im.core.proto.SetConversationCoreInfoResponseBody;
import com.bytedance.im.core.proto.SetConversationSettingInfoResponseBody;
import com.bytedance.im.core.proto.StrangerNewMessageNotify;
import com.bytedance.im.core.proto.UnReadCountReportResponseBody;
import com.bytedance.im.core.proto.UpdateConversationParticipantResponseBody;
import com.bytedance.im.core.proto.UpsertConversationCoreExtInfoResponseBody;
import com.bytedance.im.core.proto.UpsertConversationSettingExtInfoResponseBody;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import java.util.HashMap;

/* renamed from: X.Z8w, reason: case insensitive filesystem */
/* loaded from: classes17.dex */
public final class C89454Z8w extends Message.Builder<ResponseBody, C89454Z8w> {
    public SendMessageResponseBody LIZLLL;
    public MessagesPerUserResponseBody LJ;
    public MessagesPerUserInitV2ResponseBody LJFF;
    public MessagesPerUserComboInboxTypeResponseBody LJI;
    public MessagesPerUserInitComboInboxTypeResponseBody LJII;
    public CheckMessagesPerUserResponseBody LJIIIIZZ;
    public GetMessageByIdResponseBody LJIIIZ;
    public MessagesInConversationResponseBody LJIIJ;
    public GetMessagesCheckInfoInConversationResponseBody LJIIJJI;
    public GetMessagesCheckInfoV2ResponseBody LJIIL;
    public RR0 LJIILIIL;
    public SendInputStatusResponseBody LJIILJJIL;
    public NewMessageNotify LJIILL;
    public MarkConversationReadNotify LJIILLIIL;
    public StrangerNewMessageNotify LJIIZILJ;
    public NewDirectPushNotify LJIJ;
    public InputStatusNotify LJIJI;
    public BatchMarkConversationReadResponseBody LJIJJ;
    public GetConversationsCheckInfoResponseBody LJIJJLI;
    public GetConversationsCheckInfoV2ResponseBody LJIL;
    public BatchDeleteConversationResponseBody LJJ;
    public GetConversationInfoV2ResponseBody LJJI;
    public CreateConversationV2ResponseBody LJJIFFI;
    public GetConversationInfoListV2ResponseBody LJJII;
    public GetConversationInfoListByFavoriteV2ResponseBody LJJIII;
    public GetConversationInfoListByTopV2ResponseBody LJJIIJ;
    public ConversationParticipantsListResponseBody LJJIIJZLJL;
    public ConversationAddParticipantsResponseBody LJJIIZ;
    public ConversationRemoveParticipantsResponseBody LJJIIZI;
    public UpdateConversationParticipantResponseBody LJJIJ;
    public BatchUpdateConversationParticipantResponseBody LJJIJIIJI;
    public C69533RQr LJJIJIIJIL;
    public ModifyMessagePropertyResponseBody LJJIJIL;
    public AckMessageResponseBody LJJIJL;
    public RQU LJJIJLIJ;
    public SetConversationCoreInfoResponseBody LJJIL;
    public UpsertConversationCoreExtInfoResponseBody LJJIZ;
    public SetConversationSettingInfoResponseBody LJJJ;
    public UpsertConversationSettingExtInfoResponseBody LJJJI;
    public GetStrangerConversationListResponseBody LJJJIL;
    public GetStrangerMessagesResponseBody LJJJJ;
    public C69536RQu LJJJJI;
    public C69530RQo LJJJJIZL;
    public C69527RQl LJJJJJ;
    public C69518RQc LJJJJJL;
    public RQZ LJJJJL;
    public GetStrangerUnreadCountResponseBody LJJJJLI;
    public DeleteMultiStrangerConversationResponseBody LJJJJLL;
    public MarkMultiStrangerConversationReadResponseBody LJJJJZ;
    public GetConversationParticipantsReadIndexV3ResponseBody LJJJJZI;
    public GetConversationParticipantsMinIndexV3ResponseBody LJJJLIIL;
    public GetTicketResponseBody LJJJLL;
    public GetUserConversationListResponseBody LJJJLZIJ;
    public BroadcastUserCounterResponseBody LJJJZ;
    public C69539RQx LJJL;
    public GetConfigsResponseBody LJJLI;
    public UnReadCountReportResponseBody LJJLIIIIJ;
    public BlockMembersResponseBody LJJLIIIJ;
    public C69521RQf LJJLIIIJILLIZJL;
    public GetMessageInfoByIndexV2ResponseBody LJJLIIIJJI;
    public MarkMessageResponseBody LJJLIIIJJIZ;
    public PullMarkMessageResponseBody LJJLIIIJL;
    public BatchGetConversationParticipantsReadIndexResponseBody LJJLIIIJLJLI;
    public GetRecentMessageRespBody LJJLIIIJLLLLLLLZ;
    public GetCmdMessageRespBody LJJLIIJ;
    public GetMessageInfoByIndexV2RangeResponseBody LJJLIL;
    public MessageByInitResponseBody LJJLJ;
    public PreviewerMessagesInConversationResponseBody LJJLJLI;
    public PreviewerGetConversationInfoListResponseBody LJJLL;
    public MarkMsgUnreadCountReportResponseBody LJJZ;
    public MarkMsgGetUnreadCountResponseBody LJJZZI;
    public BatchUnmarkMessageResponseBody LJJZZIII;
    public C69524RQi LJL;
    public ConversationMessagePreViewResponseBody LJLI;
    public GetMessagesResponseBody LJLIIIL;
    public BatchGetMessagesResponseBody LJLIIL;
    public HashMap<Integer, Pair<ProtoAdapter, Message>> LJLIL = new HashMap<>();
    public HashMap<String, Object> LJLILLLLZI = new HashMap<>();

    @Override // com.squareup.wire.Message.Builder
    /* renamed from: LIZIZ, reason: merged with bridge method [inline-methods] */
    public final ResponseBody build() {
        return new ResponseBody(this.LIZLLL, this.LJ, this.LJFF, this.LJI, this.LJII, this.LJIIIIZZ, this.LJIIIZ, this.LJIIJ, this.LJIIJJI, this.LJIIL, this.LJIILIIL, this.LJIILJJIL, this.LJIILL, this.LJIILLIIL, this.LJIIZILJ, this.LJIJ, this.LJIJI, this.LJIJJ, this.LJIJJLI, this.LJIL, this.LJJ, this.LJJI, this.LJJIFFI, this.LJJII, this.LJJIII, this.LJJIIJ, this.LJJIIJZLJL, this.LJJIIZ, this.LJJIIZI, this.LJJIJ, this.LJJIJIIJI, this.LJJIJIIJIL, this.LJJIJIL, this.LJJIJL, this.LJJIJLIJ, this.LJJIL, this.LJJIZ, this.LJJJ, this.LJJJI, this.LJJJIL, this.LJJJJ, this.LJJJJI, this.LJJJJIZL, this.LJJJJJ, this.LJJJJJL, this.LJJJJL, this.LJJJJLI, this.LJJJJLL, this.LJJJJZ, this.LJJJJZI, this.LJJJLIIL, this.LJJJLL, this.LJJJLZIJ, this.LJJJZ, this.LJJL, this.LJJLI, this.LJJLIIIIJ, this.LJJLIIIJ, this.LJJLIIIJILLIZJL, this.LJJLIIIJJI, this.LJJLIIIJJIZ, this.LJJLIIIJL, this.LJJLIIIJLJLI, this.LJJLIIIJLLLLLLLZ, this.LJJLIIJ, this.LJJLIL, this.LJJLJ, this.LJJLJLI, this.LJJLL, this.LJJZ, this.LJJZZI, this.LJJZZIII, this.LJL, this.LJLI, this.LJLIIIL, this.LJLIIL, this.LJLIL, this.LJLILLLLZI, buildUnknownFields());
    }
}
