package X;

import com.bytedance.ies.abmock.SettingsManager;
import com.ss.android.ugc.aweme.shortvideo.experiment.AutogeneratedCaptionLanguageSelection;

/* loaded from: classes7.dex */
public final class DU6 {
    static {
        new DU6();
    }

    public static final AutogeneratedCaptionLanguageSelection[] LIZ() {
        Object LIZ;
        try {
            LIZ = (AutogeneratedCaptionLanguageSelection[]) SettingsManager.LIZLLL().LJIIIIZZ("fixed_caption_creator_language_list", AutogeneratedCaptionLanguageSelection[].class, null);
            C3C5.m7constructorimpl(LIZ);
        } catch (Throwable th) {
            LIZ = C141335gf.LIZ(th);
            C3C5.m7constructorimpl(LIZ);
        }
        AutogeneratedCaptionLanguageSelection[] autogeneratedCaptionLanguageSelectionArr = (AutogeneratedCaptionLanguageSelection[]) (C3C5.m12isFailureimpl(LIZ) ? null : LIZ);
        if (autogeneratedCaptionLanguageSelectionArr == null) {
            return new AutogeneratedCaptionLanguageSelection[0];
        }
        return autogeneratedCaptionLanguageSelectionArr;
    }
}
