package X;

/* renamed from: X.WsI, reason: case insensitive filesystem */
/* loaded from: classes15.dex */
public enum EnumC83650WsI implements InterfaceC83714WtK {
    CLOSE_CAMERA_CONTROLLER_ON_DESTROY,
    CLOSE_CAMERA_COMPONENT_ON_DESTROY,
    CLOSE_CAMERA_SURFACE_DESTROY,
    CLOSE_CAMERA_VIEW_ON_STOP,
    CLOSE_CAMERA_COMPONENT_ON_STOP,
    CLOSE_CAMERA_ADD_STREAM,
    CLOSE_CAMERA_ON_PAUSE,
    CLOSE_CAMERA_ON_STOP_CAMERA_LOGIC,
    CLOSE_CAMERA_ON_SURFACE_DESTROY,
    CLOSE_CAMERA_ON_TEXTURE_DESTROY,
    STOP_AUDIO_ON_PAUSE,
    STOP_AUDIO_USING_SOUND_EFFECT,
    STOP_AUDIO_CANCEL_SOUND_EFFECT,
    STOP_AUDIO_SOUND_EFFECT_STOP,
    STOP_AUDIO_CAPTURE_WITH_DISABLE,
    STOP_AUDIO_CAPTURE_WITH_ENABLE,
    STOP_AUDIO_CAMERA_LOGIC_PAUSE,
    STOP_AUDIO_CAMERA_CLOSE,
    STOP_AUDIO_RELEASE_CAMERA_CLOSE;

    public static EnumC83650WsI valueOf(String str) {
        return (EnumC83650WsI) V0N.LJJJ(EnumC83650WsI.class, str);
    }
}
