package X;

/* renamed from: X.V8n, reason: case insensitive filesystem */
/* loaded from: classes14.dex */
public enum EnumC79253V8n {
    READ_DECODE,
    READ_FILE,
    READ_FILE_NOT_FOUND,
    READ_INVALID_ENTRY,
    WRITE_ENCODE,
    WRITE_CREATE_TEMPFILE,
    WRITE_UPDATE_FILE_NOT_FOUND,
    WRITE_RENAME_FILE_TEMPFILE_NOT_FOUND,
    WRITE_RENAME_FILE_TEMPFILE_PARENT_NOT_FOUND,
    WRITE_RENAME_FILE_OTHER,
    WRITE_CREATE_DIR,
    WRITE_CALLBACK_ERROR,
    WRITE_INVALID_ENTRY,
    DELETE_FILE,
    EVICTION,
    GENERIC_IO,
    OTHER
}
