package X;

/* renamed from: X.XlI, reason: case insensitive filesystem */
/* loaded from: classes16.dex */
public enum EnumC85764XlI {
    PASSKEY_REGISTRATION_JSON_EXCEPTION(-1000),
    PASSKEY_REGISTRATION_DEFAULT_EXCEPTION(-1001),
    PASSKEY_REGISTRATION_CANCELLATION_EXCEPTION(-1002),
    PASSKEY_REGISTRATION_NO_CREATE_OPTION_EXCEPTION(-1003),
    PASSKEY_REGISTRATION_UNSUPPORTED_EXCEPTION(-1004),
    PASSKEY_REGISTRATION_INTERRUPTED_EXCEPTION(-1005),
    PASSKEY_REGISTRATION_PROVIDER_CONFIGURATION_EXCEPTION(-1006),
    PASSKEY_REGISTRATION_UNKNOWN_EXCEPTION(-1007),
    PASSKEY_REGISTRATION_CUSTOM_EXCEPTION(-1008),
    PASSKEY_REGISTRATION_NOT_ON_PROFILE(-1009),
    PASSKEY_REGISTRATION_DISMISS_RECREATION_POP_UP(-1010),
    PASSKEY_REGISTRATION_ILLEGAL_ARGUMENT(-1011),
    PASSKEY_REGISTRATION_NULL_POINTER(-1012);

    public final int LJLIL;

    public static EnumC85764XlI valueOf(String str) {
        return (EnumC85764XlI) V0N.LJJJ(EnumC85764XlI.class, str);
    }

    public final int getErrorCode() {
        return this.LJLIL;
    }

    EnumC85764XlI(int i) {
        this.LJLIL = i;
    }
}
