package X;

/* renamed from: X.ItB, reason: case insensitive filesystem */
/* loaded from: classes9.dex */
public enum EnumC48033ItB {
    VIDEOEVENT_CUSTOM_INFO_FFTIME_CLICK,
    VIDEOEVENT_CUSTOM_INFO_FFTIME_VIDEOMODEL,
    VIDEOEVENT_CUSTOM_INFO_FFTIME_CUSTOMPLAY,
    VIDEOEVENT_CUSTOM_INFO_FFTIME_INITENGINE,
    VIDEOEVENT_CUSTOM_INFO_FFTIME_PLAYENGINE,
    VIDEOEVENT_CUSTOM_INFO_CAST_OBJECT,
    VIDEOEVENT_CUSTOM_INFO_OTT_PLUGIN_VERSION,
    VIDEOEVENT_CUSTOM_INFO_COMPANY_ID,
    VIDEOEVENT_CUSTOM_INFO_CUSTOM_PLAY_SESSION_ID;

    public static EnumC48033ItB valueOf(String str) {
        return (EnumC48033ItB) V0N.LJJJ(EnumC48033ItB.class, str);
    }
}
