package X;

/* renamed from: X.4zQ, reason: invalid class name and case insensitive filesystem */
/* loaded from: classes3.dex */
public enum EnumC127484zQ {
    ENABLE_LOG,
    ENABLE_DRAFT_BOX,
    IS_DEFAULT_SAVE_IN_ALBUM,
    IS_LOOP_PLAY_VIDEO,
    FREEZE_FRAME_TIME,
    PICTURE_TRACK_TIME,
    ENABLE_EFFECT_AMAZING,
    EFFECT_APPLY_GLOBAL,
    FILE_PROVIDER_AUTHORITY,
    CUSTOM_CANVAS_RATIO_LIST,
    FIXED_CANVAS_RATIO,
    WATER_MARK_PATH,
    ENABLE_LOCAL_STICKER,
    ENABLE_RECORDING_CHANGE_VOICE,
    DEFAULT_EDIT_MODE,
    ENABLE_CLICK_WHEN_DISABLE_FUNCTION_ITEM,
    MAX_EDIT_VIDEO_LIMIT_TIME_MILLIS,
    VIDEO_CLIP_MIN_DURATION,
    MAX_PIP_TRACK_COUNT,
    ENABLE_TRACK_LABEL_SCROLLABLE,
    ENABLE_TRACK_LINKAGE,
    ENABLE_SUBTRACK_OVER_MAIN,
    ENABLE_OPERATE_CAUSE_BLACK_SLOT,
    ENABLE_BLACK_SLOT_OPERATE,
    IMPORT_LIMIT,
    PLUGIN_MODE,
    ENABLE_TEMPLATE_MODE,
    ENABLE_EFFECT,
    ENABLE_MENU_HIERARCHY_OPTIMIZATION,
    ENABLE_SUBTRACK_UX_OPTIMIZATION,
    ENABLE_TRANSITION_ANIM_ON_BOTTOM_MENU,
    ENABLE_NLE_COMPOSER_FOR_EFFECT,
    ENABLE_VOLUME_ADJUST_OPTIMIZATION,
    VOLUME_DB_RANGE,
    VOLUME_DEFAULT,
    ENABLE_KEY_FRAME,
    ENABLE_VIDEO_TRANSITION,
    ENABLE_AUTO_ALIGN_BGM,
    ENABLE_NEW_ROUND_CORNER_UX_OPTIMIZATION,
    ENABLE_EDIT_PAGE_FRAMEWORK_MERGENCE,
    ENABLE_VE_HOT_UPDATE_EXPERIMENT,
    ENABLE_CHANGE_ADD_SOUND_LOGIC;

    public static EnumC127484zQ valueOf(String str) {
        return (EnumC127484zQ) V0N.LJJJ(EnumC127484zQ.class, str);
    }
}
