package X;

/* renamed from: X.8Of, reason: invalid class name and case insensitive filesystem */
/* loaded from: classes4.dex */
public enum EnumC210578Of {
    FEED_BOTTOM_BTN_CONTAINER,
    FEED_INFO_ABOVE_ANCHOR_AREA_CONTAINER,
    FEED_INFO_AREA_CONTAINER,
    FEED_INFO_BELOW_MUSIC_TITLE_CONTAINER,
    FEED_INFO_TAG_AREA_CONTAINER,
    FEED_INTERACTION_AREA_CONTAINER,
    VIDEO_TAG_CONTAINER,
    INTERACT_AREA_COMPONENT,
    INTEARCT_RIGHT_AREA_COMPONENT,
    INTEARCT_INFO_AREA_COMPONENT,
    INTERACT_BOTTOM_AREA_COMPONENT,
    INTERACT_INFO_BOTTOM_AREA_COMPONENT,
    INTERACT_BOTTOM_BANNER_COMPONENT,
    CELL_FULL_SCREEN_COMPONENT,
    LANDSCAPE_INTERACT_ENTRANCES_CONTAINER,
    SEARCH_DETAIL_FILTER_COMPONENT;

    public static EnumC210578Of valueOf(String str) {
        return (EnumC210578Of) V0N.LJJJ(EnumC210578Of.class, str);
    }
}
