package X;

import com.bytedance.android.livesdk.livesetting.broadcast.LiveTryModeCountDownThresholdSetting;
import com.bytedance.android.livesdk.livesetting.level.UserLevelGeckoUpdateSetting;
import java.util.HashMap;

/* renamed from: X.CYe, reason: case insensitive filesystem */
/* loaded from: classes6.dex */
public enum EnumC31508CYe {
    CHAT(EnumC31509CYf.CHAT.getWsMethod(), 0),
    EMOTE_CHAT(EnumC31509CYf.EMOTE_CHAT.getWsMethod(), 1),
    DONATION_INFO(EnumC31509CYf.DONATION_INFO.getWsMethod(), 2),
    CONTROL(EnumC31509CYf.CONTROL.getWsMethod(), 3),
    DIGG(EnumC31509CYf.DIGG.getWsMethod(), 4),
    LIKE(EnumC31509CYf.LIKE.getWsMethod(), 5),
    GIFT(EnumC31509CYf.GIFT.getWsMethod(), 6),
    MEMBER(EnumC31509CYf.MEMBER.getWsMethod(), 7),
    ROOM(EnumC31509CYf.ROOM.getWsMethod(), 8),
    SOCIAL(EnumC31509CYf.SOCIAL.getWsMethod(), 9),
    SCREEN(EnumC31509CYf.SCREEN.getWsMethod(), 10),
    ROOM_NOTIFY(EnumC31509CYf.ROOM_NOTIFY.getWsMethod(), 11),
    REMIND(EnumC31509CYf.REMIND.getWsMethod(), 12),
    MODIFY_DECORATION(EnumC31509CYf.MODIFY_DECORATION.getWsMethod(), 13),
    MODIFY_STICKER(EnumC31509CYf.MODIFY_STICKER.getWsMethod(), 14),
    ROOM_PUSH(EnumC31509CYf.ROOM_PUSH.getWsMethod(), 15),
    USER_STATS(EnumC31509CYf.USER_STATS.getWsMethod(), 16),
    IN_ROOM_BANNER(EnumC31509CYf.IN_ROOM_BANNER_MESSAGE.getWsMethod(), 17),
    ROOM_RICH_CHAT(EnumC31509CYf.ROOM_RICH_CHAT_MESSAGE.getWsMethod(), 18),
    LINK_MIC(EnumC31509CYf.LINK_MIC.getWsMethod(), 19),
    LINK_MIC_AD_MESSAGE(EnumC31509CYf.LINK_MIC_AD_MESSAGE.getWsMethod(), 20),
    LINK_STATE_MESSAGE(EnumC31509CYf.LINK_STATE_MESSAGE.getWsMethod(), 21),
    BASE_LINK_LAYER_MESSAGE(EnumC31509CYf.BASE_LINK_LAYER_MESSAGE.getWsMethod(), 22),
    LINK_MESSAGE(EnumC31509CYf.LINK_MESSAGE.getWsMethod(), 23),
    WISH_LIST_MESSAGE(EnumC31509CYf.WISH_LIST_UPDATE_MESSAGE.getWsMethod(), 24),
    BOTTOM_MESSAGE(EnumC31509CYf.BOTTOM_MESSAGE.getWsMethod(), 25),
    LINK_MIC_SIGNAL(EnumC31509CYf.LINK_MIC_SIGNAL.getWsMethod(), 26),
    BANNER_UPDATE(EnumC31509CYf.BANNER_UPDATE.getWsMethod(), 27),
    LINK_MIC_BATTLE(EnumC31509CYf.LINK_MIC_BATTLE.getWsMethod(), 28),
    LINK_MIC_BATTLE_ARMIES(EnumC31509CYf.LINK_MIC_BATTLE_ARMIES.getWsMethod(), 29),
    LINK_MIC_BATTLE_PUNISH_FINISH(EnumC31509CYf.LINK_MIC_BATTLE_PUNISH_FINISH.getWsMethod(), 30),
    LINK_MIC_BATTLE_ITEM_CARD(EnumC31509CYf.LINK_MIC_BATTLE_ITEM_CARD.getWsMethod(), 31),
    LINK_MIC_BATTLE_NOTICE(EnumC31509CYf.LINK_MIC_BATTLE_NOTICE.getWsMethod(), 32),
    LINK_MIC_BATTLE_TASK(EnumC31509CYf.LINK_MIC_BATTLE_TASK.getWsMethod(), 33),
    LINK_CO_HOST_GUIDE(EnumC31509CYf.LINK_CO_HOST_GUIDE.getWsMethod(), 34),
    COHOST_RESERVE_MESSAGE(EnumC31509CYf.COHOST_RESERVE_MESSAGE.getWsMethod(), 35),
    COHOST_TOPIC_MESSAGE(EnumC31509CYf.COHOST_TOPIC_MESSAGE.getWsMethod(), 36),
    BA_LEAD_GEN(EnumC31509CYf.BA_LEAD_GEN.getWsMethod(), 37),
    LINK_AUDIENCE_GUIDE(EnumC31509CYf.LINK_AUDIENCE_NOTICE.getWsMethod(), 38),
    HASHTAG(EnumC31509CYf.HASHTAG.getWsMethod(), 39),
    GIFT_UPDATE(EnumC31509CYf.GIFT_UPDATE.getWsMethod(), 40),
    COMMON_TOAST(EnumC31509CYf.COMMON_TOAST.getWsMethod(), 41),
    COMMENT_IMAGE(EnumC31509CYf.COMMENT_IMAGE.getWsMethod(), 42),
    USER_SEQ(EnumC31509CYf.USER_SEQ.getWsMethod(), 43),
    ROOM_VERIFY(EnumC31509CYf.ROOM_VERIFY.getWsMethod(), 44),
    GOODS_ORDER(EnumC31509CYf.GOODS_ORDER.getWsMethod(), 45),
    GUIDE_MESSAGE(EnumC31509CYf.GUIDE_MESSAGE.getWsMethod(), 46),
    ASSET_MESSAGE(EnumC31509CYf.ASSET_MESSAGE.getWsMethod(), 47),
    AUDIENCE_RESERVE_USER_STATE_MESSAGE(EnumC31509CYf.AUDIENCE_RESERVE_USER_STATE_MESSAGE.getWsMethod(), 48),
    D_H5_Message(EnumC31509CYf.D_H5_MESSAGE.getWsMethod(), 49),
    PORTAL_MESSAGE(EnumC31509CYf.PORTAL_MESSAGE.getWsMethod(), 50),
    POPULAR_CARD_MESSAGE(EnumC31509CYf.POPULAR_CARD_MESSAGE.getWsMethod(), 51),
    COMMON_POPUP_MESSAGE(EnumC31509CYf.COMMON_POPUP_MESSAGE.getWsMethod(), 52),
    IN_ROOM_BANNER_REFRESH(EnumC31509CYf.IN_ROOM_BANNER_REFRESH_MESSAGE.getWsMethod(), 53),
    SHARE_GUIDE_MESSAGE(EnumC31509CYf.SHARE_GUIDE_MESSAGE.getWsMethod(), 54),
    HOURLY_RANK_REWARD_MESSAGE(EnumC31509CYf.HOURLY_RANK_REWARD_MESSAGE.getWsMethod(), 55),
    OFFICIAL_CHANNEL_ANCHOR_MESSAGE(EnumC31509CYf.OFFICIAL_CHANNEL_ANCHOR_MESSAGE.getWsMethod(), 56),
    OFFICIAL_CHANNEL_MODIFY_MESSAGE(EnumC31509CYf.OFFICIAL_CHANNEL_MODIFY_MESSAGE.getWsMethod(), 57),
    OFFICIAL_CHANNEL_USER_MESSAGE(EnumC31509CYf.OFFICIAL_CHANNEL_USER_MESSAGE.getWsMethod(), 58),
    TRAY_MESSAGE(EnumC31509CYf.TRAY_MESSAGE.getWsMethod(), 59),
    QUESTION(EnumC31509CYf.QUESTION.getWsMethod(), 60),
    QUESTION_DELETE_MESSAGE(EnumC31509CYf.QUESTION_DELETE_MESSAGE.getWsMethod(), 61),
    QUESTION_SELECT_MESSAGE(EnumC31509CYf.QUESTION_SELECT_MESSAGE.getWsMethod(), 62),
    QUESTION_SLIDE_DOWN_MESSAGE(EnumC31509CYf.QUESTION_SLIDE_DOWN_MESSAGE.getWsMethod(), 63),
    QUESTION_SWITCH_MESSAGE(EnumC31509CYf.QUESTION_SWITCH_MESSAGE.getWsMethod(), 64),
    REALTIME_LIVE_CENTER_METHOD(EnumC31509CYf.REALTIME_LIVE_CENTER_METHOD.getWsMethod(), 65),
    BARRAGE_MESSAGE(EnumC31509CYf.BARRAGE_MESSAGE.getWsMethod(), 66),
    EC_BARRAGE_MESSAGE(EnumC31509CYf.EC_BARRAGE_MESSAGE.getWsMethod(), 67),
    MSG_DETECT_MESSAGE(EnumC31509CYf.MSG_DETECT_MESSAGE.getWsMethod(), 68),
    RANK_TOAST_MESSAGE(EnumC31509CYf.RANK_TOAST_MESSAGE.getWsMethod(), 69),
    GIFT_GUIDE_MESSAGE(EnumC31509CYf.GIFT_GUIDE_MESSAGE.getWsMethod(), 70),
    MARQUEE_ANNOUNCEMENT_MESSAGE(EnumC31509CYf.MARQUEE_ANNOUNCEMENT_MESSAGE.getWsMethod(), 71),
    WEEKLY_RANK_REWARD_MESSAGE(EnumC31509CYf.WEEKLY_RANK_REWARD_MESSAGE.getWsMethod(), 72),
    IM_DELETE_MESSAGE(EnumC31509CYf.IM_DELETE.getWsMethod(), 73),
    GIFT_GLOBAL_MESSAGE(EnumC31509CYf.GIFT_GLOBAL_MESSAGE.getWsMethod(), 74),
    RED_ENVELOPE_MESSAGE(EnumC31509CYf.RED_ENVELOPE_MESSAGE.getWsMethod(), 75),
    GOODY_BAG_MESSAGE(EnumC31509CYf.GOODY_BAG_MESSAGE.getWsMethod(), 76),
    LIVE_INTRO_MESSAGE(EnumC31509CYf.LIVE_INTRO_MESSAGE.getWsMethod(), 77),
    LIVE_UNAUTHORIZED_MEMBER_MESSAGE(EnumC31509CYf.LIVE_UNAUTHORIZED_MEMBER_MESSAGE.getWsMethod(), 78),
    LIVE_POLL_MESSAGE(EnumC31509CYf.LIVE_POLL_MESSAGE.getWsMethod(), 79),
    LIVE_EVENT_MESSAGE(EnumC31509CYf.LIVE_EVENT_MESSAGE.getWsMethod(), 80),
    LIVE_DRAW_GUESS_START(EnumC31509CYf.DRAW_GUESS_START_MESSAGE.getWsMethod(), 81),
    LIVE_DRAW_GUESS_END(EnumC31509CYf.DRAW_GUESS_END_MESSAGE.getWsMethod(), 82),
    LIVE_DRAW_GUESS_EXIT(EnumC31509CYf.DRAW_GUESS_EXIT_MESSAGE.getWsMethod(), 83),
    LIVE_DRAW_GUESS_UPDATE(EnumC31509CYf.DRAW_GUESS_UPDATE_MESSAGE.getWsMethod(), 84),
    SUBSCRIBE_NOTIFY_MESSAGE(EnumC31509CYf.SUB_NOTIFY_MESSAGE.getWsMethod(), 85),
    GIFT_BOOST_CARD_MESSAGE(EnumC31509CYf.GIFT_BOOST_CARD_MESSAGE.getWsMethod(), 86),
    GIFT_UNLOCK_MESSAGE(EnumC31509CYf.GIFT_UNLOCK_MESSAGE.getWsMethod(), 87),
    RANK_UPDATE_MESSAGE(EnumC31509CYf.RANK_UPDATE_MESSAGE.getWsMethod(), 88),
    STREAM_GOAL_SERVER_MESSAGE(EnumC31509CYf.STREAM_GOAL_SERVER_MESSAGE.getWsMethod(), 89),
    HIGHLIGHT_FRAGMENT_READY_MESSAGE(EnumC31509CYf.HIGHLIGHT_FRAGMENT_READY_MESSAGE.getWsMethod(), 90),
    RANK_TEXT_MESSAGE(EnumC31509CYf.RANK_TEXT_MESSAGE.getWsMethod(), 91),
    SUBSCRIPTION_GUIDE_MESSAGE(EnumC31509CYf.SUBSCRIPTION_GUIDE_MESSAGE.getWsMethod(), 92),
    SUB_TIMER_STICKER_MESSAGE(EnumC31509CYf.SUB_TIMER_STICKER_MESSAGE.getWsMethod(), 93),
    SUB_WAVE_MESSAGE(EnumC31509CYf.SUB_WAVE_MESSAGE.getWsMethod(), 94),
    ACCESS_RECALL_MESSAGE(EnumC31509CYf.ACCESS_RECALL_MESSAGE.getWsMethod(), 95),
    GIFT_COLLECTION_UPDATE_MESSAGE(EnumC31509CYf.GIFT_COLLECTION_UPDATE_MESSAGE.getWsMethod(), 96),
    PERCEPTION_MESSAGE(EnumC31509CYf.PERCEPTION_MESSAGE.getWsMethod(), 97),
    BA_LINK_FULL_MESSAGE(EnumC31509CYf.BA_LINK_FULL_MESSAGE.getWsMethod(), 98),
    OEC_LIVE_SHOPPING_MESSAGE(EnumC31509CYf.OEC_LIVE_SHOPPING_MESSAGE.getWsMethod(), 99),
    EC_SHORT_ITEM_REFRESH_MESSAGE(EnumC31509CYf.EC_SHORT_ITEM_REFRESH_MESSAGE.getWsMethod(), 100),
    EC_TASK_REFRESH_COUPON_LIST_MESSAGE(EnumC31509CYf.EC_TASK_REFRESH_COUPON_LIST_MESSAGE.getWsMethod(), 101),
    EC_DRAW_MESSAGE(EnumC31509CYf.EC_DRAW_MESSAGE.getWsMethod(), 102),
    EC_TASK_REGISTER_MESSAGE(EnumC31509CYf.EC_TASK_REGISTER_MESSAGE.getWsMethod(), 103),
    PIN_MESSAGE(EnumC31509CYf.PIN_MESSAGE.getWsMethod(), 104),
    GIFT_PROMPT_MESSAGE(EnumC31509CYf.GIFT_PROMPT_MESSAGE.getWsMethod(), 105),
    OPERATE_TOAST_MESSAGE(EnumC31509CYf.OPERATE_TOAST_MESSAGE.getWsMethod(), 106),
    ENVELOPE_PORTAL_MESSAGE(EnumC31509CYf.ENVELOPE_PORTAL_MESSAGE.getWsMethod(), 107),
    MODERATOR_OPERATE_MESSAGE(EnumC31509CYf.MODERATOR_OPERATE_MESSAGE.getWsMethod(), 108),
    LINK_MIC_BATTLE_VICTORY_LAP_MESSAGE(EnumC31509CYf.LINK_MIC_BATTLE_VICTORY_LAP_MESSAGE.getWsMethod(), 109),
    ANCHOR_TOOL_MODIFICATION_MESSAGE(EnumC31509CYf.ANCHOR_TOOL_MODIFICATION_MESSAGE.getWsMethod(), 110),
    GIFT_NOTICE_MESSAGE(EnumC31509CYf.GIFT_NOTICE_MESSAGE.getWsMethod(), 111),
    FOLLOW_CARD_MESSAGE(EnumC31509CYf.FOLLOW_CARD_MESSAGE.getWsMethod(), 112),
    PARTNERSHIP_CARD_CHANGE_MESSAGE(EnumC31509CYf.PARTNERSHIP_CARD_CHANGE_MESSAGE.getWsMethod(), 113),
    PARTNERSHIP_DOWNLOAD_COUNT_MESSAGE(EnumC31509CYf.PARTNERSHIP_DOWNLOAD_COUNT_MESSAGE.getWsMethod(), 114),
    CAPSULE_MESSAGE(EnumC31509CYf.CAPSULE_MESSAGE.getWsMethod(), 115),
    CAPTION_TEXT_MESSAGE(EnumC31509CYf.CAPTION_MESSAGE.getWsMethod(), 116),
    ACTIVITY_QUIZ_USER_IDENTITY_MESSAGE(EnumC31509CYf.ACTIVITY_QUIZ_USER_IDENTITY_MESSAGE.getWsMethod(), 117),
    ACTIVITY_QUIZ_CARD_MESSAGE(EnumC31509CYf.ACTIVITY_QUIZ_CARD_MESSAGE.getWsMethod(), 118),
    USER_LEVEL_UPGRADE_MESSAGE(EnumC31509CYf.UPGRADE_MESSAGE.getWsMethod(), 119),
    QUICK_CHAT_LIST_MESSAGE(EnumC31509CYf.QUICK_CHAT_LIST_MESSAGE.getWsMethod(), LiveTryModeCountDownThresholdSetting.DEFAULT),
    PARTNERSHIP_GAME_OFFLINE_MESSAGE(EnumC31509CYf.PARTNERSHIP_GAME_OFFLINE_MESSAGE.getWsMethod(), 121),
    PARTNERSHIP_PUNISH_MESSAGE(EnumC31509CYf.PARTNERSHIP_PUNISH_MESSAGE.getWsMethod(), 122),
    PARTNERSHIP_TASK_SHOW_MESSAGE(EnumC31509CYf.PARTNERSHIP_TASK_SHOW_MESSAGE.getWsMethod(), 123),
    PARTNERSHIP_DROPS_UPDATE_MESSAGE(EnumC31509CYf.PARTNERSHIP_DROPS_UPDATE_MESSAGE.getWsMethod(), 124),
    GAME_RANK_LIST_NOTIFY_MSG(EnumC31509CYf.GAME_RANK_NOTIFY_MESSAGE.getWsMethod(), 125),
    LINK_SCREEN_CHANGE_MESSAGE(EnumC31509CYf.LINK_SCREEN_CHANGE_MESSAGE.getWsMethod(), 126),
    LINK_MIC_FAN_TICKET_NOTICE_MESSAGE(EnumC31509CYf.LINK_MIC_FAN_TICKET_METHOD.getWsMethod(), 127),
    ACCESS_CONTROL_MESSAGE(EnumC31509CYf.ACCESS_CONTROL_MESSAGE.getWsMethod(), 128),
    FANS_EVENT_MESSAGE(EnumC31509CYf.FANS_EVENT_MESSAGE.getWsMethod(), 129),
    PAID_CONTENT_LIVE_SHOPPING_MESSAGE(EnumC31509CYf.PAID_CONTENT_LIVE_SHOPPING_MESSAGE.getWsMethod(), 130),
    GAME_OCR_PING_MESSAGE(EnumC31509CYf.GAME_O_C_R_PING_MESSAGE.getWsMethod(), 131),
    SUB_PIN_EVENT_MESSAGE(EnumC31509CYf.SUB_PIN_EVENT_MESSAGE.getWsMethod(), 132),
    LIVE_SHOW_MESSAGE(EnumC31509CYf.LIVE_SHOW_MESSAGE.getWsMethod(), 133),
    EFFECT_PRELOADING_MESSAGE(EnumC31509CYf.EFFECT_PRELOADING_MESSAGE.getWsMethod(), 134),
    COMMENT_TRAY(EnumC31509CYf.COMMENT_TRAY_MESSAGE.getWsMethod(), 135),
    KARAOKE_QUEUE_MESSAGE(EnumC31509CYf.KARAOKE_QUEUE_MESSAGE.getWsMethod(), 136),
    KARAOKE_SWITCH_MESSAGE(EnumC31509CYf.KARAOKE_SWITCH_MESSAGE.getWsMethod(), 137),
    KARAOKE_REQ_MESSAGE(EnumC31509CYf.KARAOKE_REQ_MESSAGE.getWsMethod(), 138),
    STAR_COMMENT_PUSH_MESSAGE(EnumC31509CYf.STAR_COMMENT_PUSH_MESSAGE.getWsMethod(), 139),
    STAR_COMMENT_NOTIFICATION_MESSAGE(EnumC31509CYf.STAR_COMMENT_NOTIFICATION_MESSAGE.getWsMethod(), UserLevelGeckoUpdateSetting.DEFAULT),
    NEW_ANCHOR_GUIDE_MESSAGE(EnumC31509CYf.NEW_ANCHOR_GUIDE_MESSAGE.getWsMethod(), 141),
    GREETING_MESSAGE(EnumC31509CYf.GREETING_MESSAGE.getWsMethod(), 142);

    public static final HashMap<String, EnumC31508CYe> LJLJJI = new HashMap<>();
    public final String LJLIL;
    public final Class<? extends CR6> LJLILLLLZI;
    public CR6 LJLJI;

    static {
        for (EnumC31508CYe enumC31508CYe : values()) {
            LJLJJI.put(enumC31508CYe.LJLIL, enumC31508CYe);
        }
    }

    public static Class<? extends CR6> getMessageClass(String str) {
        HashMap<String, EnumC31508CYe> hashMap = LJLJJI;
        if (hashMap.containsKey(str)) {
            return hashMap.get(str).LJLILLLLZI;
        }
        return null;
    }

    public static CR6 getMessageObject(String str) {
        EnumC31508CYe enumC31508CYe = LJLJJI.get(str);
        if (enumC31508CYe == null) {
            return null;
        }
        if (enumC31508CYe.LJLJI == null) {
            try {
                enumC31508CYe.LJLJI = enumC31508CYe.LJLILLLLZI.newInstance();
            } catch (IllegalAccessException | InstantiationException unused) {
            }
        }
        return enumC31508CYe.LJLJI;
    }

    public static EnumC31508CYe valueOf(String str) {
        return (EnumC31508CYe) V0N.LJJJ(EnumC31508CYe.class, str);
    }

    EnumC31508CYe(String str, int i) {
        this.LJLIL = str;
        this.LJLILLLLZI = r1;
    }
}
