package X;

import com.ss.android.ugc.aweme.shortvideo.ui.AutogeneratedCaptionLanguageSelectionFragment;

/* loaded from: classes8.dex */
public final class G95 implements InterfaceC252739vx {
    public final /* synthetic */ AutogeneratedCaptionLanguageSelectionFragment LIZ;

    @Override // X.InterfaceC252739vx
    public final void LIZ() {
        ASQ.LJ(this.LIZ, ASY.LIZ);
    }

    public G95(AutogeneratedCaptionLanguageSelectionFragment autogeneratedCaptionLanguageSelectionFragment) {
        this.LIZ = autogeneratedCaptionLanguageSelectionFragment;
    }
}
