package X;

import defpackage.q;
import kotlin.jvm.internal.o;

/* loaded from: classes8.dex */
public final class G98 {
    public final String LIZ;
    public final String LIZIZ;

    public final boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (!(obj instanceof G98)) {
            return false;
        }
        G98 g98 = (G98) obj;
        return o.LJ(this.LIZ, g98.LIZ) && o.LJ(this.LIZIZ, g98.LIZIZ);
    }

    public final int hashCode() {
        return this.LIZIZ.hashCode() + (this.LIZ.hashCode() * 31);
    }

    public final String toString() {
        StringBuilder LIZ = X1D.LIZ();
        LIZ.append("AutogeneratedCaptionLanguageItem(languageCode=");
        LIZ.append(this.LIZ);
        LIZ.append(", languageName=");
        return q.LIZIZ(LIZ, this.LIZIZ, ')', LIZ);
    }

    public G98(String languageCode, String languageName) {
        o.LJIIIZ(languageCode, "languageCode");
        o.LJIIIZ(languageName, "languageName");
        this.LIZ = languageCode;
        this.LIZIZ = languageName;
    }
}
