package X;

/* loaded from: classes8.dex */
public enum H1U {
    PUBLISH,
    COMPILE,
    WAIT_CLICK_PUBLISH,
    UPLOAD,
    AUTH_KEY,
    ORIGINAL_FRAME_UPLOAD,
    COVER_TEXT_UPLOAD,
    ADD_EFFECT_WATERMARK,
    CACHE_CLEAN,
    CREATE_AWEME,
    EDIT_POST,
    SAVE_IMAGE,
    SAVE_LOCAL,
    MOBILE_EFFECT_UPLOAD,
    REPLACE_LOCAL_IMAGE,
    COVER_EXTRACT,
    WAIT_UPLOAD_PARAM,
    UGC_TEMPLATE_UPLOAD,
    AUTOCUT_TEMPLATE_UPLOAD,
    VE_CODEC_DOWNLOAD,
    PUGC_TEMPLATE_UPLOAD,
    PUGC_TEMPLATE_BINDING,
    VE_BYTEVC1_PLUGIN_LOAD,
    UPDATE_AIGC_INFO_BEFORE_SAVE_LOCAL,
    CLOUD_MERGE,
    QUICK_FORWARD_PUBLISH_LOCK,
    QUICK_FORWARD_RES_RESTORE;

    public static H1U valueOf(String str) {
        return (H1U) V0N.LJJJ(H1U.class, str);
    }
}
