package X;

import com.bytedance.android.livesdk.chatroom.model.multilive.MultiLiveAnchorPanelSettings;
import com.bytedance.android.livesdk.gift.model.CpcPromptResponse;
import com.bytedance.android.livesdk.livesetting.broadcast.LiveBGMDefaultVolumeSetting;
import com.bytedance.android.livesdk.livesetting.broadcast.LiveBgMusicDefaultVolumeSetting;
import com.bytedance.android.livesdk.livesetting.performance.LiveGiftNewGifterBadgeSetting;
import com.bytedance.android.livesdk.livesetting.watchlive.LivePipDefaultOpenSetting;
import com.bytedance.android.livesdk.model.LiveEffectAutoRestoreConfig;
import com.bytedance.android.livesdkapi.host.IHostUser;
import com.google.gson.m;
import com.ss.android.ugc.aweme.feed.model.CardStruct;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.concurrent.CopyOnWriteArraySet;

/* renamed from: X.Bx8, reason: case insensitive filesystem */
/* loaded from: classes6.dex */
public interface InterfaceC30442Bx8 {
    public static final C48459J0d<Boolean> A;
    public static final C48459J0d<Boolean> A0;
    public static final C30554Byw<Boolean> A1;
    public static final C30554Byw<Double> A2;
    public static final C48459J0d<Boolean> A3;
    public static final C48459J0d<Boolean> B;
    public static final C48459J0d<Boolean> B0;
    public static final C48459J0d<Boolean> B1;
    public static final C30554Byw<Boolean> B2;
    public static final C48459J0d<String> B3;
    public static final C48459J0d<Long> C;
    public static final C48459J0d<Integer> C0;
    public static final C48459J0d<Boolean> C1;
    public static final C48459J0d<Long> C2;
    public static final C48459J0d<Integer> C3;
    public static final C48459J0d<Long> D;
    public static final C48459J0d<Long> D0;
    public static final C30554Byw<Boolean> D1;
    public static final C48459J0d<Long> D2;
    public static final C48459J0d<Integer> D3;
    public static final C48459J0d<Long> E;
    public static final C48459J0d<Boolean> E0;
    public static final C30554Byw<Boolean> E1;
    public static final C48459J0d<Long> E2;
    public static final C48459J0d<Boolean> E3;
    public static final C48459J0d<Integer> F;
    public static final C48459J0d<Boolean> F0;
    public static final C48459J0d<Integer> F1;
    public static final C30554Byw<Boolean> F2;
    public static final C48459J0d<Boolean> F3;
    public static final C48459J0d<Long> G;
    public static final C48459J0d<java.util.Map<Long, String>> G0;
    public static final C48459J0d<Integer> G1;
    public static final C30554Byw<Boolean> G2;
    public static final C48459J0d<Float> G3;
    public static final C48459J0d<Boolean> H;
    public static final C48459J0d<Long> H0;
    public static final C48459J0d<java.util.Map<String, String>> H1;
    public static final C30554Byw<Boolean> H2;
    public static final C48459J0d<Float> H3;
    public static final C48459J0d<Boolean> I;
    public static final C48459J0d<String> I0;
    public static final C48459J0d<java.util.Set<String>> I1;
    public static final C48459J0d<Long> I2;
    public static final C30554Byw<Boolean> I3;

    /* renamed from: J, reason: collision with root package name */
    public static final C48459J0d<java.util.Map<String, String>> f64J;
    public static final C48459J0d<CpcPromptResponse> J0;
    public static final C48459J0d<java.util.Map<String, String>> J1;
    public static final C48459J0d<Long> J2;
    public static final C30554Byw<Boolean> J3;
    public static final C48459J0d<Boolean> K;
    public static final C48459J0d<java.util.Map<Long, Integer>> K0;
    public static final C48459J0d<Long> K1;
    public static final C48459J0d<Long> K2;
    public static final C48459J0d<Integer> L;
    public static final C48459J0d<Boolean> L0;
    public static final C48459J0d<String> L1;
    public static final C30554Byw<Boolean> L2;
    public static final C48459J0d<Long> LIZ = new C48459J0d<>("hwg_fc_debug_timestamp", -1L);
    public static final C48459J0d<Integer> LIZIZ = new C48459J0d<>("poll_manage_dialog_tab", 0);
    public static final C48459J0d<Boolean> LIZJ;
    public static final C48459J0d<Long> LIZLLL;
    public static final C48459J0d<java.util.Set<String>> LJ;
    public static final C48459J0d<String> LJFF;
    public static final C48459J0d<String> LJI;
    public static final C48459J0d<String> LJII;
    public static final C48459J0d<Long> LJIIIIZZ;
    public static final C48459J0d<Integer> LJIIIZ;
    public static final C48459J0d<String> LJIIJ;
    public static final C48459J0d<Long> LJIIJJI;
    public static final C48459J0d<Long> LJIIL;
    public static final C48459J0d<Long> LJIILIIL;
    public static final C48459J0d<Long> LJIILJJIL;
    public static final C48459J0d<Integer> LJIILL;
    public static final C48459J0d<Integer> LJIILLIIL;
    public static final C48459J0d<Boolean> LJIIZILJ;
    public static final C48459J0d<java.util.Map<String, String>> LJIJ;
    public static final C48459J0d<Integer> LJIJI;
    public static final C48459J0d<String> LJIJJ;
    public static final C48459J0d<String> LJIJJLI;
    public static final C48459J0d<String> LJIL;
    public static final C48459J0d<Boolean> LJJ;
    public static final C48459J0d<Float> LJJI;
    public static final C48459J0d<Float> LJJIFFI;
    public static final C48459J0d<Float> LJJII;
    public static final C48459J0d<Float> LJJIII;
    public static final C48459J0d<Integer> LJJIIJ;
    public static final C48459J0d<Boolean> LJJIIJZLJL;
    public static final C48459J0d<java.util.Set<String>> LJJIIZ;
    public static final C48459J0d<Boolean> LJJIIZI;
    public static final C48459J0d<Boolean> LJJIJ;
    public static final C48459J0d<Boolean> LJJIJIIJI;
    public static final C48459J0d<Boolean> LJJIJIIJIL;
    public static final C48459J0d<Boolean> LJJIJIL;
    public static final C48459J0d<Boolean> LJJIJL;
    public static final C48459J0d<Boolean> LJJIJLIJ;
    public static final C48459J0d<Boolean> LJJIL;
    public static final C48459J0d<Boolean> LJJIZ;
    public static final C48459J0d<Boolean> LJJJ;
    public static final C48459J0d<Boolean> LJJJI;
    public static final C48459J0d<java.util.Map<String, List<String>>> LJJJIL;
    public static final C48459J0d<java.util.Map<String, java.util.Map<String, Float>>> LJJJJ;
    public static final C48459J0d<Long> LJJJJI;
    public static final C48459J0d<Boolean> LJJJJIZL;
    public static final C48459J0d<Boolean> LJJJJJ;
    public static final C48459J0d<Boolean> LJJJJJL;
    public static final C48459J0d<Boolean> LJJJJL;
    public static final C48459J0d<Boolean> LJJJJLI;
    public static final C48459J0d<Boolean> LJJJJLL;
    public static final C48459J0d<Boolean> LJJJJZ;
    public static final C48459J0d<Boolean> LJJJJZI;
    public static final C48459J0d<Boolean> LJJJLIIL;
    public static final C48459J0d<Boolean> LJJJLL;
    public static final C48459J0d<Boolean> LJJJLZIJ;
    public static final C48459J0d<Boolean> LJJJZ;
    public static final C48459J0d<Boolean> LJJL;
    public static final C48459J0d<Boolean> LJJLI;
    public static final C48459J0d<Boolean> LJJLIIIIJ;
    public static final C48459J0d<Boolean> LJJLIIIJ;
    public static final C48459J0d<Boolean> LJJLIIIJILLIZJL;
    public static final C30554Byw<Boolean> LJJLIIIJJI;
    public static final C48459J0d<Boolean> LJJLIIIJJIZ;
    public static final C48459J0d<Boolean> LJJLIIIJL;
    public static final C30554Byw<Boolean> LJJLIIIJLJLI;
    public static final C48459J0d<Long> LJJLIIIJLLLLLLLZ;
    public static final C48459J0d<Long> LJJLIIJ;
    public static final C48459J0d<Long> LJJLIL;
    public static final C48459J0d<Long> LJJLJ;
    public static final C48459J0d<String> LJJLJLI;
    public static final C48459J0d<Boolean> LJJLL;
    public static final C48459J0d<java.util.Map<String, Boolean>> LJJZ;
    public static final C48459J0d<Boolean> LJJZZI;
    public static final C30554Byw<Boolean> LJJZZIII;
    public static final C30554Byw<Boolean> LJL;
    public static final C30554Byw<Boolean> LJLI;
    public static final C30554Byw<Boolean> LJLIIIL;
    public static final C30554Byw<Boolean> LJLIIL;
    public static final C30554Byw<Boolean> LJLIL;
    public static final C30554Byw<Boolean> LJLILLLLZI;
    public static final C48459J0d<Boolean> LJLJI;
    public static final C48459J0d<java.util.Map<String, String>> LJLJJI;
    public static final C48459J0d<java.util.Map<String, String>> LJLJJL;
    public static final C48459J0d<Boolean> LJLJJLL;
    public static final C30554Byw<String> LJLJL;
    public static final C30554Byw<Boolean> LJLJLJ;
    public static final C30554Byw<Boolean> LJLJLLL;
    public static final C30554Byw<Boolean> LJLL;
    public static final C30554Byw<Boolean> LJLLI;
    public static final C48459J0d<Boolean> LJLLILLLL;
    public static final C30554Byw<Boolean> LJLLJ;
    public static final C48459J0d<Boolean> LJLLL;
    public static final C48459J0d<Boolean> LJLLLL;
    public static final C48459J0d<Boolean> LJLLLLLL;
    public static final C48459J0d<Boolean> LJLZ;
    public static final C48459J0d<Boolean> LJZ;
    public static final C48459J0d<Boolean> LJZI;
    public static final C48459J0d<Boolean> LJZL;
    public static final C48459J0d<Boolean> LL;
    public static final C48459J0d<java.util.Map<String, Boolean>> LLD;
    public static final C48459J0d<Boolean> LLF;
    public static final C48459J0d<Boolean> LLFF;
    public static final C48459J0d<Boolean> LLFFF;
    public static final C48459J0d<Boolean> LLFII;
    public static final C48459J0d<Boolean> LLFZ;
    public static final C48459J0d<Boolean> LLI;
    public static final C48459J0d<Boolean> LLIFFJFJJ;
    public static final C48459J0d<Boolean> LLII;
    public static final C48459J0d<Boolean> LLIIII;
    public static final C48459J0d<Boolean> LLIIIILZ;
    public static final C48459J0d<Boolean> LLIIIJ;
    public static final C48459J0d<Boolean> LLIIIL;
    public static final C48459J0d<Boolean> LLIIIZ;
    public static final C48459J0d<Boolean> LLIIJI;
    public static final C48459J0d<List<Double>> LLIIJLIL;
    public static final C48459J0d<Integer> LLIIL;
    public static final C48459J0d<Boolean> LLIILII;
    public static final C48459J0d<Boolean> LLIILZL;
    public static final C48459J0d<Boolean> LLIIZ;
    public static final C48459J0d<Integer> LLIL;
    public static final C30554Byw<Double> LLILII;
    public static final C48459J0d<Boolean> LLILIL;
    public static final C48459J0d<Boolean> LLILL;
    public static final C48459J0d<Boolean> LLILLIZIL;
    public static final C48459J0d<Boolean> LLILLJJLI;
    public static final C48459J0d<Boolean> LLILLL;
    public static final C48459J0d<Long> LLILZ;
    public static final C48459J0d<Long> LLILZIL;
    public static final C48459J0d<Integer> LLILZLL;
    public static final C48459J0d<Long> LLIZ;
    public static final C48459J0d<Integer> LLIZLLLIL;
    public static final C48459J0d<Boolean> LLJ;
    public static final C48459J0d<Boolean> LLJI;
    public static final C48459J0d<List<String>> LLJIJIL;
    public static final C48459J0d<Boolean> LLJILJIL;
    public static final C48459J0d<Boolean> LLJILJILJ;
    public static final C48459J0d<Boolean> LLJILLL;
    public static final C48459J0d<Boolean> LLJJ;
    public static final C48459J0d<Boolean> LLJJI;
    public static final C48459J0d<Boolean> LLJJIII;
    public static final C48459J0d<Boolean> LLJJIJI;
    public static final C48459J0d<Boolean> LLJJIJIIJIL;
    public static final C48459J0d<Boolean> LLJJIJIL;
    public static final C48459J0d<Boolean> LLJJJ;
    public static final C48459J0d<String> LLJJJIL;
    public static final C48459J0d<Boolean> LLJJJJ;
    public static final C48459J0d<Boolean> LLJJJJJIL;
    public static final C48459J0d<Boolean> LLJJJJLIIL;
    public static final C48459J0d<Boolean> LLJJL;
    public static final C48459J0d<Boolean> LLJJLIIIJLLLLLLLZ;
    public static final C48459J0d<Boolean> LLJL;
    public static final C48459J0d<Long> LLJLIL;
    public static final C48459J0d<String> LLJLILLLLZIIL;
    public static final C48459J0d<Boolean> LLJLL;
    public static final C48459J0d<Boolean> LLJLLIL;
    public static final C48459J0d<Boolean> LLJLLL;
    public static final C48459J0d<Boolean> LLJZ;
    public static final C48459J0d<Boolean> LLJZIJLIL;
    public static final C48459J0d<Boolean> LLL;
    public static final C48459J0d<Boolean> LLLF;
    public static final C48459J0d<IV1> LLLFF;
    public static final C48459J0d<Long> LLLFFI;
    public static final C48459J0d<Integer> LLLFZ;
    public static final C48459J0d<Boolean> LLLI;
    public static final C48459J0d<Boolean> LLLII;
    public static final C48459J0d<Boolean> LLLIIII;
    public static final C48459J0d<Long> LLLIIIIL;
    public static final C48459J0d<Boolean> LLLIIIL;
    public static final C48459J0d<Integer> LLLIIL;
    public static final C48459J0d<Boolean> LLLIILIL;
    public static final C48459J0d<Integer> LLLIL;
    public static final C48459J0d<Integer> LLLILZ;
    public static final C48459J0d<Boolean> LLLILZJ;
    public static final C48459J0d<Integer> LLLILZLLLI;
    public static final C48459J0d<Boolean> LLLIZZ;
    public static final C48459J0d<Integer> LLLJ;
    public static final C48459J0d<Integer> LLLJIL;
    public static final C48459J0d<Integer> LLLJL;
    public static final C48459J0d<Integer> LLLL;
    public static final C48459J0d<Integer> LLLLII;
    public static final C48459J0d<Integer> LLLLIIIILLL;
    public static final C48459J0d<Boolean> LLLLIIL;
    public static final C48459J0d<Boolean> LLLLIILL;
    public static final C48459J0d<Boolean> LLLLIILLL;
    public static final C48459J0d<Boolean> LLLLIL;
    public static final C48459J0d<Boolean> LLLLILI;
    public static final C48459J0d<Float> LLLLJ;
    public static final C48459J0d<Long> LLLLJI;
    public static final C48459J0d<Long> LLLLL;
    public static final C48459J0d<Boolean> LLLLLIL;
    public static final C48459J0d<Boolean> LLLLLILLIL;
    public static final C48459J0d<Boolean> LLLLLJIL;
    public static final C48459J0d<Integer> LLLLLJLJLL;
    public static final C48459J0d<Boolean> LLLLLL;
    public static final C48459J0d<Boolean> LLLLLLIL;
    public static final C48459J0d<Boolean> LLLLLLJ;
    public static final C48459J0d<Boolean> LLLLLLL;
    public static final C48459J0d<Boolean> LLLLLLLLL;
    public static final C48459J0d<Long> LLLLLLLLLL;
    public static final C48459J0d<Long> LLLLLLLZIL;
    public static final C48459J0d<Integer> LLLLLLZ;
    public static final C48459J0d<Long> LLLLLLZZ;
    public static final C48459J0d<Integer> LLLLLZ;
    public static final C48459J0d<java.util.Map<String, String>> LLLLLZIL;
    public static final C48459J0d<String> LLLLLZL;
    public static final C48459J0d<String> LLLLZ;
    public static final C48459J0d<String> LLLLZI;
    public static final C48459J0d<String> LLLLZIL;
    public static final C48459J0d<String> LLLLZLL;
    public static final C48459J0d<String> LLLLZLLIL;
    public static final C48459J0d<Boolean> LLLLZLLLI;
    public static final C48459J0d<java.util.Map<String, String>> LLLZ;
    public static final C48459J0d<java.util.Map<String, String>> LLLZI;
    public static final C48459J0d<String> LLLZIIL;
    public static final C48459J0d<String> LLLZIL;
    public static final C48459J0d<Long> LLLZL;
    public static final C48459J0d<Integer> LLLZLL;
    public static final C48459J0d<Long> LLLZLZ;
    public static final C48459J0d<java.util.Map<String, Double>> LLLZZ;
    public static final C48459J0d<Boolean> LLLZZIL;
    public static final C48459J0d<Boolean> LLZ;
    public static final C48459J0d<Boolean> LLZIL;
    public static final C48459J0d<Boolean> LLZILL;
    public static final C48459J0d<Boolean> LLZL;
    public static final C48459J0d<Boolean> LLZLI;
    public static final C48459J0d<Boolean> LLZLL;
    public static final C48459J0d<Boolean> LLZLLIL;
    public static final C48459J0d<Boolean> LLZLLLL;
    public static final C48459J0d<Boolean> LLZZ;
    public static final C48459J0d<java.util.Map<String, Integer>> LLZZJLIL;
    public static final C48459J0d<Boolean> LLZZLLIL;
    public static final C48459J0d<Boolean> LLZZZIL;
    public static final C48459J0d<java.util.Map<String, String>> LLZZZZ;
    public static final C48459J0d<Boolean> M;
    public static final C30554Byw<Boolean> M0;
    public static final C30554Byw<Double> M1;
    public static final C30554Byw<Boolean> M2;
    public static final C48459J0d<Boolean> N;
    public static final C30554Byw<Boolean> N0;
    public static final C30554Byw<Double> N1;
    public static final C30554Byw<Boolean> N2;
    public static final C48459J0d<Float> O;
    public static final C30554Byw<Boolean> O0;
    public static final C30554Byw<Boolean> O1;
    public static final C48459J0d<Integer> O2;
    public static final C48459J0d<Float> P;
    public static final C30554Byw<Boolean> P0;
    public static final C30554Byw<Boolean> P1;
    public static final C48459J0d<java.util.Map<String, String>> P2;
    public static final C48459J0d<Long> Q;
    public static final C30554Byw<Boolean> Q0;
    public static final C48459J0d<java.util.Map<String, java.util.Map<String, String>>> Q1;
    public static final C48459J0d<java.util.Map<String, String>> Q2;
    public static final C48459J0d<String> R;
    public static final C30554Byw<String> R0;
    public static final C30554Byw<Boolean> R1;
    public static final C48459J0d<Boolean> R2;
    public static final C48459J0d<Long> S;
    public static final C30554Byw<String> S0;
    public static final C48459J0d<java.util.Set<String>> S1;
    public static final C48459J0d<Boolean> S2;
    public static final C48459J0d<String> T;
    public static final C48459J0d<Boolean> T0;
    public static final C48459J0d<java.util.Map<String, String>> T1;
    public static final C48459J0d<Boolean> T2;
    public static final C48459J0d<Long> U;
    public static final C48459J0d<Boolean> U0;
    public static final C48459J0d<Long> U1;
    public static final C30554Byw<Boolean> U2;
    public static final C48459J0d<Integer> V;
    public static final C48459J0d<Boolean> V0;
    public static final C48459J0d<Boolean> V1;
    public static final C30554Byw<Boolean> V2;
    public static final C48459J0d<java.util.Map<String, Double>> W;
    public static final C48459J0d<Long> W0;
    public static final C48459J0d<Boolean> W1;
    public static final C30554Byw<Boolean> W2;

    /* renamed from: X, reason: collision with root package name */
    public static final C48459J0d<java.util.Map<String, Double>> f65X;
    public static final C48459J0d<Boolean> X0;
    public static final C30554Byw<List<String>> X1;
    public static final C48459J0d<Long> X2;

    /* renamed from: Y, reason: collision with root package name */
    public static final C48459J0d<Boolean> f66Y;
    public static final C48459J0d<Boolean> Y0;
    public static final C48459J0d<List<String>> Y1;
    public static final C48459J0d<Boolean> Y2;
    public static final C48459J0d<Long> Z;
    public static final C48459J0d<Boolean> Z0;
    public static final C30554Byw<Boolean> Z1;
    public static final C48459J0d<Boolean> Z2;
    public static final C48459J0d<java.util.Map<String, String>> a;
    public static final C48459J0d<java.util.Map<Integer, Integer>> a0;
    public static final C48459J0d<Long> a1;
    public static final C30554Byw<Boolean> a2;
    public static final C48459J0d<Boolean> a3;
    public static final C48459J0d<Boolean> b;
    public static final C48459J0d<Boolean> b0;
    public static final C48459J0d<Long> b1;
    public static final C30554Byw<Boolean> b2;
    public static final C48459J0d<Integer> b3;
    public static final C48459J0d<Boolean> c;
    public static final C48459J0d<Boolean> c0;
    public static final C48459J0d<Integer> c1;
    public static final C30554Byw<Boolean> c2;
    public static final C30554Byw<java.util.Map<String, List<String>>> c3;
    public static final C48459J0d<Long> d;
    public static final C48459J0d<MultiLiveAnchorPanelSettings> d0;
    public static final C48459J0d<Long> d1;
    public static final C48459J0d<Boolean> d2;
    public static final C48459J0d<java.util.Map<String, String>> d3;
    public static final C48459J0d<Boolean> e;
    public static final C48459J0d<Boolean> e0;
    public static final C30554Byw<Double> e1;
    public static final C48459J0d<Boolean> e2;
    public static final C48459J0d<Boolean> e3;
    public static final C48459J0d<Boolean> f;
    public static final C48459J0d<LiveEffectAutoRestoreConfig> f0;
    public static final C30554Byw<String> f1;
    public static final C48459J0d<Integer> f2;
    public static final C48459J0d<Integer> f3;
    public static final C48459J0d<Boolean> g;
    public static final C48459J0d<Boolean> g0;
    public static final C48459J0d<Boolean> g1;
    public static final C48459J0d<m> g2;
    public static final C48459J0d<Long> g3;
    public static final C48459J0d<Integer> h;
    public static final C48459J0d<java.util.Map<Long, Long>> h0;
    public static final C48459J0d<Boolean> h1;
    public static final C48459J0d<m> h2;
    public static final C48459J0d<java.util.Map<String, String>> h3;
    public static final C48459J0d<Integer> i;
    public static final C48459J0d<Long> i0;
    public static final C48459J0d<Boolean> i1;
    public static final C48459J0d<Integer> i2;
    public static final C48459J0d<Integer> i3;
    public static final C48459J0d<java.util.Map<Integer, Boolean>> j;
    public static final C48459J0d<Long> j0;
    public static final C48459J0d<Boolean> j1;
    public static final C48459J0d<Integer> j2;
    public static final C48459J0d<Integer> j3;
    public static final C48459J0d<Integer> k;
    public static final C48459J0d<CopyOnWriteArraySet<Double>> k0;
    public static final C48459J0d<Boolean> k1;
    public static final C30554Byw<Boolean> k2;
    public static final C48459J0d<Boolean> k3;
    public static final C48459J0d<java.util.Map<String, Boolean>> l;
    public static final C48459J0d<Boolean> l0;
    public static final C48459J0d<Boolean> l1;
    public static final C48459J0d<List<String>> l2;
    public static final C48459J0d<String> l3;
    public static final C48459J0d<Boolean> m;
    public static final C48459J0d<CopyOnWriteArraySet<String>> m0;
    public static final C48459J0d<Boolean> m1;
    public static final C30554Byw<Double> m2;
    public static final C48459J0d<java.util.Map<String, String>> m3;

    /* renamed from: n, reason: collision with root package name */
    public static final C48459J0d<Long> f67n;
    public static final C48459J0d<java.util.Map<String, ArrayList<Double>>> n0;
    public static final C48459J0d<Long> n1;
    public static final C30554Byw<Double> n2;
    public static final C48459J0d<Long> n3;
    public static final C48459J0d<long[]> o;
    public static final C48459J0d<HashMap<String, String>> o0;
    public static final C48459J0d<Integer> o1;
    public static final C30554Byw<java.util.Map<String, String>> o2;

    /* renamed from: o3, reason: collision with root package name */
    public static final C48459J0d<Boolean> f68o3;
    public static final C48459J0d<Boolean> p;
    public static final C30554Byw<Double> p0;
    public static final C30554Byw<Boolean> p1;
    public static final C30554Byw<String> p2;
    public static final C48459J0d<Integer> p3;
    public static final C48459J0d<Boolean> q;
    public static final C48459J0d<Boolean> q0;
    public static final C48459J0d<java.util.Map<Long, Integer>> q1;
    public static final C30554Byw<String> q2;
    public static final C48459J0d<Long> q3;
    public static final C48459J0d<Long> r;
    public static final C48459J0d<Boolean> r0;
    public static final C48459J0d<java.util.Map<Long, Boolean>> r1;
    public static final C48459J0d<Integer> r2;
    public static final C48459J0d<Boolean> r3;
    public static final C48459J0d<Boolean> s;
    public static final C48459J0d<Boolean> s0;
    public static final C48459J0d<java.util.Map<Long, Boolean>> s1;
    public static final C48459J0d<Integer> s2;
    public static final C48459J0d<Boolean> s3;
    public static final C48459J0d<Boolean> t;
    public static final C48459J0d<Boolean> t0;
    public static final C30554Byw<Boolean> t1;
    public static final C48459J0d<Integer> t2;
    public static final C48459J0d<Boolean> t3;
    public static final C48459J0d<Boolean> u;
    public static final C48459J0d<Boolean> u0;
    public static final C30554Byw<Boolean> u1;
    public static final C48459J0d<Boolean> u2;
    public static final C48459J0d<Boolean> u3;
    public static final C48459J0d<java.util.Set<String>> v;
    public static final C48459J0d<Boolean> v0;
    public static final C30554Byw<Boolean> v1;
    public static final C48459J0d<String> v2;
    public static final C48459J0d<Boolean> v3;
    public static final C48459J0d<java.util.Set<String>> w;
    public static final C48459J0d<Boolean> w0;
    public static final C30554Byw<Boolean> w1;
    public static final C48459J0d<Integer> w2;
    public static final C48459J0d<HashSet<String>> w3;
    public static final C48459J0d<java.util.Set<String>> x;
    public static final C48459J0d<Boolean> x0;
    public static final C30554Byw<Double> x1;
    public static final C48459J0d<Float> x2;
    public static final C48459J0d<Boolean> x3;
    public static final C48459J0d<Boolean> y;
    public static final C48459J0d<Boolean> y0;
    public static final C48459J0d<Boolean> y1;
    public static final C48459J0d<java.util.Map<String, String>> y2;
    public static final C48459J0d<Boolean> y3;
    public static final C48459J0d<java.util.Set<String>> z;
    public static final C48459J0d<Boolean> z0;
    public static final C30554Byw<Boolean> z1;
    public static final C30554Byw<Boolean> z2;
    public static final C48459J0d<List<String>> z3;

    static {
        Boolean bool = Boolean.TRUE;
        LIZJ = new C48459J0d<>("gift_poll_warn_dialog_show", bool);
        LIZLLL = new C48459J0d<>("live_audience_gift_poll_id", 0L);
        LJ = new C48459J0d<>("gift_list_type", new HashSet());
        LJFF = new C48459J0d<>("assets_cache_data", "");
        LJI = new C48459J0d<>("disk_present_assets_cache_data", "");
        LJII = new C48459J0d<>("assets_cache_data_last_download_time", "");
        LJIIIIZZ = new C48459J0d<>("assets_cache_last_check_time", 0L);
        LJIIIZ = new C48459J0d<>("live_camera_type", 1);
        LJIIJ = new C48459J0d<>("live_resource_current_version", "");
        new C48459J0d("live_prop_expire_tip_time", 0L);
        LJIIJJI = new C48459J0d<>("current_room_id", 0L);
        LJIIL = new C48459J0d<>("current_room_start_time", 0L);
        LJIILIIL = new C48459J0d<>("recent_go_live_start_time", 0L);
        LJIILJJIL = new C48459J0d<>("live_stream_video_capture_last_time", 0L);
        LJIILL = new C48459J0d<>("live_ctrl_window_x", -1);
        LJIILLIIL = new C48459J0d<>("live_ctrl_window_y", -1);
        LJIIZILJ = new C48459J0d<>("live_game_msg_enabled", bool);
        new C48459J0d("show_screen_record_notification_tips_permission_count", 0);
        LJIJ = new C48459J0d<>("live_start_live_tag", new HashMap());
        LJIJI = new C48459J0d<>("live_filter_index_new", -1);
        LJIJJ = new C48459J0d<>("live_filter_id_new", CardStruct.IStatusCode.DEFAULT);
        LJIJJLI = new C48459J0d<>("live_filter_change_action_type", "click");
        LJIL = new C48459J0d<>("live_filter_resource_id", "");
        Boolean bool2 = Boolean.FALSE;
        LJJ = new C48459J0d<>("live_filter_converted_to_composer", bool2);
        Float valueOf = Float.valueOf(-1.0f);
        LJJI = new C48459J0d<>("brightening_param_v2", valueOf);
        LJJIFFI = new C48459J0d<>("beauty_skin_param_v2", valueOf);
        LJJII = new C48459J0d<>("big_eyes_param", valueOf);
        LJJIII = new C48459J0d<>("face_lift_param", valueOf);
        LJJIIJ = new C48459J0d<>("beauty_level", 3);
        LJJIIJZLJL = new C48459J0d<>("none_effect_selected", bool2);
        new C48459J0d("prop_panel_showed_red_point", new HashSet());
        LJJIIZ = new C48459J0d<>("mt_fast_gift_hide_confirm_gift", new HashSet());
        LJJIIZI = new C48459J0d<>("room_auto_gift_thanks", bool2);
        LJJIJ = new C48459J0d<>("live_game_quit_click", bool2);
        LJJIJIIJI = new C48459J0d<>("live_game_comment_msg_push", bool);
        LJJIJIIJIL = new C48459J0d<>("live_game_gift_msg_push", bool);
        LJJIJIL = new C48459J0d<>("live_game_show_bubble_gift", bool);
        LJJIJL = new C48459J0d<>("live_game_show_bubble_comment", bool);
        LJJIJLIJ = new C48459J0d<>("live_game_show_bubble_star_comment", bool);
        LJJIL = new C48459J0d<>("live_game_star_comment_msg_push", bool);
        LJJIZ = new C48459J0d<>("message_notification_entry_message", bool);
        LJJJ = new C48459J0d<>("message_notification_attention_message", bool);
        LJJJI = new C48459J0d<>("message_notification_like_message", bool);
        LJJJIL = new C48459J0d<>("gesture_magic_select_composer_path_map", new HashMap());
        LJJJJ = new C48459J0d<>("live_composer_save_node_tag_value", new HashMap());
        LJJJJI = new C48459J0d<>("last_show_flare_animation_room_id", 0L);
        new C48459J0d("current_sticker_page_position", 0);
        new C48459J0d("drawer_anim_show", 0L);
        new C48459J0d("drawer_anim_show_count", 0);
        new C48459J0d("show_question_guide_bubble_audience", bool);
        LJJJJIZL = new C48459J0d<>("show_question_guide_bubble_anchor", bool);
        LJJJJJ = new C48459J0d<>("show_poll_guide_bubble", bool);
        LJJJJJL = new C48459J0d<>("show_preview_live_center_bubble", bool);
        LJJJJL = new C48459J0d<>("show_draw_guess_guide_bubble", bool);
        LJJJJLI = new C48459J0d<>("show_draw_guess_edit_anim", bool);
        new C48459J0d("show_close_question_tip", bool);
        LJJJJLL = new C48459J0d<>("show_pause_live_tip", bool);
        new C48459J0d("live_mode_widget_new_type", bool);
        new C48459J0d("has_slide_to_exit_room", bool2);
        new C48459J0d("show_gift_dialog_prop_red_dot", bool2);
        LJJJJZ = new C48459J0d<>("show_game_live_weak_device_tips", bool2);
        LJJJJZI = new C48459J0d<>("GAME_LIVE_MONITOR_SWITCH", bool2);
        new C48459J0d("has_play_gift_failure_on_mediaplayer", bool2);
        LJJJLIIL = new C48459J0d<>("live_show_preview_moderator_setting_red_dot", bool);
        LJJJLL = new C48459J0d<>("live_show_preview_comments_setting_red_dot", bool);
        LJJJLZIJ = new C48459J0d<>("live_show_mature_setting_red_dot", bool);
        LJJJZ = new C48459J0d<>("live_show_preview_mature_setting_red_dot", bool);
        LJJL = new C48459J0d<>("live_show_moderator_setting_red_dot", bool);
        LJJLI = new C48459J0d<>("live_show_bc_toggle_setting_red_dot", bool);
        LJJLIIIIJ = new C48459J0d<>("live_show_bc_toggle_dialog_before", bool2);
        LJJLIIIJ = new C48459J0d<>("live_show_game_bc_toggle_dialog_before", bool2);
        new C48459J0d("live_partnership_drops_edu_dialog_show", bool2);
        LJJLIIIJILLIZJL = new C48459J0d<>("live_partnership_drops_pre_reddot_show", bool2);
        LJJLIIIJJI = new C30554Byw<>("live_partnership_drops_anchor_sign");
        LJJLIIIJJIZ = new C48459J0d<>("live_partnership_drops_living_red_dot_show", bool2);
        LJJLIIIJL = new C48459J0d<>("live_partnership_drops_share_red_dot_show", bool2);
        LJJLIIIJLJLI = new C30554Byw<>("live_partnership_drops_reward_count");
        LJJLIIIJLLLLLLLZ = new C48459J0d<>("live_partnership_drops_new_icon_count", 0L);
        LJJLIIJ = new C48459J0d<>("live_partnership_drops_icon_show_ts", 0L);
        LJJLIL = new C48459J0d<>("live_partnership_drops_preview_show_count", 0L);
        LJJLJ = new C48459J0d<>("live_partnership_drops_preview_show_ts", 0L);
        LJJLJLI = new C48459J0d<>("live_partnership_drops_new_icon_key", "");
        LJJLL = new C48459J0d<>("live_draw_guess_first_time_show_draw_guide", bool);
        LJJZ = new C48459J0d<>("live_subscribe_chat_only_switch_new", new HashMap());
        LJJZZI = new C48459J0d<>("live_subscribe_show_preview_reddot", bool);
        LJJZZIII = new C30554Byw<>("live_sucscribe_finished_guide");
        LJL = new C30554Byw<>("live_subscribe_item_community_banner");
        LJLI = new C30554Byw<>("live_subscribe_has_shown_sub_only_live_guide");
        LJLIIIL = new C30554Byw<>("live_subscribe_item_email_bind_banner");
        LJLIIL = new C30554Byw<>("live_subscribe_subathon_faq");
        LJLIL = new C30554Byw<>("live_sub_wave_guide_shown");
        LJLILLLLZI = new C30554Byw<>("live_spotlight_guide_shown");
        LJLJI = new C48459J0d<>("subscription_spotlight_red_dot_enable", bool);
        LJLJJI = new C48459J0d<>("live_subscribe_link_share_inner", new HashMap());
        LJLJJL = new C48459J0d<>("live_subscribe_link_share_outer", new HashMap());
        LJLJJLL = new C48459J0d<>("anchor_subscribe_goal_guide_has_shown", bool2);
        LJLJL = new C30554Byw<>("live_sucscribe_badge_icon");
        LJLJLJ = new C30554Byw<>("live_subscribe_status_fail_tip_closed");
        LJLJLLL = new C30554Byw<>("live_subscribe_preview_on_boarding_bubble_showed");
        new C48459J0d("live_subscribe_first_get_qualification", bool);
        new C48459J0d("live_subscribe_approved_item_ids", new ArrayList());
        LJLL = new C30554Byw<>("live_subscribe_congratulation_dialog");
        LJLLI = new C30554Byw<>("live_subscribe_active_dialog");
        StringBuilder LIZ2 = X1D.LIZ();
        LIZ2.append(((IHostUser) CN1.LIZ(IHostUser.class)).getCurUserId());
        LIZ2.append("_live_subscribe_first_show_inviation_page");
        LJLLILLLL = new C48459J0d<>(X1D.LIZIZ(LIZ2), bool);
        LJLLJ = new C30554Byw<>("live_subscribe_first_show_invitation_activity");
        new C48459J0d("live_subscribe_invitation_last_description_key", 0L);
        new C48459J0d("live_subscribe_invitation_last_description_key", bool);
        new C48459J0d("live_subscription_goals_setting_red_dot", bool);
        new C48459J0d("live_subscription_custom_benefits_red_dot", bool);
        LJLLL = new C48459J0d<>("live_custom_pokk_show_preview_red_dot", bool);
        LJLLLL = new C48459J0d<>("live_custom_poll_tooltip", bool);
        LJLLLLLL = new C48459J0d<>("live_practice_mode_setting_tooltip", bool);
        LJLZ = new C48459J0d<>("live_simpified_go_live_page_tooltip", bool);
        LJZ = new C48459J0d<>("live_show_admin_setting_red_dot", bool);
        LJZI = new C48459J0d<>("live_show_comment_setting_red_dot", bool);
        LJZL = new C48459J0d<>("live_show_preview_setting_red_dot", bool);
        new C48459J0d("live_show_preview_temporary_mute_setting_red_dot", bool);
        LL = new C48459J0d<>("live_show_manage_temporary_mute_setting_red_dot", bool);
        LLD = new C48459J0d<>("live_show_star_comment_setting_red_dot", new HashMap());
        new C48459J0d("show_live_replay_prompt", bool);
        new C48459J0d("show_live_replay_prompt_private_account", bool);
        LLF = new C48459J0d<>("anchor_comments_enable", bool);
        new C48459J0d("anchor_is_first_time_accept_notification", bool);
        LLFF = new C48459J0d<>("anchor_is_first_time_accept_multi_host_notification", bool);
        LLFFF = new C48459J0d<>("anchor_is_allow_notification", bool);
        LLFII = new C48459J0d<>("anchor_is_receive_link", bool);
        LLFZ = new C48459J0d<>("anchor_is_suggested_to_another_anchor", bool2);
        LLI = new C48459J0d<>("anchor_is_receive_friend_multi_host_invites", bool);
        LLIFFJFJJ = new C48459J0d<>("anchor_is_receive_friend_multi_host_application", bool);
        LLII = new C48459J0d<>("anchor_is_receive_not_friend_multi_host_invites", bool);
        LLIIII = new C48459J0d<>("anchor_is_receive_not_friend_multi_host_application", bool);
        LLIIIILZ = new C48459J0d<>("anchor_is_block_this_multi_host_invites", bool);
        LLIIIJ = new C48459J0d<>("anchor_is_block_this_multi_host_application", bool);
        LLIIIL = new C48459J0d<>("anchor_is_allow_live_multi_host_notification", bool);
        LLIIIZ = new C48459J0d<>("link_mic_battle_has_show_guide", bool2);
        LLIIJI = new C48459J0d<>("link_mic_battle_has_show_invite_pop_tip", bool2);
        LLIIJLIL = new C48459J0d<>("rankdom_linkmic_ quickly_disconnected_record", new ArrayList());
        LLIIL = new C48459J0d<>(0);
        LLIILII = new C48459J0d<>("has_click_random_linkmic_entrance_when_ban", bool2);
        LLIILZL = new C48459J0d<>("link_mic_battle_open_gift_guide_not_show_again", bool2);
        LLIIZ = new C48459J0d<>("link_mic_battle_task_open_gift_toast", bool2);
        LLIL = new C48459J0d<>("link_mic_battle_match_item_show_time", 0);
        LLILII = new C30554Byw<>("random_linkmic_guidance_show_count");
        LLILIL = new C48459J0d<>("link_mic_battle_match_item_award_critical_dialog_shown", bool2);
        LLILL = new C48459J0d<>("link_mic_battle_match_item_award_smoke_dialog_shown", bool2);
        LLILLIZIL = new C48459J0d<>("link_multi_co_host_had_show_tips", bool2);
        LLILLJJLI = new C48459J0d<>("link_multi_co_host_had_show_guide", bool2);
        LLILLL = new C48459J0d<>("link_multi_co_host_network_exception_handler_switch", bool2);
        LLILZ = new C48459J0d<>("multi_co_host_show_feedback", 0L);
        LLILZIL = new C48459J0d<>("multi_co_host_submit_feedback", 0L);
        LLILZLL = new C48459J0d<>("multi_co_host_feedback_skip_count", 0);
        LLIZ = new C48459J0d<>("multi_co_host_admit_feedback_timestamp", 0L);
        LLIZLLLIL = new C48459J0d<>("multi_co_host_feedback_submit_version", 3060);
        LLJ = new C48459J0d<>("multi_co_host_topic_quit_setting", bool2);
        LLJI = new C48459J0d<>("multi_co_host_topic_conflict_setting", bool2);
        LLJIJIL = new C48459J0d<>("multi_co_host_topic_guide_show_list", new ArrayList());
        LLJILJIL = new C48459J0d<>("anchor_show_qa_tutorial", bool);
        LLJILJILJ = new C48459J0d<>("admin_show_qa_tutorial", bool);
        LLJILLL = new C48459J0d<>("anchor_first_turn_qa", bool);
        LLJJ = new C48459J0d<>("anchor_first_answer", bool);
        LLJJI = new C48459J0d<>("anchor_first_switch_question", bool);
        LLJJIII = new C48459J0d<>("anchor_first_pin_question", bool);
        new C48459J0d("anchor_has_show_open_suggested_switch_message", bool2);
        LLJJIJI = new C48459J0d<>("anchor_is_receive_linkmic_invitation_this_live", bool);
        LLJJIJIIJIL = new C48459J0d<>("anchor_should_open_guest_linkmic_when_start", bool);
        LLJJIJIL = new C48459J0d<>("should_show_battle_rule_guide_message", bool);
        new C48459J0d("server_enable_game_category", bool2);
        LLJJJ = new C48459J0d<>("server_enable_highlight_button", bool2);
        LLJJJIL = new C48459J0d<>("last_show_highlight_fragment_id", "");
        LLJJJJ = new C48459J0d<>("live_pip_switcher_open", Boolean.valueOf(LivePipDefaultOpenSetting.INSTANCE.getValue() == 2));
        LLJJJJJIL = new C48459J0d<>("live_pip_guide_dialog_has_shown", bool2);
        LLJJJJLIIL = new C48459J0d<>("live_bg_audio_play_open", bool);
        LLJJL = new C48459J0d<>("live_pip_ab_group_reported", bool2);
        StringBuilder LIZ3 = X1D.LIZ();
        LIZ3.append(((IHostUser) CN1.LIZ(IHostUser.class)).getCurUserId());
        LIZ3.append("_live_game_latest_set_landscape");
        LLJJLIIIJLLLLLLLZ = new C48459J0d<>(X1D.LIZIZ(LIZ3), bool);
        LLJL = new C48459J0d<>("live_first_open_hashtag_dialog_in_broadcast", bool);
        LLJLIL = new C48459J0d<>("live_hashtag_id", 0L);
        LLJLILLLLZIIL = new C48459J0d<>("live_hashtag_name", LiveGiftNewGifterBadgeSetting.DEFAULT);
        LLJLL = new C48459J0d<>("live_has_ever_use_hashtag", bool2);
        LLJLLIL = new C48459J0d<>("live_first_open_props_dialog_in_broadcast", bool);
        LLJLLL = new C48459J0d<>("live_first_open_sticker_dialog_in_broadcast", bool);
        LLJZ = new C48459J0d<>("live_bgm_tooltip_v2", bool);
        LLJZIJLIL = new C48459J0d<>("live_bgm_tooltip_v3", bool);
        LLL = new C48459J0d<>("live_bgm_v3_mini_panel", bool);
        LLLF = new C48459J0d<>("live_bgm_should_open_mini_panel", bool2);
        LLLFF = new C48459J0d<>("live_bgm_file_cache", new IV1());
        LLLFFI = new C48459J0d<>("live_finish_page_push_tip_time", 0L);
        LLLFZ = new C48459J0d<>("live_finish_page_push_tip_count", 0);
        LLLI = new C48459J0d<>("live_audience_landscape_message_panel_closed", bool2);
        LLLII = new C48459J0d<>("live_audience_landscape_video_crop_action_shown", bool2);
        LLLIIII = new C48459J0d<>("live_jsb_show_exchange_dialog", bool);
        LLLIIIIL = new C48459J0d<>("live_current_user_id", 0L);
        LLLIIIL = new C48459J0d<>("live_show_exchange_red_dot", bool);
        new C48459J0d("live_ug_exchange_click_cancel_count", 0);
        LLLIIL = new C48459J0d<>("live_gifts_exchange_click_cancel_count", 0);
        LLLIILIL = new C48459J0d<>("live_gifts_guide_exchange_click_cancel_exp", bool);
        LLLIL = new C48459J0d<>("live_gifts_guide_exchange_click_cancel_count", -1);
        LLLILZ = new C48459J0d<>("live_has_exchange_gift_success", 0);
        LLLILZJ = new C48459J0d<>("live_show_turn_on_auto_exchange_dialog", bool);
        LLLILZLLLI = new C48459J0d<>("live_has_exchange_gift_success_for_live_income", 0);
        LLLIZZ = new C48459J0d<>("live_show_turn_on_auto_exchange_dialog_for_live_income", bool);
        LLLJ = new C48459J0d<>("live_recharge_email_collection_live_room_count", 0);
        LLLJIL = new C48459J0d<>("live_recharge_email_auth_live_room_count", 0);
        LLLJL = new C48459J0d<>("live_recharge_email_collection_profile_count", 0);
        LLLL = new C48459J0d<>("live_recharge_email_auth_profile_count", 0);
        LLLLII = new C48459J0d<>("live_recharge_exchange_marquee_count", 0);
        LLLLIIIILLL = new C48459J0d<>("live_effect_echo_mode_switch", 0);
        LLLLIIL = new C48459J0d<>("live_sound_effect_red_dot_show", bool);
        LLLLIILL = new C48459J0d<>("live_real_sound_effect_red_dot_show", bool);
        LLLLIILLL = new C48459J0d<>("live_sound_effect_tip_toast_showed", bool);
        LLLLIL = new C48459J0d<>("live_center_lottie_guide_animation", bool);
        LLLLILI = new C48459J0d<>("had_show_mobile_game_live_center_tips_dialog", bool2);
        LLLLJ = new C48459J0d<>("last_game_live_high_ping_percent", Float.valueOf(0.0f));
        LLLLJI = new C48459J0d<>("last_game_live_timestamp", 0L);
        LLLLL = new C48459J0d<>("last_game_live_preparation_manual_speed_test_timestamp", 0L);
        LLLLLIL = new C48459J0d<>("live_center_lottie_guide_right_animation", bool);
        LLLLLILLIL = new C48459J0d<>("live_game_extended_screen_show_guide", bool);
        LLLLLJIL = new C48459J0d<>("live_extended_screen_close_guide", bool);
        StringBuilder LIZ4 = X1D.LIZ();
        LIZ4.append(((IHostUser) CN1.LIZ(IHostUser.class)).getCurUserId());
        LIZ4.append("_extend_public_screen_guide_time");
        LLLLLJLJLL = new C48459J0d<>(X1D.LIZIZ(LIZ4), 0);
        LLLLLL = new C48459J0d<>("live_game_extended_screen_close_guide", bool);
        LLLLLLIL = new C48459J0d<>("live_intro_preview_setting_entrance", bool);
        LLLLLLJ = new C48459J0d<>("live_intro_broadcast_setting_entrance", bool);
        LLLLLLL = new C48459J0d<>("live_reverse_camera_red_dot", bool);
        LLLLLLLLL = new C48459J0d<>("live_reverse_mirror_red_dot", bool);
        LLLLLLLLLL = new C48459J0d<>("live_last_front_camera_detection_toast_time", 0L);
        LLLLLLLZIL = new C48459J0d<>("live_last_back_camera_detection_toast_time", 0L);
        LLLLLLZ = new C48459J0d<>("live_center_has_violation", -1);
        LLLLLLZZ = new C48459J0d<>("live_sticker_favorite_animation_validity_period", 0L);
        LLLLLZ = new C48459J0d<>("live_sticker_favorite_animation_time", 0);
        StringBuilder LIZ5 = X1D.LIZ();
        LIZ5.append(((IHostUser) CN1.LIZ(IHostUser.class)).getCurUserId());
        LIZ5.append("_broadcast_live_game_category_last_select_game");
        LLLLLZIL = new C48459J0d<>(X1D.LIZIZ(LIZ5), new HashMap());
        new C48459J0d("broadcast_fetched_game_tag", new HashMap());
        StringBuilder LIZ6 = X1D.LIZ();
        LIZ6.append(((IHostUser) CN1.LIZ(IHostUser.class)).getCurUserId());
        LIZ6.append("_broadcast_live_game_category_last_select_game_gs");
        LLLLLZL = new C48459J0d<>(X1D.LIZIZ(LIZ6), "");
        LLLLZ = new C48459J0d<>("live_hashtag_gs", "");
        LLLLZI = new C48459J0d<>("broadcast_fetched_game_tag_gs", "");
        LLLLZIL = new C48459J0d<>("live_mode_game_tag_gs", "");
        LLLLZLL = new C48459J0d<>("voice_chat_hashtag_gs", "");
        LLLLZLLIL = new C48459J0d<>("voice_chat_game_tag_gs", "");
        LLLLZLLLI = new C48459J0d<>("obs_screen_live_audience_click_definition_selection", bool2);
        LLLZ = new C48459J0d<>("obs_screen_live_audience_manually_select_sdk_key", new HashMap());
        LLLZI = new C48459J0d<>("screen_live_broadcast_manually_select_sdk_new_key", new HashMap());
        LLLZIIL = new C48459J0d<>("screen_live_broadcast_last_live_definition", "");
        LLLZIL = new C48459J0d<>("screen_live_broadcast_last_live_definition_type", "");
        LLLZL = new C48459J0d<>("game_live_broadcast_last_auto_speed_test_timestamp", 0L);
        LLLZLL = new C48459J0d<>("game_live_broadcast_auto_speed_test_trigger_count", 0);
        LLLZLZ = new C48459J0d<>("live_filter_change_time", -1L);
        LLLZZ = new C48459J0d<>("live_filter_level_map", new HashMap());
        LLLZZIL = new C48459J0d<>("live_multi_live_guest_click_beauty_tips", bool2);
        LLZ = new C48459J0d<>("live_multi_live_anchor_settings_prompt_shown", bool2);
        LLZIL = new C48459J0d<>("live_multi_live_anchor_settings_bubble_shown", bool2);
        LLZILL = new C48459J0d<>("live_multi_live_anchor_settings_bubble_reset", bool2);
        new C48459J0d("live_multi_live_guest_revenue_reminder_shown", bool2);
        LLZL = new C48459J0d<>("live_multi_live_guest_revenue_info_shown", bool2);
        LLZLI = new C48459J0d<>("live_multi_live_guest_moderator_red_dot_should_show", bool);
        LLZLL = new C48459J0d<>("live_multi_live_guest_gifter_apply_red_dot_should_show", bool);
        LLZLLIL = new C48459J0d<>("multi_guest_gifter_threshold_gift_send_check", bool);
        new C48459J0d("game_live_mask_age_restricted_save_pre_checkbox", bool2);
        new C48459J0d("game_live_mask_age_restricted_pre_type", 1);
        new C48459J0d("game_live_mask_content_disturbing_save_pre_checkbox", bool2);
        new C48459J0d("game_live_mask_content_disturbing_pre_type", 1);
        LLZLLLL = new C48459J0d<>("user has ever use beauty", bool2);
        LLZZ = new C48459J0d<>("user has ever click beauty", bool2);
        LLZZJLIL = new C48459J0d<>("beauty_selected_index", new HashMap());
        LLZZLLIL = new C48459J0d<>("user has ever use filter", bool2);
        LLZZZIL = new C48459J0d<>("preview has ever show beauty bubble", bool2);
        new C48459J0d("ttlive_has_watch_education_video", bool2);
        LLZZZZ = new C48459J0d<>("live_mt_gift_color_anim_hist", new HashMap());
        a = new C48459J0d<>("live_mt_gift_color_bubble_hist", new HashMap());
        b = new C48459J0d<>("live_mt_gift_color_entered", bool2);
        c = new C48459J0d<>("live_mt_gift_color_red_point_shown", bool2);
        d = new C48459J0d<>("live_mt_gift_color_gift_id", 0L);
        new C48459J0d("multi_guest_show_feedback_time", 0L);
        e = new C48459J0d<>("should show filter red dot", bool2);
        new C48459J0d("should show beauty red dot", bool2);
        new C48459J0d("should show makeup red dot", bool2);
        f = new C48459J0d<>("live_show_preview_warning_tip", bool);
        g = new C48459J0d<>("should show props red dot", bool2);
        new C48459J0d("live_gift_group_sent", bool2);
        new C48459J0d("live_gift_group_send_guide", bool2);
        h = new C48459J0d<>("live_mt_gift_random_tips_count", 0);
        i = new C48459J0d<>("live_gift_random_last_day", 0);
        j = new C48459J0d<>("live_gift_random_count_map", new HashMap());
        k = new C48459J0d<>("random_fireworks_gift_hint_seen", -1);
        new C48459J0d("multi_mock_user_token", new HashMap());
        new C48459J0d("multi_mock_user_info", new HashMap());
        new C48459J0d("multi_mock_room_id", "");
        l = new C48459J0d<>("last_show_subscription_guide", new HashMap());
        m = new C48459J0d<>("live_center_promote_on_preview", bool2);
        f67n = new C48459J0d<>("live_center_promote_on_preview_time_point", 0L);
        o = new C48459J0d<>("live_center_promote_show_time_array", new long[]{0, 0, 0});
        p = new C48459J0d<>("live_preview_focus_guide_anim", bool2);
        q = new C48459J0d<>("ttlive_has_show_game_auto_cover_animation", bool2);
        new C48459J0d("subscription_bubble_controller", new HashMap());
        r = new C48459J0d<>("rookie_rank_tip_show_time", 0L);
        s = new C48459J0d<>("has_ever_open_sticker_panel", bool2);
        t = new C48459J0d<>("has_show_modification_guide", bool2);
        u = new C48459J0d<>("has_shown_use_cohost_effect_guide", bool2);
        v = new C48459J0d<>("has_show_inserted_sticker", new HashSet());
        w = new C48459J0d<>("has_click_recommend_sticker", new HashSet());
        x = new C48459J0d<>("should_sticker_category_show_red_dot", new HashSet());
        y = new C48459J0d<>("should_sticker_show_red_dot", bool2);
        z = new C48459J0d<>("should_beauty_category_show_red_dot", new HashSet());
        A = new C48459J0d<>("should_beauty_entrance_show_red_dot", bool2);
        new C48459J0d("LIVE_GIFT_SCROLLABLE_VERTICAL_PADDING", 1);
        new C48459J0d("LIVE_GIFT_SCROLLABLE_TOP", 4);
        new C48459J0d("LIVE_GIFT_SCROLLABLE_BOTTOM", 0);
        new C48459J0d("LIVE_GIFT_SCROLLABLE_BIAS", -2);
        new C48459J0d("had_shown_multilive_share_tip", bool2);
        StringBuilder LIZ7 = X1D.LIZ();
        LIZ7.append(((IHostUser) CN1.LIZ(IHostUser.class)).getCurUserId());
        LIZ7.append("_live_subscribe_show_update_paypal");
        B = new C48459J0d<>(X1D.LIZIZ(LIZ7), bool);
        C = new C48459J0d<>("auto_switch_show_time", -1L);
        D = new C48459J0d<>("abr_upgrade_tips_show_time", -1L);
        E = new C48459J0d<>("abr_downgrade_tips_show_time", -1L);
        new C48459J0d("sub_community_red_dot_show", bool2);
        new C48459J0d("last_community_status", 0);
        new C48459J0d("live_last_abr_resolution", "");
        F = new C48459J0d<>("non_auto_stall_tips_count", 0);
        G = new C48459J0d<>("non_auto_last_stall_tips_time", 0L);
        H = new C48459J0d<>("first_time_show_max_moderator_num_change_dialog", bool);
        I = new C48459J0d<>("first_time_add_moderator_exceed_limitation_dialog", bool);
        f64J = new C48459J0d<>("live_reply_scheduled_download_video_list", new HashMap());
        K = new C48459J0d<>("first_time_apply_bluetooth_permission_in_interceptor", bool);
        L = new C48459J0d<>("bluetooth_permission_hint_dialog_shown_times_in_interceptor", 0);
        M = new C48459J0d<>("first_time_show_age_16_to_18_live_dialog", bool);
        N = new C48459J0d<>("had_co_host_invite_preview_prompt_dialog_click_continue", bool2);
        O = new C48459J0d<>("effect_accompaniment_volume", Float.valueOf(LiveBgMusicDefaultVolumeSetting.INSTANCE.getValue()));
        P = new C48459J0d<>("effect_bgm_volume", Float.valueOf(LiveBGMDefaultVolumeSetting.INSTANCE.getValue()));
        Q = new C48459J0d<>("effect_accompaniment_offset_validity_period", -1L);
        R = new C48459J0d<>("effect_accompaniment_offsets", "");
        S = new C48459J0d<>("effect_playing_bgm_id", 0L);
        T = new C48459J0d<>("game_content_convert", "");
        U = new C48459J0d<>("tool_tips_show_management_time", 0L);
        V = new C48459J0d<>("tool_tips_show_management_count", 0);
        W = new C48459J0d<>("tool_tips_show_version_code_map", new HashMap());
        f65X = new C48459J0d<>("tool_tips_show_position_time_map", new HashMap());
        f66Y = new C48459J0d<>("live_center_red_dot_show", bool2);
        Z = new C48459J0d<>("custom_poll_card_show_record", 0L);
        new C48459J0d("live_multi_match_selected_mate_shown", bool2);
        a0 = new C48459J0d<>("live_scene_panel_setting_map", new HashMap());
        b0 = new C48459J0d<>("live_has_open_status_setting_page", bool2);
        c0 = new C48459J0d<>("live_has_do_second_confirmation_action", bool2);
        d0 = new C48459J0d<>("live_multilive_anchor_panel_setting", new MultiLiveAnchorPanelSettings(1, 1, 0, 0, null, 0, 0L));
        e0 = new C48459J0d<>("live_multi_guest_live_show_desc_guidance_has_clicked", bool2);
        f0 = new C48459J0d<>("live_effect_auto_restore_config", new LiveEffectAutoRestoreConfig());
        g0 = new C48459J0d<>("first_time_to_snap", bool);
        new C48459J0d("first_time_to_small", bool);
        h0 = new C48459J0d<>("live_weekly_ranking_gifts_anchor_notify", new HashMap());
        i0 = new C48459J0d<>("live_last_audience_weekly_ranking_gift_animation_show_time", 0L);
        j0 = new C48459J0d<>("live_last_user_level_will_sleep_text_show_time", 0L);
        StringBuilder LIZ8 = X1D.LIZ();
        LIZ8.append(((IHostUser) CN1.LIZ(IHostUser.class)).getCurUserId());
        LIZ8.append("_user_level_new_unlock_gift_id_set");
        k0 = new C48459J0d<>(X1D.LIZIZ(LIZ8), new CopyOnWriteArraySet());
        l0 = new C48459J0d<>("user_level_new_unlock_tab_show_red_dot", bool2);
        m0 = new C48459J0d<>("fans_club_new_unlock_tab_show_red_dot_set", new CopyOnWriteArraySet());
        n0 = new C48459J0d<>("fans_club_new_unlock_gift_set", new HashMap());
        o0 = new C48459J0d<>("live_limit_gift_remind_times", new HashMap());
        p0 = new C30554Byw<>("live_user_level_fe_from");
        q0 = new C48459J0d<>("had_preview_panel_opened_in_multi_guest", bool2);
        r0 = new C48459J0d<>("can_dismiss_anchor_settings_dialog_in_multi_guest", bool2);
        s0 = new C48459J0d<>("live_show_share_setting_gift_limit_red_dot", bool);
        t0 = new C48459J0d<>("had_zoom_layout_showed_in_multi_guest_audience_or_guest", bool2);
        u0 = new C48459J0d<>("live_publicscreen_auto_translate_audience", bool2);
        v0 = new C48459J0d<>("live_publicscreen_auto_translate_guide_audience", bool);
        w0 = new C48459J0d<>("live_publicscreen_auto_translate_audience_change", bool2);
        x0 = new C48459J0d<>("live_publicscreen_auto_translate_anchor", bool2);
        y0 = new C48459J0d<>("live_publicscreen_auto_translate_guide_anchor", bool);
        z0 = new C48459J0d<>("live_publicscreen_auto_translate_anchor_change", bool2);
        A0 = new C48459J0d<>("live_showed_confirm_before_send_apply_in_multi_guest", bool2);
        B0 = new C48459J0d<>("live_game_gift_separate", bool2);
        C0 = new C48459J0d<>("live_game_guide_ls_show_times", 0);
        D0 = new C48459J0d<>("live_game_guide_ls_show_last_time", 0L);
        E0 = new C48459J0d<>("live_game_guide_ls_not_pop", bool);
        F0 = new C48459J0d<>("live_landscape_slide_guide", bool);
        G0 = new C48459J0d<>("live_wallet_notice_close_id", new HashMap());
        H0 = new C48459J0d<>("live_battle_bonus_task_tip_show_count", 0L);
        I0 = new C48459J0d<>("cpc_time", "");
        J0 = new C48459J0d<>("live_cpc_server_data", new CpcPromptResponse(null, null, 0L, 0L, 0L, false));
        K0 = new C48459J0d<>("live_sub_gift_count", new HashMap());
        L0 = new C48459J0d<>("has_show_gift_box_guide", bool2);
        M0 = new C30554Byw<>("had_new_game_broadcast_enter_h5_education_page_uid");
        N0 = new C30554Byw<>("shown_live_studio_tips_widget");
        O0 = new C30554Byw<>("show_live_replay_prompt_uid");
        P0 = new C30554Byw<>("show_live_replay_prompt_private_account_uid");
        Q0 = new C30554Byw<>("had_started_obs_live");
        new C30554Byw("game_live_interruption_guide_banner_click_uid");
        R0 = new C30554Byw<>("last_show_banner_timestamp");
        S0 = new C30554Byw<>("show_banner_number");
        T0 = new C48459J0d<>("game_live_interruption_guide_complete", bool2);
        U0 = new C48459J0d<>("game_live_interruption_guide_no_complete", bool2);
        V0 = new C48459J0d<>("game_live_interruption_guide_no_show", bool);
        W0 = new C48459J0d<>("live_game_last_selected_hash_tag_id", 0L);
        X0 = new C48459J0d<>("live_comment_filter_switch_l2_filter", bool);
        Y0 = new C48459J0d<>("live_comment_filter_switch_community_flagged", bool2);
        Z0 = new C48459J0d<>("live_comment_filter_switch_community_flagged_review", bool2);
        a1 = new C48459J0d<>("follow_live_bubble_show_time", 0L);
        b1 = new C48459J0d<>("live_closing_stay_dialog_show_timestamp", 0L);
        c1 = new C48459J0d<>("live_closing_stay_dialog_show_count", 0);
        d1 = new C48459J0d<>("live_sliding_stay_dialog_show_timestamp", 0L);
        e1 = new C30554Byw<>("live_user_level_from_level_map_tag");
        f1 = new C30554Byw<>("live_user_level_model_state_cache");
        g1 = new C48459J0d<>("live_show_caption_audience_swith", bool);
        h1 = new C48459J0d<>("live_show_caption_audience_drag", bool2);
        i1 = new C48459J0d<>("live_show_caption_audience_show_share_gudience", bool2);
        j1 = new C48459J0d<>("live_show_caption_audience_server_close", bool2);
        k1 = new C48459J0d<>("live_show_caption_anchor_swith", bool);
        l1 = new C48459J0d<>("live_show_caption_anchor_pre_switch_dialog_gudience", bool2);
        m1 = new C48459J0d<>("live_show_caption_anchor_pre_switch_tooltip_gudience", bool2);
        n1 = new C48459J0d<>("live_partnership_price_update_click", 0L);
        o1 = new C48459J0d<>("live_sliding_stay_dialog_show_count", 0);
        p1 = new C30554Byw<>("live_game_gpppa_toast_showed");
        q1 = new C48459J0d<>("live_game_partnership_banner_show_count", new HashMap());
        r1 = new C48459J0d<>("live_game_partnership_is_click", new HashMap());
        s1 = new C48459J0d<>("live_game_partnership_game_topic_show", new HashMap());
        t1 = new C30554Byw<>("live_ranking_entrance_show_prompt");
        u1 = new C30554Byw<>("live_l0_enter_preview_is_first_time");
        v1 = new C30554Byw<>("live_l1_enter_preview_is_first_time");
        w1 = new C30554Byw<>("live_l2_enter_preview_is_first_time");
        x1 = new C30554Byw<>("live_anchor_tech_view_pager_index");
        y1 = new C48459J0d<>("live_l1_first_enter_preview_v2", bool);
        z1 = new C30554Byw<>("live_replay_edit_is_first_time");
        A1 = new C30554Byw<>("live_multi_guest_anchor_video_enable");
        B1 = new C48459J0d<>("live_sound_effect_mini_panel_show", bool2);
        C1 = new C48459J0d<>("live_sticker_shortcut_panel_show", bool2);
        D1 = new C30554Byw<>("live_profile_report_play_animator");
        E1 = new C30554Byw<>("live_profile_privilege_play_animator");
        F1 = new C48459J0d<>("live_pro_animation_count_anchor", 0);
        G1 = new C48459J0d<>("live_pro_animation_count_audience", 0);
        H1 = new C48459J0d<>("live_red_dot_shown_version_record", new HashMap());
        I1 = new C48459J0d<>("live_red_dot_finish_record", new HashSet());
        J1 = new C48459J0d<>("live_red_dot_last_show_time", new HashMap());
        new C48459J0d("live_red_dot_guide_complete", new HashMap());
        K1 = new C48459J0d<>("live_game_drops_banner_count", 0L);
        L1 = new C48459J0d<>("live_game_drops_banner_id", "");
        M1 = new C30554Byw<>("live_welcome_pack_click_times");
        N1 = new C30554Byw<>("live_welcome_pack_click_times_v2");
        O1 = new C30554Byw<>("live_welcome_pack_has_status");
        P1 = new C30554Byw<>("live_gift_user_is_first_gift");
        Q1 = new C48459J0d<>("live_effect_check_update_time", new HashMap());
        R1 = new C30554Byw<>("live_first_recharge_package_exchange_page_entered");
        new C48459J0d("live_effect_check_update_time_in_preview", new HashMap());
        new C48459J0d("live_effect_check_update_time_in_broadcast", new HashMap());
        new C48459J0d("live_effect_check_update_time_in_cohost", new HashMap());
        new C48459J0d("live_effect_check_update_time_in_match", new HashMap());
        new C48459J0d("live_effect_check_update_time_in_multiguest", new HashMap());
        S1 = new C48459J0d<>("live_effect_remove_list", new HashSet());
        T1 = new C48459J0d<>("live_red_dot_function_version", new HashMap());
        U1 = new C48459J0d<>("following_widget_first_show_time", 0L);
        V1 = new C48459J0d<>("following_widget_is_showed", bool2);
        W1 = new C48459J0d<>("following_widget_is_added", bool2);
        X1 = new C30554Byw<>("has_show_subs_c2c_transform_guide");
        Y1 = new C48459J0d<>("has_show_guide_subscription_bubble", new ArrayList());
        Z1 = new C30554Byw<>("has_show_subs_c2c_transform_notice");
        a2 = new C30554Byw<>("has_show_subs_c2c_not_available_notice");
        b2 = new C30554Byw<>("has_show_subs_room_entrance_tips");
        c2 = new C30554Byw<>("has_show_subs_gift_received_tips");
        d2 = new C48459J0d<>("live_first_show_camera_second_confirm", bool);
        e2 = new C48459J0d<>("live_goal_confirm_dialog_show", bool2);
        f2 = new C48459J0d<>("live_goal_capsule_show_count", 0);
        g2 = new C48459J0d<>("live_goal_info", new m());
        h2 = new C48459J0d<>("live_goal_log_params", new m());
        i2 = new C48459J0d<>("live_goal_effect_position", 0);
        j2 = new C48459J0d<>("live_goal_effect_first_use", 0);
        k2 = new C30554Byw<>("live_fans_level_start_gift_bubble_show");
        l2 = new C48459J0d<>("live_fans_club_level_config", new ArrayList());
        m2 = new C30554Byw<>("live_fans_club_entrance_guide_anim_times");
        n2 = new C30554Byw<>("live_fans_club_entrance_anchor_guide_anim_times");
        new C30554Byw("live_fans_club_entrance_click_level");
        o2 = new C30554Byw<>("live_fans_club_entrance_click_level_value");
        p2 = new C30554Byw<>("live_fans_live_center_red_dot_show_id");
        q2 = new C30554Byw<>("live_fans_live_center_tools_red_dot_show_id");
        r2 = new C48459J0d<>("live_game_opacity", 40);
        s2 = new C48459J0d<>("live_game_mic", 100);
        t2 = new C48459J0d<>("live_game_bgm", 100);
        u2 = new C48459J0d<>("live_share_to_more_guide", bool2);
        v2 = new C48459J0d<>("last_input_schema", "");
        w2 = new C48459J0d<>("live_gift_announcement_shown_count", 0);
        x2 = new C48459J0d<>("live_gift_announcement_close_ratio", Float.valueOf(0.0f));
        y2 = new C48459J0d<>("live_gift_cold_data", new HashMap());
        z2 = new C30554Byw<>("live_pro_banner_clicked");
        A2 = new C30554Byw<>("live_pro_banner_show_count");
        B2 = new C30554Byw<>("live_privilege_center_entrance");
        StringBuilder LIZ9 = X1D.LIZ();
        LIZ9.append(((IHostUser) CN1.LIZ(IHostUser.class)).getCurUserId());
        LIZ9.append("live_rank_league_primilinary_rule_period");
        C2 = new C48459J0d<>(X1D.LIZIZ(LIZ9), 0L);
        StringBuilder LIZ10 = X1D.LIZ();
        LIZ10.append(((IHostUser) CN1.LIZ(IHostUser.class)).getCurUserId());
        LIZ10.append("live_rank_league_semifinal_rule_period");
        D2 = new C48459J0d<>(X1D.LIZIZ(LIZ10), 0L);
        StringBuilder LIZ11 = X1D.LIZ();
        LIZ11.append(((IHostUser) CN1.LIZ(IHostUser.class)).getCurUserId());
        LIZ11.append("live_rank_league_final_rule_period");
        E2 = new C48459J0d<>(X1D.LIZIZ(LIZ11), 0L);
        F2 = new C30554Byw<>("live_rank_league_preliminary_rule_is_shown");
        G2 = new C30554Byw<>("live_rank_league_semifinal_rule_is_shown");
        H2 = new C30554Byw<>("live_rank_league_final_rule_is_shown");
        StringBuilder LIZ12 = X1D.LIZ();
        LIZ12.append(((IHostUser) CN1.LIZ(IHostUser.class)).getCurUserId());
        LIZ12.append("live_rank_league_primilinary_promotion_period");
        I2 = new C48459J0d<>(X1D.LIZIZ(LIZ12), 0L);
        StringBuilder LIZ13 = X1D.LIZ();
        LIZ13.append(((IHostUser) CN1.LIZ(IHostUser.class)).getCurUserId());
        LIZ13.append("live_rank_league_semifinal_promotion_period");
        J2 = new C48459J0d<>(X1D.LIZIZ(LIZ13), 0L);
        StringBuilder LIZ14 = X1D.LIZ();
        LIZ14.append(((IHostUser) CN1.LIZ(IHostUser.class)).getCurUserId());
        LIZ14.append("live_rank_league_final_promotion_period");
        K2 = new C48459J0d<>(X1D.LIZIZ(LIZ14), 0L);
        L2 = new C30554Byw<>("live_rank_league_preliminary_promotion_is_shown");
        M2 = new C30554Byw<>("live_rank_league_semifinal_promotion_is_shown");
        N2 = new C30554Byw<>("live_rank_league_final_promotion_is_shown");
        O2 = new C48459J0d<>("game_live_low_device_tips_count", 0);
        P2 = new C48459J0d<>("live_only_gift_new_gift_state", new HashMap());
        Q2 = new C48459J0d<>("live_only_gift_new_gift_version", new HashMap());
        R2 = new C48459J0d<>("live_show_activity_banner_for_anchor", bool);
        S2 = new C48459J0d<>("live_subscription_entry_migration_sheet_seen", bool2);
        T2 = new C48459J0d<>("live_subscription_entry_migration_tooltip_closed", bool2);
        U2 = new C30554Byw<>("live_subscription_sub_only_long_duration_preview");
        V2 = new C30554Byw<>("live_subscription_sub_only_long_duration_preview_shown");
        W2 = new C30554Byw<>("subscription_gift_hint_dialog_shown");
        X2 = new C48459J0d<>("access_recall_mute_end_time", -1L);
        Y2 = new C48459J0d<>("is_mic_muted", bool2);
        Z2 = new C48459J0d<>("mini_widget_status", bool2);
        a3 = new C48459J0d<>("live_star_comment_guidance_showed", bool2);
        b3 = new C48459J0d<>("live_star_comment_purchase", 0);
        c3 = new C30554Byw<>("live_user_level_show_privilege_map");
        d3 = new C48459J0d<>("sticker_insert_timestamp", new HashMap());
        e3 = new C48459J0d<>("host_ever_opened_sub_only_live", bool2);
        f3 = new C48459J0d<>("host_ignore_sub_only_guide_times", 0);
        g3 = new C48459J0d<>("host_sub_only_live_guide_silent_ts", 0L);
        h3 = new C48459J0d<>("live_gift_rank_tip_cant_on", new HashMap());
        i3 = new C48459J0d<>("live_game_dual_device_position_land", 0);
        j3 = new C48459J0d<>("live_game_dual_device_position_port", 0);
        k3 = new C48459J0d<>("crash_in_watch_live", bool2);
        l3 = new C48459J0d<>("pre_download_game_intro_card", "");
        new C48459J0d("live_banner", "");
        m3 = new C48459J0d<>("live_banner_block", new HashMap());
        n3 = new C48459J0d<>("live_banner_time", 0L);
        f68o3 = new C48459J0d<>("live_multi_cohost_reserve_button_clicked", bool2);
        p3 = new C48459J0d<>("live_multi_cohost_reserve_education_count", 0);
        q3 = new C48459J0d<>("live_multi_cohost_tag_animation", 0L);
        r3 = new C48459J0d<>("live_multi_guest_shared_bg_red_doc_should_show", bool);
        s3 = new C48459J0d<>("try_mode_co_host_webp_showed", bool);
        t3 = new C48459J0d<>("try_mode_multi_guest_webp_showed", bool);
        u3 = new C48459J0d<>("try_mode_interaction_webp_showed", bool);
        v3 = new C48459J0d<>("try_mode_gifts_webp_showed", bool);
        w3 = new C48459J0d<>("live_guide_inbox_to_follow_uid", new HashSet());
        x3 = new C48459J0d<>("live_preivew_livegoal_guide_shown", bool2);
        y3 = new C48459J0d<>("karaoke_widget_default_open", bool2);
        z3 = new C48459J0d<>("karaoke_download_cache", new ArrayList());
        A3 = new C48459J0d<>("karaoke_drag_guide_shown", bool2);
        new C48459J0d("karaoke_close_guide_shown", bool2);
        B3 = new C48459J0d<>("karaoke_sound_effect_selected_id", "");
        C3 = new C48459J0d<>("karaoke_vocal_volume", -1);
        D3 = new C48459J0d<>("karaoke_accompaniment_volume", -1);
        new C48459J0d("karaoke_tones", 0);
        E3 = new C48459J0d<>("karaoke_lyrics_switch", bool);
        F3 = new C48459J0d<>("karaoke_original_switch", bool2);
        G3 = new C48459J0d<>("karaoke_host_hoverball_pos_y", valueOf);
        H3 = new C48459J0d<>("karaoke_audience_hoverball_pos_y", valueOf);
        I3 = new C30554Byw<>("live_subscription_sub_only_allow_music_confirmation_shown");
        J3 = new C30554Byw<>("live_subscription_sub_only_allow_music_dialog_shown");
    }
}
