package X;

import com.bytedance.android.livesdk.livesetting.roomfunction.LowAgeAnchorLimitSetting;
import org.json.JSONArray;
import org.json.JSONObject;

/* loaded from: classes9.dex */
public final class IQW {
    public static void LIZ(JSONObject jSONObject, JSONObject jSONObject2) {
        JSONArray jSONArray = new JSONArray();
        jSONArray.put("config_5");
        jSONObject.put("4", jSONArray);
        JSONArray jSONArray2 = new JSONArray();
        jSONArray2.put("config_18");
        jSONArray2.put("config_15");
        jSONObject.put("12", jSONArray2);
        JSONArray jSONArray3 = new JSONArray();
        jSONArray3.put("config_19");
        jSONArray3.put("config_15");
        jSONObject.put("13", jSONArray3);
        JSONArray jSONArray4 = new JSONArray();
        jSONArray4.put("config_20");
        jSONArray4.put("config_16");
        jSONObject.put("14", jSONArray4);
        JSONArray jSONArray5 = new JSONArray();
        jSONArray5.put("config_21");
        jSONArray5.put("config_16");
        jSONObject.put("15", jSONArray5);
        JSONArray jSONArray6 = new JSONArray();
        jSONArray6.put("config_22");
        jSONArray6.put("config_16");
        jSONObject.put("16", jSONArray6);
        JSONArray jSONArray7 = new JSONArray();
        jSONArray7.put("config_23");
        jSONArray7.put("config_16");
        jSONObject.put("17", jSONArray7);
        JSONArray jSONArray8 = new JSONArray();
        jSONArray8.put("config_24");
        jSONArray8.put("config_16");
        jSONObject.put(LowAgeAnchorLimitSetting.DEFAULT, jSONArray8);
        JSONArray jSONArray9 = new JSONArray();
        jSONArray9.put("config_16");
        jSONArray9.put("config_25");
        jSONObject.put("19", jSONArray9);
        JSONArray jSONArray10 = new JSONArray();
        jSONArray10.put("config_17");
        jSONArray10.put("config_26");
        jSONObject.put("20", jSONArray10);
        JSONArray jSONArray11 = new JSONArray();
        jSONArray11.put("config_27");
        jSONObject.put("21", jSONArray11);
        JSONArray jSONArray12 = new JSONArray();
        jSONArray12.put("config_16");
        jSONArray12.put("config_31");
        jSONObject.put("25", jSONArray12);
        JSONArray jSONArray13 = new JSONArray();
        jSONArray13.put("config_16");
        jSONArray13.put("config_32");
        jSONObject.put("26", jSONArray13);
        JSONArray jSONArray14 = new JSONArray();
        jSONArray14.put("config_16");
        jSONArray14.put("config_34");
        jSONObject.put("29", jSONArray14);
        JSONArray jSONArray15 = new JSONArray();
        jSONArray15.put("config_15");
        jSONArray15.put("config_35");
        jSONObject.put("30", jSONArray15);
        JSONArray jSONArray16 = new JSONArray();
        jSONArray16.put("config_27");
        jSONObject.put("32", jSONArray16);
        JSONArray jSONArray17 = new JSONArray();
        jSONArray17.put("config_16");
        jSONArray17.put("config_39");
        jSONObject.put("35", jSONArray17);
        jSONObject2.put("config_15", "{\"params\":{\"allowList\":[\"getLastKnowLocation\",\"location_getLastKnownLocation\"]},\"type\":\"entryVerify\"}");
        jSONObject2.put("config_16", "{\"params\":{\"allowList\":[\"getLocationCert\",\"getLocation\",\"getLastKnownLocation\",\"requestSingleUpdate\",\"location_getLastKnownLocation\",\"location_requestSingleUpdate\"]},\"type\":\"entryVerify\"}");
        jSONObject2.put("config_17", "{\"params\":{\"configuration\":{\"allow_fetch_config_at_start\":true,\"chinese_channel\":false,\"enable_h3\":1,\"enable_traceroute\":true,\"h3_distance\":1,\"h3_resolution\":7,\"is_upload\":true,\"is_upload_location\":true,\"latlng_precision\":2,\"location_ropa_encrypt\":true,\"overseas_upload_interval\":86400,\"report_at_start\":false,\"report_gps\":true,\"upload_max_count\":1}},\"type\":\"config\"}");
        jSONObject2.put("config_18", "{\"params\":{\"configuration\":{\"accuracyLevel\":4,\"enable_h3\":false,\"location_mode\":2}},\"type\":\"config\"}");
        jSONObject2.put("config_19", "{\"params\":{\"configuration\":{\"accuracyLevel\":3,\"enable_h3\":false,\"location_mode\":2}},\"type\":\"config\"}");
        jSONObject2.put("config_20", "{\"params\":{\"configuration\":{\"accuracy_level\":4,\"cache_time\":0,\"enable_h3\":false,\"geocode_mode\":1,\"locate_type\":0,\"location_mode\":2,\"time_out\":30000}},\"type\":\"config\"}");
        jSONObject2.put("config_21", "{\"params\":{\"configuration\":{\"accuracy_level\":3,\"cache_time\":0,\"enable_h3\":false,\"geocode_mode\":1,\"locate_type\":0,\"location_mode\":2,\"time_out\":30000}},\"type\":\"config\"}");
        jSONObject2.put("config_22", "{\"params\":{\"configuration\":{\"accuracy_level\":3,\"cache_time\":3600000,\"enable_h3\":false,\"geocode_mode\":1,\"locate_type\":0,\"location_mode\":2,\"time_out\":30000}},\"type\":\"config\"}");
        jSONObject2.put("config_23", "{\"params\":{\"configuration\":{\"accuracy_level\":4,\"cache_time\":3600000,\"enable_h3\":false,\"geocode_mode\":1,\"locate_type\":0,\"location_mode\":2,\"time_out\":30000}},\"type\":\"config\"}");
        jSONObject2.put("config_24", "{\"params\":{\"configuration\":{\"accuracy_level\":4,\"cache_time\":0,\"enable_h3\":false,\"geocode_mode\":0,\"locate_type\":0,\"location_mode\":2,\"time_out\":30000}},\"type\":\"config\"}");
        jSONObject2.put("config_25", "{\"params\":{\"configuration\":{\"accuracy_level\":4,\"cache_time\":3600000,\"enable_h3\":false,\"geocode_mode\":0,\"locate_type\":0,\"location_mode\":2,\"time_out\":30000}},\"type\":\"config\"}");
        jSONObject2.put("config_26", "{\"params\":{\"allowList\":[\"init\"]},\"type\":\"entryVerify\"}");
        jSONObject2.put("config_27", "{\"params\":{\"placeholder\":{}},\"type\":\"placeholder\"}");
        jSONObject2.put("config_31", "{\"params\":{\"configuration\":{\"accuracy_level\":4,\"cache_time\":0,\"enable_h3\":true,\"geocode_mode\":1,\"locate_type\":0,\"location_mode\":0,\"time_out\":30000}},\"type\":\"config\"}");
        jSONObject2.put("config_32", "{\"params\":{\"configuration\":{\"accuracy_level\":4,\"cache_time\":3600000,\"enable_h3\":true,\"geocode_mode\":1,\"locate_type\":0,\"location_mode\":0,\"time_out\":30000}},\"type\":\"config\"}");
        jSONObject2.put("config_34", "{\"params\":{\"configuration\":{\"accuracy_level\":4,\"cache_time\":3600000,\"enable_h3\":false,\"geocode_mode\":0,\"locate_type\":0,\"location_mode\":2,\"need_unshifted_latlng\":true,\"time_out\":30000}},\"type\":\"config\"}");
        jSONObject2.put("config_35", "{\"params\":{\"configuration\":{\"accuracyLevel\":4,\"enable_h3\":false,\"location_mode\":2,\"need_unshifted_latlng\":true}},\"type\":\"config\"}");
        jSONObject2.put("config_39", "{\"params\":{\"configuration\":{\"accuracy_level\":4,\"cache_time\":0,\"enable_h3\":false,\"geocode_mode\":1,\"locate_type\":0,\"location_mode\":2,\"time_out\":10000}},\"type\":\"config\"}");
        jSONObject2.put("config_5", "{\"params\":{\"allowList\":[\"Decrypt\"]},\"type\":\"entryVerify\"}");
    }
}
