package X;

import java.io.Serializable;
import kotlin.jvm.internal.DefaultConstructorMarker;
import kotlin.jvm.internal.o;

/* loaded from: classes9.dex */
public final class IYA implements Serializable {
    public final long LJLIL;
    public final String LJLILLLLZI;
    public final String LJLJI;
    public final int LJLJJI;
    public final String LJLJJL;
    public final String LJLJJLL;
    public final long LJLJL;
    public final boolean LJLJLJ;
    public final long LJLJLLL;
    public final long LJLL;
    public final int LJLLI;
    public String LJLLILLLL;

    public static /* synthetic */ IYA copy$default(IYA iya, long j, String str, String str2, int i, String str3, String str4, long j2, boolean z, long j3, long j4, int i2, String str5, int i3, Object obj) {
        String str6 = str;
        long j5 = j;
        String str7 = str3;
        String str8 = str2;
        int i4 = i;
        long j6 = j2;
        String str9 = str4;
        long j7 = j3;
        boolean z2 = z;
        long j8 = j4;
        int i5 = i2;
        String str10 = str5;
        if ((i3 & 1) != 0) {
            j5 = iya.LJLIL;
        }
        if ((i3 & 2) != 0) {
            str6 = iya.LJLILLLLZI;
        }
        if ((i3 & 4) != 0) {
            str8 = iya.LJLJI;
        }
        if ((i3 & 8) != 0) {
            i4 = iya.LJLJJI;
        }
        if ((i3 & 16) != 0) {
            str7 = iya.LJLJJL;
        }
        if ((i3 & 32) != 0) {
            str9 = iya.LJLJJLL;
        }
        if ((i3 & 64) != 0) {
            j6 = iya.LJLJL;
        }
        if ((i3 & 128) != 0) {
            z2 = iya.LJLJLJ;
        }
        if ((i3 & 256) != 0) {
            j7 = iya.LJLJLLL;
        }
        if ((i3 & 512) != 0) {
            j8 = iya.LJLL;
        }
        if ((i3 & 1024) != 0) {
            i5 = iya.LJLLI;
        }
        if ((i3 & 2048) != 0) {
            str10 = iya.LJLLILLLL;
        }
        int i6 = i4;
        return iya.copy(j5, str6, str8, i6, str7, str9, j6, z2, j7, j8, i5, str10);
    }

    public final IYA copy(long j, String captionFormat, String lang, int i, String subVersion, String url, long j2, boolean z, long j3, long j4, int i2, String str) {
        o.LJIIIZ(captionFormat, "captionFormat");
        o.LJIIIZ(lang, "lang");
        o.LJIIIZ(subVersion, "subVersion");
        o.LJIIIZ(url, "url");
        return new IYA(j, captionFormat, lang, i, subVersion, url, j2, z, j3, j4, i2, str);
    }

    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (!(obj instanceof IYA)) {
            return false;
        }
        IYA iya = (IYA) obj;
        return this.LJLIL == iya.LJLIL && o.LJ(this.LJLILLLLZI, iya.LJLILLLLZI) && o.LJ(this.LJLJI, iya.LJLJI) && this.LJLJJI == iya.LJLJJI && o.LJ(this.LJLJJL, iya.LJLJJL) && o.LJ(this.LJLJJLL, iya.LJLJJLL) && this.LJLJL == iya.LJLJL && this.LJLJLJ == iya.LJLJLJ && this.LJLJLLL == iya.LJLJLLL && this.LJLL == iya.LJLL && this.LJLLI == iya.LJLLI && o.LJ(this.LJLLILLLL, iya.LJLLILLLL);
    }

    public String toString() {
        return "CaptionInfo(expire=" + this.LJLIL + ", captionFormat=" + this.LJLILLLLZI + ", lang=" + this.LJLJI + ", subId=" + this.LJLJJI + ", subVersion=" + this.LJLJJL + ", url=" + this.LJLJJLL + ", languageId=" + this.LJLJL + ", isAutoGenerated=" + this.LJLJLJ + ", complaintId=" + this.LJLJLLL + ", createTime=" + this.LJLL + ", id=" + this.LJLLI + ", uri=" + ((Object) this.LJLLILLLL) + ')';
    }

    /* JADX WARN: Multi-variable type inference failed */
    public int hashCode() {
        int hashCode;
        int LIZJ = JBR.LIZJ(this.LJLJL, C79062V1e.LJ(this.LJLJJLL, C79062V1e.LJ(this.LJLJJL, (C79062V1e.LJ(this.LJLJI, C79062V1e.LJ(this.LJLILLLLZI, C16880lQ.LLJIJIL(this.LJLIL) * 31, 31), 31) + this.LJLJJI) * 31, 31), 31), 31);
        boolean z = this.LJLJLJ;
        int i = z;
        if (z != 0) {
            i = 1;
        }
        int LIZJ2 = (JBR.LIZJ(this.LJLL, JBR.LIZJ(this.LJLJLLL, (LIZJ + i) * 31, 31), 31) + this.LJLLI) * 31;
        String str = this.LJLLILLLL;
        if (str == null) {
            hashCode = 0;
        } else {
            hashCode = str.hashCode();
        }
        return LIZJ2 + hashCode;
    }

    public final String getCaptionFormat() {
        return this.LJLILLLLZI;
    }

    public final long getComplaintId() {
        return this.LJLJLLL;
    }

    public final long getCreateTime() {
        return this.LJLL;
    }

    public final long getExpire() {
        return this.LJLIL;
    }

    public final int getId() {
        return this.LJLLI;
    }

    public final String getLang() {
        return this.LJLJI;
    }

    public final long getLanguageId() {
        return this.LJLJL;
    }

    public final int getSubId() {
        return this.LJLJJI;
    }

    public final String getSubVersion() {
        return this.LJLJJL;
    }

    public final String getUri() {
        return this.LJLLILLLL;
    }

    public final String getUrl() {
        return this.LJLJJLL;
    }

    public final boolean isAutoGenerated() {
        return this.LJLJLJ;
    }

    public final void setUri(String str) {
        this.LJLLILLLL = str;
    }

    public IYA(long j, String str, String str2, int i, String str3, String str4, long j2, boolean z, long j3, long j4, int i2, String str5) {
        C43588H8u.LIZLLL(str, "captionFormat", str2, "lang", str3, "subVersion", str4, "url");
        this.LJLIL = j;
        this.LJLILLLLZI = str;
        this.LJLJI = str2;
        this.LJLJJI = i;
        this.LJLJJL = str3;
        this.LJLJJLL = str4;
        this.LJLJL = j2;
        this.LJLJLJ = z;
        this.LJLJLLL = j3;
        this.LJLL = j4;
        this.LJLLI = i2;
        this.LJLLILLLL = str5;
    }

    public /* synthetic */ IYA(long j, String str, String str2, int i, String str3, String str4, long j2, boolean z, long j3, long j4, int i2, String str5, int i3, DefaultConstructorMarker defaultConstructorMarker) {
        this(j, str, str2, i, str3, str4, j2, z, j3, j4, i2, (i3 & 2048) != 0 ? null : str5);
    }
}
