package X;

import com.bytedance.android.livesdk.livesetting.performance.LiveGiftNewGifterBadgeSetting;
import org.json.JSONArray;

/* loaded from: classes15.dex */
public final class VAG {
    public long LIZ;
    public long LIZIZ;
    public long LIZJ;
    public long LIZLLL;
    public long LJ;
    public long LJFF;
    public long LJI;
    public long LJII;
    public long LJIIIIZZ;
    public long LJIIIZ;
    public long LJIIJ;
    public long LJIIJJI;
    public long LJIIL;
    public long LJIILIIL;
    public long LJIILJJIL;
    public long LJIILL;
    public long LJIILLIIL;
    public long LJIIZILJ;
    public long LJIJ;
    public long LJIJI;
    public long LJIJJ;
    public long LJIJJLI;
    public long LJIL;
    public long LJJ;
    public long LJJI;
    public long LJJIFFI;
    public long LJJII;
    public long LJJIII;
    public long LJJIIJ;
    public long LJJIIJZLJL;
    public long LJJIIZ;
    public long LJJIIZI;
    public int LJJIJLIJ;
    public int LJJJJI;
    public int LJJJJIZL;
    public long LJJJJJ;
    public long LJJJJLI;
    public long LJJJJLL;
    public long LJJJJZ;
    public long LJJJJZI;
    public long LJJJLIIL;
    public long LJJJLL;
    public long LJJJLZIJ;
    public long LJJJZ;
    public long LJJL;
    public long LJJLI;
    public long LJJLIIIJLJLI;
    public long LJJLIIIJLLLLLLLZ;
    public long LJJZZI;
    public long LJJZZIII;
    public long LJL;
    public long LJLI;
    public long LJLIIIL;
    public long LJLIIL;
    public long LJLJJLL;
    public long LJLJL;
    public long LJLJLJ;
    public float LJLJLLL;
    public long LJLL;
    public long LJLLI;
    public long LJLLILLLL;
    public long LJLLJ;
    public long LJLLL;
    public long LJLLLL;
    public int LJLLLLLL;
    public long LJLZ;
    public long LJZ;
    public long LJZI;
    public long LJZL;
    public long LL;
    public long LLD;
    public long LLFF;
    public long LLFFF;
    public long LLFII;
    public int LLI;
    public long LLIIIJ;
    public long LLIIIL;
    public long LLIIJI;
    public long LLIIJLIL;
    public long LLIIL;
    public long LLIILII;
    public int LLIZ;
    public int LLJ;
    public int LLJJI;
    public int LLJJJJLIIL;
    public int LLJJL;
    public int LLJJLIIIJLLLLLLLZ;
    public int LLJL;
    public long LLJLLL;
    public long LLJZ;
    public long LLJZIJLIL;
    public long LLL;
    public long LLLF;
    public long LLLFF;
    public long LLLFFI;
    public long LLLFZ;
    public long LLLI;
    public long LLLII;
    public long LLLIIII;
    public long LLLIIIIL;
    public long LLLIIIL;
    public long LLLIIL;
    public long LLLIILIL;
    public JSONArray LLLILZLLLI;
    public int LLLJ;
    public JSONArray LLLJIL;
    public long LLLL;
    public long LLLLII;
    public long LLLLIIIILLL;
    public long LLLLIIL;
    public long LLLLIILL;
    public long LLLLIILLL;
    public long LLLLIL;
    public long LLLLILI;
    public long LLLLJ;
    public int LLLLJI;
    public int LLLLL;
    public int LLLLLIL;
    public int LLLLLILLIL;
    public int LLLLLJIL;
    public int LLLLLJLJLL;
    public long LLLLLL;
    public long LLLLLLIL;
    public long LLLLLLJ;
    public long LLLLLLL;
    public long LLLLLLLLL;
    public long LLLLLLLLLL;
    public long LLLLLLLZIL;
    public String LJJIJ = "";
    public String LJJIJIIJI = "";
    public String LJJIJIIJIL = "";
    public String LJJIJIL = "";
    public String LJJIJL = "";
    public long LJJIL = -1;
    public long LJJIZ = -1;
    public long LJJJ = -1;
    public long LJJJI = -1;
    public long LJJJIL = -1;
    public long LJJJJ = -1;
    public int LJJJJJL = -1;
    public int LJJJJL = -1;
    public long LJJLIIIIJ = -1;
    public long LJJLIIIJ = -1;
    public long LJJLIIIJILLIZJL = -1;
    public long LJJLIIIJJI = -1;
    public long LJJLIIIJJIZ = -1;
    public long LJJLIIIJL = -1;
    public int LJJLIIJ = -1;
    public int LJJLIL = -1;
    public int LJJLJ = -1;
    public int LJJLJLI = -1;
    public int LJJLL = -1;
    public int LJJZ = -1;
    public long LJLIL = -1;
    public long LJLILLLLZI = -1;
    public String LJLJI = "";
    public long LJLJJI = -1;
    public long LJLJJL = -1;
    public int LLF = -1;
    public String LLFZ = LiveGiftNewGifterBadgeSetting.DEFAULT;
    public String LLIFFJFJJ = LiveGiftNewGifterBadgeSetting.DEFAULT;
    public int LLII = -1;
    public int LLIIII = -1;
    public int LLIIIILZ = -1;
    public int LLIIIZ = -1;
    public String LLIILZL = LiveGiftNewGifterBadgeSetting.DEFAULT;
    public String LLIIZ = LiveGiftNewGifterBadgeSetting.DEFAULT;
    public String LLIL = LiveGiftNewGifterBadgeSetting.DEFAULT;
    public String LLILII = LiveGiftNewGifterBadgeSetting.DEFAULT;
    public String LLILIL = "0.0.0.0";
    public String LLILL = "";
    public String LLILLIZIL = "";
    public String LLILLJJLI = "";
    public int LLILLL = -1;
    public String LLILZ = "";
    public String LLILZIL = "";
    public int LLILZLL = -1;
    public int LLIZLLLIL = -1;
    public int LLJI = -1;
    public int LLJIJIL = -1;
    public int LLJILJIL = -1;
    public int LLJILJILJ = -1;
    public String LLJILLL = "{}";
    public String LLJJ = "";
    public String LLJJIII = "";
    public String LLJJIJI = "";
    public int LLJJIJIIJIL = -1;
    public int LLJJIJIL = -1;
    public long LLJJJ = -1;
    public long LLJJJIL = -1;
    public long LLJJJJ = -1;
    public long LLJJJJJIL = -1;
    public String LLJLIL = "";
    public String LLJLILLLLZIIL = "";
    public String LLJLL = "";
    public String LLJLLIL = "";
    public String LLLIL = LiveGiftNewGifterBadgeSetting.DEFAULT;
    public String LLLILZ = "";
    public int LLLILZJ = -1;
    public int LLLIZZ = -1;
    public int LLLJL = -1;
    public String LLLLLLZ = "";
    public long LLLLLLZZ = -1;
    public int LLLLLZ = -1;
    public int LLLLLZIL = -1;
    public String LLLLLZL = "";
    public String LLLLZ = "";
    public int LLLLZI = 1;
    public int LLLLZIL = 1;

    public final void LIZ() {
        this.LIZ = 0L;
        this.LIZJ = 0L;
        this.LIZLLL = 0L;
        this.LJ = 0L;
        this.LJFF = 0L;
        this.LJIIJ = 0L;
        this.LJIILJJIL = 0L;
        this.LJIIZILJ = 0L;
        this.LJIJ = 0L;
        this.LJIJI = 0L;
        this.LJIJJ = 0L;
        this.LJIJJLI = 0L;
        this.LJIL = 0L;
        this.LJZI = 0L;
        this.LJZL = 0L;
        this.LL = 0L;
        this.LLD = 0L;
        this.LLF = -1;
        this.LJJ = 0L;
        this.LJJIIJZLJL = 0L;
        this.LJJIIZ = 0L;
        this.LJJIIZI = 0L;
        this.LJJIL = -1L;
        this.LJJIZ = -1L;
        this.LJJJ = -1L;
        this.LJJJI = -1L;
        this.LJJJIL = -1L;
        this.LJJJJ = -1L;
        this.LJJJJI = 0;
        this.LJJJJIZL = 0;
        this.LJJJJJ = 0L;
        this.LJJJJJL = -1;
        this.LJJJJL = -1;
        this.LJJJJLI = 0L;
        this.LJJJJLL = 0L;
        this.LJJJLIIL = 0L;
        this.LJJJLL = 0L;
        this.LJJII = 0L;
        this.LJJIIJ = 0L;
        this.LJJJLZIJ = 0L;
        this.LJJJZ = 0L;
        this.LJJL = 0L;
        this.LJJLI = 0L;
        this.LJJLIIJ = -1;
        this.LJJLIL = -1;
        this.LJJLJ = -1;
        this.LJJLJLI = -1;
        this.LJJLL = -1;
        this.LJJZ = -1;
        this.LLJI = -1;
        this.LLJIJIL = -1;
        this.LJJLIIIIJ = -1L;
        this.LJJLIIIJ = -1L;
        this.LJJLIIIJILLIZJL = -1L;
        this.LJJLIIIJJI = -1L;
        this.LLJILJIL = -1;
        this.LJJLIIIJJIZ = -1L;
        this.LJJLIIIJL = -1L;
        this.LLLIZZ = -1;
        this.LJJLIIIJLJLI = 0L;
        this.LJJLIIIJLLLLLLLZ = 0L;
        this.LLJJIJIIJIL = -1;
        this.LLJJIJIL = -1;
        this.LLJILJILJ = -1;
        this.LJI = 0L;
        this.LJII = 0L;
        this.LJIIIIZZ = 0L;
        this.LJIIIZ = 0L;
        this.LLJJI = 0;
        this.LLJJIII = "";
        this.LLJJIJI = "";
        this.LJJZZI = 0L;
        this.LJJZZIII = 0L;
        this.LJLJLLL = 0.0f;
        this.LJLZ = 0L;
        this.LJZ = 0L;
        this.LJIILL = 0L;
        this.LJIILLIIL = 0L;
        this.LLII = -1;
        this.LLIIII = -1;
        this.LLJLLL = 0L;
        this.LIZIZ = 0L;
        this.LLJZ = 0L;
        this.LLJZIJLIL = 0L;
        this.LLL = 0L;
        this.LLLF = 0L;
        this.LLLFF = 0L;
        this.LLLFFI = 0L;
        this.LLLFZ = 0L;
        this.LLLI = 0L;
        this.LLLII = 0L;
        this.LJIIJJI = 0L;
        this.LJIIL = 0L;
        this.LJIILIIL = 0L;
        this.LLLIIII = 0L;
        this.LLLIL = LiveGiftNewGifterBadgeSetting.DEFAULT;
        this.LJLJJLL = 0L;
        this.LJLJL = 0L;
        this.LLIILZL = LiveGiftNewGifterBadgeSetting.DEFAULT;
        this.LLFF = 0L;
        this.LLFFF = 0L;
        this.LLFII = 0L;
        this.LLFZ = LiveGiftNewGifterBadgeSetting.DEFAULT;
        this.LLI = 0;
        this.LLIFFJFJJ = LiveGiftNewGifterBadgeSetting.DEFAULT;
        this.LLLILZJ = -1;
        this.LLLILZLLLI = null;
        this.LLLJ = 0;
        this.LLLJIL = null;
        this.LLILIL = "0.0.0.0";
        this.LLILL = "";
        this.LLILLIZIL = "";
        this.LLILLJJLI = "";
        this.LLILZ = "";
        this.LLILZIL = "";
        this.LLILLL = -1;
        this.LLILZLL = -1;
        this.LLIZ = 0;
        this.LJJIJIIJI = "";
        this.LJJIJIIJIL = "";
        this.LJJIJIL = "";
        this.LJJIJL = "";
        this.LLLL = 0L;
        this.LLLLII = 0L;
        this.LLLLIIIILLL = 0L;
        this.LLLLIIL = 0L;
        this.LLLLIILL = 0L;
        this.LLLLIILLL = 0L;
        this.LLLLIL = 0L;
        this.LLLLILI = 0L;
        this.LLLLJ = 0L;
        this.LLLLJI = 0;
        this.LLLLL = 0;
        this.LLLLLIL = 0;
        this.LLLLLILLIL = 0;
        this.LLLLLJIL = 0;
        this.LLLLLJLJLL = 0;
        this.LLLLLL = 0L;
        this.LLLLLLIL = 0L;
        this.LLLLLLJ = 0L;
        this.LLLLLLL = 0L;
        this.LLLLLLLLL = 0L;
        this.LLLLLLLLLL = 0L;
        this.LLLLLLLZIL = 0L;
        this.LLLLLLZ = "";
        this.LLLLLLZZ = -1L;
        this.LJLI = 0L;
        this.LJL = 0L;
        this.LJLIL = -1L;
        this.LJLILLLLZI = -1L;
        this.LJLJI = "";
        this.LLLLLZ = -1;
        this.LLLLLZIL = -1;
        this.LLLLLZL = "";
        this.LLLLZ = "";
        this.LLLLZI = 1;
        this.LLLLZIL = 1;
        this.LJLLI = 0L;
        this.LJLLILLLL = 0L;
        this.LJLLJ = 0L;
        this.LJLLL = 0L;
        this.LJLLLL = 0L;
    }
}
