package X;

/* loaded from: classes15.dex */
public final class WCW {
    public static final /* synthetic */ InterfaceC74236TBo[] LIZ;
    public static final C62822Ol8 LIZIZ;
    public static final C62822Ol8 LIZJ;
    public static final C62822Ol8 LIZLLL;
    public static final C62822Ol8 LJ;
    public static final C62822Ol8 LJFF;
    public static final C62822Ol8 LJI;
    public static final C62822Ol8 LJII;
    public static final C62822Ol8 LJIIIIZZ;
    public static final C62822Ol8 LJIIIZ;
    public static final C62822Ol8 LJIIJ;
    public static final C62822Ol8 LJIIJJI;
    public static final C62822Ol8 LJIIL;
    public static final C62822Ol8 LJIILIIL;
    public static final C62822Ol8 LJIILJJIL;
    public static final C62822Ol8 LJIILL;
    public static final C62822Ol8 LJIILLIIL;
    public static final C62822Ol8 LJIIZILJ;
    public static final C62822Ol8 LJIJ;
    public static final C62822Ol8 LJIJI;
    public static final C62822Ol8 LJIJJ;
    public static final C62822Ol8 LJIJJLI;
    public static final C62822Ol8 LJIL;
    public static final C62822Ol8 LJJ;
    public static final C62822Ol8 LJJI;
    public static final C62822Ol8 LJJIFFI;
    public static final C62822Ol8 LJJII;
    public static final C62822Ol8 LJJIII;
    public static final C62822Ol8 LJJIIJ;
    public static final C62822Ol8 LJJIIJZLJL;
    public static final C62822Ol8 LJJIIZ;
    public static final C62822Ol8 LJJIIZI;
    public static final C62822Ol8 LJJIJ;
    public static final C62822Ol8 LJJIJIIJI;
    public static final C62822Ol8 LJJIJIIJIL;
    public static final C62822Ol8 LJJIJIL;
    public static final C62822Ol8 LJJIJL;
    public static final C62822Ol8 LJJIJLIJ;
    public static final C62822Ol8 LJJIL;
    public static final C62822Ol8 LJJIZ;
    public static final C62822Ol8 LJJJ;
    public static final C62822Ol8 LJJJI;
    public static final WCW LJJJIL;

    static {
        TBT tbt = new TBT(C65352Pkq.LIZ(WCW.class), "lazy_context", "getLazy_context()Landroid/content/Context;");
        C65352Pkq.LIZ.getClass();
        LIZ = new InterfaceC74236TBo[]{tbt, new TBT(C65352Pkq.LIZ(WCW.class), "lazy_bitmapConfig", "getLazy_bitmapConfig()Landroid/graphics/Bitmap$Config;"), new TBT(C65352Pkq.LIZ(WCW.class), "lazy_PreDecodeFrameCount", "getLazy_PreDecodeFrameCount()Ljava/lang/Integer;"), new TBT(C65352Pkq.LIZ(WCW.class), "lazy_ImageFetcherFactory", "getLazy_ImageFetcherFactory()Lcom/bytedance/lighten/core/ImageFetcherFactory;"), new TBT(C65352Pkq.LIZ(WCW.class), "lazy_DiskCacheDir", "getLazy_DiskCacheDir()Ljava/io/File;"), new TBT(C65352Pkq.LIZ(WCW.class), "lazy_MaxBitmapMemoryCacheSize", "getLazy_MaxBitmapMemoryCacheSize()Ljava/lang/Long;"), new TBT(C65352Pkq.LIZ(WCW.class), "lazy_MaxEncodedMemoryCacheSize", "getLazy_MaxEncodedMemoryCacheSize()Ljava/lang/Long;"), new TBT(C65352Pkq.LIZ(WCW.class), "lazy_MaxDiskCacheSize", "getLazy_MaxDiskCacheSize()Ljava/lang/Long;"), new TBT(C65352Pkq.LIZ(WCW.class), "lazy_SmallDiskMaxCacheSize", "getLazy_SmallDiskMaxCacheSize()Ljava/lang/Long;"), new TBT(C65352Pkq.LIZ(WCW.class), "lazy_DebugLevel", "getLazy_DebugLevel()Ljava/lang/Integer;"), new TBT(C65352Pkq.LIZ(WCW.class), "lazy_ForceInit", "getLazy_ForceInit()Ljava/lang/Boolean;"), new TBT(C65352Pkq.LIZ(WCW.class), "lazy_CacheKeyWithoutHost", "getLazy_CacheKeyWithoutHost()Ljava/lang/Boolean;"), new TBT(C65352Pkq.LIZ(WCW.class), "lazy_CacheKeyOnlyPath", "getLazy_CacheKeyOnlyPath()Ljava/lang/Boolean;"), new TBT(C65352Pkq.LIZ(WCW.class), "lazy_CacheNoHostAllowlist", "getLazy_CacheNoHostAllowlist()[Ljava/lang/String;"), new TBT(C65352Pkq.LIZ(WCW.class), "lazy_EnableMemoryCacheTracker", "getLazy_EnableMemoryCacheTracker()Ljava/lang/Boolean;"), new TBT(C65352Pkq.LIZ(WCW.class), "lazy_ConverterFactory", "getLazy_ConverterFactory()Lcom/bytedance/lighten/core/converter/Converter$Factory;"), new TBT(C65352Pkq.LIZ(WCW.class), "lazy_EnableImageMonitor", "getLazy_EnableImageMonitor()Ljava/lang/Boolean;"), new TBT(C65352Pkq.LIZ(WCW.class), "lazy_EnableMonitorLog", "getLazy_EnableMonitorLog()Ljava/lang/Boolean;"), new TBT(C65352Pkq.LIZ(WCW.class), "lazy_EnableOpt", "getLazy_EnableOpt()Ljava/lang/Boolean;"), new TBT(C65352Pkq.LIZ(WCW.class), "lazy_ImageMonitorListener", "getLazy_ImageMonitorListener()Lcom/bytedance/lighten/core/listener/ImageMonitorListener;"), new TBT(C65352Pkq.LIZ(WCW.class), "lazy_CacheEventListener", "getLazy_CacheEventListener()Lcom/bytedance/lighten/core/listener/CacheEventListener;"), new TBT(C65352Pkq.LIZ(WCW.class), "lazy_AnimationFrameSchedulers", "getLazy_AnimationFrameSchedulers()Ljava/util/List;"), new TBT(C65352Pkq.LIZ(WCW.class), "lazy_TrimMemory", "getLazy_TrimMemory()Ljava/lang/Boolean;"), new TBT(C65352Pkq.LIZ(WCW.class), "lazy_SoLoader", "getLazy_SoLoader()Lcom/bytedance/lighten/core/ISoLoader;"), new TBT(C65352Pkq.LIZ(WCW.class), "lazy_EnablePieDecode", "getLazy_EnablePieDecode()Ljava/lang/Boolean;"), new TBT(C65352Pkq.LIZ(WCW.class), "lazy_LigtenConfig", "getLazy_LigtenConfig()Lcom/bytedance/lighten/core/LightenConfig;"), new TBT(C65352Pkq.LIZ(WCW.class), "lazy_PkgName", "getLazy_PkgName()Ljava/lang/String;"), new TBT(C65352Pkq.LIZ(WCW.class), "lazy_Initialized", "getLazy_Initialized()Ljava/lang/Boolean;"), new TBT(C65352Pkq.LIZ(WCW.class), "lazy_customDiskCacheConfigs", "getLazy_customDiskCacheConfigs()Ljava/util/Map;"), new TBT(C65352Pkq.LIZ(WCW.class), "lazy_isLocalTest", "getLazy_isLocalTest()Ljava/lang/Boolean;"), new TBT(C65352Pkq.LIZ(WCW.class), "lazy_enableFilterExpired", "getLazy_enableFilterExpired()Ljava/lang/Boolean;"), new TBT(C65352Pkq.LIZ(WCW.class), "lazy_enableFixInvalidRequest", "getLazy_enableFixInvalidRequest()Ljava/lang/Boolean;"), new TBT(C65352Pkq.LIZ(WCW.class), "lazy_serverClock", "getLazy_serverClock()Lcom/bytedance/lighten/core/utils/IServerClock;"), new TBT(C65352Pkq.LIZ(WCW.class), "lazy_loadAsyncDowngrade", "getLazy_loadAsyncDowngrade()Ljava/lang/Boolean;"), new TBT(C65352Pkq.LIZ(WCW.class), "lazy_cancelDowngrade", "getLazy_cancelDowngrade()Ljava/lang/Boolean;"), new TBT(C65352Pkq.LIZ(WCW.class), "lazy_lowResEnable", "getLazy_lowResEnable()Ljava/lang/Boolean;"), new TBT(C65352Pkq.LIZ(WCW.class), "lazy_enableForceRunInSubThread", "getLazy_enableForceRunInSubThread()Ljava/lang/Boolean;"), new TBT(C65352Pkq.LIZ(WCW.class), "lazy_currentBtm", "getLazy_currentBtm()Lcom/bytedance/lighten/core/IBtmFetcher;"), new TBT(C65352Pkq.LIZ(WCW.class), "lazy_fixAttachEnable", "getLazy_fixAttachEnable()Ljava/lang/Boolean;"), new TBT(C65352Pkq.LIZ(WCW.class), "lazy_fixBitmapMemoryCacheProducerANREnable", "getLazy_fixBitmapMemoryCacheProducerANREnable()Ljava/lang/Boolean;"), new TBT(C65352Pkq.LIZ(WCW.class), "bitmapPoolMaxPoolSize", "getBitmapPoolMaxPoolSize()I")};
        LJJJIL = new WCW();
        LIZIZ = C221108m2.LIZIZ(WDJ.LJLIL);
        LIZJ = C221108m2.LIZIZ(WD3.LJLIL);
        LIZLLL = C221108m2.LIZIZ(C81922WDe.LJLIL);
        LJ = C221108m2.LIZIZ(WDX.LJLIL);
        LJFF = C221108m2.LIZIZ(WDP.LJLIL);
        LJI = C221108m2.LIZIZ(C81919WDb.LJLIL);
        LJII = C221108m2.LIZIZ(C81921WDd.LJLIL);
        LJIIIIZZ = C221108m2.LIZIZ(C81920WDc.LJLIL);
        LJIIIZ = C221108m2.LIZIZ(C81923WDf.LJLIL);
        LJIIJ = C221108m2.LIZIZ(WDO.LJLIL);
        LJIIJJI = C221108m2.LIZIZ(WDW.LJLIL);
        LJIIL = C221108m2.LIZIZ(WDM.LJLIL);
        LJIILIIL = C221108m2.LIZIZ(WDK.LJLIL);
        LJIILJJIL = C221108m2.LIZIZ(WDF.LJLIL);
        LJIILL = C221108m2.LIZIZ(WDR.LJLIL);
        LJIILLIIL = C221108m2.LIZIZ(WDN.LJLIL);
        LJIIZILJ = C221108m2.LIZIZ(WDQ.LJLIL);
        LJIJ = C221108m2.LIZIZ(WDS.LJLIL);
        LJIJI = C221108m2.LIZIZ(WDT.LJLIL);
        LJIJJ = C221108m2.LIZIZ(WDY.LJLIL);
        LJIJJLI = C221108m2.LIZIZ(WDI.LJLIL);
        LJIL = C221108m2.LIZIZ(WD5.LJLIL);
        LJJ = C221108m2.LIZIZ(WDH.LJLIL);
        LJJI = C221108m2.LIZIZ(C81924WDg.LJLIL);
        LJJIFFI = C221108m2.LIZIZ(WDU.LJLIL);
        LJJII = C221108m2.LIZIZ(C81918WDa.LJLIL);
        LJJIII = C221108m2.LIZIZ(C81925WDh.LJLIL);
        LJJIIJ = C221108m2.LIZIZ(WDZ.LJLIL);
        LJJIIJZLJL = C221108m2.LIZIZ(WD4.LJLIL);
        LJJIIZ = C221108m2.LIZIZ(WDG.LJLIL);
        LJJIIZI = C221108m2.LIZIZ(WD8.LJLIL);
        LJJIJ = C221108m2.LIZIZ(WD9.LJLIL);
        LJJIJIIJI = C221108m2.LIZIZ(WDV.LJLIL);
        LJJIJIIJIL = C221108m2.LIZIZ(WDD.LJLIL);
        LJJIJIL = C221108m2.LIZIZ(WD7.LJLIL);
        LJJIJL = C221108m2.LIZIZ(WDE.LJLIL);
        LJJIJLIJ = C221108m2.LIZIZ(WDA.LJLIL);
        LJJIL = C221108m2.LIZIZ(WDL.LJLIL);
        LJJIZ = C221108m2.LIZIZ(WDB.LJLIL);
        LJJJ = C221108m2.LIZIZ(WDC.LJLIL);
        LJJJI = C221108m2.LIZIZ(WD6.LJLIL);
    }
}
