package X;

/* loaded from: classes16.dex */
public enum YSM {
    LAYER_HOST_PLAY,
    LAYER_HOST_RELEASE_LAST,
    VIDEO_PATCH_PLAY_INTERNAL,
    SURFACE_AVAILABLE,
    VIDEO_PATCH_DO_PLAY,
    CONTROLLER_PREPARE,
    CONTROLLER_PLAY,
    CONTROLLER_RELEASE_ENGINE_WHEN_ERR,
    CONTROLLER_CREATE_ENGINE,
    CONTROLLER_ENGINE_PREPARE,
    CONTROLLER_INTERCEPT_INIT_PLAY,
    CONTROLLER_INTERCEPT_PREPARE_PLAY,
    CONTROLLER_SET_PARAMS_AND_PLAY,
    CONTROLLER_INTERCEPT_DO_PLAY,
    CONTROLLER_DO_ENGINE_PLAY,
    CONTROLLER_ON_PREPARE,
    CONTROLLER_ON_PREPARED,
    CONTROLLER_ON_RENDER_START,
    CONTROLLER_PLAY_STATE_PLAYING,
    CONTROLLER_PLAY_STATE_ERROR,
    CONTROLLER_PLAY_STATE_STOPPED,
    CONTROLLER_PLAY_STATE_PAUSED,
    CONTROLLER_LOAD_STATE_PLAYABLE,
    CONTROLLER_LOAD_STATE_STALLED,
    CONTROLLER_LOAD_STATE_ERROR,
    CONTROLLER_ON_ERROR,
    CONTROLLER_ON_STATUS_EXCEPTION,
    CONTROLLER_PAUSE,
    CONTROLLER_SEEK,
    CONTROLLER_SEEK_COMPLETE,
    CONTROLLER_RELEASE,
    TEXTURE_SIZE;

    public static YSM valueOf(String str) {
        return (YSM) V0N.LJJJ(YSM.class, str);
    }
}
