package com.ss.android.ugc.aweme.shortvideo.ui;

import X.AI8;
import X.AIF;
import X.ActivityC45651qj;
import X.C10A;
import X.C141335gf;
import X.C145995oB;
import X.C16880lQ;
import X.C221108m2;
import X.C29S;
import X.C32I;
import X.C3C5;
import X.C44172HVg;
import X.C61878OQg;
import X.C62822Ol8;
import X.C76800UCe;
import X.C78685UuP;
import X.C90903hW;
import X.FMX;
import X.G63;
import X.G96;
import X.G97;
import X.G98;
import X.G99;
import X.GAY;
import X.InterfaceC219588ja;
import Y.AObserverS75S0100000_7;
import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import androidx.fragment.app.Fragment;
import androidx.lifecycle.ViewModelProviders;
import androidx.lifecycle.ViewTreeLifecycleOwner;
import androidx.lifecycle.ViewTreeViewModelStoreOwner;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;
import com.bytedance.keva.Keva;
import com.bytedance.tux.sheet.sheet.TuxSheet;
import com.ss.android.ugc.aweme.shortvideo.edit.VideoPublishEditModel;
import com.zhiliaoapp.musically.R;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import kotlin.jvm.internal.AqS157S0100000_7;
import kotlin.jvm.internal.o;

/* loaded from: classes8.dex */
public final class AutogeneratedCaptionLanguageSelectionFragment extends Fragment implements G97, InterfaceC219588ja {
    public final String LJLIL;
    public AutogeneratedCaptionLanguageSelectionViewModel LJLILLLLZI;
    public GAY LJLJI;
    public final C62822Ol8 LJLJJI;
    public G96 LJLJJL;
    public final Map<Integer, View> LJLJJLL;

    public AutogeneratedCaptionLanguageSelectionFragment() {
        this("en");
    }

    /* JADX WARN: Code restructure failed: missing block: B:7:0x0036, code lost:
    
        if (r0 == null) goto L9;
     */
    @Override // X.InterfaceC219588ja
    /*
        Code decompiled incorrectly, please refer to instructions dump.
        To view partially-correct add '--show-bad-code' argument
    */
    public final X.C235119Kp createNavActions() {
        /*
            r5 = this;
            X.9Kp r4 = new X.9Kp
            r4.<init>()
            r3 = 1
            X.9Ih[] r2 = new X.AbstractC234519Ih[r3]
            X.9Ii r1 = defpackage.s1.LIZJ()
            r0 = 2131756485(0x7f1005c5, float:1.9143879E38)
            r1.LIZJ = r0
            X.G95 r0 = new X.G95
            r0.<init>(r5)
            r1.LIZ = r0
            r0 = 0
            r2[r0] = r1
            r4.LIZIZ(r2)
            X.9KF r2 = new X.9KF
            r2.<init>()
            android.content.Context r1 = r5.getContext()
            if (r1 == 0) goto L38
            boolean r0 = X.GAE.LIZ()
            if (r0 == 0) goto L41
            r0 = 2131846244(0x7f116464, float:1.9325932E38)
        L32:
            java.lang.String r0 = r1.getString(r0)
            if (r0 != 0) goto L3a
        L38:
            java.lang.String r0 = ""
        L3a:
            r2.LIZJ = r0
            r4.LIZJ = r2
            r4.LIZLLL = r3
            return r4
        L41:
            r0 = 2131826094(0x7f1115ae, float:1.9285063E38)
            goto L32
        */
        throw new UnsupportedOperationException("Method not decompiled: com.ss.android.ugc.aweme.shortvideo.ui.AutogeneratedCaptionLanguageSelectionFragment.createNavActions():X.9Kp");
    }

    @Override // androidx.fragment.app.Fragment
    public final void onDestroyView() {
        super.onDestroyView();
        ((LinkedHashMap) this.LJLJJLL).clear();
    }

    public AutogeneratedCaptionLanguageSelectionFragment(String initialLanguageCode) {
        o.LJIIIZ(initialLanguageCode, "initialLanguageCode");
        this.LJLJJLL = new LinkedHashMap();
        this.LJLIL = initialLanguageCode;
        this.LJLJJI = C221108m2.LIZIZ(new AqS157S0100000_7(this, 292));
    }

    /* JADX WARN: Multi-variable type inference failed */
    /* JADX WARN: Type inference failed for: r4v0, types: [X.OQg] */
    /* JADX WARN: Type inference failed for: r4v1, types: [java.util.List] */
    /* JADX WARN: Type inference failed for: r4v2, types: [java.util.ArrayList] */
    @Override // androidx.fragment.app.Fragment
    public final void onViewCreated(View view, Bundle bundle) {
        ?? r4;
        o.LJIIIZ(view, "view");
        super.onViewCreated(view, bundle);
        AutogeneratedCaptionLanguageSelectionViewModel autogeneratedCaptionLanguageSelectionViewModel = (AutogeneratedCaptionLanguageSelectionViewModel) ViewModelProviders.of(this).get(AutogeneratedCaptionLanguageSelectionViewModel.class);
        this.LJLILLLLZI = autogeneratedCaptionLanguageSelectionViewModel;
        if (autogeneratedCaptionLanguageSelectionViewModel != null) {
            List<G98> list = autogeneratedCaptionLanguageSelectionViewModel.LJLILLLLZI;
            if (list != null) {
                r4 = new ArrayList(C32I.LJJL(list, 10));
                Iterator it = ((ArrayList) list).iterator();
                while (it.hasNext()) {
                    G98 g98 = (G98) it.next();
                    r4.add(new G99(g98.LIZ, g98.LIZIZ));
                }
            } else {
                r4 = C61878OQg.INSTANCE;
            }
            this.LJLJI = new GAY(this, r4, this.LJLIL);
            Object value = this.LJLJJI.getValue();
            o.LJIIIIZZ(value, "<get-recyclerView>(...)");
            RecyclerView recyclerView = (RecyclerView) value;
            GAY gay = this.LJLJI;
            if (gay != null) {
                recyclerView.setAdapter(gay);
                Object value2 = this.LJLJJI.getValue();
                o.LJIIIIZZ(value2, "<get-recyclerView>(...)");
                getContext();
                ((RecyclerView) value2).setLayoutManager(new LinearLayoutManager());
                AutogeneratedCaptionLanguageSelectionViewModel autogeneratedCaptionLanguageSelectionViewModel2 = this.LJLILLLLZI;
                if (autogeneratedCaptionLanguageSelectionViewModel2 != null) {
                    autogeneratedCaptionLanguageSelectionViewModel2.LJLIL.observe(this, new AObserverS75S0100000_7(this, 29));
                    return;
                } else {
                    o.LJIJI("viewModel");
                    throw null;
                }
            }
            o.LJIJI("adapter");
            throw null;
        }
        o.LJIJI("viewModel");
        throw null;
    }

    @Override // X.G97
    public final void vh(String code, String name) {
        String str;
        o.LJIIIZ(code, "code");
        o.LJIIIZ(name, "name");
        AutogeneratedCaptionLanguageSelectionViewModel autogeneratedCaptionLanguageSelectionViewModel = this.LJLILLLLZI;
        if (autogeneratedCaptionLanguageSelectionViewModel != null) {
            autogeneratedCaptionLanguageSelectionViewModel.LJLIL.postValue(code);
            G96 g96 = this.LJLJJL;
            if (g96 != null) {
                VideoPublishContainerScene videoPublishContainerScene = g96.LIZ;
                G63 g63 = g96.LIZIZ;
                TuxSheet tuxSheet = g96.LIZJ;
                videoPublishContainerScene.getClass();
                g63.getClass();
                g63.LJI = name;
                AI8 ai8 = videoPublishContainerScene.LLD;
                if (ai8 != null) {
                    ((AIF) ai8.getAccessory()).LJIILIIL(name);
                }
                String LJJIIJZLJL = C78685UuP.LJJIIJZLJL();
                Keva.getRepo("TOOLS_PUBLISH_REPO_NAME").storeString("autogenerated_caption_language_selection", code);
                tuxSheet.dismiss();
                C145995oB c145995oB = new C145995oB();
                c145995oB.LJI("enter_from", "video_post_page");
                VideoPublishEditModel videoPublishEditModel = videoPublishContainerScene.LLILZLL;
                if (videoPublishEditModel != null) {
                    str = videoPublishEditModel.getCreationId();
                } else {
                    str = "mModel is null";
                }
                c145995oB.LJI("creation_id", str);
                c145995oB.LJI("shoot_way", videoPublishContainerScene.LLILZLL.mShootWay);
                c145995oB.LJI("selected_asr_lang", code);
                c145995oB.LJI("previous_saved_asr_lang", LJJIIJZLJL);
                c145995oB.LJI("author_id", C44172HVg.LJIJ.getCurrentUserID());
                FMX.LJIIL("save_asr_selected_lang", c145995oB.LIZ);
                return;
            }
            return;
        }
        o.LJIJI("viewModel");
        throw null;
    }

    @Override // androidx.fragment.app.Fragment
    public final View onCreateView(LayoutInflater inflater, ViewGroup viewGroup, Bundle bundle) {
        o.LJIIIZ(inflater, "inflater");
        View LLLLIILL = C16880lQ.LLLLIILL(inflater, R.layout.i4, viewGroup, false);
        C29S c29s = null;
        if (!(LLLLIILL instanceof View)) {
            LLLLIILL = null;
        }
        if (LLLLIILL != null) {
            try {
                ViewTreeLifecycleOwner.set(LLLLIILL, getViewLifecycleOwner());
                ViewTreeViewModelStoreOwner.set(LLLLIILL, this);
                C10A.LIZIZ(LLLLIILL, this);
                ActivityC45651qj mo49getActivity = mo49getActivity();
                if (mo49getActivity instanceof C29S) {
                    c29s = (C29S) mo49getActivity;
                }
                C90903hW.LIZ(c29s);
            } catch (Throwable th) {
                C3C5.m7constructorimpl(C141335gf.LIZ(th));
            }
        }
        C3C5.m7constructorimpl(C76800UCe.LIZ);
        return LLLLIILL;
    }
}
