package com.ss.android.ugc.aweme.shortvideo.ui;

import X.DU6;
import X.G98;
import androidx.lifecycle.MutableLiveData;
import androidx.lifecycle.ViewModel;
import com.ss.android.ugc.aweme.shortvideo.experiment.AutogeneratedCaptionLanguageSelection;
import java.util.ArrayList;
import java.util.List;

/* loaded from: classes8.dex */
public final class AutogeneratedCaptionLanguageSelectionViewModel extends ViewModel {
    public final MutableLiveData<String> LJLIL = new MutableLiveData<>();
    public final List<G98> LJLILLLLZI;

    public AutogeneratedCaptionLanguageSelectionViewModel() {
        AutogeneratedCaptionLanguageSelection[] LIZ = DU6.LIZ();
        ArrayList arrayList = new ArrayList(LIZ.length);
        for (AutogeneratedCaptionLanguageSelection autogeneratedCaptionLanguageSelection : LIZ) {
            arrayList.add(new G98(autogeneratedCaptionLanguageSelection.getCode(), autogeneratedCaptionLanguageSelection.getLocalName()));
        }
        this.LJLILLLLZI = arrayList;
    }
}
