package Y;

import X.ASL;
import X.BZI;
import X.C145995oB;
import X.C175976vR;
import X.C176996x5;
import X.C177336xd;
import X.C28787BRn;
import X.C29841BnR;
import X.C31319CQx;
import X.C44172HVg;
import X.C76800UCe;
import X.C78685UuP;
import X.CN1;
import X.CQO;
import X.EnumC12540eQ;
import X.FMX;
import X.G63;
import X.G96;
import X.InterfaceC174316sl;
import X.InterfaceC88472Yns;
import com.bytedance.android.live.publicscreen.api.IPublicScreenService;
import com.bytedance.tux.sheet.sheet.TuxSheet;
import com.ss.android.ugc.aweme.comment.commentlist.CommentListFragment;
import com.ss.android.ugc.aweme.comment.model.Comment;
import com.ss.android.ugc.aweme.feed.model.CardStruct;
import com.ss.android.ugc.aweme.profile.model.User;
import com.ss.android.ugc.aweme.shortvideo.edit.VideoPublishEditModel;
import com.ss.android.ugc.aweme.shortvideo.ui.AutogeneratedCaptionLanguageSelectionFragment;
import com.ss.android.ugc.aweme.shortvideo.ui.VideoPublishContainerScene;

/* loaded from: classes14.dex */
public class AObjectS42S0201000_13 implements InterfaceC88472Yns {
    public final int $t;
    public int i2;
    public Object l0;
    public Object l1;

    @Override // X.InterfaceC88472Yns
    public final Object invoke(Object obj) {
        switch (this.$t) {
            case 0:
                return invoke$0(this, obj);
            case 1:
                return invoke$1(this, obj);
            default:
                return null;
        }
    }

    /* JADX WARN: Removed duplicated region for block: B:20:0x0082  */
    /*
        Code decompiled incorrectly, please refer to instructions dump.
        To view partially-correct add '--show-bad-code' argument
    */
    public static final java.lang.Object invoke$0(Y.AObjectS42S0201000_13 r12, java.lang.Object r13) {
        /*
            int r0 = r12.i2
            r7 = 0
            switch(r0) {
                case 0: goto L36;
                default: goto L6;
            }
        L6:
            java.lang.Object r2 = r12.l0
            androidx.lifecycle.LifecycleOwner r2 = (androidx.lifecycle.LifecycleOwner) r2
            com.ss.android.ugc.aweme.shortvideo.ui.VideoPublishContainerScene r2 = (com.ss.android.ugc.aweme.shortvideo.ui.VideoPublishContainerScene) r2
            java.lang.Object r1 = r12.l1
            X.G63 r1 = (X.G63) r1
            com.ss.android.ugc.aweme.topic.trendingtopic.IVideoTrendingTopicService r8 = r2.LLLLL()
            X.1qj r9 = r2.LLII()
            java.lang.String r10 = r2.LLLLIILLL()
            com.ss.android.ugc.aweme.shortvideo.edit.VideoPublishEditModel r0 = r2.LLILZLL
            com.ss.android.ugc.aweme.creative.CreativeInfo r0 = r0.creativeInfo
            java.lang.String r11 = r0.getCreationId()
            com.ss.android.ugc.aweme.shortvideo.edit.VideoPublishEditModel r0 = r2.LLILZLL
            com.ss.android.ugc.aweme.creative.model.CreativeModel r0 = r0.creativeModel
            com.ss.android.ugc.aweme.creative.model.trending.TrendingUploadModel r0 = r0.trendingUploadModel
            com.ss.android.ugc.aweme.feed.model.trendingtopic.VideoTrendingTopic r12 = r0.trendingTopic
            X.G5o r13 = new X.G5o
            r13.<init>()
            r8.LIZ(r9, r10, r11, r12, r13)
            return r7
        L36:
            java.lang.Object r3 = r12.l0
            androidx.lifecycle.LifecycleOwner r3 = (androidx.lifecycle.LifecycleOwner) r3
            com.bytedance.android.livesdk.comp.impl.game.linkmic.widget.GameLinkControlWidget r3 = (com.bytedance.android.livesdk.comp.impl.game.linkmic.widget.GameLinkControlWidget) r3
            java.lang.Object r5 = r12.l1
            X.TVS r5 = (X.TVS) r5
            java.lang.Integer r13 = (java.lang.Integer) r13
            r3.getClass()
            int r0 = r13.intValue()
            r1 = 3
            r4 = 1
            r2 = 0
            java.lang.String r6 = "GameLinkControlWidget"
            if (r0 != 0) goto Lc6
            java.lang.String r0 = "Link mic bundle load succeed"
            X.C0NB.LJIIIZ(r6, r0)
            X.B83 r0 = X.B83.LIZ()
            r0.LIZIZ()
            com.bytedance.android.livesdk.chatroom.model.multilive.MultiLiveAnchorPanelSettings r0 = X.TV2.LJI()
            if (r0 == 0) goto La9
            int r0 = r0.allowViewerReq
            if (r0 != r1) goto La9
            boolean r0 = r3.LJLZ()
            if (r0 != 0) goto La9
            X.TVD r5 = X.TTV.LIZ()
            com.bytedance.android.livesdkapi.depend.model.live.Room r0 = r3.LJLJJI
            if (r0 != 0) goto Laa
            java.lang.String r0 = " getChannelIdFromRoomInfo mRoom is null"
            X.TYP.LIZ(r6, r0, r2)
        L79:
            r1 = r7
        L7a:
            java.util.HashSet<java.lang.String> r0 = r5.LJI
            boolean r0 = X.ORZ.LJLJJI(r1, r0)
            if (r0 != 0) goto La9
            X.TVQ r3 = r3.LJLJJLL
            r3.getClass()
            java.lang.StringBuilder r1 = X.X1D.LIZ()
            java.lang.String r0 = "onBundleLoaded#canLinkInRoom = "
            r1.append(r0)
            X.TaI r0 = r3.LIZ
            r0.getClass()
            r1.append(r4)
            java.lang.String r1 = X.X1D.LIZIZ(r1)
            java.lang.String r0 = "ToolbarGameLinkDelegate"
            X.TYP.LIZJ(r0, r1)
            X.TaI r0 = r3.LIZ
            r0.getClass()
            r3.LIZ(r2)
        La9:
            return r7
        Laa:
            com.bytedance.android.livesdk.model.linksetting.MultiLiveUserSettings r0 = r0.multiLiveUserSettings
            if (r0 != 0) goto Lb4
            java.lang.String r0 = " getChannelIdFromRoomInfo mRoom.multiLiveUserSettings is null"
            X.TYP.LIZ(r6, r0, r2)
            goto L79
        Lb4:
            android.util.ArrayMap<java.lang.Integer, java.lang.Long> r1 = r0.channelMap
            if (r1 == 0) goto L79
            r0 = 4
            java.lang.Integer r0 = java.lang.Integer.valueOf(r0)
            java.lang.Object r0 = r1.get(r0)
            java.lang.String r1 = java.lang.String.valueOf(r0)
            goto L7a
        Lc6:
            com.bytedance.android.livesdk.chatroom.model.multilive.MultiLiveAnchorPanelSettings r0 = X.TV2.LJI()
            if (r0 == 0) goto Le6
            int r0 = r0.allowViewerReq
            if (r0 != r1) goto Le6
            boolean r0 = r5.LIZ()
            if (r0 == 0) goto Le6
            X.TVQ r1 = r3.LJLJJLL
            X.TaI r0 = r1.LIZ
            r0.getClass()
            r1.LIZ(r2)
            java.lang.String r0 = "load link mic aab failed and show entrance"
            X.C0NB.LJIIIZ(r6, r0)
            goto La9
        Le6:
            java.lang.String r0 = "load link mic aab failed and not show entrance"
            X.C0NB.LJIIIZ(r6, r0)
            goto La9
        */
        throw new UnsupportedOperationException("Method not decompiled: Y.AObjectS42S0201000_13.invoke$0(Y.AObjectS42S0201000_13, java.lang.Object):java.lang.Object");
    }

    public static final Object invoke$1(AObjectS42S0201000_13 aObjectS42S0201000_13, Object obj) {
        String str;
        String str2;
        switch (aObjectS42S0201000_13.i2) {
            case 0:
                C31319CQx c31319CQx = (C31319CQx) aObjectS42S0201000_13.l0;
                CQO cqo = (CQO) aObjectS42S0201000_13.l1;
                if (c31319CQx.LJLILLLLZI != null && c31319CQx.LLIILZL != null) {
                    BZI LIZ = C28787BRn.LIZ("livesdk_pin_comment_icon_click");
                    LIZ.LJIILLIIL(c31319CQx.dataChannel);
                    if (c31319CQx.LLIILZL.LJIIZILJ) {
                        str = "1";
                    } else {
                        str = CardStruct.IStatusCode.DEFAULT;
                    }
                    LIZ.LJIJJ(str, "is_extended_comment_filed");
                    LIZ.LJIJJ(C29841BnR.LIZIZ(c31319CQx.LLIILZL.LJI, c31319CQx.dataChannel), "admin_type");
                    LIZ.LJJIIJZLJL();
                    if (obj != EnumC12540eQ.ON) {
                        return C76800UCe.LIZ;
                    }
                    ((IPublicScreenService) CN1.LIZ(IPublicScreenService.class)).t80(c31319CQx.LLIILZL, cqo.LJIJJLI);
                }
                return C76800UCe.LIZ;
            case 1:
                AObserverS64S0300000_3 aObserverS64S0300000_3 = (AObserverS64S0300000_3) aObjectS42S0201000_13.l0;
                InterfaceC174316sl interfaceC174316sl = (InterfaceC174316sl) aObjectS42S0201000_13.l1;
                CommentListFragment commentListFragment = (CommentListFragment) aObserverS64S0300000_3.l2;
                Comment LIZIZ = ((C175976vR) interfaceC174316sl).LIZIZ();
                commentListFragment.getClass();
                CommentListFragment.Nn(LIZIZ, "comment_restr_pin_popup_ok_click");
                return C76800UCe.LIZ;
            case 2:
                C176996x5 c176996x5 = (C176996x5) aObjectS42S0201000_13.l0;
                User user = (User) aObjectS42S0201000_13.l1;
                C177336xd c177336xd = (C177336xd) obj;
                c177336xd.LJLLI = c176996x5.LJIIZILJ();
                c177336xd.LJLJJL = c176996x5.LJLJJI.getEnterMethod();
                c177336xd.LJLILLLLZI = c176996x5.LJIL();
                c177336xd.LJLJJLL = c176996x5.LJIJJLI();
                c177336xd.LJLL = c176996x5.LJLJJI.getCommentInputViewType();
                c176996x5.LJLJJI.hasUpvoteOption();
                c176996x5.LJJIII();
                c177336xd.LJLJI = user.getAccurateRecType();
                c177336xd.LIZ(c176996x5.LJIJ());
                return null;
            default:
                VideoPublishContainerScene videoPublishContainerScene = (VideoPublishContainerScene) aObjectS42S0201000_13.l0;
                G63 g63 = (G63) aObjectS42S0201000_13.l1;
                if (videoPublishContainerScene.LL._checked.getValue().booleanValue()) {
                    AutogeneratedCaptionLanguageSelectionFragment autogeneratedCaptionLanguageSelectionFragment = new AutogeneratedCaptionLanguageSelectionFragment(C78685UuP.LJJIIJZLJL());
                    TuxSheet tuxSheet = new ASL().LIZ;
                    tuxSheet.LJLLILLLL = autogeneratedCaptionLanguageSelectionFragment;
                    autogeneratedCaptionLanguageSelectionFragment.LJLJJL = new G96(videoPublishContainerScene, g63, tuxSheet);
                    tuxSheet.show(videoPublishContainerScene.LLJLL().getSupportFragmentManager(), "AutogeneratedCaptionLanguageSelectionFragment");
                    C145995oB c145995oB = new C145995oB();
                    c145995oB.LJI("enter_from", "video_post_page");
                    VideoPublishEditModel videoPublishEditModel = videoPublishContainerScene.LLILZLL;
                    if (videoPublishEditModel != null) {
                        str2 = videoPublishEditModel.getCreationId();
                    } else {
                        str2 = "mModel is null";
                    }
                    c145995oB.LJI("creation_id", str2);
                    c145995oB.LJI("shoot_way", videoPublishContainerScene.LLILZLL.mShootWay);
                    c145995oB.LJI("current_selected_asr_lang", C78685UuP.LJJIIJZLJL());
                    c145995oB.LJI("author_id", C44172HVg.LJIJ.getCurrentUserID());
                    FMX.LJIIL("enter_asr_selected_lang", c145995oB.LIZ);
                }
                return null;
        }
    }

    public AObjectS42S0201000_13(int i, Object obj, Object obj2, int i2) {
        this.$t = i2;
        this.i2 = i;
        this.l0 = obj;
        this.l1 = obj2;
    }
}
